// Code generated by https://github.com/ahfuzhang/BaoHuLu. DO NOT EDIT.

package {{.Package}}

import (
	"encoding/base64"
	"math"
	"strconv"
	"unsafe"

	"github.com/ahfuzhang/BaoHuLu/dependencies/golang/utils"
	"github.com/valyala/fastjson"
)

var _ = unsafe.Pointer(nil)

var _ = math.Float32bits

var _ = strconv.IntSize

var _ = base64.StdEncoding

var jsonParserPool fastjson.ParserPool

// ─── Enums ───────────────────────────────────────────────────────────────────
{{range .Enums}}
type {{.Name}} int32
{{$enumName := .Name}}
const (
{{- range .Values}}
	{{.Name}} {{$enumName}} = {{.Number}}
{{- end}}
)
{{end}}
// ─── Writer structs ──────────────────────────────────────────────────────────
{{range .Messages}}
{{- $goName := .GoName}}
// {{$goName}} field tag IDs.
const (
{{- range .Fields}}
	{{$goName}}_{{.Name}}_Tag = {{.Number}}
{{- end}}
)

// {{$goName}} JSON field name string constants.
const (
{{- range .Fields}}
	nameOf{{$goName}}{{.Name}} = "{{.JsonName}}"
{{- end}}
)

{{msgCommentBlock .Comment}}// {{$goName}} writer struct.
// Fields are ordered by alignment (desc) then size (desc) for minimal memory padding.
type {{$goName}} struct {
{{- range .Fields}}
{{fieldCommentBlock .Comment}}	{{.Name}} {{.GoType}} `json:"{{.JsonName}},omitempty"`
{{- end}}
	arena []byte
}

func (m *{{$goName}}) Reset() {
{{- range .Fields}}
{{- if .Map}}
	clear(m.{{.Name}})
{{- else if .Repeated}}
	m.{{.Name}} = m.{{.Name}}[:0]
{{- else if .IsMsg}}
	m.{{.Name}}.Reset()
{{- else if isSliceType .GoType}}
	m.{{.Name}} = m.{{.Name}}[:0]
{{- else}}
	m.{{.Name}} = {{zeroVal .GoType}}
{{- end}}
{{- end}}
}

func (m *{{$goName}}) ProtobufSize() int {
	size := 0
{{- range .Fields}}
{{- if .Map}}
	for k, v := range m.{{.Name}} {
		entrySize := 0
		{{- if eq .MapKey "string"}}
		{ kn := len(k); entrySize += utils.TagSize(1, utils.WireTypeLenDelim) + utils.VarintSize(uint64(kn)) + kn }
		{{- else if eq .MapKey "bool"}}
		{ var bk uint64; if k { bk = 1 }; entrySize += utils.TagSize(1, utils.WireTypeVarint) + utils.VarintSize(bk) }
		{{- else if eq .MapKey "fixed32"}}
		_ = k; entrySize += utils.TagSize(1, utils.WireType32bit) + 4
		{{- else if eq .MapKey "sfixed32"}}
		_ = k; entrySize += utils.TagSize(1, utils.WireType32bit) + 4
		{{- else if eq .MapKey "fixed64"}}
		_ = k; entrySize += utils.TagSize(1, utils.WireType64bit) + 8
		{{- else if eq .MapKey "sfixed64"}}
		_ = k; entrySize += utils.TagSize(1, utils.WireType64bit) + 8
		{{- else if eq .MapKey "sint32"}}
		entrySize += utils.TagSize(1, utils.WireTypeVarint) + utils.VarintSize(uint64((uint32(k)<<1)^uint32(k>>31)))
		{{- else if eq .MapKey "sint64"}}
		entrySize += utils.TagSize(1, utils.WireTypeVarint) + utils.VarintSize((uint64(k)<<1)^uint64(k>>63))
		{{- else}}
		entrySize += utils.TagSize(1, {{protoWireType .MapKey}}) + utils.VarintSize(uint64(k))
		{{- end}}
		{{- if eq .MapVal "string"}}
		{ vn := len(v); entrySize += utils.TagSize(2, utils.WireTypeLenDelim) + utils.VarintSize(uint64(vn)) + vn }
		{{- else if eq .MapVal "bytes"}}
		{ vn := len(v); entrySize += utils.TagSize(2, utils.WireTypeLenDelim) + utils.VarintSize(uint64(vn)) + vn }
		{{- else if mapValIsMsg .MapVal}}
		{ sub := v.ProtobufSize(); entrySize += utils.TagSize(2, utils.WireTypeLenDelim) + utils.VarintSize(uint64(sub)) + sub }
		{{- else if eq .MapVal "double"}}
		entrySize += utils.TagSize(2, utils.WireType64bit) + 8
		{{- else if eq .MapVal "float"}}
		entrySize += utils.TagSize(2, utils.WireType32bit) + 4
		{{- else if eq .MapVal "fixed32"}}
		entrySize += utils.TagSize(2, utils.WireType32bit) + 4
		{{- else if eq .MapVal "fixed64"}}
		entrySize += utils.TagSize(2, utils.WireType64bit) + 8
		{{- else if eq .MapVal "sfixed32"}}
		entrySize += utils.TagSize(2, utils.WireType32bit) + 4
		{{- else if eq .MapVal "sfixed64"}}
		entrySize += utils.TagSize(2, utils.WireType64bit) + 8
		{{- else}}
		entrySize += utils.TagSize(2, utils.WireTypeVarint) + utils.VarintSize(uint64(v))
		{{- end}}
		size += utils.TagSize({{$goName}}_{{.Name}}_Tag, utils.WireTypeLenDelim) + utils.VarintSize(uint64(entrySize)) + entrySize
	}
{{- else if .Repeated}}
{{- if isPackable .Type}}
	if len(m.{{.Name}}) > 0 {
		packed := 0
		for _, v := range m.{{.Name}} {
			{{- if eq .Type "sint32"}}
			packed += utils.VarintSize(uint64((uint32(v) << 1) ^ uint32(v>>31)))
			{{- else if eq .Type "sint64"}}
			packed += utils.VarintSize((uint64(v) << 1) ^ uint64(v>>63))
			{{- else if eq .Type "fixed32"}}
			_ = v; packed += 4
			{{- else if eq .Type "fixed64"}}
			_ = v; packed += 8
			{{- else if eq .Type "sfixed32"}}
			_ = v; packed += 4
			{{- else if eq .Type "sfixed64"}}
			_ = v; packed += 8
			{{- else if eq .Type "float"}}
			_ = v; packed += 4
			{{- else if eq .Type "double"}}
			_ = v; packed += 8
			{{- else if eq .Type "bool"}}
			_ = v; packed += 1
			{{- else}}
			packed += utils.VarintSize(uint64(v))
			{{- end}}
		}
		size += utils.TagSize({{$goName}}_{{.Name}}_Tag, utils.WireTypeLenDelim) + utils.VarintSize(uint64(packed)) + packed
	}
{{- else if eq .Type "string"}}
	for _, v := range m.{{.Name}} {
		n := len(v)
		size += utils.TagSize({{$goName}}_{{.Name}}_Tag, utils.WireTypeLenDelim) + utils.VarintSize(uint64(n)) + n
	}
{{- else if eq .Type "bytes"}}
	for _, v := range m.{{.Name}} {
		n := len(v)
		size += utils.TagSize({{$goName}}_{{.Name}}_Tag, utils.WireTypeLenDelim) + utils.VarintSize(uint64(n)) + n
	}
{{- else}}
	for i := range m.{{.Name}} {
		sub := m.{{.Name}}[i].ProtobufSize()
		if sub > 0 {
			size += utils.TagSize({{$goName}}_{{.Name}}_Tag, utils.WireTypeLenDelim) + utils.VarintSize(uint64(sub)) + sub
		}
	}
{{- end}}
{{- else if .IsMsg}}
	{
		sub := m.{{.Name}}.ProtobufSize()
		if sub > 0 {
			size += utils.TagSize({{$goName}}_{{.Name}}_Tag, utils.WireTypeLenDelim) + utils.VarintSize(uint64(sub)) + sub
		}
	}
{{- else if eq .Type "double"}}
	if m.{{.Name}} != 0 {
		size += utils.TagSize({{$goName}}_{{.Name}}_Tag, utils.WireType64bit) + 8
	}
{{- else if eq .Type "float"}}
	if m.{{.Name}} != 0 {
		size += utils.TagSize({{$goName}}_{{.Name}}_Tag, utils.WireType32bit) + 4
	}
{{- else if eq .Type "fixed32"}}
	if m.{{.Name}} != 0 {
		size += utils.TagSize({{$goName}}_{{.Name}}_Tag, utils.WireType32bit) + 4
	}
{{- else if eq .Type "fixed64"}}
	if m.{{.Name}} != 0 {
		size += utils.TagSize({{$goName}}_{{.Name}}_Tag, utils.WireType64bit) + 8
	}
{{- else if eq .Type "sfixed32"}}
	if m.{{.Name}} != 0 {
		size += utils.TagSize({{$goName}}_{{.Name}}_Tag, utils.WireType32bit) + 4
	}
{{- else if eq .Type "sfixed64"}}
	if m.{{.Name}} != 0 {
		size += utils.TagSize({{$goName}}_{{.Name}}_Tag, utils.WireType64bit) + 8
	}
{{- else if eq .Type "sint32"}}
	if m.{{.Name}} != 0 {
		size += utils.TagSize({{$goName}}_{{.Name}}_Tag, utils.WireTypeVarint) + utils.VarintSize(uint64((uint32(m.{{.Name}}) << 1) ^ uint32(m.{{.Name}}>>31)))
	}
{{- else if eq .Type "sint64"}}
	if m.{{.Name}} != 0 {
		size += utils.TagSize({{$goName}}_{{.Name}}_Tag, utils.WireTypeVarint) + utils.VarintSize((uint64(m.{{.Name}}) << 1) ^ uint64(m.{{.Name}}>>63))
	}
{{- else if eq .Type "bool"}}
	if m.{{.Name}} {
		size += utils.TagSize({{$goName}}_{{.Name}}_Tag, utils.WireTypeVarint) + 1
	}
{{- else if eq .Type "string"}}
	if m.{{.Name}} != "" {
		n := len(m.{{.Name}})
		size += utils.TagSize({{$goName}}_{{.Name}}_Tag, utils.WireTypeLenDelim) + utils.VarintSize(uint64(n)) + n
	}
{{- else if eq .Type "bytes"}}
	if len(m.{{.Name}}) > 0 {
		n := len(m.{{.Name}})
		size += utils.TagSize({{$goName}}_{{.Name}}_Tag, utils.WireTypeLenDelim) + utils.VarintSize(uint64(n)) + n
	}
{{- else}}
	if m.{{.Name}} != 0 {
		size += utils.TagSize({{$goName}}_{{.Name}}_Tag, utils.WireTypeVarint) + utils.VarintSize(uint64(m.{{.Name}}))
	}
{{- end}}
{{- end}}
	return size
}

func (m *{{$goName}}) ToProtobuf(in []byte) []byte {
{{- range .Fields}}
{{- if .Map}}
	for k, v := range m.{{.Name}} {
		entrySize := 0
		{{- if eq .MapKey "string"}}
		{ kn := len(k); entrySize += utils.TagSize(1, utils.WireTypeLenDelim) + utils.VarintSize(uint64(kn)) + kn }
		{{- else if eq .MapKey "bool"}}
		{ var bk uint64; if k { bk = 1 }; entrySize += utils.TagSize(1, utils.WireTypeVarint) + utils.VarintSize(bk) }
		{{- else if eq .MapKey "fixed32"}}
		entrySize += utils.TagSize(1, utils.WireType32bit) + 4
		{{- else if eq .MapKey "sfixed32"}}
		entrySize += utils.TagSize(1, utils.WireType32bit) + 4
		{{- else if eq .MapKey "fixed64"}}
		entrySize += utils.TagSize(1, utils.WireType64bit) + 8
		{{- else if eq .MapKey "sfixed64"}}
		entrySize += utils.TagSize(1, utils.WireType64bit) + 8
		{{- else if eq .MapKey "sint32"}}
		entrySize += utils.TagSize(1, utils.WireTypeVarint) + utils.VarintSize(uint64((uint32(k)<<1)^uint32(k>>31)))
		{{- else if eq .MapKey "sint64"}}
		entrySize += utils.TagSize(1, utils.WireTypeVarint) + utils.VarintSize((uint64(k)<<1)^uint64(k>>63))
		{{- else}}
		entrySize += utils.TagSize(1, {{protoWireType .MapKey}}) + utils.VarintSize(uint64(k))
		{{- end}}
		{{- if eq .MapVal "string"}}
		{ vn := len(v); entrySize += utils.TagSize(2, utils.WireTypeLenDelim) + utils.VarintSize(uint64(vn)) + vn }
		{{- else if eq .MapVal "bytes"}}
		{ vn := len(v); entrySize += utils.TagSize(2, utils.WireTypeLenDelim) + utils.VarintSize(uint64(vn)) + vn }
		{{- else if (mapValIsMsg .MapVal)}}
		valMsgSize := v.ProtobufSize()
		entrySize += utils.TagSize(2, utils.WireTypeLenDelim) + utils.VarintSize(uint64(valMsgSize)) + valMsgSize
		{{- else if eq .MapVal "double"}}
		entrySize += utils.TagSize(2, utils.WireType64bit) + 8
		{{- else if eq .MapVal "float"}}
		entrySize += utils.TagSize(2, utils.WireType32bit) + 4
		{{- else if eq .MapVal "fixed32"}}
		entrySize += utils.TagSize(2, utils.WireType32bit) + 4
		{{- else if eq .MapVal "fixed64"}}
		entrySize += utils.TagSize(2, utils.WireType64bit) + 8
		{{- else if eq .MapVal "sfixed32"}}
		entrySize += utils.TagSize(2, utils.WireType32bit) + 4
		{{- else if eq .MapVal "sfixed64"}}
		entrySize += utils.TagSize(2, utils.WireType64bit) + 8
		{{- else}}
		entrySize += utils.TagSize(2, utils.WireTypeVarint) + utils.VarintSize(uint64(v))
		{{- end}}
		in = utils.AppendTag(in, {{$goName}}_{{.Name}}_Tag, utils.WireTypeLenDelim)
		in = utils.AppendVarint(in, uint64(entrySize))
		in = utils.AppendTag(in, 1, {{protoWireType .MapKey}})
		{{- if eq .MapKey "string"}}
		in = utils.AppendVarint(in, uint64(len(k)))
		in = append(in, k...)
		{{- else if eq .MapKey "bool"}}
		if k { in = utils.AppendVarint(in, 1) } else { in = utils.AppendVarint(in, 0) }
		{{- else if eq .MapKey "fixed32"}}
		in = utils.AppendFixed32(in, k)
		{{- else if eq .MapKey "sfixed32"}}
		in = utils.AppendFixed32(in, uint32(k))
		{{- else if eq .MapKey "fixed64"}}
		in = utils.AppendFixed64(in, k)
		{{- else if eq .MapKey "sfixed64"}}
		in = utils.AppendFixed64(in, uint64(k))
		{{- else if eq .MapKey "sint32"}}
		in = utils.AppendSint32(in, k)
		{{- else if eq .MapKey "sint64"}}
		in = utils.AppendSint64(in, k)
		{{- else}}
		in = utils.AppendVarint(in, uint64(k))
		{{- end}}
		in = utils.AppendTag(in, 2, {{protoWireType .MapVal}})
		{{- if eq .MapVal "string"}}
		in = utils.AppendVarint(in, uint64(len(v)))
		in = append(in, v...)
		{{- else if eq .MapVal "bytes"}}
		in = utils.AppendLenDelim(in, v)
		{{- else if (mapValIsMsg .MapVal)}}
		in = utils.AppendVarint(in, uint64(valMsgSize))
		in = v.ToProtobuf(in)
		{{- else if eq .MapVal "double"}}
		in = utils.AppendFixed64(in, math.Float64bits(v))
		{{- else if eq .MapVal "float"}}
		in = utils.AppendFixed32(in, math.Float32bits(v))
		{{- else if eq .MapVal "fixed32"}}
		in = utils.AppendFixed32(in, uint32(v))
		{{- else if eq .MapVal "fixed64"}}
		in = utils.AppendFixed64(in, uint64(v))
		{{- else if eq .MapVal "sfixed32"}}
		in = utils.AppendFixed32(in, uint32(v))
		{{- else if eq .MapVal "sfixed64"}}
		in = utils.AppendFixed64(in, uint64(v))
		{{- else}}
		in = utils.AppendVarint(in, uint64(v))
		{{- end}}
	}
{{- else if .Repeated}}
{{- if isPackable .Type}}
	if len(m.{{.Name}}) > 0 {
		packedSize := 0
		for _, v := range m.{{.Name}} {
			{{- if eq .Type "sint32"}}
			packedSize += utils.VarintSize(uint64((uint32(v) << 1) ^ uint32(v>>31)))
			{{- else if eq .Type "sint64"}}
			packedSize += utils.VarintSize((uint64(v) << 1) ^ uint64(v>>63))
			{{- else if eq .Type "fixed32"}}
			_ = v; packedSize += 4
			{{- else if eq .Type "fixed64"}}
			_ = v; packedSize += 8
			{{- else if eq .Type "sfixed32"}}
			_ = v; packedSize += 4
			{{- else if eq .Type "sfixed64"}}
			_ = v; packedSize += 8
			{{- else if eq .Type "float"}}
			_ = v; packedSize += 4
			{{- else if eq .Type "double"}}
			_ = v; packedSize += 8
			{{- else if eq .Type "bool"}}
			_ = v; packedSize += 1
			{{- else}}
			packedSize += utils.VarintSize(uint64(v))
			{{- end}}
		}
		in = utils.AppendTag(in, {{$goName}}_{{.Name}}_Tag, utils.WireTypeLenDelim)
		in = utils.AppendVarint(in, uint64(packedSize))
		for _, v := range m.{{.Name}} {
			{{- if eq .Type "sint32"}}
			in = utils.AppendSint32(in, v)
			{{- else if eq .Type "sint64"}}
			in = utils.AppendSint64(in, v)
			{{- else if eq .Type "fixed32"}}
			in = utils.AppendFixed32(in, uint32(v))
			{{- else if eq .Type "fixed64"}}
			in = utils.AppendFixed64(in, uint64(v))
			{{- else if eq .Type "sfixed32"}}
			in = utils.AppendFixed32(in, uint32(v))
			{{- else if eq .Type "sfixed64"}}
			in = utils.AppendFixed64(in, uint64(v))
			{{- else if eq .Type "float"}}
			in = utils.AppendFixed32(in, math.Float32bits(v))
			{{- else if eq .Type "double"}}
			in = utils.AppendFixed64(in, math.Float64bits(v))
			{{- else if eq .Type "bool"}}
			if v { in = append(in, 1) } else { in = append(in, 0) }
			{{- else}}
			in = utils.AppendVarint(in, uint64(v))
			{{- end}}
		}
	}
{{- else if eq .Type "string"}}
	for _, v := range m.{{.Name}} {
		in = utils.AppendTag(in, {{$goName}}_{{.Name}}_Tag, utils.WireTypeLenDelim)
		in = utils.AppendLenDelim(in, unsafe.Slice(unsafe.StringData(v), len(v)))
	}
{{- else if eq .Type "bytes"}}
	for _, v := range m.{{.Name}} {
		in = utils.AppendTag(in, {{$goName}}_{{.Name}}_Tag, utils.WireTypeLenDelim)
		in = utils.AppendLenDelim(in, v)
	}
{{- else}}
	for i := range m.{{.Name}} {
		sub := m.{{.Name}}[i].ProtobufSize()
		if sub > 0 {
			in = utils.AppendTag(in, {{$goName}}_{{.Name}}_Tag, utils.WireTypeLenDelim)
			in = utils.AppendVarint(in, uint64(sub))
			in = m.{{.Name}}[i].ToProtobuf(in)
		}
	}
{{- end}}
{{- else if .IsMsg}}
	{
		sub := m.{{.Name}}.ProtobufSize()
		if sub > 0 {
			in = utils.AppendTag(in, {{$goName}}_{{.Name}}_Tag, utils.WireTypeLenDelim)
			in = utils.AppendVarint(in, uint64(sub))
			in = m.{{.Name}}.ToProtobuf(in)
		}
	}
{{- else if eq .Type "double"}}
	if m.{{.Name}} != 0 {
		in = utils.AppendTag(in, {{$goName}}_{{.Name}}_Tag, utils.WireType64bit)
		in = utils.AppendFixed64(in, math.Float64bits(m.{{.Name}}))
	}
{{- else if eq .Type "float"}}
	if m.{{.Name}} != 0 {
		in = utils.AppendTag(in, {{$goName}}_{{.Name}}_Tag, utils.WireType32bit)
		in = utils.AppendFixed32(in, math.Float32bits(m.{{.Name}}))
	}
{{- else if eq .Type "fixed32"}}
	if m.{{.Name}} != 0 {
		in = utils.AppendTag(in, {{$goName}}_{{.Name}}_Tag, utils.WireType32bit)
		in = utils.AppendFixed32(in, m.{{.Name}})
	}
{{- else if eq .Type "fixed64"}}
	if m.{{.Name}} != 0 {
		in = utils.AppendTag(in, {{$goName}}_{{.Name}}_Tag, utils.WireType64bit)
		in = utils.AppendFixed64(in, m.{{.Name}})
	}
{{- else if eq .Type "sfixed32"}}
	if m.{{.Name}} != 0 {
		in = utils.AppendTag(in, {{$goName}}_{{.Name}}_Tag, utils.WireType32bit)
		in = utils.AppendFixed32(in, uint32(m.{{.Name}}))
	}
{{- else if eq .Type "sfixed64"}}
	if m.{{.Name}} != 0 {
		in = utils.AppendTag(in, {{$goName}}_{{.Name}}_Tag, utils.WireType64bit)
		in = utils.AppendFixed64(in, uint64(m.{{.Name}}))
	}
{{- else if eq .Type "sint32"}}
	if m.{{.Name}} != 0 {
		in = utils.AppendTag(in, {{$goName}}_{{.Name}}_Tag, utils.WireTypeVarint)
		in = utils.AppendSint32(in, m.{{.Name}})
	}
{{- else if eq .Type "sint64"}}
	if m.{{.Name}} != 0 {
		in = utils.AppendTag(in, {{$goName}}_{{.Name}}_Tag, utils.WireTypeVarint)
		in = utils.AppendSint64(in, m.{{.Name}})
	}
{{- else if eq .Type "bool"}}
	if m.{{.Name}} {
		in = utils.AppendTag(in, {{$goName}}_{{.Name}}_Tag, utils.WireTypeVarint)
		in = append(in, 1)
	}
{{- else if eq .Type "string"}}
	if m.{{.Name}} != "" {
		in = utils.AppendTag(in, {{$goName}}_{{.Name}}_Tag, utils.WireTypeLenDelim)
		in = utils.AppendLenDelim(in, unsafe.Slice(unsafe.StringData(m.{{.Name}}), len(m.{{.Name}})))
	}
{{- else if eq .Type "bytes"}}
	if len(m.{{.Name}}) > 0 {
		in = utils.AppendTag(in, {{$goName}}_{{.Name}}_Tag, utils.WireTypeLenDelim)
		in = utils.AppendLenDelim(in, m.{{.Name}})
	}
{{- else}}
	if m.{{.Name}} != 0 {
		in = utils.AppendTag(in, {{$goName}}_{{.Name}}_Tag, utils.WireTypeVarint)
		in = utils.AppendVarint(in, uint64(m.{{.Name}}))
	}
{{- end}}
{{- end}}
	return in
}

func (m *{{$goName}}) ToJSON(dst []byte) []byte {
	dst = append(dst, '{')
{{- range $i, $f := .Fields}}
{{- if gt $i 0}}
	dst = append(dst, ',')
{{- end}}
	dst = append(dst, '"')
	dst = append(dst, nameOf{{$goName}}{{$f.Name}}...)
	dst = append(dst, '"', ':')
{{- if $f.Map}}
	{
		dst = append(dst, '{')
		_jsonFirst := true
		for _k, _v := range m.{{$f.Name}} {
			if !_jsonFirst {
				dst = append(dst, ',')
			}
			_jsonFirst = false
			dst = append(dst, '"')
{{- if eq $f.MapKey "string"}}
			dst = utils.EncodeJSONString(_k, dst)
{{- else if eq $f.MapKey "bool"}}
			if _k {
				dst = append(dst, "true"...)
			} else {
				dst = append(dst, "false"...)
			}
{{- else if or (eq $f.MapKey "uint32") (eq $f.MapKey "uint64") (eq $f.MapKey "fixed32") (eq $f.MapKey "fixed64")}}
			dst = strconv.AppendUint(dst, uint64(_k), 10)
{{- else}}
			dst = strconv.AppendInt(dst, int64(_k), 10)
{{- end}}
			dst = append(dst, '"', ':')
{{- if eq $f.MapVal "string"}}
			dst = append(dst, '"')
			dst = utils.EncodeJSONString(_v, dst)
			dst = append(dst, '"')
{{- else if eq $f.MapVal "bool"}}
			if _v {
				dst = append(dst, "true"...)
			} else {
				dst = append(dst, "false"...)
			}
{{- else if eq $f.MapVal "double"}}
			{
				_fv := _v
				_iv := int64(_fv)
				if math.Round(_fv) == _fv && float64(_iv) == _fv {
					dst = strconv.AppendInt(dst, _iv, 10)
				} else {
					dst = strconv.AppendFloat(dst, _fv, 'f', -1, 64)
				}
			}
{{- else if eq $f.MapVal "float"}}
			{
				_fv := float64(_v)
				_iv := int64(_fv)
				if math.Round(_fv) == _fv && float64(_iv) == _fv {
					dst = strconv.AppendInt(dst, _iv, 10)
				} else {
					dst = strconv.AppendFloat(dst, _fv, 'f', -1, 32)
				}
			}
{{- else if or (eq $f.MapVal "uint32") (eq $f.MapVal "fixed32")}}
			dst = strconv.AppendUint(dst, uint64(_v), 10)
{{- else if or (eq $f.MapVal "uint64") (eq $f.MapVal "fixed64")}}
			if uint64(_v) > 9007199254740991 {
				dst = append(dst, '"')
				dst = strconv.AppendUint(dst, uint64(_v), 10)
				dst = append(dst, '"')
			} else {
				dst = strconv.AppendUint(dst, uint64(_v), 10)
			}
{{- else if eq $f.MapVal "bytes"}}
			dst = append(dst, '"')
			dst = base64.StdEncoding.AppendEncode(dst, _v)
			dst = append(dst, '"')
{{- else if mapValIsMsg $f.MapVal}}
			dst = _v.ToJSON(dst)
{{- else if or (eq $f.MapVal "int64") (eq $f.MapVal "sint64") (eq $f.MapVal "sfixed64")}}
			if int64(_v) > 9007199254740991 || int64(_v) < -9007199254740991 {
				dst = append(dst, '"')
				dst = strconv.AppendInt(dst, int64(_v), 10)
				dst = append(dst, '"')
			} else {
				dst = strconv.AppendInt(dst, int64(_v), 10)
			}
{{- else}}
			dst = strconv.AppendInt(dst, int64(_v), 10)
{{- end}}
		}
		dst = append(dst, '}')
	}
{{- else if $f.Repeated}}
	{
		dst = append(dst, '[')
		for _i, _v := range m.{{$f.Name}} {
			if _i > 0 {
				dst = append(dst, ',')
			}
{{- if $f.IsMsg}}
			dst = _v.ToJSON(dst)
{{- else if eq $f.Type "string"}}
			dst = append(dst, '"')
			dst = utils.EncodeJSONString(_v, dst)
			dst = append(dst, '"')
{{- else if eq $f.Type "bool"}}
			if _v {
				dst = append(dst, "true"...)
			} else {
				dst = append(dst, "false"...)
			}
{{- else if eq $f.Type "double"}}
			{
				_fv := _v
				_iv := int64(_fv)
				if math.Round(_fv) == _fv && float64(_iv) == _fv {
					dst = strconv.AppendInt(dst, _iv, 10)
				} else {
					dst = strconv.AppendFloat(dst, _fv, 'f', -1, 64)
				}
			}
{{- else if eq $f.Type "float"}}
			{
				_fv := float64(_v)
				_iv := int64(_fv)
				if math.Round(_fv) == _fv && float64(_iv) == _fv {
					dst = strconv.AppendInt(dst, _iv, 10)
				} else {
					dst = strconv.AppendFloat(dst, _fv, 'f', -1, 32)
				}
			}
{{- else if or (eq $f.Type "uint32") (eq $f.Type "fixed32")}}
			dst = strconv.AppendUint(dst, uint64(_v), 10)
{{- else if or (eq $f.Type "uint64") (eq $f.Type "fixed64")}}
			if uint64(_v) > 9007199254740991 {
				dst = append(dst, '"')
				dst = strconv.AppendUint(dst, uint64(_v), 10)
				dst = append(dst, '"')
			} else {
				dst = strconv.AppendUint(dst, uint64(_v), 10)
			}
{{- else if eq $f.Type "bytes"}}
			dst = append(dst, '"')
			dst = base64.StdEncoding.AppendEncode(dst, _v)
			dst = append(dst, '"')
{{- else if or (eq $f.Type "int64") (eq $f.Type "sint64") (eq $f.Type "sfixed64")}}
			if int64(_v) > 9007199254740991 || int64(_v) < -9007199254740991 {
				dst = append(dst, '"')
				dst = strconv.AppendInt(dst, int64(_v), 10)
				dst = append(dst, '"')
			} else {
				dst = strconv.AppendInt(dst, int64(_v), 10)
			}
{{- else}}
			dst = strconv.AppendInt(dst, int64(_v), 10)
{{- end}}
		}
		dst = append(dst, ']')
	}
{{- else if $f.IsMsg}}
	dst = m.{{$f.Name}}.ToJSON(dst)
{{- else if eq $f.Type "string"}}
	dst = append(dst, '"')
	dst = utils.EncodeJSONString(m.{{$f.Name}}, dst)
	dst = append(dst, '"')
{{- else if eq $f.Type "bool"}}
	if m.{{$f.Name}} {
		dst = append(dst, "true"...)
	} else {
		dst = append(dst, "false"...)
	}
{{- else if eq $f.Type "double"}}
	{
		_fv := m.{{$f.Name}}
		_iv := int64(_fv)
		if math.Round(_fv) == _fv && float64(_iv) == _fv {
			dst = strconv.AppendInt(dst, _iv, 10)
		} else {
			dst = strconv.AppendFloat(dst, _fv, 'f', -1, 64)
		}
	}
{{- else if eq $f.Type "float"}}
	{
		_fv := float64(m.{{$f.Name}})
		_iv := int64(_fv)
		if math.Round(_fv) == _fv && float64(_iv) == _fv {
			dst = strconv.AppendInt(dst, _iv, 10)
		} else {
			dst = strconv.AppendFloat(dst, _fv, 'f', -1, 32)
		}
	}
{{- else if or (eq $f.Type "uint32") (eq $f.Type "fixed32")}}
	dst = strconv.AppendUint(dst, uint64(m.{{$f.Name}}), 10)
{{- else if or (eq $f.Type "uint64") (eq $f.Type "fixed64")}}
	if uint64(m.{{$f.Name}}) > 9007199254740991 {
		dst = append(dst, '"')
		dst = strconv.AppendUint(dst, uint64(m.{{$f.Name}}), 10)
		dst = append(dst, '"')
	} else {
		dst = strconv.AppendUint(dst, uint64(m.{{$f.Name}}), 10)
	}
{{- else if eq $f.Type "bytes"}}
	dst = append(dst, '"')
	dst = base64.StdEncoding.AppendEncode(dst, m.{{$f.Name}})
	dst = append(dst, '"')
{{- else if or (eq $f.Type "int64") (eq $f.Type "sint64") (eq $f.Type "sfixed64")}}
	if int64(m.{{$f.Name}}) > 9007199254740991 || int64(m.{{$f.Name}}) < -9007199254740991 {
		dst = append(dst, '"')
		dst = strconv.AppendInt(dst, int64(m.{{$f.Name}}), 10)
		dst = append(dst, '"')
	} else {
		dst = strconv.AppendInt(dst, int64(m.{{$f.Name}}), 10)
	}
{{- else}}
	dst = strconv.AppendInt(dst, int64(m.{{$f.Name}}), 10)
{{- end}}
{{- end}}
	dst = append(dst, '}')
	return dst
}

{{msgCommentBlock .Comment}}// Readonly{{$goName}} readonly struct.
// Fields (including rawBuffer) are sorted with the fieldalignment strategy for
// minimal memory padding and minimal GC scan range.
type Readonly{{$goName}} struct {
{{- range .ReaderFields}}
{{- if .IsRawBuf}}
	rawBuffer []byte
{{- else}}
{{fieldCommentBlock .Comment}}	{{.Name}} {{.ReaderType}} `json:"{{.JsonName}},omitempty"`
{{- end}}
{{- end}}
}

func (r *Readonly{{$goName}}) Clone(dst *{{$goName}}) *{{$goName}} {
	if dst == nil {
		dst = &{{$goName}}{}
	}
	if dst.arena == nil {
		dst.arena = make([]byte, 0, len(r.rawBuffer))
	} else {
		dst.arena = dst.arena[:0]
	}
{{- range .Fields}}
{{- if .Map}}
	if len(r.{{.Name}}) > 0 {
		if dst.{{.Name}} == nil {
			dst.{{.Name}} = make({{.GoType}}, len(r.{{.Name}}))
		} else {
			for _k := range dst.{{.Name}} { delete(dst.{{.Name}}, _k) }
		}
		for _rk, _rv := range r.{{.Name}} {
			{{- if eq .MapKey "string"}}
			{
				_kloc := len(dst.arena)
				dst.arena = append(dst.arena, _rk...)
				_nk := unsafe.String(&dst.arena[_kloc], len(_rk))
				{{- if eq .MapVal "string"}}
				if len(_rv) > 0 {
					_vloc := len(dst.arena)
					dst.arena = append(dst.arena, _rv...)
					dst.{{.Name}}[_nk] = unsafe.String(&dst.arena[_vloc], len(_rv))
				} else {
					dst.{{.Name}}[_nk] = ""
				}
				{{- else if eq .MapVal "bytes"}}
				if len(_rv) > 0 {
					_vloc := len(dst.arena)
					dst.arena = append(dst.arena, _rv...)
					_vend := _vloc + len(_rv)
					dst.{{.Name}}[_nk] = dst.arena[_vloc:_vend:_vend]
				} else {
					dst.{{.Name}}[_nk] = nil
				}
				{{- else if mapValIsMsg .MapVal}}
				var _nv {{mapValGoType .MapVal}}
				_rv.Clone(&_nv)
				dst.{{.Name}}[_nk] = _nv
				{{- else}}
				dst.{{.Name}}[_nk] = _rv
				{{- end}}
			}
			{{- else}}
			{
				{{- if eq .MapVal "string"}}
				if len(_rv) > 0 {
					_vloc := len(dst.arena)
					dst.arena = append(dst.arena, _rv...)
					dst.{{.Name}}[_rk] = unsafe.String(&dst.arena[_vloc], len(_rv))
				} else {
					dst.{{.Name}}[_rk] = ""
				}
				{{- else if eq .MapVal "bytes"}}
				if len(_rv) > 0 {
					_vloc := len(dst.arena)
					dst.arena = append(dst.arena, _rv...)
					_vend := _vloc + len(_rv)
					dst.{{.Name}}[_rk] = dst.arena[_vloc:_vend:_vend]
				} else {
					dst.{{.Name}}[_rk] = nil
				}
				{{- else if mapValIsMsg .MapVal}}
				var _nv {{mapValGoType .MapVal}}
				_rv.Clone(&_nv)
				dst.{{.Name}}[_rk] = _nv
				{{- else}}
				dst.{{.Name}}[_rk] = _rv
				{{- end}}
			}
			{{- end}}
		}
	}
{{- else if .Repeated}}
{{- if isPackable .Type}}
	if len(r.{{.Name}}) > 0 {
		{{- if is8ByteNumeric .Type}}
		if _rem := len(dst.arena) & 7; _rem != 0 {
			dst.arena = append(dst.arena, make([]byte, 8-_rem)...)
		}
		_nb := len(r.{{.Name}}) * 8
		{{- else if eq .Type "bool"}}
		_nb := len(r.{{.Name}}) * 1
		{{- else}}
		if _rem := len(dst.arena) & 3; _rem != 0 {
			dst.arena = append(dst.arena, make([]byte, 4-_rem)...)
		}
		_nb := len(r.{{.Name}}) * 4
		{{- end}}
		if cap(dst.arena)-len(dst.arena) < _nb {
			_nc := cap(dst.arena)*2 + _nb
			_na := make([]byte, len(dst.arena), _nc)
			copy(_na, dst.arena)
			dst.arena = _na
		}
		_loc := len(dst.arena)
		dst.arena = dst.arena[:_loc+_nb]
		copy(dst.arena[_loc:], unsafe.Slice((*byte)(unsafe.Pointer(&r.{{.Name}}[0])), _nb))
		_n := len(r.{{.Name}})
		dst.{{.Name}} = unsafe.Slice((*{{elemType .GoType}})(unsafe.Pointer(&dst.arena[_loc])), _n)
	} else {
		dst.{{.Name}} = dst.{{.Name}}[:0]
	}
{{- else if eq .Type "string"}}
	if len(r.{{.Name}}) > 0 {
		_total := 0
		for _, _s := range r.{{.Name}} { _total += len(_s) }
		if cap(dst.arena)-len(dst.arena) < _total {
			_nc := cap(dst.arena)*2 + _total
			_na := make([]byte, len(dst.arena), _nc)
			copy(_na, dst.arena)
			dst.arena = _na
		}
		if cap(dst.{{.Name}}) >= len(r.{{.Name}}) {
			dst.{{.Name}} = dst.{{.Name}}[:len(r.{{.Name}})]
		} else {
			dst.{{.Name}} = make([]string, len(r.{{.Name}}))
		}
		for _i, _s := range r.{{.Name}} {
			_loc := len(dst.arena)
			dst.arena = append(dst.arena, _s...)
			dst.{{.Name}}[_i] = unsafe.String(&dst.arena[_loc], len(_s))
		}
	} else {
		dst.{{.Name}} = dst.{{.Name}}[:0]
	}
{{- else if eq .Type "bytes"}}
	if len(r.{{.Name}}) > 0 {
		_total := 0
		for _, _b := range r.{{.Name}} { _total += len(_b) }
		if cap(dst.arena)-len(dst.arena) < _total {
			_nc := cap(dst.arena)*2 + _total
			_na := make([]byte, len(dst.arena), _nc)
			copy(_na, dst.arena)
			dst.arena = _na
		}
		if cap(dst.{{.Name}}) >= len(r.{{.Name}}) {
			dst.{{.Name}} = dst.{{.Name}}[:len(r.{{.Name}})]
		} else {
			dst.{{.Name}} = make([][]byte, len(r.{{.Name}}))
		}
		for _i, _b := range r.{{.Name}} {
			_loc := len(dst.arena)
			dst.arena = append(dst.arena, _b...)
			_end := _loc + len(_b)
			dst.{{.Name}}[_i] = dst.arena[_loc:_end:_end]
		}
	} else {
		dst.{{.Name}} = dst.{{.Name}}[:0]
	}
{{- else if .IsMsg}}
	if len(r.{{.Name}}) > 0 {
		if cap(dst.{{.Name}}) >= len(r.{{.Name}}) {
			dst.{{.Name}} = dst.{{.Name}}[:len(r.{{.Name}})]
		} else {
			dst.{{.Name}} = make([]{{elemType .GoType}}, len(r.{{.Name}}))
		}
		for _i := range r.{{.Name}} {
			r.{{.Name}}[_i].Clone(&dst.{{.Name}}[_i])
		}
	} else {
		dst.{{.Name}} = dst.{{.Name}}[:0]
	}
{{- else}}
	// repeated enum: direct copy
	if len(r.{{.Name}}) > 0 {
		if cap(dst.{{.Name}}) >= len(r.{{.Name}}) {
			dst.{{.Name}} = dst.{{.Name}}[:len(r.{{.Name}})]
			copy(dst.{{.Name}}, r.{{.Name}})
		} else {
			dst.{{.Name}} = make([]{{elemType .GoType}}, len(r.{{.Name}}))
			copy(dst.{{.Name}}, r.{{.Name}})
		}
	} else {
		dst.{{.Name}} = dst.{{.Name}}[:0]
	}
{{- end}}
{{- else if .IsMsg}}
	r.{{.Name}}.Clone(&dst.{{.Name}})
{{- else if eq .Type "string"}}
	if len(r.{{.Name}}) > 0 {
		_loc := len(dst.arena)
		dst.arena = append(dst.arena, r.{{.Name}}...)
		dst.{{.Name}} = unsafe.String(&dst.arena[_loc], len(r.{{.Name}}))
	} else {
		dst.{{.Name}} = ""
	}
{{- else if eq .Type "bytes"}}
	if len(r.{{.Name}}) > 0 {
		_loc := len(dst.arena)
		dst.arena = append(dst.arena, r.{{.Name}}...)
		_end := _loc + len(r.{{.Name}})
		dst.{{.Name}} = dst.arena[_loc:_end:_end]
	} else {
		dst.{{.Name}} = nil
	}
{{- else}}
	dst.{{.Name}} = r.{{.Name}}
{{- end}}
{{- end}}
	return dst
}

func (r *Readonly{{$goName}}) Reset() {
	r.rawBuffer = r.rawBuffer[:0]
{{- range .Fields}}
{{- if .Map}}
	clear(r.{{.Name}})
{{- else if .Repeated}}
	r.{{.Name}} = r.{{.Name}}[:0]
{{- else if .IsMsg}}
	r.{{.Name}}.Reset()
{{- else if isSliceType .ReaderType}}
	r.{{.Name}} = r.{{.Name}}[:0]
{{- else}}
	r.{{.Name}} = {{readerZero .ReaderType}}
{{- end}}
{{- end}}
}

func (r *Readonly{{$goName}}) FromProtobuf(in []byte) error {
	r.rawBuffer = in
	var err error
	for len(in) > 0 {
		var fieldNum int
		var wt utils.WireType
		fieldNum, wt, in, err = utils.ConsumeTag(in)
		if err != nil {
			return err
		}
		switch fieldNum {
{{- range .Fields}}
		case {{$goName}}_{{.Name}}_Tag: // {{.Name}}
{{- if .Map}}
			var entryData []byte
			entryData, in, err = utils.ConsumeBytes(in)
			if err != nil { return err }
			var mKey {{mapKeyGoType .MapKey}}
			var mVal {{mapValGoType .MapVal}}
			for len(entryData) > 0 {
				var efn int
				var ewt utils.WireType
				efn, ewt, entryData, err = utils.ConsumeTag(entryData)
				_ = ewt
				if err != nil { return err }
				switch efn {
				case 1:
					mKey, entryData, err = {{readFunc .MapKey}}(entryData)
				case 2:
					mVal, entryData, err = {{readFunc .MapVal}}(entryData)
				}
				if err != nil { return err }
			}
			if r.{{.Name}} == nil {
				r.{{.Name}} = make({{.ReaderType}})
			}
			r.{{.Name}}[mKey] = mVal
{{- else if .Repeated}}
{{- if isPackable .Type}}
			var packedData []byte
			packedData, in, err = utils.ConsumeBytes(in)
			if err != nil { return err }
			for len(packedData) > 0 {
				var pv {{mapKeyGoType .Type}}
				pv, packedData, err = {{readFunc .Type}}(packedData)
				if err != nil { return err }
				r.{{.Name}} = append(r.{{.Name}}, pv)
			}
{{- else if eq .Type "string"}}
			var sv string
			sv, in, err = utils.ReadString(in)
			if err != nil { return err }
			r.{{.Name}} = append(r.{{.Name}}, sv)
{{- else if eq .Type "bytes"}}
			var bv []byte
			bv, in, err = utils.ReadBytes(in)
			if err != nil { return err }
			r.{{.Name}} = append(r.{{.Name}}, bv)
{{- else}}
			var subData []byte
			subData, in, err = utils.ConsumeBytes(in)
			if err != nil { return err }
			var elem {{readerElemType .}}
			if err = elem.FromProtobuf(subData); err != nil { return err }
			r.{{.Name}} = append(r.{{.Name}}, elem)
{{- end}}
{{- else if .IsMsg}}
			var subData []byte
			subData, in, err = utils.ConsumeBytes(in)
			if err != nil { return err }
			if err = r.{{.Name}}.FromProtobuf(subData); err != nil { return err }
{{- else if eq .Type "double"}}
			r.{{.Name}}, in, err = utils.ReadDouble(in)
			if err != nil { return err }
{{- else if eq .Type "float"}}
			r.{{.Name}}, in, err = utils.ReadFloat(in)
			if err != nil { return err }
{{- else if eq .Type "fixed32"}}
			r.{{.Name}}, in, err = utils.ReadFixed32(in)
			if err != nil { return err }
{{- else if eq .Type "fixed64"}}
			r.{{.Name}}, in, err = utils.ReadFixed64(in)
			if err != nil { return err }
{{- else if eq .Type "sfixed32"}}
			r.{{.Name}}, in, err = utils.ReadSfixed32(in)
			if err != nil { return err }
{{- else if eq .Type "sfixed64"}}
			r.{{.Name}}, in, err = utils.ReadSfixed64(in)
			if err != nil { return err }
{{- else if eq .Type "sint32"}}
			r.{{.Name}}, in, err = utils.ReadSint32(in)
			if err != nil { return err }
{{- else if eq .Type "sint64"}}
			r.{{.Name}}, in, err = utils.ReadSint64(in)
			if err != nil { return err }
{{- else if eq .Type "int32"}}
			r.{{.Name}}, in, err = utils.ReadInt32(in)
			if err != nil { return err }
{{- else if eq .Type "int64"}}
			r.{{.Name}}, in, err = utils.ReadInt64(in)
			if err != nil { return err }
{{- else if eq .Type "uint32"}}
			r.{{.Name}}, in, err = utils.ReadUint32(in)
			if err != nil { return err }
{{- else if eq .Type "uint64"}}
			r.{{.Name}}, in, err = utils.ReadUint64(in)
			if err != nil { return err }
{{- else if eq .Type "bool"}}
			r.{{.Name}}, in, err = utils.ReadBool(in)
			if err != nil { return err }
{{- else if eq .Type "string"}}
			r.{{.Name}}, in, err = utils.ReadString(in)
			if err != nil { return err }
{{- else if eq .Type "bytes"}}
			r.{{.Name}}, in, err = utils.ReadBytes(in)
			if err != nil { return err }
{{- else}}
			var ev int32
			ev, in, err = utils.ReadInt32(in)
			if err != nil { return err }
			r.{{.Name}} = {{.ReaderType}}(ev)
{{- end}}
			_ = wt
{{- end}}
		default:
			var err2 error
			in, err2 = utils.SkipField(wt, in)
			if err2 != nil { return err2 }
		}
	}
	return nil
}

func (r *Readonly{{$goName}}) fromJSONValue(obj *fastjson.Object) error {
	var visitErr error
	obj.Visit(func(k []byte, v *fastjson.Value) {
		if visitErr != nil {
			return
		}
		switch string(k) {
{{- range .Fields}}
		case nameOf{{$goName}}{{.Name}}:
{{- if .Map}}
			_mapObj, _e := v.Object()
			if _e != nil { visitErr = _e; return }
			if r.{{.Name}} == nil { r.{{.Name}} = make({{.ReaderType}}) }
			_mapObj.Visit(func(mk []byte, mv *fastjson.Value) {
				if visitErr != nil { return }
				var mKey {{mapKeyGoType .MapKey}}
{{- $kc := jsonMapKeyClass .MapKey}}
{{- if eq $kc "string"}}
				mKey = unsafe.String(unsafe.SliceData(mk), len(mk))
{{- else if eq $kc "bool"}}
				mKey = unsafe.String(unsafe.SliceData(mk), len(mk)) == "true"
{{- else if eq $kc "signed32"}}
				_mk64, _ek := strconv.ParseInt(unsafe.String(unsafe.SliceData(mk), len(mk)), 10, 32)
				if _ek != nil { visitErr = _ek; return }
				mKey = {{mapKeyGoType .MapKey}}(_mk64)
{{- else if eq $kc "signed64"}}
				_mk64, _ek := strconv.ParseInt(unsafe.String(unsafe.SliceData(mk), len(mk)), 10, 64)
				if _ek != nil { visitErr = _ek; return }
				mKey = _mk64
{{- else if eq $kc "unsigned32"}}
				_mku64, _ek := strconv.ParseUint(unsafe.String(unsafe.SliceData(mk), len(mk)), 10, 32)
				if _ek != nil { visitErr = _ek; return }
				mKey = {{mapKeyGoType .MapKey}}(_mku64)
{{- else if eq $kc "unsigned64"}}
				_mku64, _ek := strconv.ParseUint(unsafe.String(unsafe.SliceData(mk), len(mk)), 10, 64)
				if _ek != nil { visitErr = _ek; return }
				mKey = _mku64
{{- end}}
				var mVal {{mapValGoType .MapVal}}
{{- if mapValIsMsg .MapVal}}
				_subObj, _eo := mv.Object()
				if _eo != nil { visitErr = _eo; return }
				var _msgVal {{readonlyTypeName .MapVal}}
				if _eo2 := _msgVal.fromJSONValue(_subObj); _eo2 != nil { visitErr = _eo2; return }
				mVal = _msgVal
{{- else}}
{{- $vc := jsonScalarClass .MapVal}}
{{- if eq $vc "string"}}
				_b, _ev := mv.StringBytes()
				if _ev != nil { visitErr = _ev; return }
				mVal = unsafe.String(unsafe.SliceData(_b), len(_b))
{{- else if eq $vc "bytes"}}
				_b64, _ev := mv.StringBytes()
				if _ev != nil { visitErr = _ev; return }
				var _ev2 error
				mVal, _ev2 = base64.StdEncoding.AppendDecode(nil, _b64)
				if _ev2 != nil { visitErr = _ev2; return }
{{- else if eq $vc "bool"}}
				_bv, _ev := mv.Bool()
				if _ev != nil { visitErr = _ev; return }
				mVal = _bv
{{- else if eq $vc "float"}}
				_fv, _ev := mv.Float64()
				if _ev != nil { visitErr = _ev; return }
				mVal = {{mapValGoType .MapVal}}(_fv)
{{- else if eq $vc "signed"}}
				_iv, _ev := mv.Int64()
				if _ev != nil { visitErr = _ev; return }
				mVal = {{mapValGoType .MapVal}}(_iv)
{{- else if eq $vc "signed64"}}
				var _iv int64
				if mv.Type() == fastjson.TypeString {
					_sb, _ev := mv.StringBytes()
					if _ev != nil { visitErr = _ev; return }
					var _ev2 error
					_iv, _ev2 = strconv.ParseInt(unsafe.String(unsafe.SliceData(_sb), len(_sb)), 10, 64)
					if _ev2 != nil { visitErr = _ev2; return }
				} else {
					var _ev error
					_iv, _ev = mv.Int64()
					if _ev != nil { visitErr = _ev; return }
				}
				mVal = {{mapValGoType .MapVal}}(_iv)
{{- else if eq $vc "unsigned"}}
				_uv, _ev := mv.Uint64()
				if _ev != nil { visitErr = _ev; return }
				mVal = {{mapValGoType .MapVal}}(_uv)
{{- else if eq $vc "unsigned64"}}
				var _uv uint64
				if mv.Type() == fastjson.TypeString {
					_sb, _ev := mv.StringBytes()
					if _ev != nil { visitErr = _ev; return }
					var _ev2 error
					_uv, _ev2 = strconv.ParseUint(unsafe.String(unsafe.SliceData(_sb), len(_sb)), 10, 64)
					if _ev2 != nil { visitErr = _ev2; return }
				} else {
					var _ev error
					_uv, _ev = mv.Uint64()
					if _ev != nil { visitErr = _ev; return }
				}
				mVal = {{mapValGoType .MapVal}}(_uv)
{{- end}}
{{- end}}
				r.{{.Name}}[mKey] = mVal
			})
{{- else if .Repeated}}
			_arr, _e := v.Array()
			if _e != nil { visitErr = _e; return }
			r.{{.Name}} = r.{{.Name}}[:0]
{{- if .IsMsg}}
			for _, _item := range _arr {
				var _elem {{elemType .ReaderType}}
				_subObj, _eo := _item.Object()
				if _eo != nil { visitErr = _eo; return }
				if _eo2 := _elem.fromJSONValue(_subObj); _eo2 != nil { visitErr = _eo2; return }
				r.{{.Name}} = append(r.{{.Name}}, _elem)
			}
{{- else if .IsEnum}}
			for _, _item := range _arr {
				_iv, _ei := _item.Int64()
				if _ei != nil { visitErr = _ei; return }
				r.{{.Name}} = append(r.{{.Name}}, {{elemType .ReaderType}}(_iv))
			}
{{- else}}
{{- $sc := jsonScalarClass .Type}}
			for _, _item := range _arr {
{{- if eq $sc "string"}}
				_b, _ei := _item.StringBytes()
				if _ei != nil { visitErr = _ei; return }
				r.{{.Name}} = append(r.{{.Name}}, unsafe.String(unsafe.SliceData(_b), len(_b)))
{{- else if eq $sc "bytes"}}
				_b64, _ei := _item.StringBytes()
				if _ei != nil { visitErr = _ei; return }
				var _dec []byte
				var _ei2 error
				_dec, _ei2 = base64.StdEncoding.AppendDecode(nil, _b64)
				if _ei2 != nil { visitErr = _ei2; return }
				r.{{.Name}} = append(r.{{.Name}}, _dec)
{{- else if eq $sc "bool"}}
				_bv, _ei := _item.Bool()
				if _ei != nil { visitErr = _ei; return }
				r.{{.Name}} = append(r.{{.Name}}, _bv)
{{- else if eq $sc "float"}}
				_fv, _ei := _item.Float64()
				if _ei != nil { visitErr = _ei; return }
				r.{{.Name}} = append(r.{{.Name}}, {{elemType .ReaderType}}(_fv))
{{- else if eq $sc "signed"}}
				_iv, _ei := _item.Int64()
				if _ei != nil { visitErr = _ei; return }
				r.{{.Name}} = append(r.{{.Name}}, {{elemType .ReaderType}}(_iv))
{{- else if eq $sc "signed64"}}
				var _iv int64
				if _item.Type() == fastjson.TypeString {
					_sb, _ei := _item.StringBytes()
					if _ei != nil { visitErr = _ei; return }
					var _ei2 error
					_iv, _ei2 = strconv.ParseInt(unsafe.String(unsafe.SliceData(_sb), len(_sb)), 10, 64)
					if _ei2 != nil { visitErr = _ei2; return }
				} else {
					var _ei error
					_iv, _ei = _item.Int64()
					if _ei != nil { visitErr = _ei; return }
				}
				r.{{.Name}} = append(r.{{.Name}}, {{elemType .ReaderType}}(_iv))
{{- else if eq $sc "unsigned"}}
				_uv, _ei := _item.Uint64()
				if _ei != nil { visitErr = _ei; return }
				r.{{.Name}} = append(r.{{.Name}}, {{elemType .ReaderType}}(_uv))
{{- else if eq $sc "unsigned64"}}
				var _uv uint64
				if _item.Type() == fastjson.TypeString {
					_sb, _ei := _item.StringBytes()
					if _ei != nil { visitErr = _ei; return }
					var _ei2 error
					_uv, _ei2 = strconv.ParseUint(unsafe.String(unsafe.SliceData(_sb), len(_sb)), 10, 64)
					if _ei2 != nil { visitErr = _ei2; return }
				} else {
					var _ei error
					_uv, _ei = _item.Uint64()
					if _ei != nil { visitErr = _ei; return }
				}
				r.{{.Name}} = append(r.{{.Name}}, {{elemType .ReaderType}}(_uv))
{{- end}}
			}
{{- end}}
{{- else if .IsMsg}}
			_subObj, _e := v.Object()
			if _e != nil { visitErr = _e; return }
			if _e2 := r.{{.Name}}.fromJSONValue(_subObj); _e2 != nil { visitErr = _e2 }
{{- else if .IsEnum}}
			_iv, _e := v.Int64()
			if _e != nil { visitErr = _e; return }
			r.{{.Name}} = {{.ReaderType}}(_iv)
{{- else}}
{{- $sc := jsonScalarClass .Type}}
{{- if eq $sc "string"}}
			_b, _e := v.StringBytes()
			if _e != nil { visitErr = _e; return }
			r.{{.Name}} = unsafe.String(unsafe.SliceData(_b), len(_b))
{{- else if eq $sc "bytes"}}
			_b64, _e := v.StringBytes()
			if _e != nil { visitErr = _e; return }
			var _e2 error
			r.{{.Name}}, _e2 = base64.StdEncoding.AppendDecode(r.{{.Name}}[:0], _b64)
			if _e2 != nil { visitErr = _e2; return }
{{- else if eq $sc "bool"}}
			_bv, _e := v.Bool()
			if _e != nil { visitErr = _e; return }
			r.{{.Name}} = _bv
{{- else if eq $sc "float"}}
			_fv, _e := v.Float64()
			if _e != nil { visitErr = _e; return }
			r.{{.Name}} = {{.ReaderType}}(_fv)
{{- else if eq $sc "signed"}}
			_iv, _e := v.Int64()
			if _e != nil { visitErr = _e; return }
			r.{{.Name}} = {{.ReaderType}}(_iv)
{{- else if eq $sc "signed64"}}
			var _iv int64
			if v.Type() == fastjson.TypeString {
				_sb, _e := v.StringBytes()
				if _e != nil { visitErr = _e; return }
				var _e2 error
				_iv, _e2 = strconv.ParseInt(unsafe.String(unsafe.SliceData(_sb), len(_sb)), 10, 64)
				if _e2 != nil { visitErr = _e2; return }
			} else {
				var _e error
				_iv, _e = v.Int64()
				if _e != nil { visitErr = _e; return }
			}
			r.{{.Name}} = {{.ReaderType}}(_iv)
{{- else if eq $sc "unsigned"}}
			_uv, _e := v.Uint64()
			if _e != nil { visitErr = _e; return }
			r.{{.Name}} = {{.ReaderType}}(_uv)
{{- else if eq $sc "unsigned64"}}
			var _uv uint64
			if v.Type() == fastjson.TypeString {
				_sb, _e := v.StringBytes()
				if _e != nil { visitErr = _e; return }
				var _e2 error
				_uv, _e2 = strconv.ParseUint(unsafe.String(unsafe.SliceData(_sb), len(_sb)), 10, 64)
				if _e2 != nil { visitErr = _e2; return }
			} else {
				var _e error
				_uv, _e = v.Uint64()
				if _e != nil { visitErr = _e; return }
			}
			r.{{.Name}} = {{.ReaderType}}(_uv)
{{- end}}
{{- end}}
{{- end}}
		}
	})
	return visitErr
}

func (r *Readonly{{$goName}}) FromJSON(src []byte) error {
	r.rawBuffer = src
	p := jsonParserPool.Get()
	defer func(){
		p.Reset()
		jsonParserPool.Put(p)
	}()
	v, err := p.Parse(unsafe.String(&src[0], len(src)))
	if err != nil {
		return err
	}
	obj, err := v.Object()
	if err != nil {
		return err
	}
	return r.fromJSONValue(obj)
}

{{end}}
