// Code generated by https://github.com/ahfuzhang/BaoHuLu. DO NOT EDIT.

package {{.Package}}

import (
	"bytes"
	"encoding/json"
{{- if anyMsgHasNumericBoundary .Messages}}
	"math"
{{- end}}
	"testing"

	"github.com/ahfuzhang/BaoHuLu/dependencies/golang/utils"
)

{{range .Messages}}
{{- $goName := .GoName}}
{{- $roName := printf "Readonly%s" $goName}}

// ─── {{$goName}} ──────────────────────────────────────────────────────────────

// makeSample{{$goName}} returns a writer struct pre-filled with representative
// non-zero values. Maps have exactly one entry to avoid non-deterministic
// serialisation order.
func makeSample{{$goName}}() {{$goName}} {
	return {{$goName}}{
{{- range .Fields}}
		{{.Name}}: {{sampleLit .}},
{{- end}}
	}
}

func Test{{$goName}}Empty(t *testing.T) {
	m := &{{$goName}}{}
	if got := m.ProtobufSize(); got != 0 {
		t.Fatalf("ProtobufSize() = %d, want 0 for empty {{$goName}}", got)
	}
	out := m.ToProtobuf(nil)
	if len(out) != 0 {
		t.Fatalf("ToProtobuf() = %d bytes, want 0 for empty {{$goName}}", len(out))
	}
}

func Test{{$goName}}ProtobufRoundtrip(t *testing.T) {
	w := makeSample{{$goName}}()
	sz := w.ProtobufSize()
	buf := make([]byte, 0, sz)
	buf = w.ToProtobuf(buf)
	if len(buf) != sz {
		t.Fatalf("ProtobufSize=%d but ToProtobuf produced %d bytes", sz, len(buf))
	}

	var r {{$roName}}
	if err := r.FromProtobuf(buf); err != nil {
		t.Fatalf("FromProtobuf error: %v", err)
	}

	// Clone → re-serialize → compare bytes (proves lossless roundtrip).
	w2 := r.Clone(nil)
	buf2 := w2.ToProtobuf(make([]byte, 0, w2.ProtobufSize()))
	if !bytes.Equal(buf, buf2) {
		t.Fatalf("protobuf roundtrip mismatch:\n  want %v\n  got  %v", buf, buf2)
	}
}

// Test{{$goName}}JSONRoundtrip checks two things:
//  1. encoding/json (stdlib) can parse the output of ToJSON() and produce a
//     struct whose re-serialisation via ToJSON() is byte-identical.
//     (Skipped when the struct has bool-keyed maps: encoding/json cannot decode
//     those. See https://pkg.go.dev/encoding/json – map key restrictions.)
//  2. The custom FromJSON+Clone path also produces a byte-identical result.
func Test{{$goName}}JSONRoundtrip(t *testing.T) {
	w := makeSample{{$goName}}()
	j := w.ToJSON(nil)

{{if not (skipEncodingJSON .Fields) -}}
	// ── Part 1: verify with encoding/json ────────────────────────────────────
	// Sample values are within JavaScript's safe-integer range, so
	// encoding/json can decode all numeric fields without precision loss.
	var decoded {{$goName}}
	if err := json.Unmarshal(j, &decoded); err != nil {
		t.Fatalf("encoding/json.Unmarshal error: %v\nJSON: %s", err, j)
	}
	// Re-serialise the decoded struct using our custom ToJSON and compare.
	// Any field that encoding/json decoded incorrectly will produce a
	// different JSON output, catching mismatches early.
	jDecoded := decoded.ToJSON(nil)
	if !bytes.Equal(j, jDecoded) {
		t.Fatalf("encoding/json decoded struct differs from original:\n  original: %s\n  decoded:  %s", j, jDecoded)
	}

{{else -}}
	// ── Part 1 (encoding/json skipped) ───────────────────────────────────────
	// This struct contains a map[bool]T field. encoding/json does not support
	// bool map keys for Unmarshal, so stdlib verification is skipped here.
	// The custom FromJSON path below still validates the JSON output fully.
	_ = json.Marshal // suppress unused import
{{end -}}
	// ── Part 2: verify with our custom FromJSON + Clone ───────────────────────
	var r {{$roName}}
	if err := r.FromJSON(j, nil); err != nil {
		t.Fatalf("FromJSON error: %v\nJSON: %s", err, j)
	}
	w2 := r.Clone(nil)
	j2 := w2.ToJSON(nil)
	if !bytes.Equal(j, j2) {
		t.Fatalf("JSON roundtrip (FromJSON+Clone) mismatch:\n  want: %s\n  got:  %s", j, j2)
	}
}
{{if hasLargeIntFields .Fields}}
// Test{{$goName}}JSONLargeIntegers verifies that int64/uint64 values exceeding
// JavaScript's Number.MAX_SAFE_INTEGER (2^53 − 1 = 9007199254740991) are
// serialised as quoted strings by ToJSON() and correctly recovered by FromJSON().
// encoding/json cannot decode quoted numeric strings into plain int64/uint64
// fields, so this test uses only the custom FromJSON path.
func Test{{$goName}}JSONLargeIntegers(t *testing.T) {
	w := {{$goName}}{
{{range largeIntFields .Fields -}}
		{{.Name}}: {{largeIntLit .}},
{{end -}}
	}
	j := w.ToJSON(nil)

	// Our custom FromJSON must recover the exact large values.
	var r {{$roName}}
	if err := r.FromJSON(j, nil); err != nil {
		t.Fatalf("FromJSON error: %v\nJSON: %s", err, j)
	}
{{range largeIntFields .Fields}}
	if r.{{.Name}} != w.{{.Name}} {
		t.Errorf("{{.Name}}: got %v, want %v", r.{{.Name}}, w.{{.Name}})
	}
{{end}}
	// Clone must also preserve large values.
	w2 := r.Clone(nil)
{{range largeIntFields .Fields}}
	if w2.{{.Name}} != w.{{.Name}} {
		t.Errorf("Clone {{.Name}}: got %v, want %v", w2.{{.Name}}, w.{{.Name}})
	}
{{end}}
}
{{end}}
{{if hasNumericBoundaryFields .Fields}}
// Test{{$goName}}NumericBoundary verifies that boundary values for numeric
// fields (int32/sint32/sfixed32 min/max, uint32/fixed32 max, int64 min/max,
// uint64 max, float32 ±max/smallest, float64 ±max/smallest) survive a full
// protobuf roundtrip without corruption.
func Test{{$goName}}NumericBoundary(t *testing.T) {
	cases := []struct {
		name string
		w    {{$goName}}
	}{
{{- range numericBoundaryCases .Fields}}
		{name: "{{.Label}}", w: {{$goName}}{ {{.FieldName}}: {{.Lit}} }},
{{- end}}
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			sz := tc.w.ProtobufSize()
			buf := tc.w.ToProtobuf(make([]byte, 0, sz))
			var r {{$roName}}
			if err := r.FromProtobuf(buf); err != nil {
				t.Fatalf("FromProtobuf error: %v", err)
			}
			w2 := r.Clone(nil)
			buf2 := w2.ToProtobuf(make([]byte, 0, w2.ProtobufSize()))
			if !bytes.Equal(buf, buf2) {
				t.Fatalf("protobuf roundtrip mismatch for %q:\n  want %v\n  got  %v", tc.name, buf, buf2)
			}
		})
	}
}
{{end}}
{{if hasFloatFields .Fields}}
// Test{{$goName}}FloatIntegerEquivalent verifies that float/double fields whose
// value is exactly representable as an integer (e.g. 4.0, 10.0) survive both a
// protobuf roundtrip and a JSON roundtrip without corruption.
// JSON serialisers sometimes emit "4" instead of "4.0" for such values; the
// custom parsers must accept both forms.
func Test{{$goName}}FloatIntegerEquivalent(t *testing.T) {
	w := {{$goName}}{
{{range floatFields .Fields -}}
		{{.Name}}: {{floatIntLit .}},
{{end -}}
	}

	// ── Protobuf roundtrip ────────────────────────────────────────────────────
	buf := w.ToProtobuf(make([]byte, 0, w.ProtobufSize()))
	var r {{$roName}}
	if err := r.FromProtobuf(buf); err != nil {
		t.Fatalf("FromProtobuf error: %v", err)
	}
	w2 := r.Clone(nil)
	buf2 := w2.ToProtobuf(make([]byte, 0, w2.ProtobufSize()))
	if !bytes.Equal(buf, buf2) {
		t.Fatalf("protobuf roundtrip mismatch:\n  want %v\n  got  %v", buf, buf2)
	}

	// ── JSON roundtrip ────────────────────────────────────────────────────────
	j := w.ToJSON(nil)
	var r2 {{$roName}}
	if err := r2.FromJSON(j, nil); err != nil {
		t.Fatalf("FromJSON error: %v\nJSON: %s", err, j)
	}
	w3 := r2.Clone(nil)
{{range floatFields .Fields}}
	if w3.{{.Name}} != w.{{.Name}} {
		t.Errorf("JSON roundtrip {{.Name}}: got %v, want %v", w3.{{.Name}}, w.{{.Name}})
	}
{{end -}}
}
{{end}}
{{- $strf := firstStringScalarField .Fields}}
{{if $strf}}
// Test{{$goName}}StringEscapes verifies that strings containing special escape
// characters (\n newline, \t tab, \" double-quote, \\ backslash) survive both
// a protobuf roundtrip and a JSON roundtrip without mangling.
// Field under test: {{$strf.Name}} (string)
func Test{{$goName}}StringEscapes(t *testing.T) {
	// The value exercises all four common escape sequences at once.
	escStr := "hello\nworld\ttab\"quote\\backslash"
	w := {{$goName}}{
		{{$strf.Name}}: escStr,
	}

	// ── Protobuf roundtrip ────────────────────────────────────────────────────
	buf := w.ToProtobuf(make([]byte, 0, w.ProtobufSize()))
	var r {{$roName}}
	if err := r.FromProtobuf(buf); err != nil {
		t.Fatalf("FromProtobuf error: %v", err)
	}
	w2 := r.Clone(nil)
	if w2.{{$strf.Name}} != escStr {
		t.Errorf("protobuf roundtrip: got %q, want %q", w2.{{$strf.Name}}, escStr)
	}

	// ── JSON roundtrip ────────────────────────────────────────────────────────
	j := w.ToJSON(nil)
	var r2 {{$roName}}
	if err := r2.FromJSON(j, nil); err != nil {
		t.Fatalf("FromJSON error: %v\nJSON: %s", err, j)
	}
	w3 := r2.Clone(nil)
	if w3.{{$strf.Name}} != escStr {
		t.Errorf("JSON roundtrip: got %q, want %q", w3.{{$strf.Name}}, escStr)
	}
}
{{end}}
func Test{{$goName}}Reset(t *testing.T) {
	w := makeSample{{$goName}}()
	w.Reset()
	if got := w.ProtobufSize(); got != 0 {
		t.Errorf("ProtobufSize() = %d after Reset(), want 0", got)
	}
}

func Test{{$roName}}Reset(t *testing.T) {
	w := makeSample{{$goName}}()
	buf := w.ToProtobuf(make([]byte, 0, w.ProtobufSize()))
	var r {{$roName}}
	if err := r.FromProtobuf(buf); err != nil {
		t.Fatalf("FromProtobuf error: %v", err)
	}
	r.Reset()
}

func Test{{$goName}}FromProtobufEmpty(t *testing.T) {
	var r {{$roName}}
	if err := r.FromProtobuf(nil); err != nil {
		t.Fatalf("FromProtobuf(nil) error: %v", err)
	}
	if err := r.FromProtobuf([]byte{}); err != nil {
		t.Fatalf("FromProtobuf(empty) error: %v", err)
	}
}

func Test{{$goName}}FromProtobufUnknownField(t *testing.T) {
	// unknownVarintField100: field 100, wire-type 0, value 1
	//   tag  = (100 << 3) | 0 = 800 → varint [0xA0, 0x06]
	//   value = varint(1)             → [0x01]
	unknownVarintField100 := []byte{0xA0, 0x06, 0x01}
	var r {{$roName}}
	if err := r.FromProtobuf(unknownVarintField100); err != nil {
		t.Fatalf("unexpected error for unknown protobuf field: %v", err)
	}
}

// Test{{$goName}}FromProtobufBadTag verifies that a truncated/invalid varint
// tag byte causes FromProtobuf to return an error (exercises the ConsumeTag
// error branch).
func Test{{$goName}}FromProtobufBadTag(t *testing.T) {
	// badTagVarint: single-byte incomplete multi-byte varint (high bit set, no continuation)
	badTagVarint := []byte{0x80}
	var r {{$roName}}
	if err := r.FromProtobuf(badTagVarint); err == nil {
		t.Error("expected error for bad varint tag, got nil")
	}
}

// Test{{$goName}}FromProtobufSkipError verifies that an unknown LenDelim field
// that claims more bytes than are present causes FromProtobuf to return an
// error (exercises the SkipField error branch in the default case).
func Test{{$goName}}FromProtobufSkipError(t *testing.T) {
	// unknownLenDelimField100: field 100, wire-type 2/LenDelim, claims 100 bytes but supplies none
	//   tag    = (100 << 3) | 2 = 802 → varint [0xA2, 0x06]
	//   length = varint(100)           → [0x64]
	unknownLenDelimField100 := []byte{0xA2, 0x06, 0x64}
	var r {{$roName}}
	if err := r.FromProtobuf(unknownLenDelimField100); err == nil {
		t.Error("expected error for truncated unknown LenDelim field, got nil")
	}
}

func Test{{$goName}}FromJSONErrors(t *testing.T) {
	var r {{$roName}}
	if err := r.FromJSON([]byte("not-json"), nil); err == nil {
		t.Error("expected error for invalid JSON, got nil")
	}
	if err := r.FromJSON([]byte(`[1,2,3]`), nil); err == nil {
		t.Error("expected error for JSON array (not object), got nil")
	}
}
{{- $sf := firstScalarField .Fields}}
{{- $mf := firstMsgField .Fields}}
{{- $mapf := firstMapField .Fields}}
{{- $repf := firstRepeatedField .Fields}}
{{- $bf := firstBytesField .Fields}}
{{if $sf}}
// Test{{$goName}}FromJSONScalarTypeError verifies that a null JSON value for a
// scalar field causes FromJSON to return an error (exercises the per-field
// error branch inside fromJSONValue).
// Field under test: {{$sf.JsonName}} ({{$sf.Type}})
func Test{{$goName}}FromJSONScalarTypeError(t *testing.T) {
	var r {{$roName}}
	if err := r.FromJSON([]byte(`{"{{$sf.JsonName}}": null}`), nil); err == nil {
		t.Errorf("expected error when scalar field %q receives null, got nil", "{{$sf.JsonName}}")
	}
}
{{end}}
{{- if $mf}}
// Test{{$goName}}FromJSONMsgTypeError verifies that passing null for an
// embedded-message field causes FromJSON to return an error.
// Field under test: {{$mf.JsonName}}
func Test{{$goName}}FromJSONMsgTypeError(t *testing.T) {
	var r {{$roName}}
	if err := r.FromJSON([]byte(`{"{{$mf.JsonName}}": null}`), nil); err == nil {
		t.Errorf("expected error when msg field %q receives null, got nil", "{{$mf.JsonName}}")
	}
}
{{end}}
{{- if $mapf}}
// Test{{$goName}}FromJSONMapTypeError verifies that passing null for a map
// field causes FromJSON to return an error (exercises the outer v.Object()
// error branch for map fields).
// Field under test: {{$mapf.JsonName}}
func Test{{$goName}}FromJSONMapTypeError(t *testing.T) {
	var r {{$roName}}
	if err := r.FromJSON([]byte(`{"{{$mapf.JsonName}}": null}`), nil); err == nil {
		t.Errorf("expected error when map field %q receives null, got nil", "{{$mapf.JsonName}}")
	}
}
{{end}}
{{- if $repf}}
// Test{{$goName}}FromJSONArrayTypeError verifies that passing null for a
// repeated field causes FromJSON to return an error (exercises the v.Array()
// error branch).
// Field under test: {{$repf.JsonName}}
func Test{{$goName}}FromJSONArrayTypeError(t *testing.T) {
	var r {{$roName}}
	if err := r.FromJSON([]byte(`{"{{$repf.JsonName}}": null}`), nil); err == nil {
		t.Errorf("expected error when repeated field %q receives null, got nil", "{{$repf.JsonName}}")
	}
}
{{end}}
{{- if $bf}}
// Test{{$goName}}FromJSONBytesDecodeError verifies that an invalid base64
// string for a bytes field causes FromJSON to return an error (exercises the
// base64 decode error path).
// Field under test: {{$bf.JsonName}}
func Test{{$goName}}FromJSONBytesDecodeError(t *testing.T) {
	var r {{$roName}}
	// "!!!" is not valid standard base64.
	if err := r.FromJSON([]byte(`{"{{$bf.JsonName}}": "!!!"}`), nil); err == nil {
		t.Errorf("expected error for invalid base64 in field %q, got nil", "{{$bf.JsonName}}")
	}
}
{{end}}
{{- $skm := firstStringKeyMapField .Fields}}
{{- if $skm}}
// Test{{$goName}}FromJSONMapValueTypeError verifies that a null map value
// causes FromJSON to return an error (exercises the inner value-parse error
// branch for string-keyed maps).
// Field under test: {{$skm.JsonName}}
func Test{{$goName}}FromJSONMapValueTypeError(t *testing.T) {
	var r {{$roName}}
	// Null is not a valid value; the inner mv.Int64()/StringBytes()/etc. must error.
	if err := r.FromJSON([]byte(`{"{{$skm.JsonName}}": {"k": null}}`), nil); err == nil {
		t.Errorf("expected error for null map value in field %q, got nil", "{{$skm.JsonName}}")
	}
}
{{end}}
{{- $nkm := firstNumericKeyMapField .Fields}}
{{- if $nkm}}
// Test{{$goName}}FromJSONMapKeyTypeError verifies that a non-numeric map key
// string causes FromJSON to return an error (exercises the strconv.Parse*
// error branch for numeric-keyed maps).
// Field under test: {{$nkm.JsonName}}
func Test{{$goName}}FromJSONMapKeyTypeError(t *testing.T) {
	var r {{$roName}}
	// "not-a-number" cannot be parsed as the numeric key type.
	if err := r.FromJSON([]byte(`{"{{$nkm.JsonName}}": {"not-a-number": 1}}`), nil); err == nil {
		t.Errorf("expected error for non-numeric map key in field %q, got nil", "{{$nkm.JsonName}}")
	}
}
{{end}}
// Test{{$goName}}FromProtobufWithCopyRoundtrip verifies that
// FromProtobufWithCopy produces the correct result and that mutating the
// original input buffer after the call does not affect the parsed data (the
// internal copy is independent of the caller's buffer).
func Test{{$goName}}FromProtobufWithCopyRoundtrip(t *testing.T) {
	w := makeSample{{$goName}}()
	buf := w.ToProtobuf(make([]byte, 0, w.ProtobufSize()))

	// Keep a pristine reference before we corrupt the source buffer.
	ref := make([]byte, len(buf))
	copy(ref, buf)

	var r {{$roName}}
	if err := r.FromProtobufWithCopy(buf); err != nil {
		t.Fatalf("FromProtobufWithCopy error: %v", err)
	}

	// Overwrite every byte in the original buffer; the parsed data must not change.
	for i := range buf {
		buf[i] = 0xFF
	}

	w2 := r.Clone(nil)
	got := w2.ToProtobuf(make([]byte, 0, w2.ProtobufSize()))
	if !bytes.Equal(ref, got) {
		t.Fatalf("FromProtobufWithCopy: data changed after source mutation\n  want %v\n  got  %v", ref, got)
	}
}

// Test{{$goName}}FromProtobufWithCopyAfterReset verifies the common struct-reuse
// pattern: parse → use → Reset → parse again. After Reset(), all fields are
// zeroed and rawBuffer is cleared, so the second call re-allocates and the
// result must be identical to the first call.
func Test{{$goName}}FromProtobufWithCopyAfterReset(t *testing.T) {
	w := makeSample{{$goName}}()
	buf := w.ToProtobuf(make([]byte, 0, w.ProtobufSize()))
	if len(buf) != w.ProtobufSize(){
		t.Fatal("len(buf) != w.ProtobufSize()")
	}
	var r {{$roName}}
	if err := r.FromProtobufWithCopy(buf); err != nil {
		t.Fatalf("first FromProtobufWithCopy error: %v", err)
	}
	r.Reset()

	// Second call after Reset with a fresh copy of the same payload.
	buf2 := make([]byte, len(buf))
	copy(buf2, buf)
	if err := r.FromProtobufWithCopy(buf2); err != nil {
		t.Fatalf("second FromProtobufWithCopy (after reset) error: %v", err)
	}
	w2 := r.Clone(nil)
	got := w2.ToProtobuf(make([]byte, 0, w2.ProtobufSize()))
	if !bytes.Equal(buf, got) {
		t.Fatalf("FromProtobufWithCopy after reset: roundtrip mismatch\n  want %v\n  got  %v", buf, got)
	}
}

// Test{{$goName}}FromJSONWithCopyRoundtrip verifies that FromJSONWithCopy
// produces the correct result and that mutating the original input buffer
// after the call does not affect the parsed data.
func Test{{$goName}}FromJSONWithCopyRoundtrip(t *testing.T) {
	w := makeSample{{$goName}}()
	j := w.ToJSON(nil)

	// Keep a pristine reference JSON before we corrupt the source buffer.
	wRef := make([]byte, len(j))
	copy(wRef, j)

	var r {{$roName}}
	if err := r.FromJSONWithCopy(j, nil); err != nil {
		t.Fatalf("FromJSONWithCopy error: %v\nJSON: %s", err, j)
	}

	// Overwrite every byte of the original buffer; the parsed data must not change.
	for i := range j {
		j[i] = 0xFF
	}

	w2 := r.Clone(nil)
	got := w2.ToJSON(nil)
	if !bytes.Equal(wRef, got) {
		t.Fatalf("FromJSONWithCopy: data changed after source mutation\n  want: %s\n  got:  %s", wRef, got)
	}
}

// Test{{$goName}}FromJSONWithCopyAfterReset verifies the common struct-reuse
// pattern: parse → use → Reset → parse again. After Reset(), all fields are
// zeroed and rawBuffer is cleared, so the second call re-allocates and the
// result must be identical to the first call.
func Test{{$goName}}FromJSONWithCopyAfterReset(t *testing.T) {
	w := makeSample{{$goName}}()
	j := w.ToJSON(nil)

	var r {{$roName}}
	if err := r.FromJSONWithCopy(j, nil); err != nil {
		t.Fatalf("first FromJSONWithCopy error: %v\nJSON: %s", err, j)
	}
	r.Reset()

	// Second call after Reset with a fresh copy of the same JSON.
	j2 := make([]byte, len(j))
	copy(j2, j)
	if err := r.FromJSONWithCopy(j2, nil); err != nil {
		t.Fatalf("second FromJSONWithCopy (after reset) error: %v\nJSON: %s", err, j2)
	}
	w2 := r.Clone(nil)
	got := w2.ToJSON(nil)
	if !bytes.Equal(j, got) {
		t.Fatalf("FromJSONWithCopy after reset: roundtrip mismatch\n  want: %s\n  got:  %s", j, got)
	}
}

func Test{{$goName}}CloneNilDst(t *testing.T) {
	w := makeSample{{$goName}}()
	buf := w.ToProtobuf(make([]byte, 0, w.ProtobufSize()))
	var r {{$roName}}
	if err := r.FromProtobuf(buf); err != nil {
		t.Fatalf("FromProtobuf error: %v", err)
	}
	w2 := r.Clone(nil)
	if w2 == nil {
		t.Fatal("Clone(nil) returned nil")
	}
	buf2 := w2.ToProtobuf(make([]byte, 0, w2.ProtobufSize()))
	if !bytes.Equal(buf, buf2) {
		t.Fatalf("Clone roundtrip mismatch")
	}
}

func Test{{$goName}}CloneExistingDst(t *testing.T) {
	w := makeSample{{$goName}}()
	buf := w.ToProtobuf(make([]byte, 0, w.ProtobufSize()))
	var r {{$roName}}
	if err := r.FromProtobuf(buf); err != nil {
		t.Fatalf("FromProtobuf error: %v", err)
	}
	existing := &{{$goName}}{}
	w2 := r.Clone(existing)
	if w2 != existing {
		t.Error("Clone(existing) must return the same pointer")
	}
	buf2 := w2.ToProtobuf(make([]byte, 0, w2.ProtobufSize()))
	if !bytes.Equal(buf, buf2) {
		t.Fatalf("Clone(existing) roundtrip mismatch")
	}
}
{{if hasMapsOrSlices .Fields}}
// Test{{$goName}}CloneReuseDst clones the same source into an already-populated
// destination.  On the second call dst's internal maps/slices are non-nil, so
// Clone must call clear() instead of allocating fresh containers.
func Test{{$goName}}CloneReuseDst(t *testing.T) {
	w := makeSample{{$goName}}()
	buf := w.ToProtobuf(make([]byte, 0, w.ProtobufSize()))

	var r1 {{$roName}}
	if err := r1.FromProtobuf(buf); err != nil {
		t.Fatalf("FromProtobuf error: %v", err)
	}
	// First clone: dst starts empty.
	dst := r1.Clone(nil)

	// Re-parse the cloned output so r2 mirrors r1 exactly.
	buf2 := dst.ToProtobuf(make([]byte, 0, dst.ProtobufSize()))
	var r2 {{$roName}}
	if err := r2.FromProtobuf(buf2); err != nil {
		t.Fatalf("second FromProtobuf error: %v", err)
	}

	// Second clone: dst already has populated maps/slices → exercises clear().
	dst2 := r2.Clone(dst)
	buf3 := dst2.ToProtobuf(make([]byte, 0, dst2.ProtobufSize()))
	if !bytes.Equal(buf, buf3) {
		t.Fatalf("Clone(reuse dst) roundtrip mismatch:\n  want %v\n  got  %v", buf, buf3)
	}
}
{{end}}
{{end}}
