// Code generated by https://github.com/ahfuzhang/BaoHuLu. DO NOT EDIT.

package {{.Package}}

import (
	"encoding/json"
{{- if benchNeedsStrconv .Messages}}
	"strconv"
{{- end}}
	"testing"

	"github.com/bytedance/sonic"

	"github.com/valyala/fastjson"
)

{{range .Messages}}
{{- $goName := .GoName}}
{{- $roName := printf "Readonly%s" $goName}}

// benchBuild{{$goName}} returns a large {{$goName}} for benchmarking.
// Non-bool-keyed maps have 101 entries, slices have 101 elements, string/bytes
// fields are ≥100 bytes and include escape sequences (\n \t \" \\).
// Bool-keyed maps are left nil so encoding/json benchmarks can run.
func benchBuild{{$goName}}() {{$goName}} {
	w := {{$goName}}{}
{{- range .Fields}}
{{- if .IsMsg}}
	w.{{.Name}} = benchBuild{{.GoType}}()
{{- else if .Map}}
{{- if eq .MapKey "bool"}}
	// Leave bool-keyed maps nil: encoding/json does not support map[bool] keys.
{{- else}}
	{
		m := make({{mapWriterGoType .}}, 101)
		{{benchMapFill .}}
		w.{{.Name}} = m
	}
{{- end}}
{{- else if .Repeated}}
	{
		s := make({{.GoType}}, 101)
		{{benchSliceFill .}}
		w.{{.Name}} = s
	}
{{- else if eq .Type "string"}}
	w.{{.Name}} = "benchmark payload with escape chars:\n newline \t tab \" double-quote \\ backslash; " +
		"padding to ensure length exceeds one hundred bytes: 0123456789abcdef0123456789abcdef"
{{- else if eq .Type "bytes"}}
	w.{{.Name}} = []byte("benchmark bytes payload with special chars: \n \t \\ " +
		"padding to exceed one hundred bytes: 0123456789abcdef0123456789abcdef")
{{- else}}
	w.{{.Name}} = {{sampleLit .}}
{{- end}}
{{- end}}
	return w
}

// ── ToJSON benchmarks ─────────────────────────────────────────────────────────

// BenchmarkToJSON_{{$goName}}_Generated measures ToJSON throughput of generated code.
// The output buffer is reused across iterations to demonstrate zero-allocation amortisation.
func BenchmarkToJSON_{{$goName}}_Generated(b *testing.B) {
	src := benchBuild{{$goName}}()
	j := src.ToJSON(nil)
	b.SetBytes(int64(len(j)))
	b.ResetTimer()
	b.ReportAllocs()
	buf := make([]byte, 0, len(j))
	for i := 0; i < b.N; i++ {
		buf = src.ToJSON(buf[:0])
	}
	_ = buf
}

// BenchmarkToJSON_{{$goName}}_EncodingJSON measures json.Marshal throughput.
func BenchmarkToJSON_{{$goName}}_EncodingJSON(b *testing.B) {
	src := benchBuild{{$goName}}()
	j, err := json.Marshal(src)
	if err != nil {
		b.Skipf("encoding/json.Marshal unsupported for {{$goName}}: %v", err)
	}
	b.SetBytes(int64(len(j)))
	b.ResetTimer()
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		if _, err := json.Marshal(src); err != nil {
			b.Fatal(err)
		}
	}
}

// BenchmarkToJSON_{{$goName}}_Sonic measures sonic.Marshal throughput.
func BenchmarkToJSON_{{$goName}}_Sonic(b *testing.B) {
	src := benchBuild{{$goName}}()
	j, err := sonic.Marshal(src)
	if err != nil {
		b.Skipf("sonic.Marshal unsupported for {{$goName}}: %v", err)
	}
	b.SetBytes(int64(len(j)))
	b.ResetTimer()
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		if _, err := sonic.Marshal(src); err != nil {
			b.Fatal(err)
		}
	}
}

// ── FromJSON benchmarks ───────────────────────────────────────────────────────

// BenchmarkFromJSON_{{$goName}}_Generated measures FromJSON throughput of generated code.
// The Readonly struct is reset between iterations to reuse its memory without extra allocs.
func BenchmarkFromJSON_{{$goName}}_Generated(b *testing.B) {
	src := benchBuild{{$goName}}()
	j := src.ToJSON(nil)
	b.SetBytes(int64(len(j)))
	b.ResetTimer()
	b.ReportAllocs()
	var r {{$roName}}
	var p fastjson.Parser
	for i := 0; i < b.N; i++ {
		r.Reset()
		if err := r.FromJSON(j, &p); err != nil {
			b.Fatal(err)
		}
	}
}

// BenchmarkFromJSON_{{$goName}}_EncodingJSON measures json.Unmarshal throughput.
func BenchmarkFromJSON_{{$goName}}_EncodingJSON(b *testing.B) {
	src := benchBuild{{$goName}}()
	j := src.ToJSON(nil)
	var w {{$goName}}
	if err := json.Unmarshal(j, &w); err != nil {
		b.Skipf("encoding/json.Unmarshal unsupported for {{$goName}}: %v", err)
	}
	b.SetBytes(int64(len(j)))
	b.ResetTimer()
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		w = {{$goName}}{}
		if err := json.Unmarshal(j, &w); err != nil {
			b.Fatal(err)
		}
	}
	_ = w
}

// BenchmarkFromJSON_{{$goName}}_Sonic measures sonic.Unmarshal throughput.
func BenchmarkFromJSON_{{$goName}}_Sonic(b *testing.B) {
	src := benchBuild{{$goName}}()
	j := src.ToJSON(nil)
	var w {{$goName}}
	if err := sonic.Unmarshal(j, &w); err != nil {
		b.Skipf("sonic.Unmarshal unsupported for {{$goName}}: %v", err)
	}
	b.SetBytes(int64(len(j)))
	b.ResetTimer()
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		w = {{$goName}}{}
		if err := sonic.Unmarshal(j, &w); err != nil {
			b.Fatal(err)
		}
	}
	_ = w
}

// ── Protobuf benchmarks ───────────────────────────────────────────────────────

// BenchmarkToProtobuf_{{$goName}} measures ToProtobuf throughput of generated code.
// The output buffer is reused across iterations.
func BenchmarkToProtobuf_{{$goName}}(b *testing.B) {
	src := benchBuild{{$goName}}()
	pb := src.ToProtobuf(nil)
	b.SetBytes(int64(len(pb)))
	b.ResetTimer()
	b.ReportAllocs()
	buf := make([]byte, 0, len(pb))
	for i := 0; i < b.N; i++ {
		buf = src.ToProtobuf(buf[:0])
	}
	_ = buf
}

// BenchmarkFromProtobuf_{{$goName}} measures FromProtobuf throughput of generated code.
// The Readonly struct is reset between iterations to reuse its memory without extra allocs.
func BenchmarkFromProtobuf_{{$goName}}(b *testing.B) {
	src := benchBuild{{$goName}}()
	pb := src.ToProtobuf(nil)
	b.SetBytes(int64(len(pb)))
	b.ResetTimer()
	b.ReportAllocs()
	var r {{$roName}}
	for i := 0; i < b.N; i++ {
		r.Reset()
		if err := r.FromProtobuf(pb); err != nil {
			b.Fatal(err)
		}
	}
}
{{end}}
