// Code generated by https://github.com/ahfuzhang/BaoHuLu. DO NOT EDIT.

package {{.Package}}

import (
	"bytes"
	"testing"
)

{{range .Messages}}
{{- $goName := .GoName}}
{{- $roName := printf "Readonly%s" $goName}}

// ─── {{$goName}} vtprotobuf methods ──────────────────────────────────────────

func Test{{$goName}}ProtobufSizeVTNil(t *testing.T) {
	var m *{{$goName}}
	if got := m.ProtobufSizeVT(); got != 0 {
		t.Fatalf("ProtobufSizeVT() on nil = %d, want 0", got)
	}
}

func Test{{$goName}}ToProtobufVTNil(t *testing.T) {
	var m *{{$goName}}
	out, err := m.ToProtobufVT(nil)
	if err != nil {
		t.Fatalf("ToProtobufVT() on nil error: %v", err)
	}
	if out != nil {
		t.Fatalf("ToProtobufVT() on nil = %v, want nil", out)
	}
}

func Test{{$goName}}VTEmpty(t *testing.T) {
	m := &{{$goName}}{}
	if got := m.ProtobufSizeVT(); got != 0 {
		t.Fatalf("ProtobufSizeVT() = %d, want 0 for empty {{$goName}}", got)
	}
	out, err := m.ToProtobufVT(nil)
	if err != nil {
		t.Fatalf("ToProtobufVT() error: %v", err)
	}
	if len(out) != 0 {
		t.Fatalf("ToProtobufVT() = %d bytes, want 0 for empty {{$goName}}", len(out))
	}
}

func Test{{$goName}}FromProtobufVTEmpty(t *testing.T) {
	var r {{$roName}}
	if err := r.FromProtobufVT(nil); err != nil {
		t.Fatalf("FromProtobufVT(nil) error: %v", err)
	}
	if err := r.FromProtobufVT([]byte{}); err != nil {
		t.Fatalf("FromProtobufVT(empty) error: %v", err)
	}
}

func Test{{$goName}}VTRoundtrip(t *testing.T) {
	w := makeSample{{$goName}}()
	sz := w.ProtobufSizeVT()
	out, err := w.ToProtobufVT(nil)
	if err != nil {
		t.Fatalf("ToProtobufVT error: %v", err)
	}
	if len(out) != sz {
		t.Fatalf("ProtobufSizeVT=%d but ToProtobufVT produced %d bytes", sz, len(out))
	}

	var r {{$roName}}
	if err := r.FromProtobufVT(out); err != nil {
		t.Fatalf("FromProtobufVT error: %v", err)
	}

	w2 := r.Clone(nil)
	out2, err := w2.ToProtobufVT(make([]byte, 0, w2.ProtobufSizeVT()))
	if err != nil {
		t.Fatalf("second ToProtobufVT error: %v", err)
	}
	if !bytes.Equal(out, out2) {
		t.Fatalf("VT roundtrip mismatch:\n  want %v\n  got  %v", out, out2)
	}
}

// Test{{$goName}}ToProtobufVTBufferReuse verifies that ToProtobufVT reuses
// the caller's buffer when its capacity is sufficient, and allocates a fresh
// one when the buffer is too small — both paths must produce identical bytes.
func Test{{$goName}}ToProtobufVTBufferReuse(t *testing.T) {
	w := makeSample{{$goName}}()
	sz := w.ProtobufSizeVT()
	if sz == 0 {
		t.Skip("empty message: no bytes to verify buffer-reuse behaviour")
	}
	// Sufficient capacity: backing array must be reused.
	preallocated := make([]byte, 0, sz)
	out, err := w.ToProtobufVT(preallocated)
	if err != nil {
		t.Fatalf("ToProtobufVT error: %v", err)
	}
	if len(out) != sz {
		t.Fatalf("ToProtobufVT produced %d bytes, want %d", len(out), sz)
	}
	if &preallocated[:cap(preallocated)][0] != &out[:cap(out)][0] {
		t.Error("ToProtobufVT did not reuse the provided buffer when cap was sufficient")
	}
	// Undersized capacity (cap=0): a fresh buffer must be allocated and the
	// result must be byte-identical to the reused-buffer path.
	out2, err := w.ToProtobufVT(make([]byte, 0))
	if err != nil {
		t.Fatalf("ToProtobufVT (undersized) error: %v", err)
	}
	if !bytes.Equal(out, out2) {
		t.Fatalf("ToProtobufVT (undersized) result mismatch:\n  want %v\n  got  %v", out, out2)
	}
}

// Test{{$goName}}VTWireCompatibility verifies that the VT and standard protobuf
// serialization formats are mutually parseable (wire-compatible). The two
// implementations may encode fields in different orders, so only round-trip
// idempotence is checked, not byte-level identity.
func Test{{$goName}}VTWireCompatibility(t *testing.T) {
	w := makeSample{{$goName}}()

	// std→VT→std: parse standard bytes with VT parser, re-encode with VT,
	// then parse that with standard parser and re-encode with standard.
	// The final standard encoding must equal the original standard encoding.
	stdBuf := w.ToProtobuf(nil)
	var r1 {{$roName}}
	if err := r1.FromProtobufVT(stdBuf); err != nil {
		t.Fatalf("FromProtobufVT(standard output) error: %v", err)
	}
	vtBuf1, err := r1.Clone(nil).ToProtobufVT(nil)
	if err != nil {
		t.Fatalf("ToProtobufVT after std-parse error: %v", err)
	}
	var r1b {{$roName}}
	if err := r1b.FromProtobuf(vtBuf1); err != nil {
		t.Fatalf("FromProtobuf(VT re-encoded) error: %v", err)
	}
	stdBuf1b := r1b.Clone(nil).ToProtobuf(nil)
	if !bytes.Equal(stdBuf, stdBuf1b) {
		t.Fatalf("wire compat (std→VT→std) mismatch:\n  want %v\n  got  %v", stdBuf, stdBuf1b)
	}

	// VT→std→VT: parse VT bytes with standard parser, re-encode with standard,
	// then parse that with VT parser and re-encode with VT.
	// The final VT encoding must equal the original VT encoding.
	vtBuf, err := w.ToProtobufVT(nil)
	if err != nil {
		t.Fatalf("ToProtobufVT error: %v", err)
	}
	var r2 {{$roName}}
	if err := r2.FromProtobuf(vtBuf); err != nil {
		t.Fatalf("FromProtobuf(VT output) error: %v", err)
	}
	stdBuf2 := r2.Clone(nil).ToProtobuf(nil)
	var r2b {{$roName}}
	if err := r2b.FromProtobufVT(stdBuf2); err != nil {
		t.Fatalf("FromProtobufVT(std re-encoded) error: %v", err)
	}
	vtBuf2, err := r2b.Clone(nil).ToProtobufVT(nil)
	if err != nil {
		t.Fatalf("ToProtobufVT after std re-encoded error: %v", err)
	}
	if !bytes.Equal(vtBuf, vtBuf2) {
		t.Fatalf("wire compat (VT→std→VT) mismatch:\n  want %v\n  got  %v", vtBuf, vtBuf2)
	}
}

// Test{{$goName}}FromProtobufVTBadTag verifies that a truncated/invalid varint
// tag byte causes FromProtobufVT to return an error.
func Test{{$goName}}FromProtobufVTBadTag(t *testing.T) {
	// single-byte incomplete multi-byte varint (high bit set, no continuation byte)
	badTagVarint := []byte{0x80}
	var r {{$roName}}
	if err := r.FromProtobufVT(badTagVarint); err == nil {
		t.Error("expected error for bad varint tag, got nil")
	}
}

// Test{{$goName}}FromProtobufVTEndGroup verifies that a wire-type 4 (end-group)
// tag causes FromProtobufVT to return an error.
func Test{{$goName}}FromProtobufVTEndGroup(t *testing.T) {
	// field 1, wire type 4 (end group): (1<<3)|4 = 0x0C
	endGroupByte := []byte{0x0C}
	var r {{$roName}}
	if err := r.FromProtobufVT(endGroupByte); err == nil {
		t.Error("expected error for end-group wire type 4, got nil")
	}
}

// Test{{$goName}}FromProtobufVTZeroFieldNum verifies that a field number of 0
// causes FromProtobufVT to return an error.
func Test{{$goName}}FromProtobufVTZeroFieldNum(t *testing.T) {
	// field 0, wire type 0: (0<<3)|0 = 0x00
	zeroFieldByte := []byte{0x00}
	var r {{$roName}}
	if err := r.FromProtobufVT(zeroFieldByte); err == nil {
		t.Error("expected error for field number 0, got nil")
	}
}

// Test{{$goName}}FromProtobufVTUnknownField verifies that unknown fields are
// silently skipped without error.
func Test{{$goName}}FromProtobufVTUnknownField(t *testing.T) {
	// field 100, wire-type 0 (varint), value 1
	//   tag   = (100<<3)|0 = 800 → varint [0xA0, 0x06]
	//   value = varint(1)         → [0x01]
	unknownVarintField := []byte{0xA0, 0x06, 0x01}
	var r {{$roName}}
	if err := r.FromProtobufVT(unknownVarintField); err != nil {
		t.Fatalf("unexpected error for unknown field: %v", err)
	}
}

// Test{{$goName}}FromProtobufVTSkipError verifies that an unknown LenDelim
// field that claims more bytes than are present causes FromProtobufVT to
// return an error (exercises the skip-field error branch).
func Test{{$goName}}FromProtobufVTSkipError(t *testing.T) {
	// field 100, wire-type 2 (LenDelim), claims 100 bytes but supplies none
	//   tag    = (100<<3)|2 = 802 → varint [0xA2, 0x06]
	//   length = varint(100)       → [0x64]
	truncatedLenDelim := []byte{0xA2, 0x06, 0x64}
	var r {{$roName}}
	if err := r.FromProtobufVT(truncatedLenDelim); err == nil {
		t.Error("expected error for truncated unknown LenDelim field, got nil")
	}
}

{{end}}
