// Code generated by https://github.com/ahfuzhang/BaoHuLu. DO NOT EDIT.

package {{.Package}}

import (
	"testing"
)

{{range .Messages}}
{{- $goName := .GoName}}
{{- $roName := printf "Readonly%s" $goName}}

// ── vtprotobuf benchmarks for {{$goName}} ─────────────────────────────────────

// BenchmarkToProtobufVT_{{$goName}} measures ToProtobufVT throughput.
// The output buffer is reused across iterations to demonstrate zero-allocation amortisation.
func BenchmarkToProtobufVT_{{$goName}}(b *testing.B) {
	src := benchBuild{{$goName}}()
	pb, err := src.ToProtobufVT(nil)
	if err != nil {
		b.Fatal(err)
	}
	b.SetBytes(int64(len(pb)))
	b.ResetTimer()
	b.ReportAllocs()
	buf := make([]byte, 0, len(pb))
	for i := 0; i < b.N; i++ {
		buf, err = src.ToProtobufVT(buf[:0])
		if err != nil {
			b.Fatal(err)
		}
	}
	_ = buf
}

// BenchmarkFromProtobufVT_{{$goName}} measures FromProtobufVT throughput.
// The Readonly struct is reset between iterations to reuse its memory without extra allocs.
func BenchmarkFromProtobufVT_{{$goName}}(b *testing.B) {
	src := benchBuild{{$goName}}()
	pb, err := src.ToProtobufVT(nil)
	if err != nil {
		b.Fatal(err)
	}
	b.SetBytes(int64(len(pb)))
	b.ResetTimer()
	b.ReportAllocs()
	var r {{$roName}}
	for i := 0; i < b.N; i++ {
		r.Reset()
		if err := r.FromProtobufVT(pb); err != nil {
			b.Fatal(err)
		}
	}
}

// BenchmarkProtobufSizeVT_{{$goName}} measures ProtobufSizeVT throughput.
func BenchmarkProtobufSizeVT_{{$goName}}(b *testing.B) {
	src := benchBuild{{$goName}}()
	sz := src.ProtobufSizeVT()
	b.SetBytes(int64(sz))
	b.ResetTimer()
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		_ = src.ProtobufSizeVT()
	}
}
{{end}}
