// Code generated by https://github.com/ahfuzhang/BaoHuLu. DO NOT EDIT.

package {{.Package}}

import (
	"encoding/json"
	jsonv2 "encoding/json/v2"
	"fmt"
	"runtime"
	"testing"
	"time"

	"github.com/bytedance/sonic"
	"github.com/ahfuzhang/BaoHuLu/dependencies/golang/fastjson"
)

{{range .Messages}}
{{- $goName := .GoName}}
{{- $roName := printf "Readonly%s" $goName}}
// Test_{{$goName}}_with_compare runs sub-benchmarks (each ≥ 30 s) and prints a
// formatted comparison table covering JSON encode/decode and Protobuf encode/decode,
// followed by two copy-pasteable Markdown tables.
func Test_{{$goName}}_with_compare(t *testing.T) {
	const minDuration = 30 * time.Second

	type metrics struct {
		bytesPerSec float64
		allocsPerOp int64
	}

	runBench := func(fn func() int) metrics {
		for i := 0; i < 1000; i++ {
			fn()
		}
		runtime.GC()

		var m1, m2 runtime.MemStats
		runtime.ReadMemStats(&m1)

		var totalBytes, count int64
		start := time.Now()
		for time.Since(start) < minDuration {
			totalBytes += int64(fn())
			count++
		}
		elapsed := time.Since(start)

		runtime.GC()
		runtime.ReadMemStats(&m2)

		var allocsPerOp int64
		if count > 0 {
			allocsPerOp = int64(m2.Mallocs-m1.Mallocs) / count
		}
		return metrics{
			bytesPerSec: float64(totalBytes) / elapsed.Seconds(),
			allocsPerOp: allocsPerOp,
		}
	}

	fmtBPS := func(bps float64) string {
		if bps >= 1e9 {
			return fmt.Sprintf("%.2f GB/s", bps/1e9)
		}
		return fmt.Sprintf("%.2f MB/s", bps/1e6)
	}

	fmtPct := func(base, cmp float64, cmpName string) string {
		if cmp == 0 {
			return "N/A"
		}
		pct := (base - cmp) / cmp * 100
		if pct >= 0 {
			return fmt.Sprintf("%.1f%% faster than %s", pct, cmpName)
		}
		return fmt.Sprintf("%.1f%% slower than %s", -pct, cmpName)
	}

	fmtPctMD := func(base, cmp float64) string {
		if cmp == 0 {
			return "N/A"
		}
		pct := (base - cmp) / cmp * 100
		if pct >= 0 {
			return fmt.Sprintf(`<span style="color:red">+%.1f%%</span>`, pct)
		}
		return fmt.Sprintf(`<span style="color:green">%.1f%%</span>`, pct)
	}

	src := benchBuild{{$goName}}()
	jsonData := src.ToJSON(nil)
	pbData := src.ToProtobuf(nil)
{{- if $.WithVtprotobuf}}
	pbVTData, err := src.ToProtobufVT(nil)
	if err != nil {
		t.Fatal(err)
	}
{{- end}}

	var (
		mJEncBHL, mJEncStd, mJEncJV2, mJEncSonic metrics
		mJDecBHL, mJDecStd, mJDecJV2, mJDecSonic metrics
		mPbEncReg                       metrics
		mPbDecReg                       metrics
{{- if $.WithVtprotobuf}}
		mPbEncVT metrics
		mPbDecVT metrics
{{- end}}
	)

	fmt.Println()
	fmt.Println("=== {{$goName}} Performance Comparison (each benchmark runs ≥ 30 s) ===")
	fmt.Println()

	// JSON encode
	{
		buf := make([]byte, 0, len(jsonData))
		mJEncBHL = runBench(func() int {
			buf = src.ToJSON(buf[:0])
			return len(buf)
		})
		mJEncStd = runBench(func() int {
			j, _ := json.Marshal(src)
			return len(j)
		})
		mJEncJV2 = runBench(func() int {
			j, _ := jsonv2.Marshal(src)
			return len(j)
		})
		mJEncSonic = runBench(func() int {
			j, _ := sonic.Marshal(src)
			return len(j)
		})
		fmt.Printf(
			"json encode:  [ToJSON] %s, %d allocs/op"+
				" | [encoding/json] %s, %d allocs/op, %s"+
				" | [encoding/json/v2] %s, %d allocs/op, %s"+
				" | [bytedance/sonic] %s, %d allocs/op, %s\n",
			fmtBPS(mJEncBHL.bytesPerSec), mJEncBHL.allocsPerOp,
			fmtBPS(mJEncStd.bytesPerSec), mJEncStd.allocsPerOp, fmtPct(mJEncBHL.bytesPerSec, mJEncStd.bytesPerSec, "encoding/json"),
			fmtBPS(mJEncJV2.bytesPerSec), mJEncJV2.allocsPerOp, fmtPct(mJEncBHL.bytesPerSec, mJEncJV2.bytesPerSec, "encoding/json/v2"),
			fmtBPS(mJEncSonic.bytesPerSec), mJEncSonic.allocsPerOp, fmtPct(mJEncBHL.bytesPerSec, mJEncSonic.bytesPerSec, "bytedance/sonic"),
		)
	}

	// JSON decode
	{
		var r {{$roName}}
		var p fastjson.Parser
		mJDecBHL = runBench(func() int {
			r.Reset()
			if err := r.FromJSON(jsonData, &p); err != nil {
				t.Fatal("FromJSON failed:", err)
			}
			return len(jsonData)
		})
		mJDecStd = runBench(func() int {
			var w {{$goName}}
			if err := json.Unmarshal(jsonData, &w); err != nil {
				t.Fatal("json.Unmarshal failed:", err)
			}
			return len(jsonData)
		})
		mJDecJV2 = runBench(func() int {
			var w {{$goName}}
			if err := jsonv2.Unmarshal(jsonData, &w); err != nil {
				t.Fatal("jsonv2.Unmarshal failed:", err)
			}
			return len(jsonData)
		})
		mJDecSonic = runBench(func() int {
			var w {{$goName}}
			if err := sonic.Unmarshal(jsonData, &w); err != nil {
				t.Fatal("sonic.Unmarshal failed:", err)
			}
			return len(jsonData)
		})
		fmt.Printf(
			"json decode:  [FromJSON] %s, %d allocs/op"+
				" | [encoding/json] %s, %d allocs/op, %s"+
				" | [encoding/json/v2] %s, %d allocs/op, %s"+
				" | [bytedance/sonic] %s, %d allocs/op, %s\n",
			fmtBPS(mJDecBHL.bytesPerSec), mJDecBHL.allocsPerOp,
			fmtBPS(mJDecStd.bytesPerSec), mJDecStd.allocsPerOp, fmtPct(mJDecBHL.bytesPerSec, mJDecStd.bytesPerSec, "encoding/json"),
			fmtBPS(mJDecJV2.bytesPerSec), mJDecJV2.allocsPerOp, fmtPct(mJDecBHL.bytesPerSec, mJDecJV2.bytesPerSec, "encoding/json/v2"),
			fmtBPS(mJDecSonic.bytesPerSec), mJDecSonic.allocsPerOp, fmtPct(mJDecBHL.bytesPerSec, mJDecSonic.bytesPerSec, "bytedance/sonic"),
		)
	}

{{- if $.WithVtprotobuf}}
	// Protobuf encode
	{
		buf := make([]byte, 0, len(pbVTData))
		var encErr error
		mPbEncVT = runBench(func() int {
			buf, encErr = src.ToProtobufVT(buf[:0])
			if encErr != nil {
				return 0
			}
			return len(buf)
		})
		buf2 := make([]byte, 0, len(pbData))
		mPbEncReg = runBench(func() int {
			buf2 = src.ToProtobuf(buf2[:0])
			return len(buf2)
		})
		fmt.Printf(
			"pb encode:    [ToProtobufVT] %s, %d allocs/op"+
				" | [ToProtobuf] %s, %d allocs/op, %s\n",
			fmtBPS(mPbEncVT.bytesPerSec), mPbEncVT.allocsPerOp,
			fmtBPS(mPbEncReg.bytesPerSec), mPbEncReg.allocsPerOp, fmtPct(mPbEncVT.bytesPerSec, mPbEncReg.bytesPerSec, "ToProtobuf"),
		)
	}

	// Protobuf decode
	{
		var rVT {{$roName}}
		mPbDecVT = runBench(func() int {
			rVT.Reset()
			if err := rVT.FromProtobufVT(pbVTData); err != nil {
				t.Fatal("FromProtobufVT failed:", err)
			}
			return len(pbVTData)
		})
		var rPB {{$roName}}
		mPbDecReg = runBench(func() int {
			rPB.Reset()
			if err := rPB.FromProtobuf(pbData); err != nil {
				t.Fatal("FromProtobuf failed:", err)
			}
			return len(pbData)
		})
		fmt.Printf(
			"pb decode:    [FromProtobufVT] %s, %d allocs/op"+
				" | [FromProtobuf] %s, %d allocs/op, %s\n",
			fmtBPS(mPbDecVT.bytesPerSec), mPbDecVT.allocsPerOp,
			fmtBPS(mPbDecReg.bytesPerSec), mPbDecReg.allocsPerOp, fmtPct(mPbDecVT.bytesPerSec, mPbDecReg.bytesPerSec, "FromProtobuf"),
		)
	}
{{- else}}
	// Protobuf encode
	{
		buf := make([]byte, 0, len(pbData))
		mPbEncReg = runBench(func() int {
			buf = src.ToProtobuf(buf[:0])
			return len(buf)
		})
		fmt.Printf(
			"pb encode:    [ToProtobuf] %s, %d allocs/op\n",
			fmtBPS(mPbEncReg.bytesPerSec), mPbEncReg.allocsPerOp,
		)
	}

	// Protobuf decode
	{
		var rPB {{$roName}}
		mPbDecReg = runBench(func() int {
			rPB.Reset()
			if err := rPB.FromProtobuf(pbData); err != nil {
				t.Fatal("FromProtobuf failed:", err)
			}
			return len(pbData)
		})
		fmt.Printf(
			"pb decode:    [FromProtobuf] %s, %d allocs/op\n",
			fmtBPS(mPbDecReg.bytesPerSec), mPbDecReg.allocsPerOp,
		)
	}
{{- end}}

	mdBase := func(m metrics) string {
		return fmt.Sprintf("%s<br>%d allocs/op", fmtBPS(m.bytesPerSec), m.allocsPerOp)
	}
	mdCmp := func(m, base metrics) string {
		return fmt.Sprintf("%s<br>%d allocs/op<br>%s",
			fmtBPS(m.bytesPerSec), m.allocsPerOp,
			fmtPctMD(base.bytesPerSec, m.bytesPerSec),
		)
	}

	fmt.Println()
	fmt.Println("---")
	fmt.Println()

	fmt.Println("### JSON Performance")
	fmt.Println()
	fmt.Println("| Operation | BaoHuLu | encoding/json | encoding/json/v2 | bytedance/sonic |")
	fmt.Println("|:----------|:-------:|:-------------:|:----------------:|:---------------:|")
	fmt.Printf("| json encode | %s | %s | %s | %s |\n",
		mdBase(mJEncBHL),
		mdCmp(mJEncStd, mJEncBHL),
		mdCmp(mJEncJV2, mJEncBHL),
		mdCmp(mJEncSonic, mJEncBHL),
	)
	fmt.Printf("| json decode | %s | %s | %s | %s |\n",
		mdBase(mJDecBHL),
		mdCmp(mJDecStd, mJDecBHL),
		mdCmp(mJDecJV2, mJDecBHL),
		mdCmp(mJDecSonic, mJDecBHL),
	)

	fmt.Println()

{{- if $.WithVtprotobuf}}
	fmt.Println("### Protobuf Performance")
	fmt.Println()
	fmt.Println("| Operation | BaoHuLu VT (baseline) | BaoHuLu |")
	fmt.Println("|:----------|:---------------------:|:-------:|")
	fmt.Printf("| pb encode | %s | %s |\n",
		mdBase(mPbEncVT),
		mdCmp(mPbEncReg, mPbEncVT),
	)
	fmt.Printf("| pb decode | %s | %s |\n",
		mdBase(mPbDecVT),
		mdCmp(mPbDecReg, mPbDecVT),
	)
{{- else}}
	fmt.Println("### Protobuf Performance")
	fmt.Println()
	fmt.Println("| Operation | BaoHuLu |")
	fmt.Println("|:----------|:-------:|")
	fmt.Printf("| pb encode | %s |\n", mdBase(mPbEncReg))
	fmt.Printf("| pb decode | %s |\n", mdBase(mPbDecReg))
{{- end}}

	fmt.Println()
}
{{end}}
