// Code generated by https://github.com/ahfuzhang/BaoHuLu. DO NOT EDIT.

package {{.Package}}

import (
	"encoding/base64"
	"fmt"
	"math"
	"math/bits"
	"strconv"
	"unsafe"

	"github.com/ahfuzhang/BaoHuLu/dependencies/golang/utils"
	"github.com/ahfuzhang/BaoHuLu/dependencies/golang/fastjson"
	"github.com/ahfuzhang/BaoHuLu/dependencies/golang/fastfloat"
{{- if anyMsgHasDecimalField .Messages}}
	"github.com/govalues/decimal"
{{- end}}
)

// for build time check
var _ = unsafe.Pointer(nil)
var _ = math.Float32bits
var _ = strconv.IntSize
var _ = base64.StdEncoding
var _ = utils.AppendVarint
var _ *fastjson.Parser
var _ = fastfloat.ParseBestEffort
{{- if anyMsgHasDecimalField .Messages}}
var _ = decimal.New
{{- end}}

// ─── Enums ───────────────────────────────────────────────────────────────────
{{range .Enums}}
type {{.Name}} int32
{{$enumName := .Name}}
{{- $enumMaxLen := maxEnumValLen .Values}}
const (
{{- range .Values}}
	{{padRight (enumValueGoName .Name) $enumMaxLen}} {{$enumName}} = {{.Number}}
{{- end}}
)
{{end}}
// ─── Writer structs ──────────────────────────────────────────────────────────
{{range .Messages}}
{{- $goName := .GoName}}
// {{$goName}} field tag IDs.
{{- $tagMaxLen := maxTagLen $goName .Fields}}
const (
{{- range .Fields}}
	{{padRight (printf "%s%sTag" $goName .Name) $tagMaxLen}} = {{.Number}}
{{- end}}
)

// {{$goName}} JSON field name string constants.
{{- $nameOfMaxLen := maxNameOfLen $goName .Fields}}
const (
{{- range .Fields}}
	{{padRight (printf "NameOf%s%s" $goName .Name) $nameOfMaxLen}} = "{{.JsonName}}"
{{- end}}
)
{{if hasYamlFields .Fields}}
// {{$goName}} YAML field name string constants.
const (
{{- range .Fields}}
{{- if .YamlName}}
	NameOfYamlField{{$goName}}{{.Name}} = "{{.YamlName}}"
{{- end}}
{{- end}}
)
{{end}}
{{msgCommentBlock .Comment}}// {{$goName}} writer struct.
// Fields are ordered by alignment (desc) then size (desc) for minimal memory padding.
type {{$goName}} struct {
{{- range writerAlignedFields .Fields}}
{{- if .StructTag}}
{{fieldCommentBlock .Comment}}	{{padRight .Name .NameW}} {{padRight .TypeStr .TypeW}} {{.StructTag}}
{{- else}}
{{fieldCommentBlock .Comment}}	{{padRight .Name .NameW}} {{.TypeStr}}
{{- end}}
{{- end}}
}

func (m *{{$goName}}) Reset() {
	clear(m.arena) // pointer might be cause not GC correctly, so must use memset(0) to dereference
	m.arena = m.arena[:0]
{{- range .Fields}}
{{- if .Map}}
	clear(m.{{.Name}})
{{- else if .Repeated}}
	m.{{.Name}} = m.{{.Name}}[:0]
{{- else if .IsMsg}}
{{- if .IsRecursive}}
	m.{{.Name}} = nil
{{- else}}
	m.{{.Name}}.Reset()
{{- end}}
{{- else if isSliceType .GoType}}
	m.{{.Name}} = m.{{.Name}}[:0]
{{- else if .IsDecimal}}
	m.{{.Name}} = decimal.Decimal{}
{{- else}}
	m.{{.Name}} = {{zeroVal .GoType}}
{{- end}}
{{- end}}
	/*
	Risk of misuse: After calling `Reset()`, the data in objects referencing the value portion of 
	a map, as well as members of array types, might be set to \0. If you want this to persist, 
	be sure to use the `Clone()` method to copy them before calling `Reset()`.

	Reference to string and bytes types is safe, as these types are copied during decoding.

	误用风险：调用 Reset() 后，引用 map 的 value 部分的对象指针，以及引用数组类型中的成员，其内部的数据可能被设置为 \0。如果希望长期有效，一定要在 Reset() 之前使用 Clone() 方法进行复制。
	引用字符串类型以及 bytes 类型是安全的，这些类型会在 decode 时进行复制。
	*/
}

func (m *{{$goName}}) ProtobufSize() int {
	size := 0
{{- range .Fields}}
{{- if .Map}}
	for k, v := range m.{{.Name}} {
		entrySize := 0
		{{- if eq .MapKey "string"}}
		{
			kn := len(k)
			entrySize += {{tagSize 1 2}} /* TagSize(1, LenDelim=2) */ + (bits.Len64((uint64(kn))|1) + 6) / 7 + kn
		}
		{{- else if eq .MapKey "bool"}}
		{
			var bk uint64
			if k {
				bk = 1
			}
			entrySize += {{tagSize 1 0}} /* TagSize(1, Varint=0) */ + (bits.Len64((bk)|1) + 6) / 7
		}
		{{- else if eq .MapKey "fixed32"}}
		_ = k
		entrySize += {{tagSize 1 5}} /* TagSize(1, 32bit=5) */ + 4
		{{- else if eq .MapKey "sfixed32"}}
		_ = k
		entrySize += {{tagSize 1 5}} /* TagSize(1, 32bit=5) */ + 4
		{{- else if eq .MapKey "fixed64"}}
		_ = k
		entrySize += {{tagSize 1 1}} /* TagSize(1, 64bit=1) */ + 8
		{{- else if eq .MapKey "sfixed64"}}
		_ = k
		entrySize += {{tagSize 1 1}} /* TagSize(1, 64bit=1) */ + 8
		{{- else if eq .MapKey "sint32"}}
		entrySize += {{tagSize 1 0}} /* TagSize(1, Varint=0) */ + (bits.Len64((uint64((uint32(k)<<1)^uint32(k>>31)))|1) + 6) / 7
		{{- else if eq .MapKey "sint64"}}
		entrySize += {{tagSize 1 0}} /* TagSize(1, Varint=0) */ + (bits.Len64(((uint64(k)<<1)^uint64(k>>63))|1) + 6) / 7
		{{- else}}
		entrySize += {{tagSize 1 (protoWireTypeInt .MapKey)}} /* TagSize(1, {{protoWireType .MapKey}}) */ + (bits.Len64((uint64(k))|1) + 6) / 7
		{{- end}}
		{{- if eq .MapVal "string"}}
		{
			vn := len(v)
			entrySize += {{tagSize 2 2}} /* TagSize(2, LenDelim=2) */ + (bits.Len64((uint64(vn))|1) + 6) / 7 + vn
		}
		{{- else if eq .MapVal "bytes"}}
		{
			vn := len(v)
			entrySize += {{tagSize 2 2}} /* TagSize(2, LenDelim=2) */ + (bits.Len64((uint64(vn))|1) + 6) / 7 + vn
		}
		{{- else if mapValIsMsg .MapVal}}
		{
			var sub int
			if v != nil {
				sub = v.ProtobufSize()
			}
			entrySize += {{tagSize 2 2}} /* TagSize(2, LenDelim=2) */ + (bits.Len64((uint64(sub))|1) + 6) / 7 + sub
		}
		{{- else if eq .MapVal "double"}}
		_ = v
		entrySize += {{tagSize 2 1}} /* TagSize(2, 64bit=1) */ + 8
		{{- else if eq .MapVal "float"}}
		_ = v
		entrySize += {{tagSize 2 5}} /* TagSize(2, 32bit=5) */ + 4
		{{- else if eq .MapVal "fixed32"}}
		_ = v
		entrySize += {{tagSize 2 5}} /* TagSize(2, 32bit=5) */ + 4
		{{- else if eq .MapVal "fixed64"}}
		_ = v
		entrySize += {{tagSize 2 1}} /* TagSize(2, 64bit=1) */ + 8
		{{- else if eq .MapVal "sfixed32"}}
		_ = v
		entrySize += {{tagSize 2 5}} /* TagSize(2, 32bit=5) */ + 4
		{{- else if eq .MapVal "sfixed64"}}
		_ = v
		entrySize += {{tagSize 2 1}} /* TagSize(2, 64bit=1) */ + 8
		{{- else}}
		entrySize += {{tagSize 2 0}} /* TagSize(2, Varint=0) */ + (bits.Len64((uint64(v))|1) + 6) / 7
		{{- end}}
		size += {{tagSize .Number 2}} /* TagSize({{$goName}}{{.Name}}Tag, LenDelim=2) */ + (bits.Len64((uint64(entrySize))|1) + 6) / 7 + entrySize
	}
{{- else if .Repeated}}
{{- if isPackable .Type}}
	if len(m.{{.Name}}) > 0 {
		packed := 0
		for _, v := range m.{{.Name}} {
			{{- if eq .Type "sint32"}}
			packed += (bits.Len64((uint64((uint32(v) << 1) ^ uint32(v>>31)))|1) + 6) / 7
			{{- else if eq .Type "sint64"}}
			packed += (bits.Len64(((uint64(v) << 1) ^ uint64(v>>63))|1) + 6) / 7
			{{- else if eq .Type "fixed32"}}
			_ = v; packed += 4
			{{- else if eq .Type "fixed64"}}
			_ = v; packed += 8
			{{- else if eq .Type "sfixed32"}}
			_ = v; packed += 4
			{{- else if eq .Type "sfixed64"}}
			_ = v; packed += 8
			{{- else if eq .Type "float"}}
			_ = v; packed += 4
			{{- else if eq .Type "double"}}
			_ = v; packed += 8
			{{- else if eq .Type "bool"}}
			_ = v; packed += 1
			{{- else}}
			packed += (bits.Len64((uint64(v))|1) + 6) / 7
			{{- end}}
		}
		size += {{tagSize .Number 2}} /* TagSize({{$goName}}{{.Name}}Tag, LenDelim=2) */ + (bits.Len64((uint64(packed))|1) + 6) / 7 + packed
	}
{{- else if eq .Type "string"}}
	for _, v := range m.{{.Name}} {
		n := len(v)
		size += {{tagSize .Number 2}} /* TagSize({{$goName}}{{.Name}}Tag, LenDelim=2) */ + (bits.Len64((uint64(n))|1) + 6) / 7 + n
	}
{{- else if eq .Type "bytes"}}
	for _, v := range m.{{.Name}} {
		n := len(v)
		size += {{tagSize .Number 2}} /* TagSize({{$goName}}{{.Name}}Tag, LenDelim=2) */ + (bits.Len64((uint64(n))|1) + 6) / 7 + n
	}
{{- else}}
	for i := range m.{{.Name}} {
		sub := m.{{.Name}}[i].ProtobufSize()
		if sub > 0 {
			size += {{tagSize .Number 2}} /* TagSize({{$goName}}{{.Name}}Tag, LenDelim=2) */ + (bits.Len64((uint64(sub))|1) + 6) / 7 + sub
		}
	}
{{- end}}
{{- else if .IsMsg}}
{{- if .IsRecursive}}
	if m.{{.Name}} != nil {
		sub := m.{{.Name}}.ProtobufSize()
		if sub > 0 {
			size += {{tagSize .Number 2}} /* TagSize({{$goName}}{{.Name}}Tag, LenDelim=2) */ + (bits.Len64((uint64(sub))|1) + 6) / 7 + sub
		}
	}
{{- else}}
	{
		sub := m.{{.Name}}.ProtobufSize()
		if sub > 0 {
			size += {{tagSize .Number 2}} /* TagSize({{$goName}}{{.Name}}Tag, LenDelim=2) */ + (bits.Len64((uint64(sub))|1) + 6) / 7 + sub
		}
	}
{{- end}}
{{- else if .IsDecimal}}
	if !m.{{.Name}}.IsZero() {
		size += {{tagSize .Number 1}} /* TagSize({{$goName}}{{.Name}}Tag, 64bit=1) */ + 8
	}
{{- else if eq .Type "double"}}
	if m.{{.Name}} != 0 {
		size += {{tagSize .Number 1}} /* TagSize({{$goName}}{{.Name}}Tag, 64bit=1) */ + 8
	}
{{- else if eq .Type "float"}}
	if m.{{.Name}} != 0 {
		size += {{tagSize .Number 5}} /* TagSize({{$goName}}{{.Name}}Tag, 32bit=5) */ + 4
	}
{{- else if eq .Type "fixed32"}}
	if m.{{.Name}} != 0 {
		size += {{tagSize .Number 5}} /* TagSize({{$goName}}{{.Name}}Tag, 32bit=5) */ + 4
	}
{{- else if eq .Type "fixed64"}}
	if m.{{.Name}} != 0 {
		size += {{tagSize .Number 1}} /* TagSize({{$goName}}{{.Name}}Tag, 64bit=1) */ + 8
	}
{{- else if eq .Type "sfixed32"}}
	if m.{{.Name}} != 0 {
		size += {{tagSize .Number 5}} /* TagSize({{$goName}}{{.Name}}Tag, 32bit=5) */ + 4
	}
{{- else if eq .Type "sfixed64"}}
	if m.{{.Name}} != 0 {
		size += {{tagSize .Number 1}} /* TagSize({{$goName}}{{.Name}}Tag, 64bit=1) */ + 8
	}
{{- else if eq .Type "sint32"}}
	if m.{{.Name}} != 0 {
		size += {{tagSize .Number 0}} /* TagSize({{$goName}}{{.Name}}Tag, Varint=0) */ + (bits.Len64((uint64((uint32(m.{{.Name}})<<1)^uint32(m.{{.Name}}>>31)))|1) + 6) / 7
	}
{{- else if eq .Type "sint64"}}
	if m.{{.Name}} != 0 {
		size += {{tagSize .Number 0}} /* TagSize({{$goName}}{{.Name}}Tag, Varint=0) */ + (bits.Len64(((uint64(m.{{.Name}})<<1)^uint64(m.{{.Name}}>>63))|1) + 6) / 7
	}
{{- else if eq .Type "bool"}}
	if m.{{.Name}} {
		size += {{tagSize .Number 0}} /* TagSize({{$goName}}{{.Name}}Tag, Varint=0) */ + 1
	}
{{- else if eq .Type "string"}}
	if m.{{.Name}} != "" {
		n := len(m.{{.Name}})
		size += {{tagSize .Number 2}} /* TagSize({{$goName}}{{.Name}}Tag, LenDelim=2) */ + (bits.Len64((uint64(n))|1) + 6) / 7 + n
	}
{{- else if eq .Type "bytes"}}
	if len(m.{{.Name}}) > 0 {
		n := len(m.{{.Name}})
		size += {{tagSize .Number 2}} /* TagSize({{$goName}}{{.Name}}Tag, LenDelim=2) */ + (bits.Len64((uint64(n))|1) + 6) / 7 + n
	}
{{- else}}
	if m.{{.Name}} != 0 {
		size += {{tagSize .Number 0}} /* TagSize({{$goName}}{{.Name}}Tag, Varint=0) */ + (bits.Len64((uint64(m.{{.Name}}))|1) + 6) / 7
	}
{{- end}}
{{- end}}
	return size
}

func (m *{{$goName}}) ToProtobufByAppend(in []byte) []byte {
{{- range .ReverseFields}}
{{- if .Map}}
	for k, v := range m.{{.Name}} {
		entrySize := 0
		{{- if eq .MapKey "string"}}
		{
			kn := len(k)
			entrySize += {{tagSize 1 2}} /* TagSize(1, LenDelim=2) */ + (bits.Len64((uint64(kn))|1) + 6) / 7 + kn
		}
		{{- else if eq .MapKey "bool"}}
		{
			var bk uint64
			if k {
				bk = 1
			}
			entrySize += {{tagSize 1 0}} /* TagSize(1, Varint=0) */ + (bits.Len64((bk)|1) + 6) / 7
		}
		{{- else if eq .MapKey "fixed32"}}
		entrySize += {{tagSize 1 5}} /* TagSize(1, 32bit=5) */ + 4
		{{- else if eq .MapKey "sfixed32"}}
		entrySize += {{tagSize 1 5}} /* TagSize(1, 32bit=5) */ + 4
		{{- else if eq .MapKey "fixed64"}}
		entrySize += {{tagSize 1 1}} /* TagSize(1, 64bit=1) */ + 8
		{{- else if eq .MapKey "sfixed64"}}
		entrySize += {{tagSize 1 1}} /* TagSize(1, 64bit=1) */ + 8
		{{- else if eq .MapKey "sint32"}}
		entrySize += {{tagSize 1 0}} /* TagSize(1, Varint=0) */ + (bits.Len64((uint64((uint32(k)<<1)^uint32(k>>31)))|1) + 6) / 7
		{{- else if eq .MapKey "sint64"}}
		entrySize += {{tagSize 1 0}} /* TagSize(1, Varint=0) */ + (bits.Len64(((uint64(k)<<1)^uint64(k>>63))|1) + 6) / 7
		{{- else}}
		entrySize += {{tagSize 1 (protoWireTypeInt .MapKey)}} /* TagSize(1, {{protoWireType .MapKey}}) */ + (bits.Len64((uint64(k))|1) + 6) / 7
		{{- end}}
		{{- if eq .MapVal "string"}}
		{
			vn := len(v)
			entrySize += {{tagSize 2 2}} /* TagSize(2, LenDelim=2) */ + (bits.Len64((uint64(vn))|1) + 6) / 7 + vn
		}
		{{- else if eq .MapVal "bytes"}}
		{
			vn := len(v)
			entrySize += {{tagSize 2 2}} /* TagSize(2, LenDelim=2) */ + (bits.Len64((uint64(vn))|1) + 6) / 7 + vn
		}
		{{- else if (mapValIsMsg .MapVal)}}
		var valMsgSize int
		if v != nil {
			valMsgSize = v.ProtobufSize()
		}
		entrySize += {{tagSize 2 2}} /* TagSize(2, LenDelim=2) */ + (bits.Len64((uint64(valMsgSize))|1) + 6) / 7 + valMsgSize
		{{- else if eq .MapVal "double"}}
		entrySize += {{tagSize 2 1}} /* TagSize(2, 64bit=1) */ + 8
		{{- else if eq .MapVal "float"}}
		entrySize += {{tagSize 2 5}} /* TagSize(2, 32bit=5) */ + 4
		{{- else if eq .MapVal "fixed32"}}
		entrySize += {{tagSize 2 5}} /* TagSize(2, 32bit=5) */ + 4
		{{- else if eq .MapVal "fixed64"}}
		entrySize += {{tagSize 2 1}} /* TagSize(2, 64bit=1) */ + 8
		{{- else if eq .MapVal "sfixed32"}}
		entrySize += {{tagSize 2 5}} /* TagSize(2, 32bit=5) */ + 4
		{{- else if eq .MapVal "sfixed64"}}
		entrySize += {{tagSize 2 1}} /* TagSize(2, 64bit=1) */ + 8
		{{- else}}
		entrySize += {{tagSize 2 0}} /* TagSize(2, Varint=0) */ + (bits.Len64((uint64(v))|1) + 6) / 7
		{{- end}}
		in = utils.AppendTag(in, {{$goName}}{{.Name}}Tag, utils.WireTypeLenDelim)
		in = utils.AppendVarint(in, uint64(entrySize))
		in = utils.AppendTag(in, 1, {{protoWireType .MapKey}})
		{{- if eq .MapKey "string"}}
		in = utils.AppendVarint(in, uint64(len(k)))
		in = append(in, k...)
		{{- else if eq .MapKey "bool"}}
		if k {
			in = utils.AppendVarint(in, 1)
		} else {
			in = utils.AppendVarint(in, 0)
		}
		{{- else if eq .MapKey "fixed32"}}
		in = utils.AppendFixed32(in, k)
		{{- else if eq .MapKey "sfixed32"}}
		in = utils.AppendFixed32(in, uint32(k))
		{{- else if eq .MapKey "fixed64"}}
		in = utils.AppendFixed64(in, k)
		{{- else if eq .MapKey "sfixed64"}}
		in = utils.AppendFixed64(in, uint64(k))
		{{- else if eq .MapKey "sint32"}}
		in = utils.AppendSint32(in, k)
		{{- else if eq .MapKey "sint64"}}
		in = utils.AppendSint64(in, k)
		{{- else}}
		in = utils.AppendVarint(in, uint64(k))
		{{- end}}
		{{- if (mapValIsMsg .MapVal)}}
		in = utils.AppendTag(in, 2, utils.WireTypeLenDelim)
		{{- else}}
		in = utils.AppendTag(in, 2, {{protoWireType .MapVal}})
		{{- end}}
		{{- if eq .MapVal "string"}}
		in = utils.AppendVarint(in, uint64(len(v)))
		in = append(in, v...)
		{{- else if eq .MapVal "bytes"}}
		in = utils.AppendLenDelim(in, v)
		{{- else if (mapValIsMsg .MapVal)}}
		in = utils.AppendVarint(in, uint64(valMsgSize))
		if v != nil {
			in = v.ToProtobuf(in)
		}
		{{- else if eq .MapVal "double"}}
		in = utils.AppendFixed64(in, math.Float64bits(v))
		{{- else if eq .MapVal "float"}}
		in = utils.AppendFixed32(in, math.Float32bits(v))
		{{- else if eq .MapVal "fixed32"}}
		in = utils.AppendFixed32(in, uint32(v))
		{{- else if eq .MapVal "fixed64"}}
		in = utils.AppendFixed64(in, uint64(v))
		{{- else if eq .MapVal "sfixed32"}}
		in = utils.AppendFixed32(in, uint32(v))
		{{- else if eq .MapVal "sfixed64"}}
		in = utils.AppendFixed64(in, uint64(v))
		{{- else}}
		in = utils.AppendVarint(in, uint64(v))
		{{- end}}
	}
{{- else if .Repeated}}
{{- if isPackable .Type}}
	if len(m.{{.Name}}) > 0 {
		packedSize := 0
		for _, v := range m.{{.Name}} {
			{{- if eq .Type "sint32"}}
			packedSize += (bits.Len64((uint64((uint32(v) << 1) ^ uint32(v>>31)))|1) + 6) / 7
			{{- else if eq .Type "sint64"}}
			packedSize += (bits.Len64(((uint64(v) << 1) ^ uint64(v>>63))|1) + 6) / 7
			{{- else if eq .Type "fixed32"}}
			_ = v; packedSize += 4
			{{- else if eq .Type "fixed64"}}
			_ = v; packedSize += 8
			{{- else if eq .Type "sfixed32"}}
			_ = v; packedSize += 4
			{{- else if eq .Type "sfixed64"}}
			_ = v; packedSize += 8
			{{- else if eq .Type "float"}}
			_ = v; packedSize += 4
			{{- else if eq .Type "double"}}
			_ = v; packedSize += 8
			{{- else if eq .Type "bool"}}
			_ = v; packedSize += 1
			{{- else}}
			packedSize += (bits.Len64((uint64(v))|1) + 6) / 7
			{{- end}}
		}
		in = utils.AppendTag(in, {{$goName}}{{.Name}}Tag, utils.WireTypeLenDelim)
		in = utils.AppendVarint(in, uint64(packedSize))
		for _, v := range m.{{.Name}} {
			{{- if eq .Type "sint32"}}
			in = utils.AppendSint32(in, v)
			{{- else if eq .Type "sint64"}}
			in = utils.AppendSint64(in, v)
			{{- else if eq .Type "fixed32"}}
			in = utils.AppendFixed32(in, uint32(v))
			{{- else if eq .Type "fixed64"}}
			in = utils.AppendFixed64(in, uint64(v))
			{{- else if eq .Type "sfixed32"}}
			in = utils.AppendFixed32(in, uint32(v))
			{{- else if eq .Type "sfixed64"}}
			in = utils.AppendFixed64(in, uint64(v))
			{{- else if eq .Type "float"}}
			in = utils.AppendFixed32(in, math.Float32bits(v))
			{{- else if eq .Type "double"}}
			in = utils.AppendFixed64(in, math.Float64bits(v))
			{{- else if eq .Type "bool"}}
			if v {
				in = append(in, 1)
			} else {
				in = append(in, 0)
			}
			{{- else}}
			in = utils.AppendVarint(in, uint64(v))
			{{- end}}
		}
	}
{{- else if eq .Type "string"}}
	for _, v := range m.{{.Name}} {
		in = utils.AppendTag(in, {{$goName}}{{.Name}}Tag, utils.WireTypeLenDelim)
		in = utils.AppendLenDelim(in, unsafe.Slice(unsafe.StringData(v), len(v)))
	}
{{- else if eq .Type "bytes"}}
	for _, v := range m.{{.Name}} {
		in = utils.AppendTag(in, {{$goName}}{{.Name}}Tag, utils.WireTypeLenDelim)
		in = utils.AppendLenDelim(in, v)
	}
{{- else}}
	for i := range m.{{.Name}} {
		sub := m.{{.Name}}[i].ProtobufSize()
		if sub > 0 {
			in = utils.AppendTag(in, {{$goName}}{{.Name}}Tag, utils.WireTypeLenDelim)
			in = utils.AppendVarint(in, uint64(sub))
			in = m.{{.Name}}[i].ToProtobuf(in)
		}
	}
{{- end}}
{{- else if .IsMsg}}
{{- if .IsRecursive}}
	if m.{{.Name}} != nil {
		sub := m.{{.Name}}.ProtobufSize()
		if sub > 0 {
			in = utils.AppendTag(in, {{$goName}}{{.Name}}Tag, utils.WireTypeLenDelim)
			in = utils.AppendVarint(in, uint64(sub))
			in = m.{{.Name}}.ToProtobuf(in)
		}
	}
{{- else}}
	{
		sub := m.{{.Name}}.ProtobufSize()
		if sub > 0 {
			in = utils.AppendTag(in, {{$goName}}{{.Name}}Tag, utils.WireTypeLenDelim)
			in = utils.AppendVarint(in, uint64(sub))
			in = m.{{.Name}}.ToProtobuf(in)
		}
	}
{{- end}}
{{- else if .IsDecimal}}
	if !m.{{.Name}}.IsZero() {
		_df{{.Name}}, _ := m.{{.Name}}.Round({{.DecimalRound}}).Float64()
		in = utils.AppendTag(in, {{$goName}}{{.Name}}Tag, utils.WireType64bit)
		in = utils.AppendFixed64(in, math.Float64bits(_df{{.Name}}))
	}
{{- else if eq .Type "double"}}
	if m.{{.Name}} != 0 {
		in = utils.AppendTag(in, {{$goName}}{{.Name}}Tag, utils.WireType64bit)
		in = utils.AppendFixed64(in, math.Float64bits(m.{{.Name}}))
	}
{{- else if eq .Type "float"}}
	if m.{{.Name}} != 0 {
		in = utils.AppendTag(in, {{$goName}}{{.Name}}Tag, utils.WireType32bit)
		in = utils.AppendFixed32(in, math.Float32bits(m.{{.Name}}))
	}
{{- else if eq .Type "fixed32"}}
	if m.{{.Name}} != 0 {
		in = utils.AppendTag(in, {{$goName}}{{.Name}}Tag, utils.WireType32bit)
		in = utils.AppendFixed32(in, m.{{.Name}})
	}
{{- else if eq .Type "fixed64"}}
	if m.{{.Name}} != 0 {
		in = utils.AppendTag(in, {{$goName}}{{.Name}}Tag, utils.WireType64bit)
		in = utils.AppendFixed64(in, m.{{.Name}})
	}
{{- else if eq .Type "sfixed32"}}
	if m.{{.Name}} != 0 {
		in = utils.AppendTag(in, {{$goName}}{{.Name}}Tag, utils.WireType32bit)
		in = utils.AppendFixed32(in, uint32(m.{{.Name}}))
	}
{{- else if eq .Type "sfixed64"}}
	if m.{{.Name}} != 0 {
		in = utils.AppendTag(in, {{$goName}}{{.Name}}Tag, utils.WireType64bit)
		in = utils.AppendFixed64(in, uint64(m.{{.Name}}))
	}
{{- else if eq .Type "sint32"}}
	if m.{{.Name}} != 0 {
		in = utils.AppendTag(in, {{$goName}}{{.Name}}Tag, utils.WireTypeVarint)
		in = utils.AppendSint32(in, m.{{.Name}})
	}
{{- else if eq .Type "sint64"}}
	if m.{{.Name}} != 0 {
		in = utils.AppendTag(in, {{$goName}}{{.Name}}Tag, utils.WireTypeVarint)
		in = utils.AppendSint64(in, m.{{.Name}})
	}
{{- else if eq .Type "bool"}}
	if m.{{.Name}} {
		in = utils.AppendTag(in, {{$goName}}{{.Name}}Tag, utils.WireTypeVarint)
		in = append(in, 1)
	}
{{- else if eq .Type "string"}}
	if m.{{.Name}} != "" {
		in = utils.AppendTag(in, {{$goName}}{{.Name}}Tag, utils.WireTypeLenDelim)
		in = utils.AppendLenDelim(in, unsafe.Slice(unsafe.StringData(m.{{.Name}}), len(m.{{.Name}})))
	}
{{- else if eq .Type "bytes"}}
	if len(m.{{.Name}}) > 0 {
		in = utils.AppendTag(in, {{$goName}}{{.Name}}Tag, utils.WireTypeLenDelim)
		in = utils.AppendLenDelim(in, m.{{.Name}})
	}
{{- else}}
	if m.{{.Name}} != 0 {
		in = utils.AppendTag(in, {{$goName}}{{.Name}}Tag, utils.WireTypeVarint)
		in = utils.AppendVarint(in, uint64(m.{{.Name}}))
	}
{{- end}}
{{- end}}
	return in
}

{{- if .AsMap}}
{{- $f := index .Fields 0}}
func (m *{{$goName}}) ToJSON(dst []byte) []byte {
	dst = append(dst, '{')
	_jsonFirst := true
	for _k, _v := range m.{{$f.Name}} {
		if !_jsonFirst {
			dst = append(dst, ',')
		}
		_jsonFirst = false
{{- if eq $f.MapKey "string"}}
		dst = append(dst, '"')
		dst = utils.EncodeJSONString(_k, dst)
		dst = append(dst, '"')
{{- else}}
		dst = append(dst, '"')
{{- if eq $f.MapKey "bool"}}
		if _k {
			dst = append(dst, "true"...)
		} else {
			dst = append(dst, "false"...)
		}
{{- else if or (eq $f.MapKey "uint32") (eq $f.MapKey "uint64") (eq $f.MapKey "fixed32") (eq $f.MapKey "fixed64")}}
		dst = strconv.AppendUint(dst, uint64(_k), 10)
{{- else}}
		dst = strconv.AppendInt(dst, int64(_k), 10)
{{- end}}
		dst = append(dst, '"')
{{- end}}
		dst = append(dst, ':')
{{- if eq $f.MapVal "string"}}
		dst = append(dst, '"')
		dst = utils.EncodeJSONString(_v, dst)
		dst = append(dst, '"')
{{- else if eq $f.MapVal "bool"}}
		if _v {
			dst = append(dst, "true"...)
		} else {
			dst = append(dst, "false"...)
		}
{{- else if eq $f.MapVal "double"}}
		{
			_fv := _v
			_iv := int64(_fv)
			if math.Round(_fv) == _fv && float64(_iv) == _fv {
				dst = strconv.AppendInt(dst, _iv, 10)
			} else {
				dst = strconv.AppendFloat(dst, _fv, 'f', -1, 64)
			}
		}
{{- else if eq $f.MapVal "float"}}
		{
			_fv := float64(_v)
			_iv := int64(_fv)
			if math.Round(_fv) == _fv && float64(_iv) == _fv {
				dst = strconv.AppendInt(dst, _iv, 10)
			} else {
				dst = strconv.AppendFloat(dst, _fv, 'f', -1, 32)
			}
		}
{{- else if or (eq $f.MapVal "uint32") (eq $f.MapVal "fixed32")}}
		dst = strconv.AppendUint(dst, uint64(_v), 10)
{{- else if or (eq $f.MapVal "uint64") (eq $f.MapVal "fixed64")}}
		if uint64(_v) > 9007199254740991 {
			dst = append(dst, '"')
			dst = strconv.AppendUint(dst, uint64(_v), 10)
			dst = append(dst, '"')
		} else {
			dst = strconv.AppendUint(dst, uint64(_v), 10)
		}
{{- else if eq $f.MapVal "bytes"}}
		dst = append(dst, '"')
		dst = base64.StdEncoding.AppendEncode(dst, _v)
		dst = append(dst, '"')
{{- else if mapValIsMsg $f.MapVal}}
		if _v != nil {
			dst = _v.ToJSON(dst)
		} else {
			dst = append(dst, "null"...)
		}
{{- else if or (eq $f.MapVal "int64") (eq $f.MapVal "sint64") (eq $f.MapVal "sfixed64")}}
		if int64(_v) > 9007199254740991 || int64(_v) < -9007199254740991 {
			dst = append(dst, '"')
			dst = strconv.AppendInt(dst, int64(_v), 10)
			dst = append(dst, '"')
		} else {
			dst = strconv.AppendInt(dst, int64(_v), 10)
		}
{{- else}}
		dst = strconv.AppendInt(dst, int64(_v), 10)
{{- end}}
	}
	dst = append(dst, '}')
	return dst
}
{{- else if .AsArray}}
{{- $f := index .Fields 0}}
func (m *{{$goName}}) ToJSON(dst []byte) []byte {
	dst = append(dst, '[')
	for _i, _v := range m.{{$f.Name}} {
		if _i > 0 {
			dst = append(dst, ',')
		}
{{- if $f.IsMsg}}
		dst = _v.ToJSON(dst)
{{- else if eq $f.Type "string"}}
		dst = append(dst, '"')
		dst = utils.EncodeJSONString(_v, dst)
		dst = append(dst, '"')
{{- else if eq $f.Type "bool"}}
		if _v {
			dst = append(dst, "true"...)
		} else {
			dst = append(dst, "false"...)
		}
{{- else if eq $f.Type "double"}}
		{
			_fv := _v
			_iv := int64(_fv)
			if math.Round(_fv) == _fv && float64(_iv) == _fv {
				dst = strconv.AppendInt(dst, _iv, 10)
			} else {
				dst = strconv.AppendFloat(dst, _fv, 'f', -1, 64)
			}
		}
{{- else if eq $f.Type "float"}}
		{
			_fv := float64(_v)
			_iv := int64(_fv)
			if math.Round(_fv) == _fv && float64(_iv) == _fv {
				dst = strconv.AppendInt(dst, _iv, 10)
			} else {
				dst = strconv.AppendFloat(dst, _fv, 'f', -1, 32)
			}
		}
{{- else if or (eq $f.Type "uint32") (eq $f.Type "fixed32")}}
		dst = strconv.AppendUint(dst, uint64(_v), 10)
{{- else if or (eq $f.Type "uint64") (eq $f.Type "fixed64")}}
		if uint64(_v) > 9007199254740991 {
			dst = append(dst, '"')
			dst = strconv.AppendUint(dst, uint64(_v), 10)
			dst = append(dst, '"')
		} else {
			dst = strconv.AppendUint(dst, uint64(_v), 10)
		}
{{- else if eq $f.Type "bytes"}}
		dst = append(dst, '"')
		dst = base64.StdEncoding.AppendEncode(dst, _v)
		dst = append(dst, '"')
{{- else if or (eq $f.Type "int64") (eq $f.Type "sint64") (eq $f.Type "sfixed64")}}
		if int64(_v) > 9007199254740991 || int64(_v) < -9007199254740991 {
			dst = append(dst, '"')
			dst = strconv.AppendInt(dst, int64(_v), 10)
			dst = append(dst, '"')
		} else {
			dst = strconv.AppendInt(dst, int64(_v), 10)
		}
{{- else}}
		dst = strconv.AppendInt(dst, int64(_v), 10)
{{- end}}
	}
	dst = append(dst, ']')
	return dst
}
{{- else}}
func (m *{{$goName}}) ToJSON(dst []byte) []byte {
	dst = append(dst, '{')
{{- if .Fields}}
	_jsonFirstField := true
{{- range $i, $f := .Fields}}
{{- if $f.Map}}
	if len(m.{{$f.Name}}) > 0 {
		if !_jsonFirstField {
			dst = append(dst, ',')
		}
		_jsonFirstField = false
		dst = append(dst, '"')
		dst = append(dst, NameOf{{$goName}}{{$f.Name}}...)
		dst = append(dst, '"', ':')
		{
			dst = append(dst, '{')
			_jsonFirst := true
			for _k, _v := range m.{{$f.Name}} {
				if !_jsonFirst {
					dst = append(dst, ',')
				}
				_jsonFirst = false
{{- if eq $f.MapKey "string"}}
				dst = append(dst, '"')
				dst = utils.EncodeJSONString(_k, dst)
				dst = append(dst, '"')
{{- else}}
				dst = append(dst, '"')
{{- if eq $f.MapKey "bool"}}
				if _k {
					dst = append(dst, "true"...)
				} else {
					dst = append(dst, "false"...)
				}
{{- else if or (eq $f.MapKey "uint32") (eq $f.MapKey "uint64") (eq $f.MapKey "fixed32") (eq $f.MapKey "fixed64")}}
				dst = strconv.AppendUint(dst, uint64(_k), 10)
{{- else}}
				dst = strconv.AppendInt(dst, int64(_k), 10)
{{- end}}
				dst = append(dst, '"')
{{- end}}
				dst = append(dst, ':')
{{- if eq $f.MapVal "string"}}
				dst = append(dst, '"')
				dst = utils.EncodeJSONString(_v, dst)
				dst = append(dst, '"')
{{- else if eq $f.MapVal "bool"}}
				if _v {
					dst = append(dst, "true"...)
				} else {
					dst = append(dst, "false"...)
				}
{{- else if eq $f.MapVal "double"}}
				{
					_fv := _v
					_iv := int64(_fv)
					if math.Round(_fv) == _fv && float64(_iv) == _fv {
						dst = strconv.AppendInt(dst, _iv, 10)
					} else {
						dst = strconv.AppendFloat(dst, _fv, 'f', -1, 64)
					}
				}
{{- else if eq $f.MapVal "float"}}
				{
					_fv := float64(_v)
					_iv := int64(_fv)
					if math.Round(_fv) == _fv && float64(_iv) == _fv {
						dst = strconv.AppendInt(dst, _iv, 10)
					} else {
						dst = strconv.AppendFloat(dst, _fv, 'f', -1, 32)
					}
				}
{{- else if or (eq $f.MapVal "uint32") (eq $f.MapVal "fixed32")}}
				dst = strconv.AppendUint(dst, uint64(_v), 10)
{{- else if or (eq $f.MapVal "uint64") (eq $f.MapVal "fixed64")}}
				if uint64(_v) > 9007199254740991 {
					dst = append(dst, '"')
					dst = strconv.AppendUint(dst, uint64(_v), 10)
					dst = append(dst, '"')
				} else {
					dst = strconv.AppendUint(dst, uint64(_v), 10)
				}
{{- else if eq $f.MapVal "bytes"}}
				dst = append(dst, '"')
				dst = base64.StdEncoding.AppendEncode(dst, _v)
				dst = append(dst, '"')
{{- else if mapValIsMsg $f.MapVal}}
				if _v != nil {
					dst = _v.ToJSON(dst)
				} else {
					dst = append(dst, "null"...)
				}
{{- else if or (eq $f.MapVal "int64") (eq $f.MapVal "sint64") (eq $f.MapVal "sfixed64")}}
				if int64(_v) > 9007199254740991 || int64(_v) < -9007199254740991 {
					dst = append(dst, '"')
					dst = strconv.AppendInt(dst, int64(_v), 10)
					dst = append(dst, '"')
				} else {
					dst = strconv.AppendInt(dst, int64(_v), 10)
				}
{{- else}}
				dst = strconv.AppendInt(dst, int64(_v), 10)
{{- end}}
			}
			dst = append(dst, '}')
		}
	}
{{- else if $f.Repeated}}
	if len(m.{{$f.Name}}) > 0 {
		if !_jsonFirstField {
			dst = append(dst, ',')
		}
		_jsonFirstField = false
		dst = append(dst, '"')
		dst = append(dst, NameOf{{$goName}}{{$f.Name}}...)
		dst = append(dst, '"', ':')
		{
			dst = append(dst, '[')
			for _i, _v := range m.{{$f.Name}} {
				if _i > 0 {
					dst = append(dst, ',')
				}
{{- if $f.IsMsg}}
				dst = _v.ToJSON(dst)
{{- else if eq $f.Type "string"}}
				dst = append(dst, '"')
				dst = utils.EncodeJSONString(_v, dst)
				dst = append(dst, '"')
{{- else if eq $f.Type "bool"}}
				if _v {
					dst = append(dst, "true"...)
				} else {
					dst = append(dst, "false"...)
				}
{{- else if eq $f.Type "double"}}
				{
					_fv := _v
					_iv := int64(_fv)
					if math.Round(_fv) == _fv && float64(_iv) == _fv {
						dst = strconv.AppendInt(dst, _iv, 10)
					} else {
						dst = strconv.AppendFloat(dst, _fv, 'f', -1, 64)
					}
				}
{{- else if eq $f.Type "float"}}
				{
					_fv := float64(_v)
					_iv := int64(_fv)
					if math.Round(_fv) == _fv && float64(_iv) == _fv {
						dst = strconv.AppendInt(dst, _iv, 10)
					} else {
						dst = strconv.AppendFloat(dst, _fv, 'f', -1, 32)
					}
				}
{{- else if or (eq $f.Type "uint32") (eq $f.Type "fixed32")}}
				dst = strconv.AppendUint(dst, uint64(_v), 10)
{{- else if or (eq $f.Type "uint64") (eq $f.Type "fixed64")}}
				if uint64(_v) > 9007199254740991 {
					dst = append(dst, '"')
					dst = strconv.AppendUint(dst, uint64(_v), 10)
					dst = append(dst, '"')
				} else {
					dst = strconv.AppendUint(dst, uint64(_v), 10)
				}
{{- else if eq $f.Type "bytes"}}
				dst = append(dst, '"')
				dst = base64.StdEncoding.AppendEncode(dst, _v)
				dst = append(dst, '"')
{{- else if or (eq $f.Type "int64") (eq $f.Type "sint64") (eq $f.Type "sfixed64")}}
				if int64(_v) > 9007199254740991 || int64(_v) < -9007199254740991 {
					dst = append(dst, '"')
					dst = strconv.AppendInt(dst, int64(_v), 10)
					dst = append(dst, '"')
				} else {
					dst = strconv.AppendInt(dst, int64(_v), 10)
				}
{{- else}}
				dst = strconv.AppendInt(dst, int64(_v), 10)
{{- end}}
			}
			dst = append(dst, ']')
		}
	}
{{- else if $f.IsMsg}}
{{- if $f.IsRecursive}}
	if m.{{$f.Name}} != nil {
		if !_jsonFirstField {
			dst = append(dst, ',')
		}
		_jsonFirstField = false
		dst = append(dst, '"')
		dst = append(dst, NameOf{{$goName}}{{$f.Name}}...)
		dst = append(dst, '"', ':')
		dst = m.{{$f.Name}}.ToJSON(dst)
	}
{{- else}}
	if !_jsonFirstField {
		dst = append(dst, ',')
	}
	_jsonFirstField = false
	dst = append(dst, '"')
	dst = append(dst, NameOf{{$goName}}{{$f.Name}}...)
	dst = append(dst, '"', ':')
	dst = m.{{$f.Name}}.ToJSON(dst)
{{- end}}
{{- else if eq $f.Type "string"}}
	if len(m.{{$f.Name}}) > 0 {
		if !_jsonFirstField {
			dst = append(dst, ',')
		}
		_jsonFirstField = false
		dst = append(dst, '"')
		dst = append(dst, NameOf{{$goName}}{{$f.Name}}...)
		dst = append(dst, '"', ':')
		dst = append(dst, '"')
		dst = utils.EncodeJSONString(m.{{$f.Name}}, dst)
		dst = append(dst, '"')
	}
{{- else if eq $f.Type "bool"}}
	if m.{{$f.Name}} {
		if !_jsonFirstField {
			dst = append(dst, ',')
		}
		_jsonFirstField = false
		dst = append(dst, '"')
		dst = append(dst, NameOf{{$goName}}{{$f.Name}}...)
		dst = append(dst, '"', ':')
		dst = append(dst, "true"...)
	}
{{- else if $f.IsDecimal}}
	if !m.{{$f.Name}}.IsZero() {
		if !_jsonFirstField {
			dst = append(dst, ',')
		}
		_jsonFirstField = false
		dst = append(dst, '"')
		dst = append(dst, NameOf{{$goName}}{{$f.Name}}...)
		dst = append(dst, '"', ':')
		{
			_df, _ := m.{{$f.Name}}.Round({{decimalRound $f}}).Float64()
			dst = strconv.AppendFloat(dst, _df, 'f', {{decimalRound $f}}, 64)
		}
	}
{{- else if eq $f.Type "double"}}
	if m.{{$f.Name}} != 0 {
		if !_jsonFirstField {
			dst = append(dst, ',')
		}
		_jsonFirstField = false
		dst = append(dst, '"')
		dst = append(dst, NameOf{{$goName}}{{$f.Name}}...)
		dst = append(dst, '"', ':')
		{
			_fv := m.{{$f.Name}}
			_iv := int64(_fv)
			if math.Round(_fv) == _fv && float64(_iv) == _fv {
				dst = strconv.AppendInt(dst, _iv, 10)
			} else {
				dst = strconv.AppendFloat(dst, _fv, 'f', -1, 64)
			}
		}
	}
{{- else if eq $f.Type "float"}}
	if m.{{$f.Name}} != 0 {
		if !_jsonFirstField {
			dst = append(dst, ',')
		}
		_jsonFirstField = false
		dst = append(dst, '"')
		dst = append(dst, NameOf{{$goName}}{{$f.Name}}...)
		dst = append(dst, '"', ':')
		{
			_fv := float64(m.{{$f.Name}})
			_iv := int64(_fv)
			if math.Round(_fv) == _fv && float64(_iv) == _fv {
				dst = strconv.AppendInt(dst, _iv, 10)
			} else {
				dst = strconv.AppendFloat(dst, _fv, 'f', -1, 32)
			}
		}
	}
{{- else if or (eq $f.Type "uint32") (eq $f.Type "fixed32")}}
	if m.{{$f.Name}} != 0 {
		if !_jsonFirstField {
			dst = append(dst, ',')
		}
		_jsonFirstField = false
		dst = append(dst, '"')
		dst = append(dst, NameOf{{$goName}}{{$f.Name}}...)
		dst = append(dst, '"', ':')
		dst = strconv.AppendUint(dst, uint64(m.{{$f.Name}}), 10)
	}
{{- else if or (eq $f.Type "uint64") (eq $f.Type "fixed64")}}
	if m.{{$f.Name}} != 0 {
		if !_jsonFirstField {
			dst = append(dst, ',')
		}
		_jsonFirstField = false
		dst = append(dst, '"')
		dst = append(dst, NameOf{{$goName}}{{$f.Name}}...)
		dst = append(dst, '"', ':')
		if uint64(m.{{$f.Name}}) > 9007199254740991 {
			dst = append(dst, '"')
			dst = strconv.AppendUint(dst, uint64(m.{{$f.Name}}), 10)
			dst = append(dst, '"')
		} else {
			dst = strconv.AppendUint(dst, uint64(m.{{$f.Name}}), 10)
		}
	}
{{- else if eq $f.Type "bytes"}}
	if len(m.{{$f.Name}}) > 0 {
		if !_jsonFirstField {
			dst = append(dst, ',')
		}
		_jsonFirstField = false
		dst = append(dst, '"')
		dst = append(dst, NameOf{{$goName}}{{$f.Name}}...)
		dst = append(dst, '"', ':')
		dst = append(dst, '"')
		dst = base64.StdEncoding.AppendEncode(dst, m.{{$f.Name}})
		dst = append(dst, '"')
	}
{{- else if or (eq $f.Type "int64") (eq $f.Type "sint64") (eq $f.Type "sfixed64")}}
	if m.{{$f.Name}} != 0 {
		if !_jsonFirstField {
			dst = append(dst, ',')
		}
		_jsonFirstField = false
		dst = append(dst, '"')
		dst = append(dst, NameOf{{$goName}}{{$f.Name}}...)
		dst = append(dst, '"', ':')
		if int64(m.{{$f.Name}}) > 9007199254740991 || int64(m.{{$f.Name}}) < -9007199254740991 {
			dst = append(dst, '"')
			dst = strconv.AppendInt(dst, int64(m.{{$f.Name}}), 10)
			dst = append(dst, '"')
		} else {
			dst = strconv.AppendInt(dst, int64(m.{{$f.Name}}), 10)
		}
	}
{{- else}}
	if m.{{$f.Name}} != 0 {
		if !_jsonFirstField {
			dst = append(dst, ',')
		}
		_jsonFirstField = false
		dst = append(dst, '"')
		dst = append(dst, NameOf{{$goName}}{{$f.Name}}...)
		dst = append(dst, '"', ':')
		dst = strconv.AppendInt(dst, int64(m.{{$f.Name}}), 10)
	}
{{- end}}
{{- end}}
{{- end}}
	dst = append(dst, '}')
	return dst
}
{{- end}}

{{msgCommentBlock .Comment}}// Readonly{{$goName}} readonly struct.
// Fields are sorted with the fieldalignment strategy for
// minimal memory padding and minimal GC scan range.
type Readonly{{$goName}} struct {
	parser    fastjson.Parser
	strArena *fastjson.Arena
{{- range readerAlignedFields .ReaderFields}}
{{- if .StructTag}}
{{fieldCommentBlock .Comment}}	{{padRight .Name .NameW}} {{padRight .TypeStr .TypeW}} {{.StructTag}}
{{- else}}
{{fieldCommentBlock .Comment}}	{{padRight .Name .NameW}} {{.TypeStr}}
{{- end}}
{{- end}}
}

func (r *Readonly{{$goName}}) Clone(dst *{{$goName}}) *{{$goName}} {
	// _alignZeroPad provides zero bytes for alignment padding without heap allocation.
	// append(slice, _alignZeroPad[:n]...) appends a string — no temporary []byte is allocated.
	const _alignZeroPad = "\x00\x00\x00\x00\x00\x00\x00" // 7 bytes covers up to 8-byte alignment
	if dst == nil {
		dst = &{{$goName}}{}
	}
	if dst.arena == nil {
		dst.arena = make([]byte, 0, r.rawBufferLen)  // todo: 做一个预估大小的函数
	}
{{- range .Fields}}
{{- if .Map}}
	if len(r.{{.Name}}) > 0 {
		if dst.{{.Name}} == nil {
			{{- if mapValIsMsg .MapVal}}
			dst.{{.Name}} = make(map[{{mapKeyGoType .MapKey}}]*{{mapValGoType .MapVal}}, len(r.{{.Name}}))
			{{- else}}
			dst.{{.Name}} = make({{.GoType}}, len(r.{{.Name}}))
			{{- end}}
		}
		for _rk, _rv := range r.{{.Name}} {
		{{- if eq .MapKey "string"}}
			_kloc := len(dst.arena)
			dst.arena = append(dst.arena, _rk...)
			_nk := unsafe.String(&dst.arena[_kloc], len(_rk))
			{{- if eq .MapVal "string"}}
			if len(_rv) > 0 {
				_vloc := len(dst.arena)
				dst.arena = append(dst.arena, _rv...)
				dst.{{.Name}}[_nk] = unsafe.String(&dst.arena[_vloc], len(_rv))
			} else {
				dst.{{.Name}}[_nk] = ""
			}
			{{- else if eq .MapVal "bytes"}}
			if len(_rv) > 0 {
				_vloc := len(dst.arena)
				dst.arena = append(dst.arena, _rv...)
				_vend := _vloc + len(_rv)
				dst.{{.Name}}[_nk] = dst.arena[_vloc:_vend:_vend]
			} else {
				dst.{{.Name}}[_nk] = nil
			}
			{{- else if mapValIsMsg .MapVal}}
			_nv := new({{mapValGoType .MapVal}})  // todo: 在 arena 中分配，减少对象
			_rv.Clone(_nv)
			dst.{{.Name}}[_nk] = _nv
			{{- else}}
			dst.{{.Name}}[_nk] = _rv
			{{- end}}
		{{- else}}
			{{- if eq .MapVal "string"}}
			if len(_rv) > 0 {
				_vloc := len(dst.arena)
				dst.arena = append(dst.arena, _rv...)
				dst.{{.Name}}[_rk] = unsafe.String(&dst.arena[_vloc], len(_rv))
			} else {
				dst.{{.Name}}[_rk] = ""
			}
			{{- else if eq .MapVal "bytes"}}
			if len(_rv) > 0 {
				_vloc := len(dst.arena)
				dst.arena = append(dst.arena, _rv...)
				_vend := _vloc + len(_rv)
				dst.{{.Name}}[_rk] = dst.arena[_vloc:_vend:_vend]
			} else {
				dst.{{.Name}}[_rk] = nil
			}
			{{- else if mapValIsMsg .MapVal}}
			_nv := new({{mapValGoType .MapVal}})  // todo: 这里可以使用数组，减少对象的数量
			_rv.Clone(_nv)
			dst.{{.Name}}[_rk] = _nv
			{{- else}}
			dst.{{.Name}}[_rk] = _rv
			{{- end}}
		{{- end}}
		}
	}
{{- else if .Repeated}}
{{- if isPackable .Type}}
	if len(r.{{.Name}}) > 0 {
		{{- if is8ByteNumeric .Type}}
		if _rem := len(dst.arena) & 7; _rem != 0 {
			dst.arena = append(dst.arena, _alignZeroPad[:8-_rem]...)
		}
		_nb := len(r.{{.Name}}) * 8
		{{- else if eq .Type "bool"}}
		_nb := len(r.{{.Name}}) * 1
		{{- else}}
		if _rem := len(dst.arena) & 3; _rem != 0 {
			dst.arena = append(dst.arena, _alignZeroPad[:4-_rem]...)
		}
		_nb := len(r.{{.Name}}) * 4
		{{- end}}
		if cap(dst.arena)-len(dst.arena) < _nb {
			_nc := cap(dst.arena)*2 + _nb
			_na := make([]byte, len(dst.arena), _nc)
			copy(_na, dst.arena)
			dst.arena = _na
		}
		_loc := len(dst.arena)
		dst.arena = dst.arena[:_loc+_nb]
		copy(dst.arena[_loc:], unsafe.Slice((*byte)(unsafe.Pointer(&r.{{.Name}}[0])), _nb))
		_n := len(r.{{.Name}})
		dst.{{.Name}} = unsafe.Slice((*{{elemType .GoType}})(unsafe.Pointer(&dst.arena[_loc])), _n)
	} else {
		dst.{{.Name}} = dst.{{.Name}}[:0]
	}
{{- else if eq .Type "string"}}
	if len(r.{{.Name}}) > 0 {
		_total := 0
		for _, _s := range r.{{.Name}} {
			_total += len(_s)
		}
		if cap(dst.arena)-len(dst.arena) < _total {
			_nc := cap(dst.arena)*2 + _total
			_na := make([]byte, len(dst.arena), _nc)
			copy(_na, dst.arena)
			dst.arena = _na
		}
		if cap(dst.{{.Name}}) >= len(r.{{.Name}}) {
			dst.{{.Name}} = dst.{{.Name}}[:len(r.{{.Name}})]
		} else {
			dst.{{.Name}} = make([]string, len(r.{{.Name}}))
		}
		for _i, _s := range r.{{.Name}} {
			_loc := len(dst.arena)
			dst.arena = append(dst.arena, _s...)
			dst.{{.Name}}[_i] = unsafe.String(&dst.arena[_loc], len(_s))
		}
	} else {
		dst.{{.Name}} = dst.{{.Name}}[:0]
	}
{{- else if eq .Type "bytes"}}
	if len(r.{{.Name}}) > 0 {
		_total := 0
		for _, _b := range r.{{.Name}} {
			_total += len(_b)
		}
		if cap(dst.arena)-len(dst.arena) < _total {
			_nc := cap(dst.arena)*2 + _total
			_na := make([]byte, len(dst.arena), _nc)
			copy(_na, dst.arena)
			dst.arena = _na
		}
		if cap(dst.{{.Name}}) >= len(r.{{.Name}}) {
			dst.{{.Name}} = dst.{{.Name}}[:len(r.{{.Name}})]
		} else {
			dst.{{.Name}} = make([][]byte, len(r.{{.Name}}))
		}
		for _i, _b := range r.{{.Name}} {
			_loc := len(dst.arena)
			dst.arena = append(dst.arena, _b...)
			_end := _loc + len(_b)
			dst.{{.Name}}[_i] = dst.arena[_loc:_end:_end]
		}
	} else {
		dst.{{.Name}} = dst.{{.Name}}[:0]
	}
{{- else if .IsMsg}}
	if len(r.{{.Name}}) > 0 {
		if cap(dst.{{.Name}}) >= len(r.{{.Name}}) {
			dst.{{.Name}} = dst.{{.Name}}[:len(r.{{.Name}})]
		} else {
			dst.{{.Name}} = make([]{{elemType .GoType}}, len(r.{{.Name}}))
		}
		for _i := range r.{{.Name}} {
			r.{{.Name}}[_i].Clone(&dst.{{.Name}}[_i])
		}
	} else {
		dst.{{.Name}} = dst.{{.Name}}[:0]
	}
{{- else}}
	// repeated enum: direct copy
	if len(r.{{.Name}}) > 0 {
		if cap(dst.{{.Name}}) >= len(r.{{.Name}}) {
			dst.{{.Name}} = dst.{{.Name}}[:len(r.{{.Name}})]
			copy(dst.{{.Name}}, r.{{.Name}})
		} else {
			dst.{{.Name}} = make([]{{elemType .GoType}}, len(r.{{.Name}}))
			copy(dst.{{.Name}}, r.{{.Name}})
		}
	} else {
		dst.{{.Name}} = dst.{{.Name}}[:0]
	}
{{- end}}
{{- else if .IsMsg}}
{{- if .IsRecursive}}
	if r._has{{.Name}} && r.{{.Name}} != nil {
		dst.{{.Name}} = r.{{.Name}}.Clone(dst.{{.Name}})
	}
{{- else}}
	r.{{.Name}}.Clone(&dst.{{.Name}})
{{- end}}
{{- else if eq .Type "string"}}
	if len(r.{{.Name}}) > 0 {
		_loc := len(dst.arena)
		dst.arena = append(dst.arena, r.{{.Name}}...)
		dst.{{.Name}} = unsafe.String(&dst.arena[_loc], len(r.{{.Name}}))
	} else {
		dst.{{.Name}} = ""
	}
{{- else if eq .Type "bytes"}}
	if len(r.{{.Name}}) > 0 {
		_loc := len(dst.arena)
		dst.arena = append(dst.arena, r.{{.Name}}...)
		_end := _loc + len(r.{{.Name}})
		dst.{{.Name}} = dst.arena[_loc:_end:_end]
	} else {
		dst.{{.Name}} = nil
	}
{{- else}}
	dst.{{.Name}} = r.{{.Name}}
{{- end}}
{{- end}}
	return dst
}

func (r *Readonly{{$goName}}) Reset() {
	r.rawBufferLen = 0
	r.parser.Reset()
{{- range .Fields}}
{{- if .Map}}
	clear(r.{{.Name}})
{{- if (mapValIsMsg .MapVal)}}
	clear(r._{{.Name}}Arr)
	r._{{.Name}}Arr = r._{{.Name}}Arr[:0]
{{- end}}
{{- else if .Repeated}}
	r.{{.Name}} = r.{{.Name}}[:0]
{{- else if .IsMsg}}
{{- if .IsRecursive}}
	r._has{{.Name}} = false
	if r.{{.Name}} != nil {
		r.{{.Name}}.Reset()
	}
{{- else}}
	r.{{.Name}}.Reset()
{{- end}}
{{- else if isSliceType .ReaderType}}
	r.{{.Name}} = r.{{.Name}}[:0]
{{- else if .IsDecimal}}
	r.{{.Name}} = decimal.Decimal{}
{{- else}}
	r.{{.Name}} = {{readerZero .ReaderType}}
{{- end}}
{{- end}}
	r.strArena = nil  // Make the object no longer referenced, and let the GC manage its lifecycle.
}

func (r *Readonly{{$goName}}) FromProtobuf(in []byte) error {
	r.rawBufferLen = len(in)
{{- if hasStringOrBytesFields .Fields}}
	if r.strArena == nil {
		r.strArena = fastjson.NewArena(r.rawBufferLen)
	}
{{- end}}	
	var err error
	for len(in) > 0 {
		var fieldNum int
		var wt utils.WireType
		fieldNum, wt, in, err = utils.ConsumeTag(in)
		if err != nil {
			return err
		}
		switch fieldNum {
{{- range .Fields}}
		case {{$goName}}{{.Name}}Tag: // {{.Name}}
			{{- if not (or (eq .Type "int32") (eq .Type "uint32") (eq .Type "sint32") (eq .Type "int64") (eq .Type "uint64") (eq .Type "sint64"))}}
			if {{if or .Map .Repeated .IsMsg (eq .Type "string") (eq .Type "bytes")}}wt != utils.WireTypeLenDelim{{else if or (eq .Type "double") (eq .Type "fixed64") (eq .Type "sfixed64")}}wt != utils.WireType64bit{{else if or (eq .Type "float") (eq .Type "fixed32") (eq .Type "sfixed32")}}wt != utils.WireType32bit{{else}}wt != utils.WireTypeVarint{{end}} {
				return fmt.Errorf("proto: wrong wireType = %d for field {{.Name}}", wt)
			}
			{{- end}}
{{- if .Map}}
			var entryData []byte
			entryData, in, err = utils.ConsumeBytes(in)
			if err != nil {
				return err
			}
			// todo: 提前 count 元素个数
			var mKey {{mapKeyGoType .MapKey}}
			{{- if mapValIsMsg .MapVal}}
			if cap(r._{{.Name}}Arr) < 16 {
				r._{{.Name}}Arr = append(make([]{{readonlyTypeName .MapVal}}, 0, 16), r._{{.Name}}Arr...)
			}
			if cap(r._{{.Name}}Arr) == len(r._{{.Name}}Arr) {
				r._{{.Name}}Arr = append(r._{{.Name}}Arr, {{readonlyTypeName .MapVal}}{})
			} else {
				r._{{.Name}}Arr = r._{{.Name}}Arr[:len(r._{{.Name}}Arr)+1]
			}
			_mValIdx := len(r._{{.Name}}Arr) - 1
			{{- else}}
			var mVal {{mapValGoType .MapVal}}
			{{- end}}
			for len(entryData) > 0 {
				var efn int
				var ewt utils.WireType
				efn, ewt, entryData, err = utils.ConsumeTag(entryData)
				if err != nil {
					return err
				}
				switch efn {
				case 1:
					mKey, entryData, err = {{readFunc .MapKey}}(entryData)
					{{- if eq .MapKey "string"}}
					mKey = r.strArena.PutString(mKey)  // The string must be copied; otherwise, Reset() may cause the string content to be set to \0.
					{{- end}}
				case 2:
					{{- if mapValIsMsg .MapVal}}
					var _subBytes []byte
					_subBytes, entryData, err = utils.ConsumeBytes(entryData)
					if err != nil {
						break
					}
					err = r._{{.Name}}Arr[_mValIdx].FromProtobufWithArena(_subBytes, r.strArena)  // reuse parent message's arena
					{{- else if mapValIsEnum .MapVal}}
					{
						var _ev int32
						_ev, entryData, err = utils.ReadInt32(entryData)
						mVal = {{mapValGoType .MapVal}}(_ev)
					}
					{{- else}}
					mVal, entryData, err = {{readFunc .MapVal}}(entryData)
					{{- if eq .MapVal "string"}}
					mVal = r.strArena.PutString(mVal)  // The string must be copied; otherwise, Reset() may cause the string content to be set to \0.
					{{- else if eq .MapVal "bytes"}}
					mVal = r.strArena.PutBytes(mVal)  // The string must be copied; otherwise, Reset() may cause the string content to be set to \0.
					{{- end}}
					{{- end}}
				default:
					entryData, err = utils.SkipField(ewt, entryData)
				}
				if err != nil {
					return err
				}
			}
			if r.{{.Name}} == nil {
				{{- if mapValIsMsg .MapVal}}
				r.{{.Name}} = make(map[{{mapKeyGoType .MapKey}}]*{{readonlyTypeName .MapVal}}, 64)
				{{- else}}
				r.{{.Name}} = make({{.ReaderType}}, 64)
				{{- end}}
			}
			{{- if mapValIsMsg .MapVal}}
			r.{{.Name}}[mKey] = &r._{{.Name}}Arr[_mValIdx]
			{{- else}}
			r.{{.Name}}[mKey] = mVal
			{{- end}}
{{- else if .Repeated}}
            if cap(r.{{.Name}}) < 64 {
				temp := make({{.ReaderType}}, 0, 64)  // 一开始就分配一个大一点内存，避免频繁的对 slice 扩容
				r.{{.Name}} = append(temp, r.{{.Name}}...)
			}
{{- if isPackable .Type}}
			var packedData []byte
			packedData, in, err = utils.ConsumeBytes(in)
			if err != nil {
				return err
			}
			for len(packedData) > 0 {
				var pv {{mapKeyGoType .Type}}
				pv, packedData, err = {{readFunc .Type}}(packedData)
				if err != nil {
					return err
				}
				r.{{.Name}} = append(r.{{.Name}}, pv)
			}
{{- else if eq .Type "string"}}
			var sv string
			sv, in, err = utils.ReadString(in)
			if err != nil {
				return err
			}
			sv = r.strArena.PutString(sv)  // The string must be copied; otherwise, Reset() may cause the string content to be set to \0.
			r.{{.Name}} = append(r.{{.Name}}, sv)
{{- else if eq .Type "bytes"}}
			var bv []byte
			bv, in, err = utils.ReadBytes(in)
			if err != nil {
				return err
			}
			bv = r.strArena.PutBytes(bv)  // The string must be copied; otherwise, Reset() may cause the string content to be set to \0.
			r.{{.Name}} = append(r.{{.Name}}, bv)
{{- else}}
			var subData []byte
			subData, in, err = utils.ConsumeBytes(in)
			if err != nil {
				return err
			}
			var elem {{readerElemType .}}
			if err = elem.FromProtobufWithArena(subData, r.strArena); err != nil {
				return err
			}
			r.{{.Name}} = append(r.{{.Name}}, elem)
{{- end}}
{{- else if .IsMsg}}
			var subData []byte
			subData, in, err = utils.ConsumeBytes(in)
			if err != nil {
				return err
			}
{{- if .IsRecursive}}
			if r.{{.Name}} == nil {
				r.{{.Name}} = &{{.ReaderType}}{}
			}
			r._has{{.Name}} = true
{{- end}}
			if err = r.{{.Name}}.FromProtobufWithArena(subData, r.strArena); err != nil {
				return err
			}
{{- else if .IsDecimal}}
			var _rawDouble{{.Name}} float64
			_rawDouble{{.Name}}, in, err = utils.ReadDouble(in)
			if err != nil {
				return err
			}
			r.{{.Name}} = decimal.MustNew(int64(math.Round(_rawDouble{{.Name}} * math.Pow10({{.DecimalRound}}))), {{.DecimalRound}})
{{- else if eq .Type "double"}}
			r.{{.Name}}, in, err = utils.ReadDouble(in)
			if err != nil {
				return err
			}
{{- else if eq .Type "float"}}
			r.{{.Name}}, in, err = utils.ReadFloat(in)
			if err != nil {
				return err
			}
{{- else if eq .Type "fixed32"}}
			r.{{.Name}}, in, err = utils.ReadFixed32(in)
			if err != nil {
				return err
			}
{{- else if eq .Type "fixed64"}}
			r.{{.Name}}, in, err = utils.ReadFixed64(in)
			if err != nil {
				return err
			}
{{- else if eq .Type "sfixed32"}}
			r.{{.Name}}, in, err = utils.ReadSfixed32(in)
			if err != nil {
				return err
			}
{{- else if eq .Type "sfixed64"}}
			r.{{.Name}}, in, err = utils.ReadSfixed64(in)
			if err != nil {
				return err
			}
{{- else if eq .Type "sint32"}}
			if wt == utils.WireTypeVarint {
				r.{{.Name}}, in, err = utils.ReadSint32(in)
			} else if wt == utils.WireType32bit {
				// 此处只是兼容性的解码逻辑，没有风险。
				// 注意： RewriteDatatype 功能，可能导致二进制格式无法兼容。别的工具生成的代码，无法被解码
				var _fv uint32
				_fv, in, err = utils.ReadFixed32(in)
				r.{{.Name}} = int32(_fv)
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field {{.Name}}", wt)
			}
			if err != nil {
				return err
			}
{{- else if eq .Type "sint64"}}
			if wt == utils.WireTypeVarint {
				r.{{.Name}}, in, err = utils.ReadSint64(in)
			} else if wt == utils.WireType64bit {
				var _fv uint64
				_fv, in, err = utils.ReadFixed64(in)
				r.{{.Name}} = int64(_fv)
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field {{.Name}}", wt)
			}
			if err != nil {
				return err
			}
{{- else if eq .Type "int32"}}
			if wt == utils.WireTypeVarint {
				r.{{.Name}}, in, err = utils.ReadInt32(in)
			} else if wt == utils.WireType32bit {
				var _fv uint32
				_fv, in, err = utils.ReadFixed32(in)
				r.{{.Name}} = int32(_fv)
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field {{.Name}}", wt)
			}
			if err != nil {
				return err
			}
{{- else if eq .Type "int64"}}
			if wt == utils.WireTypeVarint {
				r.{{.Name}}, in, err = utils.ReadInt64(in)
			} else if wt == utils.WireType64bit {
				var _fv uint64
				_fv, in, err = utils.ReadFixed64(in)
				r.{{.Name}} = int64(_fv)
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field {{.Name}}", wt)
			}
			if err != nil {
				return err
			}
{{- else if eq .Type "uint32"}}
			if wt == utils.WireTypeVarint {
				r.{{.Name}}, in, err = utils.ReadUint32(in)
			} else if wt == utils.WireType32bit {
				r.{{.Name}}, in, err = utils.ReadFixed32(in)
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field {{.Name}}", wt)
			}
			if err != nil {
				return err
			}
{{- else if eq .Type "uint64"}}
			if wt == utils.WireTypeVarint {
				r.{{.Name}}, in, err = utils.ReadUint64(in)
			} else if wt == utils.WireType64bit {
				r.{{.Name}}, in, err = utils.ReadFixed64(in)
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field {{.Name}}", wt)
			}
			if err != nil {
				return err
			}
{{- else if eq .Type "bool"}}
			r.{{.Name}}, in, err = utils.ReadBool(in)
			if err != nil {
				return err
			}
{{- else if eq .Type "string"}}
			r.{{.Name}}, in, err = utils.ReadString(in)
			if err != nil {
				return err
			}
			r.{{.Name}} = r.strArena.PutString(r.{{.Name}})  // The string must be copied; otherwise, Reset() may cause the string content to be set to \0.
{{- else if eq .Type "bytes"}}
			r.{{.Name}}, in, err = utils.ReadBytes(in)
			if err != nil {
				return err
			}
			r.{{.Name}} = r.strArena.PutBytes(r.{{.Name}})  // The string must be copied; otherwise, Reset() may cause the string content to be set to \0.
{{- else}}
			var ev int32
			ev, in, err = utils.ReadInt32(in)
			if err != nil {
				return err
			}
			r.{{.Name}} = {{.ReaderType}}(ev)
{{- end}}
{{- end}}
		default:
			var err2 error
			in, err2 = utils.SkipField(wt, in)
			if err2 != nil {
				return err2
			}
		}
	}
	return nil
}
{{- if .AsMap}}
{{- $f := index .Fields 0}}
func (r *Readonly{{$goName}}) fromJSONValue(obj *fastjson.Object, parser *fastjson.Parser, arena *fastjson.Arena) error {
	if r.strArena == nil && arena != nil {
		r.strArena = arena
	}
	var visitErr error
	if r.{{$f.Name}} == nil {
		{{- if mapValIsMsg $f.MapVal}}
		r.{{$f.Name}} = make(map[{{mapKeyGoType $f.MapKey}}]*{{readonlyTypeName $f.MapVal}}, obj.Len())
		{{- else}}
		r.{{$f.Name}} = make({{$f.ReaderType}}, obj.Len())
		{{- end}}
	}
{{- if mapValIsMsg $f.MapVal}}
	if r._{{$f.Name}}Arr == nil {
		r._{{$f.Name}}Arr = make([]{{readonlyTypeName $f.MapVal}}, 0, obj.Len())
	} else {
		if cap(r._{{$f.Name}}Arr) >= obj.Len() {
			r._{{$f.Name}}Arr = r._{{$f.Name}}Arr[:0]
		} else {
			r._{{$f.Name}}Arr = make([]{{readonlyTypeName $f.MapVal}}, 0, obj.Len())
		}
	}
{{- end}}
	obj.Visit(func(mk []byte, mv *fastjson.Value) (isContinue bool) {
		var mKey {{mapKeyGoType $f.MapKey}}
{{- $kc := jsonMapKeyClass $f.MapKey}}
{{- if eq $kc "string"}}
		mKey = unsafe.String(unsafe.SliceData(mk), len(mk))
		mKey = r.strArena.PutString(mKey)  // copy string
{{- else if eq $kc "bool"}}
		mKey = unsafe.String(unsafe.SliceData(mk), len(mk)) == "true"
{{- else if eq $kc "signed32"}}
		_mk64, _ek := fastfloat.ParseInt64(unsafe.String(unsafe.SliceData(mk), len(mk)))
		if _ek != nil {
			visitErr = _ek
			return
		}
		mKey = {{mapKeyGoType $f.MapKey}}(_mk64)
{{- else if eq $kc "signed64"}}
		_mk64, _ek := fastfloat.ParseInt64(unsafe.String(unsafe.SliceData(mk), len(mk)))
		if _ek != nil {
			visitErr = _ek
			return
		}
		mKey = _mk64
{{- else if eq $kc "unsigned32"}}
		_mku64, _ek := fastfloat.ParseUint64(unsafe.String(unsafe.SliceData(mk), len(mk)))
		if _ek != nil {
			visitErr = _ek
			return
		}
		mKey = {{mapKeyGoType $f.MapKey}}(_mku64)
{{- else if eq $kc "unsigned64"}}
		_mku64, _ek := fastfloat.ParseUint64(unsafe.String(unsafe.SliceData(mk), len(mk)))
		if _ek != nil {
			visitErr = _ek
			return
		}
		mKey = _mku64
{{- end}}
{{- if mapValIsMsg $f.MapVal}}
		r._{{$f.Name}}Arr = r._{{$f.Name}}Arr[:len(r._{{$f.Name}}Arr)+1]
		_mValIdx := len(r._{{$f.Name}}Arr) - 1
		sub := &r._{{$f.Name}}Arr[_mValIdx]
{{- if $f.MapValMsgIsAsArray}}
		_subArr, _eo := mv.Array()
		if _eo != nil {
			visitErr = _eo
			return
		}
		if _eo2 := sub.fromJSONArray(_subArr, parser, r.strArena); _eo2 != nil {
			visitErr = _eo2
			return
		}
{{- else}}
		_subObj, _eo := mv.Object()
		if _eo != nil {
			visitErr = _eo
			return
		}
		if _eo2 := sub.fromJSONValue(_subObj, parser, r.strArena); _eo2 != nil {
			visitErr = _eo2
			return
		}
{{- end}}
		r.{{$f.Name}}[mKey] = sub
{{- else}}
		var mVal {{mapValGoType $f.MapVal}}
{{- $vc := jsonScalarClass $f.MapVal}}
{{- if eq $vc "string"}}
		_s, _ev := mv.UnescapeString(parser)  // unescape and clone
		if _ev != nil {
			visitErr = _ev
			return
		}
		mVal = _s
{{- else if eq $vc "bytes"}}
		_b64, _ev := mv.StringBytes()
		if _ev != nil {
			visitErr = _ev
			return
		}
		var _ev2 error
		mVal = r.strArena.Reserve(len(_b64))
		mVal, _ev2 = base64.StdEncoding.AppendDecode(mVal[:0], _b64)
		if _ev2 != nil {
			visitErr = _ev2
			return
		}
{{- else if eq $vc "bool"}}
		_bv, _ev := mv.Bool()
		if _ev != nil {
			visitErr = _ev
			return
		}
		mVal = _bv
{{- else if eq $vc "float"}}
		var _fv float64
		if mv.Type(parser) == fastjson.TypeString {
			_sb, _ev := mv.StringBytes()
			if _ev != nil {
				visitErr = _ev
				return
			}
			var _ev2 error
			_fv, _ev2 = fastfloat.Parse(unsafe.String(unsafe.SliceData(_sb), len(_sb)))
			if _ev2 != nil {
				visitErr = _ev2
				return
			}
		} else {
			var _ev error
			_fv, _ev = mv.Float64()
			if _ev != nil {
				visitErr = _ev
				return
			}
		}
		mVal = {{mapValGoType $f.MapVal}}(_fv)
{{- else if eq $vc "signed"}}
		_iv, _ev := mv.Int64()
		if _ev != nil {
			visitErr = _ev
			return
		}
		mVal = {{mapValGoType $f.MapVal}}(_iv)
{{- else if eq $vc "signed64"}}
		var _iv int64
		if mv.Type(parser) == fastjson.TypeString {
			_sb, _ev := mv.StringBytes()
			if _ev != nil {
				visitErr = _ev
				return
			}
			var _ev2 error
			_iv, _ev2 = fastfloat.ParseInt64(unsafe.String(unsafe.SliceData(_sb), len(_sb)))
			if _ev2 != nil {
				visitErr = _ev2
				return
			}
		} else {
			var _ev error
			_iv, _ev = mv.Int64()
			if _ev != nil {
				visitErr = _ev
				return
			}
		}
		mVal = {{mapValGoType $f.MapVal}}(_iv)
{{- else if eq $vc "unsigned"}}
		_uv, _ev := mv.Uint64()
		if _ev != nil {
			visitErr = _ev
			return
		}
		mVal = {{mapValGoType $f.MapVal}}(_uv)
{{- else if eq $vc "unsigned64"}}
		var _uv uint64
		if mv.Type(parser) == fastjson.TypeString {
			_sb, _ev := mv.StringBytes()
			if _ev != nil {
				visitErr = _ev
				return
			}
			var _ev2 error
			_uv, _ev2 = fastfloat.ParseUint64(unsafe.String(unsafe.SliceData(_sb), len(_sb)))
			if _ev2 != nil {
				visitErr = _ev2
				return
			}
		} else {
			var _ev error
			_uv, _ev = mv.Uint64()
			if _ev != nil {
				visitErr = _ev
				return
			}
		}
		mVal = {{mapValGoType $f.MapVal}}(_uv)
{{- end}}
		r.{{$f.Name}}[mKey] = mVal
{{- end}}
		isContinue = true
		return
	}, parser, {{if eq $f.MapKey "string"}}false{{else}}true{{end}})
	return visitErr
}
{{- else if .AsArray}}
{{- $f := index .Fields 0}}
func (r *Readonly{{$goName}}) fromJSONArray(arr []*fastjson.Value, parser *fastjson.Parser, arena *fastjson.Arena) error {
	if r.strArena == nil && arena != nil {
		r.strArena = arena
	}
	if cap(r.{{$f.Name}}) < len(arr) {
		r.{{$f.Name}} = make({{$f.ReaderType}}, 0, len(arr))
	} else {
		r.{{$f.Name}} = r.{{$f.Name}}[:0]
	}
{{- if $f.IsMsg}}
	for _, _item := range arr {
		var _elem {{elemType $f.ReaderType}}
{{- if $f.MsgIsAsArray}}
		_subArr, _eo := _item.Array()
		if _eo != nil {
			return _eo
		}
		if _eo2 := _elem.fromJSONArray(_subArr, parser, r.strArena); _eo2 != nil {
			return _eo2
		}
{{- else}}
		_subObj, _eo := _item.Object()
		if _eo != nil {
			return _eo
		}
		if _eo2 := _elem.fromJSONValue(_subObj, parser, r.strArena); _eo2 != nil {
			return _eo2
		}
{{- end}}
		r.{{$f.Name}} = append(r.{{$f.Name}}, _elem)
	}
{{- else if $f.IsEnum}}
	for _, _item := range arr {
		_iv, _ei := _item.Int64()
		if _ei != nil {
			return _ei
		}
		r.{{$f.Name}} = append(r.{{$f.Name}}, {{elemType $f.ReaderType}}(_iv))
	}
{{- else}}
{{- $sc := jsonScalarClass $f.Type}}
	for _, _item := range arr {
{{- if eq $sc "string"}}
		_s, _ei := _item.UnescapeString(parser)  // Unescape and clone
		if _ei != nil {
			return _ei
		}
		r.{{$f.Name}} = append(r.{{$f.Name}}, _s)
{{- else if eq $sc "bytes"}}
		_b64, _ei := _item.StringBytes()
		if _ei != nil {
			return _ei
		}
		var _dec []byte
		var _ei2 error
		_dec = r.strArena.Reserve(len(_b64))
		_dec, _ei2 = base64.StdEncoding.AppendDecode(_dec[:0], _b64)
		if _ei2 != nil {
			return _ei2
		}
		r.{{$f.Name}} = append(r.{{$f.Name}}, _dec)
{{- else if eq $sc "bool"}}
		_bv, _ei := _item.Bool()
		if _ei != nil {
			return _ei
		}
		r.{{$f.Name}} = append(r.{{$f.Name}}, _bv)
{{- else if eq $sc "float"}}
		var _fv float64
		if _item.Type(parser) == fastjson.TypeString {
			_sb, _ei := _item.StringBytes()
			if _ei != nil {
				return _ei
			}
			var _ei2 error
			_fv, _ei2 = fastfloat.Parse(unsafe.String(unsafe.SliceData(_sb), len(_sb)))
			if _ei2 != nil {
				return _ei2
			}
		} else {
			var _ei error
			_fv, _ei = _item.Float64()
			if _ei != nil {
				return _ei
			}
		}
		r.{{$f.Name}} = append(r.{{$f.Name}}, {{elemType $f.ReaderType}}(_fv))
{{- else if eq $sc "signed"}}
		_iv, _ei := _item.Int64()
		if _ei != nil {
			return _ei
		}
		r.{{$f.Name}} = append(r.{{$f.Name}}, {{elemType $f.ReaderType}}(_iv))
{{- else if eq $sc "signed64"}}
		var _iv int64
		if _item.Type(parser) == fastjson.TypeString {
			_sb, _ei := _item.StringBytes()
			if _ei != nil {
				return _ei
			}
			var _ei2 error
			_iv, _ei2 = fastfloat.ParseInt64(unsafe.String(unsafe.SliceData(_sb), len(_sb)))
			if _ei2 != nil {
				return _ei2
			}
		} else {
			var _ei error
			_iv, _ei = _item.Int64()
			if _ei != nil {
				return _ei
			}
		}
		r.{{$f.Name}} = append(r.{{$f.Name}}, {{elemType $f.ReaderType}}(_iv))
{{- else if eq $sc "unsigned"}}
		_uv, _ei := _item.Uint64()
		if _ei != nil {
			return _ei
		}
		r.{{$f.Name}} = append(r.{{$f.Name}}, {{elemType $f.ReaderType}}(_uv))
{{- else if eq $sc "unsigned64"}}
		var _uv uint64
		if _item.Type(parser) == fastjson.TypeString {
			_sb, _ei := _item.StringBytes()
			if _ei != nil {
				return _ei
			}
			var _ei2 error
			_uv, _ei2 = fastfloat.ParseUint64(unsafe.String(unsafe.SliceData(_sb), len(_sb)))
			if _ei2 != nil {
				return _ei2
			}
		} else {
			var _ei error
			_uv, _ei = _item.Uint64()
			if _ei != nil {
				return _ei
			}
		}
		r.{{$f.Name}} = append(r.{{$f.Name}}, {{elemType $f.ReaderType}}(_uv))
{{- end}}
	}
{{- end}}
	return nil
}
{{- else}}
func (r *Readonly{{$goName}}) fromJSONValue(obj *fastjson.Object, parser *fastjson.Parser, arena *fastjson.Arena) error {
	if r.strArena == nil && arena != nil {
		r.strArena = arena
	}
	var visitErr error
	obj.Visit(func(k []byte, v *fastjson.Value) (isContinue bool) {
		k1 := unsafe.String(unsafe.SliceData(k), len(k))
		switch k1 {
{{- range .Fields}}
		case NameOf{{$goName}}{{.Name}}:
{{- $nullSc := jsonScalarClass .Type}}
{{- $isPlainStrBytes := and (not .Map) (not .Repeated) (not .IsMsg) (not .IsEnum) (not .IsDecimal) (or (eq $nullSc "string") (eq $nullSc "bytes"))}}
{{- if not $isPlainStrBytes}}
			// a JSON null value means the field is absent; keep its zero value and skip.
			// (Type() is side-effect-free here since the value is object/array/number/bool/null, never a raw string.)
			if v.Type(parser) == fastjson.TypeNull {
				isContinue = true
				return
			}
{{- end}}
{{- if .Map}}
			_mapObj, _e := v.Object()
			if _e != nil {
				visitErr = _e
				return
			}
			if r.{{.Name}} == nil {
				{{- if mapValIsMsg .MapVal}}
				r.{{.Name}} = make(map[{{mapKeyGoType .MapKey}}]*{{readonlyTypeName .MapVal}}, _mapObj.Len())
				{{- else}}
				r.{{.Name}} = make({{.ReaderType}}, _mapObj.Len())
				{{- end}}
			}
{{- if mapValIsMsg .MapVal}}
			if r._{{.Name}}Arr == nil {
				r._{{.Name}}Arr = make([]{{readonlyTypeName .MapVal}}, 0, _mapObj.Len())
			} else {
				if cap(r._{{.Name}}Arr) >= _mapObj.Len() {
					r._{{.Name}}Arr = r._{{.Name}}Arr[:0]
				} else {
					r._{{.Name}}Arr = make([]{{readonlyTypeName .MapVal}}, 0, _mapObj.Len())
				}
			}
{{- end}}
			_mapObj.Visit(func(mk []byte, mv *fastjson.Value) (isContinue bool) {
				var mKey {{mapKeyGoType .MapKey}}
{{- $kc := jsonMapKeyClass .MapKey}}
{{- if eq $kc "string"}}
				mKey = unsafe.String(unsafe.SliceData(mk), len(mk))
				mKey = r.strArena.PutString(mKey)  // copy string  // todo: 如果 key 存在转义字符，这时候就会导致重复拷贝
{{- else if eq $kc "bool"}}
				mKey = unsafe.String(unsafe.SliceData(mk), len(mk)) == "true"
{{- else if eq $kc "signed32"}}
				_mk64, _ek := fastfloat.ParseInt64(unsafe.String(unsafe.SliceData(mk), len(mk)))
				if _ek != nil {
					visitErr = _ek
					return
				}
				mKey = {{mapKeyGoType .MapKey}}(_mk64)
{{- else if eq $kc "signed64"}}
				_mk64, _ek := fastfloat.ParseInt64(unsafe.String(unsafe.SliceData(mk), len(mk)))
				if _ek != nil {
					visitErr = _ek
					return
				}
				mKey = _mk64
{{- else if eq $kc "unsigned32"}}
				_mku64, _ek := fastfloat.ParseUint64(unsafe.String(unsafe.SliceData(mk), len(mk)))
				if _ek != nil {
					visitErr = _ek
					return
				}
				mKey = {{mapKeyGoType .MapKey}}(_mku64)
{{- else if eq $kc "unsigned64"}}
				_mku64, _ek := fastfloat.ParseUint64(unsafe.String(unsafe.SliceData(mk), len(mk)))
				if _ek != nil {
					visitErr = _ek
					return
				}
				mKey = _mku64
{{- end}}
{{- if mapValIsMsg .MapVal}}
				r._{{.Name}}Arr = r._{{.Name}}Arr[:len(r._{{.Name}}Arr)+1]
				_mValIdx := len(r._{{.Name}}Arr) - 1
				sub := &r._{{.Name}}Arr[_mValIdx]
{{- if .MapValMsgIsAsArray}}
				_subArr, _eo := mv.Array()
				if _eo != nil {
					visitErr = _eo
					return
				}
				if _eo2 := sub.fromJSONArray(_subArr, parser, r.strArena); _eo2 != nil {
					visitErr = _eo2
					return
				}
{{- else}}
				_subObj, _eo := mv.Object()
				if _eo != nil {
					visitErr = _eo
					return
				}
				if _eo2 := sub.fromJSONValue(_subObj, parser, r.strArena); _eo2 != nil {
					visitErr = _eo2
					return
				}
{{- end}}
				r.{{.Name}}[mKey] = sub
{{- else}}
				var mVal {{mapValGoType .MapVal}}
{{- $vc := jsonScalarClass .MapVal}}
{{- if eq $vc "string"}}
				_s, _ev := mv.UnescapeString(parser)  // unescape and clone
				if _ev != nil {
					visitErr = _ev
					return
				}
				mVal = _s
{{- else if eq $vc "bytes"}}
				_b64, _ev := mv.StringBytes()
				if _ev != nil {
					visitErr = _ev
					return
				}
				var _ev2 error
				mVal = r.strArena.Reserve(len(_b64))
				mVal, _ev2 = base64.StdEncoding.AppendDecode(mVal[:0], _b64)
				if _ev2 != nil {
					visitErr = _ev2
					return
				}
{{- else if eq $vc "bool"}}
				_bv, _ev := mv.Bool()
				if _ev != nil {
					visitErr = _ev
					return
				}
				mVal = _bv
{{- else if eq $vc "float"}}
				var _fv float64
				if mv.Type(parser) == fastjson.TypeString {
					_sb, _ev := mv.StringBytes()
					if _ev != nil {
						visitErr = _ev
						return
					}
					var _ev2 error
					_fv, _ev2 = fastfloat.Parse(unsafe.String(unsafe.SliceData(_sb), len(_sb)))
					if _ev2 != nil {
						visitErr = _ev2
						return
					}
				} else {
					var _ev error
					_fv, _ev = mv.Float64()
					if _ev != nil {
						visitErr = _ev
						return
					}
				}
				mVal = {{mapValGoType .MapVal}}(_fv)
{{- else if eq $vc "signed"}}
				_iv, _ev := mv.Int64()
				if _ev != nil {
					visitErr = _ev
					return
				}
				mVal = {{mapValGoType .MapVal}}(_iv)
{{- else if eq $vc "signed64"}}
				var _iv int64
				if mv.Type(parser) == fastjson.TypeString {
					_sb, _ev := mv.StringBytes()
					if _ev != nil {
						visitErr = _ev
						return
					}
					var _ev2 error
					_iv, _ev2 = fastfloat.ParseInt64(unsafe.String(unsafe.SliceData(_sb), len(_sb)))
					if _ev2 != nil {
						visitErr = _ev2
						return
					}
				} else {
					var _ev error
					_iv, _ev = mv.Int64()
					if _ev != nil {
						visitErr = _ev
						return
					}
				}
				mVal = {{mapValGoType .MapVal}}(_iv)
{{- else if eq $vc "unsigned"}}
				_uv, _ev := mv.Uint64()
				if _ev != nil {
					visitErr = _ev
					return
				}
				mVal = {{mapValGoType .MapVal}}(_uv)
{{- else if eq $vc "unsigned64"}}
				var _uv uint64
				if mv.Type(parser) == fastjson.TypeString {
					_sb, _ev := mv.StringBytes()
					if _ev != nil {
						visitErr = _ev
						return
					}
					var _ev2 error
					_uv, _ev2 = fastfloat.ParseUint64(unsafe.String(unsafe.SliceData(_sb), len(_sb)))
					if _ev2 != nil {
						visitErr = _ev2
						return
					}
				} else {
					var _ev error
					_uv, _ev = mv.Uint64()
					if _ev != nil {
						visitErr = _ev
						return
					}
				}
				mVal = {{mapValGoType .MapVal}}(_uv)
{{- end}}
				r.{{.Name}}[mKey] = mVal
{{- end}}
				isContinue = true
				return
			}, parser, {{if eq .MapKey "string"}}false{{else}}true{{end}})
{{- else if .Repeated}}
			_arr, _e := v.Array()
			if _e != nil {
				visitErr = _e
				return
			}
			if cap(r.{{.Name}}) < len(_arr) {
				r.{{.Name}} = make({{.ReaderType}}, 0, len(_arr))
			} else {
				r.{{.Name}} = r.{{.Name}}[:0]
			}
{{- if .IsMsg}}
			for _, _item := range _arr {
				var _elem {{elemType .ReaderType}}
{{- if .MsgIsAsArray}}
				_subArr, _eo := _item.Array()
				if _eo != nil {
					visitErr = _eo
					return
				}
				if _eo2 := _elem.fromJSONArray(_subArr, parser, r.strArena); _eo2 != nil {
					visitErr = _eo2
					return
				}
{{- else}}
				_subObj, _eo := _item.Object()
				if _eo != nil {
					visitErr = _eo
					return
				}
				if _eo2 := _elem.fromJSONValue(_subObj, parser, r.strArena); _eo2 != nil {
					visitErr = _eo2
					return
				}
{{- end}}
				r.{{.Name}} = append(r.{{.Name}}, _elem)
			}
{{- else if .IsEnum}}
			for _, _item := range _arr {
				_iv, _ei := _item.Int64()
				if _ei != nil {
					visitErr = _ei
					return
				}
				r.{{.Name}} = append(r.{{.Name}}, {{elemType .ReaderType}}(_iv))
			}
{{- else}}
{{- $sc := jsonScalarClass .Type}}
			for _, _item := range _arr {
{{- if eq $sc "string"}}
				_s, _ei := _item.UnescapeString(parser)  // unescape and clone
				if _ei != nil {
					visitErr = _ei
					return
				}
				r.{{.Name}} = append(r.{{.Name}}, _s)
{{- else if eq $sc "bytes"}}
				_b64, _ei := _item.StringBytes()
				if _ei != nil {
					visitErr = _ei
					return
				}
				var _dec []byte
				var _ei2 error
				_dec = r.strArena.Reserve(len(_b64))
				_dec, _ei2 = base64.StdEncoding.AppendDecode(_dec[:0], _b64)
				if _ei2 != nil {
					visitErr = _ei2
					return
				}
				r.{{.Name}} = append(r.{{.Name}}, _dec)
{{- else if eq $sc "bool"}}
				_bv, _ei := _item.Bool()
				if _ei != nil {
					visitErr = _ei
					return
				}
				r.{{.Name}} = append(r.{{.Name}}, _bv)
{{- else if eq $sc "float"}}
				var _fv float64
				if _item.Type(parser) == fastjson.TypeString {
					_sb, _ei := _item.StringBytes()
					if _ei != nil {
						visitErr = _ei
						return
					}
					var _ei2 error
					_fv, _ei2 = fastfloat.Parse(unsafe.String(unsafe.SliceData(_sb), len(_sb)))
					if _ei2 != nil {
						visitErr = _ei2
						return
					}
				} else {
					var _ei error
					_fv, _ei = _item.Float64()
					if _ei != nil {
						visitErr = _ei
						return
					}
				}
				r.{{.Name}} = append(r.{{.Name}}, {{elemType .ReaderType}}(_fv))
{{- else if eq $sc "signed"}}
				_iv, _ei := _item.Int64()
				if _ei != nil {
					visitErr = _ei
					return
				}
				r.{{.Name}} = append(r.{{.Name}}, {{elemType .ReaderType}}(_iv))
{{- else if eq $sc "signed64"}}
				var _iv int64
				if _item.Type(parser) == fastjson.TypeString {
					_sb, _ei := _item.StringBytes()
					if _ei != nil {
						visitErr = _ei
						return
					}
					var _ei2 error
					_iv, _ei2 = fastfloat.ParseInt64(unsafe.String(unsafe.SliceData(_sb), len(_sb)))
					if _ei2 != nil {
						visitErr = _ei2
						return
					}
				} else {
					var _ei error
					_iv, _ei = _item.Int64()
					if _ei != nil {
						visitErr = _ei
						return
					}
				}
				r.{{.Name}} = append(r.{{.Name}}, {{elemType .ReaderType}}(_iv))
{{- else if eq $sc "unsigned"}}
				_uv, _ei := _item.Uint64()
				if _ei != nil {
					visitErr = _ei
					return
				}
				r.{{.Name}} = append(r.{{.Name}}, {{elemType .ReaderType}}(_uv))
{{- else if eq $sc "unsigned64"}}
				var _uv uint64
				if _item.Type(parser) == fastjson.TypeString {
					_sb, _ei := _item.StringBytes()
					if _ei != nil {
						visitErr = _ei
						return
					}
					var _ei2 error
					_uv, _ei2 = fastfloat.ParseUint64(unsafe.String(unsafe.SliceData(_sb), len(_sb)))
					if _ei2 != nil {
						visitErr = _ei2
						return
					}
				} else {
					var _ei error
					_uv, _ei = _item.Uint64()
					if _ei != nil {
						visitErr = _ei
						return
					}
				}
				r.{{.Name}} = append(r.{{.Name}}, {{elemType .ReaderType}}(_uv))
{{- end}}
			}
{{- end}}
{{- else if .IsMsg}}
{{- if .MsgIsAsArray}}
			_arr, _e := v.Array()
			if _e != nil {
				visitErr = _e
				return
			}
{{- if .IsRecursive}}
			if r.{{.Name}} == nil {
				r.{{.Name}} = &{{.ReaderType}}{}
			}
			r._has{{.Name}} = true
{{- end}}
			if _e2 := r.{{.Name}}.fromJSONArray(_arr, parser, r.strArena); _e2 != nil {
				visitErr = _e2
				return
			}
{{- else}}
			_subObj, _e := v.Object()
			if _e != nil {
				visitErr = _e
				return
			}
{{- if .IsRecursive}}
			if r.{{.Name}} == nil {
				r.{{.Name}} = &{{.ReaderType}}{}
			}
			r._has{{.Name}} = true
{{- end}}
			if _e2 := r.{{.Name}}.fromJSONValue(_subObj, parser, r.strArena); _e2 != nil {
				visitErr = _e2
				return
			}
{{- end}}
{{- else if .IsEnum}}
			_iv, _e := v.Int64()
			if _e != nil {
				visitErr = _e
				return
			}
			r.{{.Name}} = {{.ReaderType}}(_iv)
{{- else if .IsDecimal}}
			_fv{{.Name}}, _e{{.Name}} := v.Float64()
			if _e{{.Name}} != nil {
				visitErr = _e{{.Name}}
				return
			}
			r.{{.Name}} = decimal.MustNew(int64(math.Round(_fv{{.Name}} * math.Pow10({{.DecimalRound}}))), {{.DecimalRound}})
{{- else}}
{{- $sc := jsonScalarClass .Type}}
{{- if eq $sc "string"}}
			_s, _e := v.UnescapeString(parser)
			if _e != nil {
				if v.Type(parser) == fastjson.TypeNull {
					// a JSON null value means the field is absent; keep its zero value and skip.
					// (checked on the error path so the non-null fast path never triggers Type()'s unescape side-effect.)
					isContinue = true
					return
				}
				visitErr = _e
				return
			}
			r.{{.Name}} = _s
{{- else if eq $sc "bytes"}}
			_b64, _e := v.StringBytes()
			if _e != nil {
				if v.Type(parser) == fastjson.TypeNull {
					// a JSON null value means the field is absent; keep its zero value and skip.
					// (checked on the error path so the non-null fast path never triggers Type()'s unescape side-effect.)
					isContinue = true
					return
				}
				visitErr = _e
				return
			}
			var _e2 error
			r.{{.Name}}, _e2 = base64.StdEncoding.AppendDecode(r.{{.Name}}[:0], _b64)
			if _e2 != nil {
				visitErr = _e2
				return
			}
{{- else if eq $sc "bool"}}
			_bv, _e := v.Bool()
			if _e != nil {
				visitErr = _e
				return
			}
			r.{{.Name}} = _bv
{{- else if eq $sc "float"}}
			var _fv float64
			if v.Type(parser) == fastjson.TypeString {
				_sb, _e := v.StringBytes()
				if _e != nil {
					visitErr = _e
					return
				}
				var _e2 error
				_fv, _e2 = fastfloat.Parse(unsafe.String(unsafe.SliceData(_sb), len(_sb)))
				if _e2 != nil {
					visitErr = _e2
					return
				}
			} else {
				var _e error
				_fv, _e = v.Float64()
				if _e != nil {
					visitErr = _e
					return
				}
			}
			r.{{.Name}} = {{.ReaderType}}(_fv)
{{- else if eq $sc "signed"}}
			_iv, _e := v.Int64()
			if _e != nil {
				visitErr = _e
				return
			}
			r.{{.Name}} = {{.ReaderType}}(_iv)
{{- else if eq $sc "signed64"}}
			var _iv int64
			if v.Type(parser) == fastjson.TypeString {
				_sb, _e := v.StringBytes()
				if _e != nil {
					visitErr = _e
					return
				}
				var _e2 error
				_iv, _e2 = fastfloat.ParseInt64(unsafe.String(unsafe.SliceData(_sb), len(_sb)))
				if _e2 != nil {
					visitErr = _e2
					return
				}
			} else {
				var _e error
				_iv, _e = v.Int64()
				if _e != nil {
					visitErr = _e
					return
				}
			}
			r.{{.Name}} = {{.ReaderType}}(_iv)
{{- else if eq $sc "unsigned"}}
			_uv, _e := v.Uint64()
			if _e != nil {
				visitErr = _e
				return
			}
			r.{{.Name}} = {{.ReaderType}}(_uv)
{{- else if eq $sc "unsigned64"}}
			var _uv uint64
			if v.Type(parser) == fastjson.TypeString {
				_sb, _e := v.StringBytes()
				if _e != nil {
					visitErr = _e
					return
				}
				var _e2 error
				_uv, _e2 = fastfloat.ParseUint64(unsafe.String(unsafe.SliceData(_sb), len(_sb)))
				if _e2 != nil {
					visitErr = _e2
					return
				}
			} else {
				var _e error
				_uv, _e = v.Uint64()
				if _e != nil {
					visitErr = _e
					return
				}
			}
			r.{{.Name}} = {{.ReaderType}}(_uv)
{{- end}}
{{- end}}
{{- end}}
		}
		isContinue = true
		return
	}, parser, true/*skip unescape keys, because all key must by proto field name*/)
	return visitErr
}
{{- end}}

func (r *Readonly{{$goName}}) FromJSON(src []byte) error {
	r.rawBufferLen = len(src)
	parser := &r.parser
{{- if hasStringOrBytesFields .Fields}}
	if r.strArena == nil {
		r.strArena = fastjson.NewArena(r.rawBufferLen)
	}
{{- end}}
	v, err := parser.Parse(unsafe.String(unsafe.SliceData(src), len(src)), r.strArena)
	if err != nil {
		return err
	}
{{- if .AsArray}}
	arr, err := v.Array()
	if err != nil {
		return err
	}
	return r.fromJSONArray(arr, parser, r.strArena)
{{- else}}
	obj, err := v.Object()
	if err != nil {
		return err
	}
	return r.fromJSONValue(obj, parser, r.strArena)
{{- end}}
}

func (r *Readonly{{$goName}}) FromProtobufWithArena(in []byte, arena *fastjson.Arena) error {
	r.strArena = arena
	return r.FromProtobuf(in)
}

// marshalToSizedBufferVT writes m into dAtA using vtprotobuf's backward-fill
// approach (starts at the end, works toward the front).
// Returns number of bytes written = len(dAtA) - final_i.
func (m *{{$goName}}) marshalToSizedBufferVT(dAtA []byte) int {
	if m == nil {
		return 0
	}
	i := len(dAtA)
	_ = i
{{- range .Fields}}
{{- if .Map}}
	for k := range m.{{.Name}} {
		v := m.{{.Name}}[k]
		baseI := i
		{{- if eq .MapVal "string"}}
		i -= len(v)
		copy(dAtA[i:], v)
		i = utils.EncodeVarint(dAtA, i, uint64(len(v)))
		i--
		dAtA[i] = 18 /*(2<<3)|2=18, field=2, wireType=LenDelim*/
		{{- else if eq .MapVal "bytes"}}
		i -= len(v)
		copy(dAtA[i:], v)
		i = utils.EncodeVarint(dAtA, i, uint64(len(v)))
		i--
		dAtA[i] = 18 /*(2<<3)|2=18, field=2, wireType=LenDelim*/
		{{- else if mapValIsMsg .MapVal}}
		size := v.marshalToSizedBufferVT(dAtA[:i])
		i -= size
		i = utils.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 18 /*(2<<3)|2=18, field=2, wireType=LenDelim*/
		{{- else if eq .MapVal "double"}}
		i -= 8
		_dv := math.Float64bits(v)
		dAtA[i+7] = uint8(_dv >> 56)
		dAtA[i+6] = uint8(_dv >> 48)
		dAtA[i+5] = uint8(_dv >> 40)
		dAtA[i+4] = uint8(_dv >> 32)
		dAtA[i+3] = uint8(_dv >> 24)
		dAtA[i+2] = uint8(_dv >> 16)
		dAtA[i+1] = uint8(_dv >> 8)
		dAtA[i+0] = uint8(_dv)
		i--
		dAtA[i] = 17 /*(2<<3)|1=17, field=2, wireType=64bit*/
		{{- else if eq .MapVal "float"}}
		i -= 4
		_fv := math.Float32bits(v)
		dAtA[i+3] = uint8(_fv >> 24)
		dAtA[i+2] = uint8(_fv >> 16)
		dAtA[i+1] = uint8(_fv >> 8)
		dAtA[i+0] = uint8(_fv)
		i--
		dAtA[i] = 21 /*(2<<3)|5=21, field=2, wireType=32bit*/
		{{- else if eq .MapVal "fixed32"}}
		i -= 4
		dAtA[i+3] = uint8(uint32(v) >> 24)
		dAtA[i+2] = uint8(uint32(v) >> 16)
		dAtA[i+1] = uint8(uint32(v) >> 8)
		dAtA[i+0] = uint8(uint32(v))
		i--
		dAtA[i] = 21 /*(2<<3)|5=21, field=2, wireType=32bit*/
		{{- else if eq .MapVal "sfixed32"}}
		i -= 4
		dAtA[i+3] = uint8(uint32(v) >> 24)
		dAtA[i+2] = uint8(uint32(v) >> 16)
		dAtA[i+1] = uint8(uint32(v) >> 8)
		dAtA[i+0] = uint8(uint32(v))
		i--
		dAtA[i] = 21 /*(2<<3)|5=21, field=2, wireType=32bit*/
		{{- else if eq .MapVal "fixed64"}}
		i -= 8
		dAtA[i+7] = uint8(uint64(v) >> 56)
		dAtA[i+6] = uint8(uint64(v) >> 48)
		dAtA[i+5] = uint8(uint64(v) >> 40)
		dAtA[i+4] = uint8(uint64(v) >> 32)
		dAtA[i+3] = uint8(uint64(v) >> 24)
		dAtA[i+2] = uint8(uint64(v) >> 16)
		dAtA[i+1] = uint8(uint64(v) >> 8)
		dAtA[i+0] = uint8(uint64(v))
		i--
		dAtA[i] = 17 /*(2<<3)|1=17, field=2, wireType=64bit*/
		{{- else if eq .MapVal "sfixed64"}}
		i -= 8
		dAtA[i+7] = uint8(uint64(v) >> 56)
		dAtA[i+6] = uint8(uint64(v) >> 48)
		dAtA[i+5] = uint8(uint64(v) >> 40)
		dAtA[i+4] = uint8(uint64(v) >> 32)
		dAtA[i+3] = uint8(uint64(v) >> 24)
		dAtA[i+2] = uint8(uint64(v) >> 16)
		dAtA[i+1] = uint8(uint64(v) >> 8)
		dAtA[i+0] = uint8(uint64(v))
		i--
		dAtA[i] = 17 /*(2<<3)|1=17, field=2, wireType=64bit*/
		{{- else if eq .MapVal "sint32"}}
		i = utils.EncodeVarint(dAtA, i, uint64((uint32(v)<<1)^uint32(v>>31)))
		i--
		dAtA[i] = 16 /*(2<<3)|0=16, field=2, wireType=Varint*/
		{{- else if eq .MapVal "sint64"}}
		i = utils.EncodeVarint(dAtA, i, (uint64(v)<<1)^uint64(v>>63))
		i--
		dAtA[i] = 16 /*(2<<3)|0=16, field=2, wireType=Varint*/
		{{- else if eq .MapVal "bool"}}
		i--
		if v { dAtA[i] = 1 } else { dAtA[i] = 0 }
		i--
		dAtA[i] = 16 /*(2<<3)|0=16, field=2, wireType=Varint*/
		{{- else}}
		i = utils.EncodeVarint(dAtA, i, uint64(v))
		i--
		dAtA[i] = 16 /*(2<<3)|0=16, field=2, wireType=Varint*/
		{{- end}}
		{{- if eq .MapKey "string"}}
		i -= len(k)
		copy(dAtA[i:], k)
		i = utils.EncodeVarint(dAtA, i, uint64(len(k)))
		i--
		dAtA[i] = 10 /*(1<<3)|2=10, field=1, wireType=LenDelim*/
		{{- else if eq .MapKey "bool"}}
		i--
		if k { dAtA[i] = 1 } else { dAtA[i] = 0 }
		i--
		dAtA[i] = 8 /*(1<<3)|0=8, field=1, wireType=Varint*/
		{{- else if eq .MapKey "fixed32"}}
		i -= 4
		dAtA[i+3] = uint8(uint32(k) >> 24)
		dAtA[i+2] = uint8(uint32(k) >> 16)
		dAtA[i+1] = uint8(uint32(k) >> 8)
		dAtA[i+0] = uint8(uint32(k))
		i--
		dAtA[i] = 13 /*(1<<3)|5=13, field=1, wireType=32bit*/
		{{- else if eq .MapKey "sfixed32"}}
		i -= 4
		dAtA[i+3] = uint8(uint32(k) >> 24)
		dAtA[i+2] = uint8(uint32(k) >> 16)
		dAtA[i+1] = uint8(uint32(k) >> 8)
		dAtA[i+0] = uint8(uint32(k))
		i--
		dAtA[i] = 13 /*(1<<3)|5=13, field=1, wireType=32bit*/
		{{- else if eq .MapKey "fixed64"}}
		i -= 8
		dAtA[i+7] = uint8(uint64(k) >> 56)
		dAtA[i+6] = uint8(uint64(k) >> 48)
		dAtA[i+5] = uint8(uint64(k) >> 40)
		dAtA[i+4] = uint8(uint64(k) >> 32)
		dAtA[i+3] = uint8(uint64(k) >> 24)
		dAtA[i+2] = uint8(uint64(k) >> 16)
		dAtA[i+1] = uint8(uint64(k) >> 8)
		dAtA[i+0] = uint8(uint64(k))
		i--
		dAtA[i] = 9 /*(1<<3)|1=9, field=1, wireType=64bit*/
		{{- else if eq .MapKey "sfixed64"}}
		i -= 8
		dAtA[i+7] = uint8(uint64(k) >> 56)
		dAtA[i+6] = uint8(uint64(k) >> 48)
		dAtA[i+5] = uint8(uint64(k) >> 40)
		dAtA[i+4] = uint8(uint64(k) >> 32)
		dAtA[i+3] = uint8(uint64(k) >> 24)
		dAtA[i+2] = uint8(uint64(k) >> 16)
		dAtA[i+1] = uint8(uint64(k) >> 8)
		dAtA[i+0] = uint8(uint64(k))
		i--
		dAtA[i] = 9 /*(1<<3)|1=9, field=1, wireType=64bit*/
		{{- else if eq .MapKey "sint32"}}
		i = utils.EncodeVarint(dAtA, i, uint64((uint32(k)<<1)^uint32(k>>31)))
		i--
		dAtA[i] = 8 /*(1<<3)|0=8, field=1, wireType=Varint*/
		{{- else if eq .MapKey "sint64"}}
		i = utils.EncodeVarint(dAtA, i, (uint64(k)<<1)^uint64(k>>63))
		i--
		dAtA[i] = 8 /*(1<<3)|0=8, field=1, wireType=Varint*/
		{{- else}}
		i = utils.EncodeVarint(dAtA, i, uint64(k))
		i--
		dAtA[i] = 8 /*(1<<3)|0=8, field=1, wireType=Varint*/
		{{- end}}
		// write outer map entry length + field tag
		i = utils.EncodeVarint(dAtA, i, uint64(baseI-i))
		{{writeTagBytes .Number 2}}
	}
{{- else if .Repeated}}
{{- if isPackable .Type}}
	if len(m.{{.Name}}) > 0 {
		pksize := 0
		for _, v := range m.{{.Name}} {
			{{- if eq .Type "sint32"}}
			pksize += ((bits.Len64(uint64((uint32(v)<<1)^uint32(v>>31))|1) + 6) / 7)
			{{- else if eq .Type "sint64"}}
			pksize += ((bits.Len64((uint64(v)<<1)^uint64(v>>63)|1) + 6) / 7)
			{{- else if eq .Type "fixed32"}}
			_ = v; pksize += 4
			{{- else if eq .Type "fixed64"}}
			_ = v; pksize += 8
			{{- else if eq .Type "sfixed32"}}
			_ = v; pksize += 4
			{{- else if eq .Type "sfixed64"}}
			_ = v; pksize += 8
			{{- else if eq .Type "float"}}
			_ = v; pksize += 4
			{{- else if eq .Type "double"}}
			_ = v; pksize += 8
			{{- else if eq .Type "bool"}}
			_ = v; pksize += 1
			{{- else}}
			pksize += ((bits.Len64(uint64(v)|1) + 6) / 7)
			{{- end}}
		}
		i -= pksize
		j := i
		for _, v := range m.{{.Name}} {
			{{- if eq .Type "sint32"}}
			uv := uint64((uint32(v)<<1)^uint32(v>>31))
			for uv >= 0x80 { dAtA[j] = byte(uv)|0x80; uv >>= 7; j++ }
			dAtA[j] = byte(uv); j++
			{{- else if eq .Type "sint64"}}
			uv := (uint64(v)<<1)^uint64(v>>63)
			for uv >= 0x80 { dAtA[j] = byte(uv)|0x80; uv >>= 7; j++ }
			dAtA[j] = byte(uv); j++
			{{- else if eq .Type "fixed32"}}
			dAtA[j+3] = uint8(uint32(v) >> 24)
			dAtA[j+2] = uint8(uint32(v) >> 16)
			dAtA[j+1] = uint8(uint32(v) >> 8)
			dAtA[j+0] = uint8(uint32(v))
			j += 4
			{{- else if eq .Type "fixed64"}}
			dAtA[j+7] = uint8(uint64(v) >> 56)
			dAtA[j+6] = uint8(uint64(v) >> 48)
			dAtA[j+5] = uint8(uint64(v) >> 40)
			dAtA[j+4] = uint8(uint64(v) >> 32)
			dAtA[j+3] = uint8(uint64(v) >> 24)
			dAtA[j+2] = uint8(uint64(v) >> 16)
			dAtA[j+1] = uint8(uint64(v) >> 8)
			dAtA[j+0] = uint8(uint64(v))
			j += 8
			{{- else if eq .Type "sfixed32"}}
			dAtA[j+3] = uint8(uint32(v) >> 24)
			dAtA[j+2] = uint8(uint32(v) >> 16)
			dAtA[j+1] = uint8(uint32(v) >> 8)
			dAtA[j+0] = uint8(uint32(v))
			j += 4
			{{- else if eq .Type "sfixed64"}}
			dAtA[j+7] = uint8(uint64(v) >> 56)
			dAtA[j+6] = uint8(uint64(v) >> 48)
			dAtA[j+5] = uint8(uint64(v) >> 40)
			dAtA[j+4] = uint8(uint64(v) >> 32)
			dAtA[j+3] = uint8(uint64(v) >> 24)
			dAtA[j+2] = uint8(uint64(v) >> 16)
			dAtA[j+1] = uint8(uint64(v) >> 8)
			dAtA[j+0] = uint8(uint64(v))
			j += 8
			{{- else if eq .Type "float"}}
			_fv := math.Float32bits(v)
			dAtA[j+3] = uint8(_fv >> 24)
			dAtA[j+2] = uint8(_fv >> 16)
			dAtA[j+1] = uint8(_fv >> 8)
			dAtA[j+0] = uint8(_fv)
			j += 4
			{{- else if eq .Type "double"}}
			_dv := math.Float64bits(v)
			dAtA[j+7] = uint8(_dv >> 56)
			dAtA[j+6] = uint8(_dv >> 48)
			dAtA[j+5] = uint8(_dv >> 40)
			dAtA[j+4] = uint8(_dv >> 32)
			dAtA[j+3] = uint8(_dv >> 24)
			dAtA[j+2] = uint8(_dv >> 16)
			dAtA[j+1] = uint8(_dv >> 8)
			dAtA[j+0] = uint8(_dv)
			j += 8
			{{- else if eq .Type "bool"}}
			if v { dAtA[j] = 1 } else { dAtA[j] = 0 }; j++
			{{- else}}
			uv := uint64(v)
			for uv >= 0x80 { dAtA[j] = byte(uv)|0x80; uv >>= 7; j++ }
			dAtA[j] = byte(uv); j++
			{{- end}}
		}
		i = utils.EncodeVarint(dAtA, i, uint64(pksize))
		{{writeTagBytes .Number 2}}
	}
{{- else if eq .Type "string"}}
	for iNdEx := len(m.{{.Name}}) - 1; iNdEx >= 0; iNdEx-- {
		s := m.{{.Name}}[iNdEx]
		i -= len(s)
		copy(dAtA[i:], s)
		i = utils.EncodeVarint(dAtA, i, uint64(len(s)))
		{{writeTagBytes .Number 2}}
	}
{{- else if eq .Type "bytes"}}
	for iNdEx := len(m.{{.Name}}) - 1; iNdEx >= 0; iNdEx-- {
		b := m.{{.Name}}[iNdEx]
		i -= len(b)
		copy(dAtA[i:], b)
		i = utils.EncodeVarint(dAtA, i, uint64(len(b)))
		{{writeTagBytes .Number 2}}
	}
{{- else}}
	for iNdEx := len(m.{{.Name}}) - 1; iNdEx >= 0; iNdEx-- {
		size := m.{{.Name}}[iNdEx].marshalToSizedBufferVT(dAtA[:i])
		i -= size
		i = utils.EncodeVarint(dAtA, i, uint64(size))
		{{writeTagBytes .Number 2}}
	}
{{- end}}
{{- else if .IsMsg}}
{{- if .IsRecursive}}
	if m.{{.Name}} != nil {
		size := m.{{.Name}}.marshalToSizedBufferVT(dAtA[:i])
		i -= size
		i = utils.EncodeVarint(dAtA, i, uint64(size))
		{{writeTagBytes .Number 2}}
	}
{{- else}}
	{
		size := m.{{.Name}}.marshalToSizedBufferVT(dAtA[:i])
		if size > 0 {
			i -= size
			i = utils.EncodeVarint(dAtA, i, uint64(size))
			{{writeTagBytes .Number 2}}
		}
	}
{{- end}}
{{- else if .IsDecimal}}
	if !m.{{.Name}}.IsZero() {
		_dvdec{{.Name}}, _ := m.{{.Name}}.Round({{.DecimalRound}}).Float64()
		i -= 8
		_dv := math.Float64bits(_dvdec{{.Name}})
		dAtA[i+7] = uint8(_dv >> 56)
		dAtA[i+6] = uint8(_dv >> 48)
		dAtA[i+5] = uint8(_dv >> 40)
		dAtA[i+4] = uint8(_dv >> 32)
		dAtA[i+3] = uint8(_dv >> 24)
		dAtA[i+2] = uint8(_dv >> 16)
		dAtA[i+1] = uint8(_dv >> 8)
		dAtA[i+0] = uint8(_dv)
		{{writeTagBytes .Number 1}}
	}
{{- else if eq .Type "double"}}
	if m.{{.Name}} != 0 {
		i -= 8
		_dv := math.Float64bits(m.{{.Name}})
		dAtA[i+7] = uint8(_dv >> 56)
		dAtA[i+6] = uint8(_dv >> 48)
		dAtA[i+5] = uint8(_dv >> 40)
		dAtA[i+4] = uint8(_dv >> 32)
		dAtA[i+3] = uint8(_dv >> 24)
		dAtA[i+2] = uint8(_dv >> 16)
		dAtA[i+1] = uint8(_dv >> 8)
		dAtA[i+0] = uint8(_dv)
		{{writeTagBytes .Number 1}}
	}
{{- else if eq .Type "float"}}
	if m.{{.Name}} != 0 {
		i -= 4
		_fv := math.Float32bits(m.{{.Name}})
		dAtA[i+3] = uint8(_fv >> 24)
		dAtA[i+2] = uint8(_fv >> 16)
		dAtA[i+1] = uint8(_fv >> 8)
		dAtA[i+0] = uint8(_fv)
		{{writeTagBytes .Number 5}}
	}
{{- else if eq .Type "fixed32"}}
	if m.{{.Name}} != 0 {
		i -= 4
		dAtA[i+3] = uint8(m.{{.Name}} >> 24)
		dAtA[i+2] = uint8(m.{{.Name}} >> 16)
		dAtA[i+1] = uint8(m.{{.Name}} >> 8)
		dAtA[i+0] = uint8(m.{{.Name}})
		{{writeTagBytes .Number 5}}
	}
{{- else if eq .Type "fixed64"}}
	if m.{{.Name}} != 0 {
		i -= 8
		dAtA[i+7] = uint8(m.{{.Name}} >> 56)
		dAtA[i+6] = uint8(m.{{.Name}} >> 48)
		dAtA[i+5] = uint8(m.{{.Name}} >> 40)
		dAtA[i+4] = uint8(m.{{.Name}} >> 32)
		dAtA[i+3] = uint8(m.{{.Name}} >> 24)
		dAtA[i+2] = uint8(m.{{.Name}} >> 16)
		dAtA[i+1] = uint8(m.{{.Name}} >> 8)
		dAtA[i+0] = uint8(m.{{.Name}})
		{{writeTagBytes .Number 1}}
	}
{{- else if eq .Type "sfixed32"}}
	if m.{{.Name}} != 0 {
		i -= 4
		dAtA[i+3] = uint8(uint32(m.{{.Name}}) >> 24)
		dAtA[i+2] = uint8(uint32(m.{{.Name}}) >> 16)
		dAtA[i+1] = uint8(uint32(m.{{.Name}}) >> 8)
		dAtA[i+0] = uint8(uint32(m.{{.Name}}))
		{{writeTagBytes .Number 5}}
	}
{{- else if eq .Type "sfixed64"}}
	if m.{{.Name}} != 0 {
		i -= 8
		dAtA[i+7] = uint8(uint64(m.{{.Name}}) >> 56)
		dAtA[i+6] = uint8(uint64(m.{{.Name}}) >> 48)
		dAtA[i+5] = uint8(uint64(m.{{.Name}}) >> 40)
		dAtA[i+4] = uint8(uint64(m.{{.Name}}) >> 32)
		dAtA[i+3] = uint8(uint64(m.{{.Name}}) >> 24)
		dAtA[i+2] = uint8(uint64(m.{{.Name}}) >> 16)
		dAtA[i+1] = uint8(uint64(m.{{.Name}}) >> 8)
		dAtA[i+0] = uint8(uint64(m.{{.Name}}))
		{{writeTagBytes .Number 1}}
	}
{{- else if eq .Type "sint32"}}
	if m.{{.Name}} != 0 {
		i = utils.EncodeVarint(dAtA, i, uint64((uint32(m.{{.Name}})<<1)^uint32(m.{{.Name}}>>31)))
		{{writeTagBytes .Number 0}}
	}
{{- else if eq .Type "sint64"}}
	if m.{{.Name}} != 0 {
		i = utils.EncodeVarint(dAtA, i, (uint64(m.{{.Name}})<<1)^uint64(m.{{.Name}}>>63))
		{{writeTagBytes .Number 0}}
	}
{{- else if eq .Type "bool"}}
	if m.{{.Name}} {
		i--
		if m.{{.Name}} { dAtA[i] = 1 } else { dAtA[i] = 0 }
		{{writeTagBytes .Number 0}}
	}
{{- else if eq .Type "string"}}
	if len(m.{{.Name}}) > 0 {
		i -= len(m.{{.Name}})
		copy(dAtA[i:], m.{{.Name}})
		i = utils.EncodeVarint(dAtA, i, uint64(len(m.{{.Name}})))
		{{writeTagBytes .Number 2}}
	}
{{- else if eq .Type "bytes"}}
	if len(m.{{.Name}}) > 0 {
		i -= len(m.{{.Name}})
		copy(dAtA[i:], m.{{.Name}})
		i = utils.EncodeVarint(dAtA, i, uint64(len(m.{{.Name}})))
		{{writeTagBytes .Number 2}}
	}
{{- else}}
	if m.{{.Name}} != 0 {
		i = utils.EncodeVarint(dAtA, i, uint64(m.{{.Name}}))
		{{writeTagBytes .Number 0}}
	}
{{- end}}
{{- end}}
	return len(dAtA) - i
}

// ToProtobufVT serializes m into dst, reusing its backing array when cap is sufficient.
// Pass nil to allocate a fresh buffer. Equivalent to vtprotobuf MarshalVT().
func (m *{{$goName}}) ToProtobufVT(dst []byte) []byte {
	if m == nil {
		return dst
	}
	// todo: 当存在 map 类型时。这个方法的调用导致了 ToProtobuf() 两次遍历 map，最多导致 33.1% 的性能下降
	size := m.ProtobufSize()
	oldLen := len(dst)
	if cap(dst)-oldLen < size {
		next := make([]byte, oldLen+size)
		copy(next, dst)
		dst = next
	} else {
		dst = dst[:oldLen+size]
	}
	n := m.marshalToSizedBufferVT(dst[oldLen:])
	return dst[:oldLen+n]
}

func (m *{{$goName}}) ToProtobuf(dst []byte) []byte {
{{- if hasMapsOrMsgs .Fields}}
	return m.ToProtobufByAppend(dst)
{{- else}}
	return m.ToProtobufVT(dst)
{{- end}}
}

{{- end}}
