{{- define "GoYamlFile"}}{{with .Msg}}
// Code generated by https://github.com/ahfuzhang/BaoHuLu. DO NOT EDIT.
// source: {{$.Package}}

package {{$.Package}}

import (
	"bytes"
	"encoding/base64"
	"fmt"
	"strconv"
{{- if hasDecimalFields .Fields}}
	"math"

	"github.com/govalues/decimal"
{{- end}}
)

// suppress unused-import errors for messages that do not use every package.
var (
	_ = bytes.IndexByte
	_ = base64.StdEncoding
	_ = fmt.Errorf
	_ = strconv.IntSize
{{- if hasDecimalFields .Fields}}
	_ = math.Pi
	_ decimal.Decimal
{{- end}}
)

{{- $goName := .GoName}}
{{- $hasYamlNames := hasYamlFields .Fields}}
{{- if $hasYamlNames}}

// yaml field key constants for {{$goName}}.
const (
{{- range .Fields}}
{{- if .IsRawBuf}}{{continue}}{{end}}
	_{{$goName}}_{{.Name}}_yamlKey = "{{yamlKey .}}"
{{- end}}
)
{{end}}
{{- $msgCmtNums := .CommentLineNums}}
{{- if hasAnyYamlComments .}}

// yaml comment constants for {{$goName}}.
const (
{{- range $i, $line := .Comment}}
{{- if gt (index $msgCmtNums $i) 0}}
	_yamlCommentLine{{index $msgCmtNums $i}} = {{printf "%q" (printf "%s\n" $line)}}
{{- end}}
{{- end}}
{{- range .Fields}}
{{- if .IsRawBuf}}{{continue}}{{end}}
{{- $f := .}}
{{- range $i, $line := .Comment}}
{{- if gt (index $f.CommentLineNums $i) 0}}
	_yamlCommentLine{{index $f.CommentLineNums $i}} = {{printf "%q" (printf "%s\n" $line)}}
{{- end}}
{{- end}}
{{- if gt .InlineCommentLineNum 0}}
	_yamlInlineCommentLine{{.InlineCommentLineNum}} = {{printf "%q" (printf "%s\n" .InlineComment)}}
{{- end}}
{{- end}}
)
{{end}}
// ============================================================================
// {{$goName}} — ToYAML serialization
// ============================================================================

// ToYAML appends the YAML encoding of m to dst using indent as the base
// indentation width (in spaces). Returns the extended slice.
func (m *{{$goName}}) ToYAML(dst []byte, indent int) []byte {
	sp := make([]byte, indent)
	for _i := range sp {
		sp[_i] = ' '
	}
	sp2 := make([]byte, indent+2)
	for _i := range sp2 {
		sp2[_i] = ' '
	}
	_ = sp
	_ = sp2
	// _strVal appends a YAML-safe string scalar value, quoting when necessary.
	_strVal := func(dst []byte, s string) []byte {
		for i := 0; i < len(s); i++ {
			c := s[i]
			if c < 0x20 || c == ':' || c == '#' || c == '"' || c == '\'' || c == '\\' ||
				c == '{' || c == '}' || c == '[' || c == ']' {
				return strconv.AppendQuote(dst, s)
			}
		}
		return append(dst, s...)
	}
	_ = _strVal
{{- if .AsMap}}
{{- $f0 := index .Fields 0}}
{{- if .Comment}}
	if len(m.{{$f0.Name}}) > 0 {
{{- range $i, $line := .Comment}}
		dst = append(dst, sp...)
		dst = append(dst, '#')
		dst = append(dst, {{yamlCommentExpr $msgCmtNums $i $line}}...)
{{- end}}
	}
{{- end}}
	for _k, _v := range m.{{$f0.Name}} {
		dst = append(dst, sp...)
{{- if eq $f0.MapKey "string"}}
		dst = _strVal(dst, _k)
{{- else if eq $f0.MapKey "bool"}}
		if _k {
			dst = append(dst, "true"...)
		} else {
			dst = append(dst, "false"...)
		}
{{- else if or (eq $f0.MapKey "uint64") (eq $f0.MapKey "fixed64")}}
		dst = strconv.AppendUint(dst, uint64(_k), 10)
{{- else if or (eq $f0.MapKey "uint32") (eq $f0.MapKey "fixed32")}}
		dst = strconv.AppendUint(dst, uint64(_k), 10)
{{- else if or (eq $f0.MapKey "int64") (eq $f0.MapKey "sint64") (eq $f0.MapKey "sfixed64")}}
		dst = strconv.AppendInt(dst, int64(_k), 10)
{{- else}}
		dst = strconv.AppendInt(dst, int64(_k), 10)
{{- end}}
		dst = append(dst, ": "...)
{{- if $f0.MapValIsMsg}}
		if _v != nil {
			dst = append(dst, '\n')
			dst = _v.ToYAML(dst, indent+2)
		} else {
			dst = append(dst, '\n')
		}
{{- else if eq $f0.MapVal "string"}}
		dst = _strVal(dst, _v)
		dst = append(dst, '\n')
{{- else if eq $f0.MapVal "bytes"}}
		dst = append(dst, base64.StdEncoding.EncodeToString(_v)...)
		dst = append(dst, '\n')
{{- else if eq $f0.MapVal "bool"}}
		if _v {
			dst = append(dst, "true\n"...)
		} else {
			dst = append(dst, "false\n"...)
		}
{{- else if eq $f0.MapVal "double"}}
		dst = strconv.AppendFloat(dst, _v, 'f', -1, 64)
		dst = append(dst, '\n')
{{- else if eq $f0.MapVal "float"}}
		dst = strconv.AppendFloat(dst, float64(_v), 'f', -1, 32)
		dst = append(dst, '\n')
{{- else if or (eq $f0.MapVal "uint64") (eq $f0.MapVal "fixed64")}}
		dst = strconv.AppendUint(dst, uint64(_v), 10)
		dst = append(dst, '\n')
{{- else if or (eq $f0.MapVal "uint32") (eq $f0.MapVal "fixed32")}}
		dst = strconv.AppendUint(dst, uint64(_v), 10)
		dst = append(dst, '\n')
{{- else if or (eq $f0.MapVal "int64") (eq $f0.MapVal "sint64") (eq $f0.MapVal "sfixed64")}}
		dst = strconv.AppendInt(dst, int64(_v), 10)
		dst = append(dst, '\n')
{{- else}}
		dst = strconv.AppendInt(dst, int64(_v), 10)
		dst = append(dst, '\n')
{{- end}}
	}
{{- else if .AsArray}}
{{- $fa := index .Fields 0}}
{{- if .Comment}}
	if len(m.{{$fa.Name}}) > 0 {
{{- range $i, $line := .Comment}}
		dst = append(dst, sp...)
		dst = append(dst, '#')
		dst = append(dst, {{yamlCommentExpr $msgCmtNums $i $line}}...)
{{- end}}
	}
{{- end}}
	for _, _v := range m.{{$fa.Name}} {
		dst = append(dst, sp...)
		dst = append(dst, "- "...)
{{- if $fa.IsMsg}}
		dst = append(dst, '\n')
		dst = _v.ToYAML(dst, indent+2)
{{- else if eq $fa.Type "string"}}
		dst = _strVal(dst, _v)
		dst = append(dst, '\n')
{{- else if eq $fa.Type "bytes"}}
		dst = append(dst, base64.StdEncoding.EncodeToString(_v)...)
		dst = append(dst, '\n')
{{- else if eq $fa.Type "bool"}}
		if _v {
			dst = append(dst, "true\n"...)
		} else {
			dst = append(dst, "false\n"...)
		}
{{- else if eq $fa.Type "double"}}
		dst = strconv.AppendFloat(dst, _v, 'f', -1, 64)
		dst = append(dst, '\n')
{{- else if eq $fa.Type "float"}}
		dst = strconv.AppendFloat(dst, float64(_v), 'f', -1, 32)
		dst = append(dst, '\n')
{{- else if or (eq $fa.Type "uint64") (eq $fa.Type "fixed64")}}
		dst = strconv.AppendUint(dst, uint64(_v), 10)
		dst = append(dst, '\n')
{{- else if or (eq $fa.Type "uint32") (eq $fa.Type "fixed32")}}
		dst = strconv.AppendUint(dst, uint64(_v), 10)
		dst = append(dst, '\n')
{{- else if or (eq $fa.Type "int64") (eq $fa.Type "sint64") (eq $fa.Type "sfixed64")}}
		dst = strconv.AppendInt(dst, int64(_v), 10)
		dst = append(dst, '\n')
{{- else}}
		dst = strconv.AppendInt(dst, int64(_v), 10)
		dst = append(dst, '\n')
{{- end}}
	}
{{- else}}
{{- range $i, $line := .Comment}}
	dst = append(dst, sp...)
	dst = append(dst, '#')
	dst = append(dst, {{yamlCommentExpr $msgCmtNums $i $line}}...)
{{- end}}
{{range .Fields}}
{{- if .IsRawBuf}}{{continue}}{{end}}
{{- $cmt := .Comment}}
{{- $cmtNums := .CommentLineNums}}
{{- if .Map}}
	if len(m.{{.Name}}) > 0 {
{{- range $i, $line := $cmt}}
		dst = append(dst, sp...)
		dst = append(dst, '#')
		dst = append(dst, {{yamlCommentExpr $cmtNums $i $line}}...)
{{- end}}
		dst = append(dst, sp...)
{{- if gt .InlineCommentLineNum 0}}
		dst = append(dst, {{yamlKeyAppendExpr $hasYamlNames $goName . ":  "}}...)
		dst = append(dst, '#')
		dst = append(dst, {{yamlInlineCommentExpr .}}...)
{{- else}}
		dst = append(dst, {{yamlKeyAppendExpr $hasYamlNames $goName . ":\n"}}...)
{{- end}}
		for _k, _v := range m.{{.Name}} {
			dst = append(dst, sp2...)
{{- if eq .MapKey "string"}}
			dst = _strVal(dst, _k)
{{- else if eq .MapKey "bool"}}
			if _k {
				dst = append(dst, "true"...)
			} else {
				dst = append(dst, "false"...)
			}
{{- else if or (eq .MapKey "uint64") (eq .MapKey "fixed64")}}
			dst = strconv.AppendUint(dst, uint64(_k), 10)
{{- else if or (eq .MapKey "uint32") (eq .MapKey "fixed32")}}
			dst = strconv.AppendUint(dst, uint64(_k), 10)
{{- else if or (eq .MapKey "int64") (eq .MapKey "sint64") (eq .MapKey "sfixed64")}}
			dst = strconv.AppendInt(dst, int64(_k), 10)
{{- else}}
			dst = strconv.AppendInt(dst, int64(_k), 10)
{{- end}}
			dst = append(dst, ": "...)
{{- if .MapValIsMsg}}
			dst = append(dst, '\n')
			dst = _v.ToYAML(dst, indent+4)
{{- else if eq .MapVal "string"}}
			dst = _strVal(dst, _v)
			dst = append(dst, '\n')
{{- else if eq .MapVal "bytes"}}
			dst = append(dst, base64.StdEncoding.EncodeToString(_v)...)
			dst = append(dst, '\n')
{{- else if eq .MapVal "bool"}}
			if _v {
				dst = append(dst, "true\n"...)
			} else {
				dst = append(dst, "false\n"...)
			}
{{- else if eq .MapVal "double"}}
			dst = strconv.AppendFloat(dst, _v, 'f', -1, 64)
			dst = append(dst, '\n')
{{- else if eq .MapVal "float"}}
			dst = strconv.AppendFloat(dst, float64(_v), 'f', -1, 32)
			dst = append(dst, '\n')
{{- else if or (eq .MapVal "uint64") (eq .MapVal "fixed64")}}
			dst = strconv.AppendUint(dst, uint64(_v), 10)
			dst = append(dst, '\n')
{{- else if or (eq .MapVal "uint32") (eq .MapVal "fixed32")}}
			dst = strconv.AppendUint(dst, uint64(_v), 10)
			dst = append(dst, '\n')
{{- else if or (eq .MapVal "int64") (eq .MapVal "sint64") (eq .MapVal "sfixed64")}}
			dst = strconv.AppendInt(dst, int64(_v), 10)
			dst = append(dst, '\n')
{{- else}}
			dst = strconv.AppendInt(dst, int64(_v), 10)
			dst = append(dst, '\n')
{{- end}}
		}
	}
{{- else if .Repeated}}
	if len(m.{{.Name}}) > 0 {
{{- range $i, $line := $cmt}}
		dst = append(dst, sp...)
		dst = append(dst, '#')
		dst = append(dst, {{yamlCommentExpr $cmtNums $i $line}}...)
{{- end}}
		dst = append(dst, sp...)
{{- if gt .InlineCommentLineNum 0}}
		dst = append(dst, {{yamlKeyAppendExpr $hasYamlNames $goName . ":  "}}...)
		dst = append(dst, '#')
		dst = append(dst, {{yamlInlineCommentExpr .}}...)
{{- else}}
		dst = append(dst, {{yamlKeyAppendExpr $hasYamlNames $goName . ":\n"}}...)
{{- end}}
		for _, _v := range m.{{.Name}} {
			dst = append(dst, sp2...)
			dst = append(dst, "- "...)
{{- if .IsMsg}}
			dst = append(dst, '\n')
			dst = _v.ToYAML(dst, indent+4)
{{- else if eq .Type "string"}}
			dst = _strVal(dst, _v)
			dst = append(dst, '\n')
{{- else if eq .Type "bytes"}}
			dst = append(dst, base64.StdEncoding.EncodeToString(_v)...)
			dst = append(dst, '\n')
{{- else if eq .Type "bool"}}
			if _v {
				dst = append(dst, "true\n"...)
			} else {
				dst = append(dst, "false\n"...)
			}
{{- else if eq .Type "double"}}
			dst = strconv.AppendFloat(dst, _v, 'f', -1, 64)
			dst = append(dst, '\n')
{{- else if eq .Type "float"}}
			dst = strconv.AppendFloat(dst, float64(_v), 'f', -1, 32)
			dst = append(dst, '\n')
{{- else if or (eq .Type "uint64") (eq .Type "fixed64")}}
			dst = strconv.AppendUint(dst, uint64(_v), 10)
			dst = append(dst, '\n')
{{- else if or (eq .Type "uint32") (eq .Type "fixed32")}}
			dst = strconv.AppendUint(dst, uint64(_v), 10)
			dst = append(dst, '\n')
{{- else if or (eq .Type "int64") (eq .Type "sint64") (eq .Type "sfixed64")}}
			dst = strconv.AppendInt(dst, int64(_v), 10)
			dst = append(dst, '\n')
{{- else}}
			dst = strconv.AppendInt(dst, int64(_v), 10)
			dst = append(dst, '\n')
{{- end}}
		}
	}
{{- else if .IsMsg}}
{{- if .IsRecursive}}
	if m.{{.Name}} != nil {
		_sub{{.Name}} := m.{{.Name}}.ToYAML(nil, indent+2)
		if len(_sub{{.Name}}) > 0 {
{{- range $i, $line := $cmt}}
			dst = append(dst, sp...)
			dst = append(dst, '#')
			dst = append(dst, {{yamlCommentExpr $cmtNums $i $line}}...)
{{- end}}
			dst = append(dst, sp...)
{{- if gt .InlineCommentLineNum 0}}
			dst = append(dst, {{yamlKeyAppendExpr $hasYamlNames $goName . ":  "}}...)
			dst = append(dst, '#')
			dst = append(dst, {{yamlInlineCommentExpr .}}...)
{{- else}}
			dst = append(dst, {{yamlKeyAppendExpr $hasYamlNames $goName . ":\n"}}...)
{{- end}}
			dst = append(dst, _sub{{.Name}}...)
		}
	}
{{- else}}
	{
		_sub{{.Name}} := m.{{.Name}}.ToYAML(nil, indent+2)
		if len(_sub{{.Name}}) > 0 {
{{- range $i, $line := $cmt}}
			dst = append(dst, sp...)
			dst = append(dst, '#')
			dst = append(dst, {{yamlCommentExpr $cmtNums $i $line}}...)
{{- end}}
			dst = append(dst, sp...)
{{- if gt .InlineCommentLineNum 0}}
			dst = append(dst, {{yamlKeyAppendExpr $hasYamlNames $goName . ":  "}}...)
			dst = append(dst, '#')
			dst = append(dst, {{yamlInlineCommentExpr .}}...)
{{- else}}
			dst = append(dst, {{yamlKeyAppendExpr $hasYamlNames $goName . ":\n"}}...)
{{- end}}
			dst = append(dst, _sub{{.Name}}...)
		}
	}
{{- end}}
{{- else if .IsDecimal}}
	if !m.{{.Name}}.IsZero() {
{{- range $i, $line := $cmt}}
		dst = append(dst, sp...)
		dst = append(dst, '#')
		dst = append(dst, {{yamlCommentExpr $cmtNums $i $line}}...)
{{- end}}
		dst = append(dst, sp...)
		dst = append(dst, {{yamlKeyAppendExpr $hasYamlNames $goName . ": "}}...)
		_df{{.Name}}, _ := m.{{.Name}}.Round({{decimalRound .}}).Float64()
		dst = strconv.AppendFloat(dst, _df{{.Name}}, 'f', {{decimalRound .}}, 64)
{{- if gt .InlineCommentLineNum 0}}
		dst = append(dst, "  "...)
		dst = append(dst, '#')
		dst = append(dst, {{yamlInlineCommentExpr .}}...)
{{- else}}
		dst = append(dst, '\n')
{{- end}}
	}
{{- else if eq .Type "bool"}}
	if m.{{.Name}} {
{{- range $i, $line := $cmt}}
		dst = append(dst, sp...)
		dst = append(dst, '#')
		dst = append(dst, {{yamlCommentExpr $cmtNums $i $line}}...)
{{- end}}
		dst = append(dst, sp...)
{{- if gt .InlineCommentLineNum 0}}
		dst = append(dst, {{yamlKeyAppendExpr $hasYamlNames $goName . ": true  "}}...)
		dst = append(dst, '#')
		dst = append(dst, {{yamlInlineCommentExpr .}}...)
{{- else}}
		dst = append(dst, {{yamlKeyAppendExpr $hasYamlNames $goName . ": true\n"}}...)
{{- end}}
	}
{{- else if eq .Type "string"}}
	if m.{{.Name}} != "" {
{{- range $i, $line := $cmt}}
		dst = append(dst, sp...)
		dst = append(dst, '#')
		dst = append(dst, {{yamlCommentExpr $cmtNums $i $line}}...)
{{- end}}
		dst = append(dst, sp...)
		dst = append(dst, {{yamlKeyAppendExpr $hasYamlNames $goName . ": "}}...)
		dst = _strVal(dst, m.{{.Name}})
{{- if gt .InlineCommentLineNum 0}}
		dst = append(dst, "  "...)
		dst = append(dst, '#')
		dst = append(dst, {{yamlInlineCommentExpr .}}...)
{{- else}}
		dst = append(dst, '\n')
{{- end}}
	}
{{- else if eq .Type "bytes"}}
	if len(m.{{.Name}}) > 0 {
{{- range $i, $line := $cmt}}
		dst = append(dst, sp...)
		dst = append(dst, '#')
		dst = append(dst, {{yamlCommentExpr $cmtNums $i $line}}...)
{{- end}}
		dst = append(dst, sp...)
		dst = append(dst, {{yamlKeyAppendExpr $hasYamlNames $goName . ": "}}...)
		dst = append(dst, base64.StdEncoding.EncodeToString(m.{{.Name}})...)
{{- if gt .InlineCommentLineNum 0}}
		dst = append(dst, "  "...)
		dst = append(dst, '#')
		dst = append(dst, {{yamlInlineCommentExpr .}}...)
{{- else}}
		dst = append(dst, '\n')
{{- end}}
	}
{{- else if eq .Type "double"}}
	if m.{{.Name}} != 0 {
{{- range $i, $line := $cmt}}
		dst = append(dst, sp...)
		dst = append(dst, '#')
		dst = append(dst, {{yamlCommentExpr $cmtNums $i $line}}...)
{{- end}}
		dst = append(dst, sp...)
		dst = append(dst, {{yamlKeyAppendExpr $hasYamlNames $goName . ": "}}...)
		dst = strconv.AppendFloat(dst, m.{{.Name}}, 'f', -1, 64)
{{- if gt .InlineCommentLineNum 0}}
		dst = append(dst, "  "...)
		dst = append(dst, '#')
		dst = append(dst, {{yamlInlineCommentExpr .}}...)
{{- else}}
		dst = append(dst, '\n')
{{- end}}
	}
{{- else if eq .Type "float"}}
	if m.{{.Name}} != 0 {
{{- range $i, $line := $cmt}}
		dst = append(dst, sp...)
		dst = append(dst, '#')
		dst = append(dst, {{yamlCommentExpr $cmtNums $i $line}}...)
{{- end}}
		dst = append(dst, sp...)
		dst = append(dst, {{yamlKeyAppendExpr $hasYamlNames $goName . ": "}}...)
		dst = strconv.AppendFloat(dst, float64(m.{{.Name}}), 'f', -1, 32)
{{- if gt .InlineCommentLineNum 0}}
		dst = append(dst, "  "...)
		dst = append(dst, '#')
		dst = append(dst, {{yamlInlineCommentExpr .}}...)
{{- else}}
		dst = append(dst, '\n')
{{- end}}
	}
{{- else if or (eq .Type "uint64") (eq .Type "fixed64")}}
	if m.{{.Name}} != 0 {
{{- range $i, $line := $cmt}}
		dst = append(dst, sp...)
		dst = append(dst, '#')
		dst = append(dst, {{yamlCommentExpr $cmtNums $i $line}}...)
{{- end}}
		dst = append(dst, sp...)
		dst = append(dst, {{yamlKeyAppendExpr $hasYamlNames $goName . ": "}}...)
		dst = strconv.AppendUint(dst, m.{{.Name}}, 10)
{{- if gt .InlineCommentLineNum 0}}
		dst = append(dst, "  "...)
		dst = append(dst, '#')
		dst = append(dst, {{yamlInlineCommentExpr .}}...)
{{- else}}
		dst = append(dst, '\n')
{{- end}}
	}
{{- else if or (eq .Type "uint32") (eq .Type "fixed32")}}
	if m.{{.Name}} != 0 {
{{- range $i, $line := $cmt}}
		dst = append(dst, sp...)
		dst = append(dst, '#')
		dst = append(dst, {{yamlCommentExpr $cmtNums $i $line}}...)
{{- end}}
		dst = append(dst, sp...)
		dst = append(dst, {{yamlKeyAppendExpr $hasYamlNames $goName . ": "}}...)
		dst = strconv.AppendUint(dst, uint64(m.{{.Name}}), 10)
{{- if gt .InlineCommentLineNum 0}}
		dst = append(dst, "  "...)
		dst = append(dst, '#')
		dst = append(dst, {{yamlInlineCommentExpr .}}...)
{{- else}}
		dst = append(dst, '\n')
{{- end}}
	}
{{- else if or (eq .Type "int64") (eq .Type "sint64") (eq .Type "sfixed64")}}
	if m.{{.Name}} != 0 {
{{- range $i, $line := $cmt}}
		dst = append(dst, sp...)
		dst = append(dst, '#')
		dst = append(dst, {{yamlCommentExpr $cmtNums $i $line}}...)
{{- end}}
		dst = append(dst, sp...)
		dst = append(dst, {{yamlKeyAppendExpr $hasYamlNames $goName . ": "}}...)
		dst = strconv.AppendInt(dst, m.{{.Name}}, 10)
{{- if gt .InlineCommentLineNum 0}}
		dst = append(dst, "  "...)
		dst = append(dst, '#')
		dst = append(dst, {{yamlInlineCommentExpr .}}...)
{{- else}}
		dst = append(dst, '\n')
{{- end}}
	}
{{- else}}
	if m.{{.Name}} != 0 {
{{- range $i, $line := $cmt}}
		dst = append(dst, sp...)
		dst = append(dst, '#')
		dst = append(dst, {{yamlCommentExpr $cmtNums $i $line}}...)
{{- end}}
		dst = append(dst, sp...)
		dst = append(dst, {{yamlKeyAppendExpr $hasYamlNames $goName . ": "}}...)
		dst = strconv.AppendInt(dst, int64(m.{{.Name}}), 10)
{{- if gt .InlineCommentLineNum 0}}
		dst = append(dst, "  "...)
		dst = append(dst, '#')
		dst = append(dst, {{yamlInlineCommentExpr .}}...)
{{- else}}
		dst = append(dst, '\n')
{{- end}}
	}
{{- end}}
{{end}}
{{- end}}
	return dst
}

// ============================================================================
// Readonly{{$goName}} — FromYAML deserialization
// ============================================================================

// FromYAML parses the YAML text in src into r.
func (r *Readonly{{$goName}}) FromYAML(src []byte) error {
	// _unquoteStr removes YAML string quoting from v.
	_unquoteStr := func(v []byte) string {
		if len(v) == 0 {
			return ""
		}
		if v[0] == '"' {
			s, _ := strconv.Unquote(string(v))
			return s
		}
		if len(v) >= 2 && v[0] == '\'' && v[len(v)-1] == '\'' {
			return string(v[1 : len(v)-1])
		}
		return string(v)
	}
	_ = _unquoteStr

	_lines := bytes.SplitAfter(src, []byte("\n"))

	// Detect base indentation from the first non-empty line.
	_baseIndent := -1
	for _, _ln := range _lines {
		_s := bytes.TrimRight(_ln, "\r\n")
		if len(bytes.TrimSpace(_s)) > 0 {
			_t := bytes.TrimLeft(_s, " ")
			_baseIndent = len(_s) - len(_t)
			break
		}
	}
	if _baseIndent < 0 {
		return nil
	}

	// _collectBlock collects the indented sub-block that follows _lines[*_ip].
	// Advances *_ip to the index of the last line consumed.
	_collectBlock := func(ip *int) []byte {
		var _sub []byte
		_j := *ip + 1
		for _j < len(_lines) {
			_sl := bytes.TrimRight(_lines[_j], "\r\n")
			if len(bytes.TrimSpace(_sl)) == 0 {
				_sub = append(_sub, _lines[_j]...)
				_j++
				continue
			}
			_st := bytes.TrimLeft(_sl, " ")
			if len(_sl)-len(_st) > _baseIndent {
				_sub = append(_sub, _lines[_j]...)
				_j++
			} else {
				break
			}
		}
		*ip = _j - 1
		return _sub
	}
	_ = _collectBlock
{{- if .AsArray}}
{{- $fa := index .Fields 0}}
{{- if $fa.IsMsg}}
	{
		_list := make([]{{readonlyTypeName $fa.Type}}, 0)
		for _j := 0; _j < len(_lines); _j++ {
			_sl := bytes.TrimRight(_lines[_j], "\r\n")
			_st := bytes.TrimSpace(_sl)
			if len(_st) == 0 || !bytes.HasPrefix(_st, []byte("-")) {
				continue
			}
			var _itemBytes []byte
			_j2 := _j + 1
			_itemBase := -1
			for _j2 < len(_lines) {
				_ssl := bytes.TrimRight(_lines[_j2], "\r\n")
				if len(bytes.TrimSpace(_ssl)) == 0 {
					_itemBytes = append(_itemBytes, _lines[_j2]...)
					_j2++
					continue
				}
				_sst := bytes.TrimLeft(_ssl, " ")
				_ssi := len(_ssl) - len(_sst)
				if _itemBase < 0 && _ssi > _baseIndent+2 {
					_itemBase = _ssi
				}
				if _itemBase < 0 || _ssi >= _itemBase {
					_itemBytes = append(_itemBytes, _lines[_j2]...)
					_j2++
				} else {
					break
				}
			}
			_j = _j2 - 1
			var _elem {{readonlyTypeName $fa.Type}}
			if _e := _elem.FromYAML(_itemBytes); _e != nil {
				return fmt.Errorf("item: %w", _e)
			}
			_list = append(_list, _elem)
		}
		r.{{$fa.Name}} = _list
	}
{{- else}}
	{
		_list := make({{$fa.ReaderType}}, 0)
		for _, _sl := range _lines {
			_ss := bytes.TrimRight(_sl, "\r\n")
			_st := bytes.TrimSpace(_ss)
			if len(_st) == 0 || !bytes.HasPrefix(_st, []byte("- ")) {
				continue
			}
			_item := bytes.TrimSpace(_st[2:])
{{- if eq $fa.Type "string"}}
			_list = append(_list, _unquoteStr(_item))
{{- else if eq $fa.Type "bytes"}}
			_b, _be := base64.StdEncoding.DecodeString(string(_item))
			if _be != nil {
				return fmt.Errorf("item: %w", _be)
			}
			_list = append(_list, _b)
{{- else if eq $fa.Type "bool"}}
			_list = append(_list, string(_item) == "true" || string(_item) == "1")
{{- else if eq $fa.Type "double"}}
			_v, _ve := strconv.ParseFloat(string(_item), 64)
			if _ve != nil {
				return fmt.Errorf("item: %w", _ve)
			}
			_list = append(_list, _v)
{{- else if eq $fa.Type "float"}}
			_v, _ve := strconv.ParseFloat(string(_item), 32)
			if _ve != nil {
				return fmt.Errorf("item: %w", _ve)
			}
			_list = append(_list, float32(_v))
{{- else if or (eq $fa.Type "uint64") (eq $fa.Type "fixed64")}}
			_v, _ve := strconv.ParseUint(string(_item), 10, 64)
			if _ve != nil {
				return fmt.Errorf("item: %w", _ve)
			}
			_list = append(_list, {{elemType $fa.ReaderType}}(_v))
{{- else if or (eq $fa.Type "uint32") (eq $fa.Type "fixed32")}}
			_v, _ve := strconv.ParseUint(string(_item), 10, 32)
			if _ve != nil {
				return fmt.Errorf("item: %w", _ve)
			}
			_list = append(_list, {{elemType $fa.ReaderType}}(_v))
{{- else if or (eq $fa.Type "int64") (eq $fa.Type "sint64") (eq $fa.Type "sfixed64")}}
			_v, _ve := strconv.ParseInt(string(_item), 10, 64)
			if _ve != nil {
				return fmt.Errorf("item: %w", _ve)
			}
			_list = append(_list, {{elemType $fa.ReaderType}}(_v))
{{- else}}
			_v, _ve := strconv.ParseInt(string(_item), 10, 32)
			if _ve != nil {
				return fmt.Errorf("item: %w", _ve)
			}
			_list = append(_list, {{elemType $fa.ReaderType}}(_v))
{{- end}}
		}
		r.{{$fa.Name}} = _list
	}
{{- end}}
{{- else}}
{{- if .AsMap}}
{{- $f0 := index .Fields 0}}
	if r.{{$f0.Name}} == nil {
{{- if $f0.MapValIsMsg}}
		r.{{$f0.Name}} = make(map[{{mapKeyGoType $f0.MapKey}}]*{{readonlyTypeName $f0.MapVal}})
{{- else}}
		r.{{$f0.Name}} = make({{$f0.ReaderType}})
{{- end}}
	}
{{- end}}

	for _i := 0; _i < len(_lines); _i++ {
		_line := bytes.TrimRight(_lines[_i], "\r\n")
		if len(bytes.TrimSpace(_line)) == 0 {
			continue
		}
		_trimmed := bytes.TrimLeft(_line, " ")
		_curIndent := len(_line) - len(_trimmed)
		if _curIndent != _baseIndent {
			continue
		}
		if len(_trimmed) > 0 && _trimmed[0] == '#' {
			continue
		}
		_colonPos := bytes.IndexByte(_trimmed, ':')
		if _colonPos < 0 {
			continue
		}
		_key := _trimmed[:_colonPos]
		_valBytes := bytes.TrimSpace(_trimmed[_colonPos+1:])
		_ = _valBytes

{{- if .AsMap}}
{{- $f0 := index .Fields 0}}
{{- if eq $f0.MapKey "string"}}
		_mk := _unquoteStr(_key)
{{- else if eq $f0.MapKey "bool"}}
		_mk := string(_key) == "true" || string(_key) == "1"
{{- else if or (eq $f0.MapKey "uint64") (eq $f0.MapKey "fixed64")}}
		_mkv, _mke := strconv.ParseUint(string(_key), 10, 64)
		if _mke != nil {
			return fmt.Errorf("map key: %w", _mke)
		}
		_mk := {{mapKeyGoType $f0.MapKey}}(_mkv)
{{- else if or (eq $f0.MapKey "uint32") (eq $f0.MapKey "fixed32")}}
		_mkv, _mke := strconv.ParseUint(string(_key), 10, 32)
		if _mke != nil {
			return fmt.Errorf("map key: %w", _mke)
		}
		_mk := {{mapKeyGoType $f0.MapKey}}(_mkv)
{{- else if or (eq $f0.MapKey "int64") (eq $f0.MapKey "sint64") (eq $f0.MapKey "sfixed64")}}
		_mkv, _mke := strconv.ParseInt(string(_key), 10, 64)
		if _mke != nil {
			return fmt.Errorf("map key: %w", _mke)
		}
		_mk := {{mapKeyGoType $f0.MapKey}}(_mkv)
{{- else}}
		_mkv, _mke := strconv.ParseInt(string(_key), 10, 32)
		if _mke != nil {
			return fmt.Errorf("map key: %w", _mke)
		}
		_mk := {{mapKeyGoType $f0.MapKey}}(_mkv)
{{- end}}
{{- if $f0.MapValIsMsg}}
		{
			_sub := _collectBlock(&_i)
			_mv := new({{readonlyTypeName $f0.MapVal}})
			if _ve := _mv.FromYAML(_sub); _ve != nil {
				return fmt.Errorf("entry: %w", _ve)
			}
			r.{{$f0.Name}}[_mk] = _mv
		}
{{- else if eq $f0.MapVal "string"}}
		r.{{$f0.Name}}[_mk] = _unquoteStr(_valBytes)
{{- else if eq $f0.MapVal "bytes"}}
		{
			_vb, _vbe := base64.StdEncoding.DecodeString(string(_valBytes))
			if _vbe != nil {
				return fmt.Errorf("value: %w", _vbe)
			}
			r.{{$f0.Name}}[_mk] = _vb
		}
{{- else if eq $f0.MapVal "bool"}}
		r.{{$f0.Name}}[_mk] = string(_valBytes) == "true" || string(_valBytes) == "1"
{{- else if eq $f0.MapVal "double"}}
		{
			_vf, _vfe := strconv.ParseFloat(string(_valBytes), 64)
			if _vfe != nil {
				return fmt.Errorf("value: %w", _vfe)
			}
			r.{{$f0.Name}}[_mk] = _vf
		}
{{- else if eq $f0.MapVal "float"}}
		{
			_vf, _vfe := strconv.ParseFloat(string(_valBytes), 32)
			if _vfe != nil {
				return fmt.Errorf("value: %w", _vfe)
			}
			r.{{$f0.Name}}[_mk] = float32(_vf)
		}
{{- else if or (eq $f0.MapVal "uint64") (eq $f0.MapVal "fixed64")}}
		{
			_vu, _vue := strconv.ParseUint(string(_valBytes), 10, 64)
			if _vue != nil {
				return fmt.Errorf("value: %w", _vue)
			}
			r.{{$f0.Name}}[_mk] = {{mapValGoType $f0.MapVal}}(_vu)
		}
{{- else if or (eq $f0.MapVal "uint32") (eq $f0.MapVal "fixed32")}}
		{
			_vu, _vue := strconv.ParseUint(string(_valBytes), 10, 32)
			if _vue != nil {
				return fmt.Errorf("value: %w", _vue)
			}
			r.{{$f0.Name}}[_mk] = {{mapValGoType $f0.MapVal}}(_vu)
		}
{{- else if or (eq $f0.MapVal "int64") (eq $f0.MapVal "sint64") (eq $f0.MapVal "sfixed64")}}
		{
			_vi, _vie := strconv.ParseInt(string(_valBytes), 10, 64)
			if _vie != nil {
				return fmt.Errorf("value: %w", _vie)
			}
			r.{{$f0.Name}}[_mk] = {{mapValGoType $f0.MapVal}}(_vi)
		}
{{- else}}
		{
			_vi, _vie := strconv.ParseInt(string(_valBytes), 10, 32)
			if _vie != nil {
				return fmt.Errorf("value: %w", _vie)
			}
			r.{{$f0.Name}}[_mk] = {{mapValGoType $f0.MapVal}}(_vi)
		}
{{- end}}
{{- else}}
		switch string(_key) {
{{range .Fields}}
{{- if .IsRawBuf}}{{continue}}{{end}}
		case {{yamlKeyExpr $hasYamlNames $goName .}}:
{{- if .Map}}
			{
				_sub := _collectBlock(&_i)
				_subLines := bytes.SplitAfter(_sub, []byte("\n"))
				_subBase := -1
				for _, _sl := range _subLines {
					_ss := bytes.TrimRight(_sl, "\r\n")
					if len(bytes.TrimSpace(_ss)) > 0 {
						_st := bytes.TrimLeft(_ss, " ")
						_subBase = len(_ss) - len(_st)
						break
					}
				}
				if _subBase >= 0 {
{{- if .MapValIsMsg}}
					_dict := make(map[{{mapKeyGoType .MapKey}}]*{{readonlyTypeName .MapVal}})
					for _j := 0; _j < len(_subLines); _j++ {
						_sl := bytes.TrimRight(_subLines[_j], "\r\n")
						if len(bytes.TrimSpace(_sl)) == 0 {
							continue
						}
						_st := bytes.TrimLeft(_sl, " ")
						if len(_sl)-len(_st) != _subBase {
							continue
						}
						_cp := bytes.IndexByte(_st, ':')
						if _cp < 0 {
							continue
						}
{{- if eq .MapKey "string"}}
						_k := _unquoteStr(_st[:_cp])
{{- else if eq .MapKey "bool"}}
						_k := string(_st[:_cp]) == "true" || string(_st[:_cp]) == "1"
{{- else if or (eq .MapKey "uint64") (eq .MapKey "fixed64")}}
						_kv, _ke := strconv.ParseUint(string(_st[:_cp]), 10, 64)
						if _ke != nil {
							return fmt.Errorf("field {{yamlKey .}} key: %w", _ke)
						}
						_k := {{mapKeyGoType .MapKey}}(_kv)
{{- else if or (eq .MapKey "uint32") (eq .MapKey "fixed32")}}
						_kv, _ke := strconv.ParseUint(string(_st[:_cp]), 10, 32)
						if _ke != nil {
							return fmt.Errorf("field {{yamlKey .}} key: %w", _ke)
						}
						_k := {{mapKeyGoType .MapKey}}(_kv)
{{- else if or (eq .MapKey "int64") (eq .MapKey "sint64") (eq .MapKey "sfixed64")}}
						_kv, _ke := strconv.ParseInt(string(_st[:_cp]), 10, 64)
						if _ke != nil {
							return fmt.Errorf("field {{yamlKey .}} key: %w", _ke)
						}
						_k := {{mapKeyGoType .MapKey}}(_kv)
{{- else}}
						_kv, _ke := strconv.ParseInt(string(_st[:_cp]), 10, 32)
						if _ke != nil {
							return fmt.Errorf("field {{yamlKey .}} key: %w", _ke)
						}
						_k := {{mapKeyGoType .MapKey}}(_kv)
{{- end}}
						// Collect the sub-entry block for this map value (a nested message).
						var _entryBytes []byte
						_j2 := _j + 1
						for _j2 < len(_subLines) {
							_ssl := bytes.TrimRight(_subLines[_j2], "\r\n")
							if len(bytes.TrimSpace(_ssl)) == 0 {
								_entryBytes = append(_entryBytes, _subLines[_j2]...)
								_j2++
								continue
							}
							_sst := bytes.TrimLeft(_ssl, " ")
							if len(_ssl)-len(_sst) > _subBase {
								_entryBytes = append(_entryBytes, _subLines[_j2]...)
								_j2++
							} else {
								break
							}
						}
						_j = _j2 - 1
						_val := new({{readonlyTypeName .MapVal}})
						if _ve := _val.FromYAML(_entryBytes); _ve != nil {
							return fmt.Errorf("field {{yamlKey .}}: %w", _ve)
						}
						_dict[_k] = _val
					}
{{- else}}
					_dict := make({{.ReaderType}})
					for _, _sl := range _subLines {
						_ss := bytes.TrimRight(_sl, "\r\n")
						if len(bytes.TrimSpace(_ss)) == 0 {
							continue
						}
						_st := bytes.TrimLeft(_ss, " ")
						if len(_ss)-len(_st) != _subBase {
							continue
						}
						_cp := bytes.IndexByte(_st, ':')
						if _cp < 0 {
							continue
						}
						_mv := bytes.TrimSpace(_st[_cp+1:])
{{- if eq .MapKey "string"}}
						_k := _unquoteStr(_st[:_cp])
{{- else if eq .MapKey "bool"}}
						_k := string(_st[:_cp]) == "true" || string(_st[:_cp]) == "1"
{{- else if or (eq .MapKey "uint64") (eq .MapKey "fixed64")}}
						_kv, _ke := strconv.ParseUint(string(_st[:_cp]), 10, 64)
						if _ke != nil {
							return fmt.Errorf("field {{yamlKey .}} key: %w", _ke)
						}
						_k := {{mapKeyGoType .MapKey}}(_kv)
{{- else if or (eq .MapKey "uint32") (eq .MapKey "fixed32")}}
						_kv, _ke := strconv.ParseUint(string(_st[:_cp]), 10, 32)
						if _ke != nil {
							return fmt.Errorf("field {{yamlKey .}} key: %w", _ke)
						}
						_k := {{mapKeyGoType .MapKey}}(_kv)
{{- else if or (eq .MapKey "int64") (eq .MapKey "sint64") (eq .MapKey "sfixed64")}}
						_kv, _ke := strconv.ParseInt(string(_st[:_cp]), 10, 64)
						if _ke != nil {
							return fmt.Errorf("field {{yamlKey .}} key: %w", _ke)
						}
						_k := {{mapKeyGoType .MapKey}}(_kv)
{{- else}}
						_kv, _ke := strconv.ParseInt(string(_st[:_cp]), 10, 32)
						if _ke != nil {
							return fmt.Errorf("field {{yamlKey .}} key: %w", _ke)
						}
						_k := {{mapKeyGoType .MapKey}}(_kv)
{{- end}}
{{- if eq .MapVal "string"}}
						_dict[_k] = _unquoteStr(_mv)
{{- else if eq .MapVal "bytes"}}
						_vb, _vbe := base64.StdEncoding.DecodeString(string(_mv))
						if _vbe != nil {
							return fmt.Errorf("field {{yamlKey .}}: %w", _vbe)
						}
						_dict[_k] = _vb
{{- else if eq .MapVal "bool"}}
						_dict[_k] = string(_mv) == "true" || string(_mv) == "1"
{{- else if eq .MapVal "double"}}
						_vf, _vfe := strconv.ParseFloat(string(_mv), 64)
						if _vfe != nil {
							return fmt.Errorf("field {{yamlKey .}}: %w", _vfe)
						}
						_dict[_k] = _vf
{{- else if eq .MapVal "float"}}
						_vf, _vfe := strconv.ParseFloat(string(_mv), 32)
						if _vfe != nil {
							return fmt.Errorf("field {{yamlKey .}}: %w", _vfe)
						}
						_dict[_k] = float32(_vf)
{{- else if or (eq .MapVal "uint64") (eq .MapVal "fixed64")}}
						_vu, _vue := strconv.ParseUint(string(_mv), 10, 64)
						if _vue != nil {
							return fmt.Errorf("field {{yamlKey .}}: %w", _vue)
						}
						_dict[_k] = {{mapValGoType .MapVal}}(_vu)
{{- else if or (eq .MapVal "uint32") (eq .MapVal "fixed32")}}
						_vu, _vue := strconv.ParseUint(string(_mv), 10, 32)
						if _vue != nil {
							return fmt.Errorf("field {{yamlKey .}}: %w", _vue)
						}
						_dict[_k] = {{mapValGoType .MapVal}}(_vu)
{{- else if or (eq .MapVal "int64") (eq .MapVal "sint64") (eq .MapVal "sfixed64")}}
						_vi, _vie := strconv.ParseInt(string(_mv), 10, 64)
						if _vie != nil {
							return fmt.Errorf("field {{yamlKey .}}: %w", _vie)
						}
						_dict[_k] = {{mapValGoType .MapVal}}(_vi)
{{- else}}
						_vi, _vie := strconv.ParseInt(string(_mv), 10, 32)
						if _vie != nil {
							return fmt.Errorf("field {{yamlKey .}}: %w", _vie)
						}
						_dict[_k] = {{mapValGoType .MapVal}}(_vi)
{{- end}}
					}
{{- end}}
					r.{{.Name}} = _dict
				}
			}
{{- else if .Repeated}}
			{
				_sub := _collectBlock(&_i)
				_subLines := bytes.SplitAfter(_sub, []byte("\n"))
{{- if .IsMsg}}
				_list := make([]{{readonlyTypeName .Type}}, 0)
				for _j := 0; _j < len(_subLines); _j++ {
					_sl := bytes.TrimRight(_subLines[_j], "\r\n")
					_st := bytes.TrimSpace(_sl)
					if len(_st) == 0 || !bytes.HasPrefix(_st, []byte("-")) {
						continue
					}
					// Collect the indented block belonging to this list item.
					var _itemBytes []byte
					_j2 := _j + 1
					_itemBase := -1
					for _j2 < len(_subLines) {
						_ssl := bytes.TrimRight(_subLines[_j2], "\r\n")
						if len(bytes.TrimSpace(_ssl)) == 0 {
							_itemBytes = append(_itemBytes, _subLines[_j2]...)
							_j2++
							continue
						}
						_sst := bytes.TrimLeft(_ssl, " ")
						_ssi := len(_ssl) - len(_sst)
						if _itemBase < 0 && _ssi > _baseIndent+2 {
							_itemBase = _ssi
						}
						if _itemBase < 0 || _ssi >= _itemBase {
							_itemBytes = append(_itemBytes, _subLines[_j2]...)
							_j2++
						} else {
							break
						}
					}
					_j = _j2 - 1
					var _elem {{readonlyTypeName .Type}}
					if _e := _elem.FromYAML(_itemBytes); _e != nil {
						return fmt.Errorf("field {{yamlKey .}}: %w", _e)
					}
					_list = append(_list, _elem)
				}
				r.{{.Name}} = _list
{{- else}}
				_list := make({{.ReaderType}}, 0)
				for _, _sl := range _subLines {
					_ss := bytes.TrimRight(_sl, "\r\n")
					_st := bytes.TrimSpace(_ss)
					if len(_st) == 0 || !bytes.HasPrefix(_st, []byte("- ")) {
						continue
					}
					_item := bytes.TrimSpace(_st[2:])
{{- if eq .Type "string"}}
					_list = append(_list, _unquoteStr(_item))
{{- else if eq .Type "bytes"}}
					_b, _be := base64.StdEncoding.DecodeString(string(_item))
					if _be != nil {
						return fmt.Errorf("field {{yamlKey .}}: %w", _be)
					}
					_list = append(_list, _b)
{{- else if eq .Type "bool"}}
					_list = append(_list, string(_item) == "true" || string(_item) == "1")
{{- else if eq .Type "double"}}
					_v, _ve := strconv.ParseFloat(string(_item), 64)
					if _ve != nil {
						return fmt.Errorf("field {{yamlKey .}}: %w", _ve)
					}
					_list = append(_list, _v)
{{- else if eq .Type "float"}}
					_v, _ve := strconv.ParseFloat(string(_item), 32)
					if _ve != nil {
						return fmt.Errorf("field {{yamlKey .}}: %w", _ve)
					}
					_list = append(_list, float32(_v))
{{- else if or (eq .Type "uint64") (eq .Type "fixed64")}}
					_v, _ve := strconv.ParseUint(string(_item), 10, 64)
					if _ve != nil {
						return fmt.Errorf("field {{yamlKey .}}: %w", _ve)
					}
					_list = append(_list, {{elemType .ReaderType}}(_v))
{{- else if or (eq .Type "uint32") (eq .Type "fixed32")}}
					_v, _ve := strconv.ParseUint(string(_item), 10, 32)
					if _ve != nil {
						return fmt.Errorf("field {{yamlKey .}}: %w", _ve)
					}
					_list = append(_list, {{elemType .ReaderType}}(_v))
{{- else if or (eq .Type "int64") (eq .Type "sint64") (eq .Type "sfixed64")}}
					_v, _ve := strconv.ParseInt(string(_item), 10, 64)
					if _ve != nil {
						return fmt.Errorf("field {{yamlKey .}}: %w", _ve)
					}
					_list = append(_list, {{elemType .ReaderType}}(_v))
{{- else if .IsEnum}}
					_v, _ve := strconv.ParseInt(string(_item), 10, 32)
					if _ve != nil {
						return fmt.Errorf("field {{yamlKey .}}: %w", _ve)
					}
					_list = append(_list, {{elemType .ReaderType}}(_v))
{{- else}}
					_v, _ve := strconv.ParseInt(string(_item), 10, 32)
					if _ve != nil {
						return fmt.Errorf("field {{yamlKey .}}: %w", _ve)
					}
					_list = append(_list, {{elemType .ReaderType}}(_v))
{{- end}}
				}
				r.{{.Name}} = _list
{{- end}}
			}
{{- else if .IsMsg}}
{{- if .IsRecursive}}
			if r.{{.Name}} == nil {
				r.{{.Name}} = new({{.ReaderType}})
			}
			r._has{{.Name}} = true
			if _e := r.{{.Name}}.FromYAML(_collectBlock(&_i)); _e != nil {
				return fmt.Errorf("field {{yamlKey .}}: %w", _e)
			}
{{- else}}
			if _e := r.{{.Name}}.FromYAML(_collectBlock(&_i)); _e != nil {
				return fmt.Errorf("field {{yamlKey .}}: %w", _e)
			}
{{- end}}
{{- else if .IsDecimal}}
			{
				_v, _e := strconv.ParseFloat(string(_valBytes), 64)
				if _e != nil {
					return fmt.Errorf("field {{yamlKey .}}: %w", _e)
				}
				r.{{.Name}} = decimal.MustNew(int64(math.Round(_v*math.Pow10({{decimalRound .}}))), {{decimalRound .}})
			}
{{- else if eq .Type "string"}}
			r.{{.Name}} = _unquoteStr(_valBytes)
{{- else if eq .Type "bytes"}}
			{
				_v, _e := base64.StdEncoding.DecodeString(string(_valBytes))
				if _e != nil {
					return fmt.Errorf("field {{yamlKey .}}: %w", _e)
				}
				r.{{.Name}} = _v
			}
{{- else if eq .Type "bool"}}
			r.{{.Name}} = string(_valBytes) == "true" || string(_valBytes) == "1"
{{- else if eq .Type "double"}}
			{
				_v, _e := strconv.ParseFloat(string(_valBytes), 64)
				if _e != nil {
					return fmt.Errorf("field {{yamlKey .}}: %w", _e)
				}
				r.{{.Name}} = _v
			}
{{- else if eq .Type "float"}}
			{
				_v, _e := strconv.ParseFloat(string(_valBytes), 32)
				if _e != nil {
					return fmt.Errorf("field {{yamlKey .}}: %w", _e)
				}
				r.{{.Name}} = float32(_v)
			}
{{- else if or (eq .Type "uint64") (eq .Type "fixed64")}}
			{
				_v, _e := strconv.ParseUint(string(_valBytes), 10, 64)
				if _e != nil {
					return fmt.Errorf("field {{yamlKey .}}: %w", _e)
				}
				r.{{.Name}} = {{.GoType}}(_v)
			}
{{- else if or (eq .Type "uint32") (eq .Type "fixed32")}}
			{
				_v, _e := strconv.ParseUint(string(_valBytes), 10, 32)
				if _e != nil {
					return fmt.Errorf("field {{yamlKey .}}: %w", _e)
				}
				r.{{.Name}} = {{.GoType}}(_v)
			}
{{- else if or (eq .Type "int64") (eq .Type "sint64") (eq .Type "sfixed64")}}
			{
				_v, _e := strconv.ParseInt(string(_valBytes), 10, 64)
				if _e != nil {
					return fmt.Errorf("field {{yamlKey .}}: %w", _e)
				}
				r.{{.Name}} = {{.GoType}}(_v)
			}
{{- else if .IsEnum}}
			{
				_v, _e := strconv.ParseInt(string(_valBytes), 10, 32)
				if _e != nil {
					return fmt.Errorf("field {{yamlKey .}}: %w", _e)
				}
				r.{{.Name}} = {{.ReaderType}}(_v)
			}
{{- else}}
			{
				_v, _e := strconv.ParseInt(string(_valBytes), 10, 32)
				if _e != nil {
					return fmt.Errorf("field {{yamlKey .}}: %w", _e)
				}
				r.{{.Name}} = {{.GoType}}(_v)
			}
{{- end}}
{{end}}		}
{{- end}}
	}
{{- end}}
	return nil
}
{{end}}{{end}}
