// Code generated by https://github.com/ahfuzhang/BaoHuLu. DO NOT EDIT.
// source: {{.Namespace}}

#pragma warning disable CS8600, CS8601, CS8602, CS8618, CS8625

using System;
using System.Buffers.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using QiWa.Common;
using static QiWa.Common.ProtobufUtils;

namespace {{.Namespace}};

// ─── Enums ───────────────────────────────────────────────────────────────────
{{range .Enums}}
public enum {{.Name}} : int
{
{{- range .Values}}
    {{.Name}} = {{.Number}},
{{- end}}
}
{{end}}

// ─── Messages ────────────────────────────────────────────────────────────────
{{range .Messages}}
{{- $goName := .GoName}}
// ── Tag numbers and JSON keys for {{$goName}} ──────────────────────────────────
internal struct {{$goName}}Tags
{
{{- range .Fields}}
    internal const int Tag{{.Name}} = {{.Number}};
{{- end}}
{{- range .Fields}}
    internal static ReadOnlySpan<byte> JsonKey{{.Name}} => "{{.JsonName}}"u8;
{{- end}}
}

// ============================================================================
// Readonly{{$goName}} — immutable view over decoded protobuf bytes
// ============================================================================

public struct Readonly{{$goName}} : IResettable
{
{{- range .Fields}}
    [JsonPropertyName("{{.JsonName}}")]
    public {{.ReadonlyType}} {{.Name}};
{{- end}}

    // ── FromProtobuf ─────────────────────────────────────────────────────────

    public Error FromProtobuf(ReadOnlySpan<byte> binary)
    {
        // local decode variables
{{- range .Fields}}
{{- if .IsMap}}
        {{.LocalType}}? _{{.Name}}Dict = null;
{{- else if .IsRepeated}}
        var _{{.Name}}List = this.{{.Name}} ?? new {{.LocalType}}();
        _{{.Name}}List.Clear();
{{- else if .IsString}}
        string? _{{.Name}} = null;
{{- else if .IsBytes}}
        byte[]? _{{.Name}} = null;
{{- else if .IsMsg}}
        {{.ReadonlyType}} _{{.Name}} = default;
{{- else if .IsEnum}}
        {{.WriterType}} _{{.Name}} = default;
{{- else if .IsBool}}
        bool _{{.Name}} = false;
{{- else}}
        {{.WriterType}} _{{.Name}} = {{csDefault .WriterType}};
{{- end}}
{{- end}}

        int _pos = 0;
        while (_pos < binary.Length)
        {
            if (!TryReadVarint(binary, _pos, out ulong _tagRaw, out int _tagBytes))
                return Error.WithLoc(1, "failed to read tag");
            _pos += _tagBytes;
            int _fieldNum = (int)(_tagRaw >> 3);
            int _wireType = (int)(_tagRaw & 7);
            switch (_fieldNum)
            {
{{- range .Fields}}
                case {{$goName}}Tags.Tag{{.Name}}: // {{.Name}}
{{- if .IsMap}}
                {
                    if (!TryReadVarint(binary, _pos, out ulong _elen{{.Name}}, out int _elb{{.Name}}))
                        return Error.WithLoc(1, "bad map {{.Name}}");
                    _pos += _elb{{.Name}};
                    var _entBin{{.Name}} = binary.Slice(_pos, (int)_elen{{.Name}});
{{- if eq .MapKeyCS "string"}}
                    {{.MapKeyCS}} _entKey{{.Name}} = string.Empty;
{{- else}}
                    {{.MapKeyCS}} _entKey{{.Name}} = default;
{{- end}}
{{- if eq .ReadonlyMapValCS "string"}}
                    {{.ReadonlyMapValCS}} _entVal{{.Name}} = string.Empty;
{{- else}}
                    {{.ReadonlyMapValCS}} _entVal{{.Name}} = default;
{{- end}}
                    int _ep{{.Name}} = 0;
                    while (_ep{{.Name}} < _entBin{{.Name}}.Length)
                    {
                        if (!TryReadVarint(_entBin{{.Name}}, _ep{{.Name}}, out ulong _etag{{.Name}}, out int _etb{{.Name}})) break;
                        _ep{{.Name}} += _etb{{.Name}};
                        int _ef{{.Name}} = (int)(_etag{{.Name}} >> 3);
                        int _ew{{.Name}} = (int)(_etag{{.Name}} & 7);
                        if (_ef{{.Name}} == 1) // map key
                        {
{{- if eq .MapKey "string"}}
                            if (!TryReadVarint(_entBin{{.Name}}, _ep{{.Name}}, out ulong _ksl{{.Name}}, out int _ksb{{.Name}})) break;
                            _ep{{.Name}} += _ksb{{.Name}};
                            _entKey{{.Name}} = Encoding.UTF8.GetString(_entBin{{.Name}}.Slice(_ep{{.Name}}, (int)_ksl{{.Name}}));
                            _ep{{.Name}} += (int)_ksl{{.Name}};
{{- else if eq .MapKey "bool"}}
                            if (!TryReadVarint(_entBin{{.Name}}, _ep{{.Name}}, out ulong _kbv{{.Name}}, out int _kbb{{.Name}})) break;
                            _entKey{{.Name}} = _kbv{{.Name}} != 0;
                            _ep{{.Name}} += _kbb{{.Name}};
{{- else if eq .MapKey "fixed32"}}
                            TryReadFixed32(_entBin{{.Name}}, _ep{{.Name}}, out uint _kf32{{.Name}});
                            _entKey{{.Name}} = _kf32{{.Name}}; _ep{{.Name}} += 4;
{{- else if eq .MapKey "sfixed32"}}
                            TryReadFixed32(_entBin{{.Name}}, _ep{{.Name}}, out uint _ksf32{{.Name}});
                            _entKey{{.Name}} = (int)_ksf32{{.Name}}; _ep{{.Name}} += 4;
{{- else if eq .MapKey "fixed64"}}
                            TryReadFixed64(_entBin{{.Name}}, _ep{{.Name}}, out ulong _kf64{{.Name}});
                            _entKey{{.Name}} = _kf64{{.Name}}; _ep{{.Name}} += 8;
{{- else if eq .MapKey "sfixed64"}}
                            TryReadFixed64(_entBin{{.Name}}, _ep{{.Name}}, out ulong _ksf64{{.Name}});
                            _entKey{{.Name}} = (long)_ksf64{{.Name}}; _ep{{.Name}} += 8;
{{- else if eq .MapKey "sint32"}}
                            if (!TryReadVarint(_entBin{{.Name}}, _ep{{.Name}}, out ulong _ks32{{.Name}}, out int _kb32{{.Name}})) break;
                            _entKey{{.Name}} = ZigZagDecode32(_ks32{{.Name}}); _ep{{.Name}} += _kb32{{.Name}};
{{- else if eq .MapKey "sint64"}}
                            if (!TryReadVarint(_entBin{{.Name}}, _ep{{.Name}}, out ulong _ks64{{.Name}}, out int _kb64{{.Name}})) break;
                            _entKey{{.Name}} = ZigZagDecode64(_ks64{{.Name}}); _ep{{.Name}} += _kb64{{.Name}};
{{- else}}
                            if (!TryReadVarint(_entBin{{.Name}}, _ep{{.Name}}, out ulong _kv{{.Name}}, out int _kvb{{.Name}})) break;
                            _entKey{{.Name}} = ({{.MapKeyCS}})_kv{{.Name}}; _ep{{.Name}} += _kvb{{.Name}};
{{- end}}
                        }
                        else if (_ef{{.Name}} == 2) // map value
                        {
{{- if .MapValIsMsg}}
                            if (!TryReadVarint(_entBin{{.Name}}, _ep{{.Name}}, out ulong _vmlen{{.Name}}, out int _vmlb{{.Name}})) break;
                            _ep{{.Name}} += _vmlb{{.Name}};
                            {{.ReadonlyMapValCS}} _vsubMsg{{.Name}} = default;
                            var _vsubErr{{.Name}} = _vsubMsg{{.Name}}.FromProtobuf(_entBin{{.Name}}.Slice(_ep{{.Name}}, (int)_vmlen{{.Name}}));
                            if (_vsubErr{{.Name}}.Err()) return _vsubErr{{.Name}};
                            _entVal{{.Name}} = _vsubMsg{{.Name}}; _ep{{.Name}} += (int)_vmlen{{.Name}};
{{- else if eq .MapVal "string"}}
                            if (!TryReadVarint(_entBin{{.Name}}, _ep{{.Name}}, out ulong _vsl{{.Name}}, out int _vsb{{.Name}})) break;
                            _ep{{.Name}} += _vsb{{.Name}};
                            _entVal{{.Name}} = Encoding.UTF8.GetString(_entBin{{.Name}}.Slice(_ep{{.Name}}, (int)_vsl{{.Name}}));
                            _ep{{.Name}} += (int)_vsl{{.Name}};
{{- else if eq .MapVal "bytes"}}
                            if (!TryReadVarint(_entBin{{.Name}}, _ep{{.Name}}, out ulong _vbl{{.Name}}, out int _vbb{{.Name}})) break;
                            _ep{{.Name}} += _vbb{{.Name}};
                            _entVal{{.Name}} = _entBin{{.Name}}.Slice(_ep{{.Name}}, (int)_vbl{{.Name}}).ToArray(); _ep{{.Name}} += (int)_vbl{{.Name}};
{{- else if eq .MapVal "double"}}
                            TryReadFixed64(_entBin{{.Name}}, _ep{{.Name}}, out ulong _vd64{{.Name}});
                            _entVal{{.Name}} = BitConverter.UInt64BitsToDouble(_vd64{{.Name}}); _ep{{.Name}} += 8;
{{- else if eq .MapVal "float"}}
                            TryReadFixed32(_entBin{{.Name}}, _ep{{.Name}}, out uint _vf32{{.Name}});
                            _entVal{{.Name}} = BitConverter.UInt32BitsToSingle(_vf32{{.Name}}); _ep{{.Name}} += 4;
{{- else if eq .MapVal "fixed32"}}
                            TryReadFixed32(_entBin{{.Name}}, _ep{{.Name}}, out uint _vfx32{{.Name}});
                            _entVal{{.Name}} = _vfx32{{.Name}}; _ep{{.Name}} += 4;
{{- else if eq .MapVal "sfixed32"}}
                            TryReadFixed32(_entBin{{.Name}}, _ep{{.Name}}, out uint _vsfx32{{.Name}});
                            _entVal{{.Name}} = (int)_vsfx32{{.Name}}; _ep{{.Name}} += 4;
{{- else if eq .MapVal "fixed64"}}
                            TryReadFixed64(_entBin{{.Name}}, _ep{{.Name}}, out ulong _vfx64{{.Name}});
                            _entVal{{.Name}} = _vfx64{{.Name}}; _ep{{.Name}} += 8;
{{- else if eq .MapVal "sfixed64"}}
                            TryReadFixed64(_entBin{{.Name}}, _ep{{.Name}}, out ulong _vsfx64{{.Name}});
                            _entVal{{.Name}} = (long)_vsfx64{{.Name}}; _ep{{.Name}} += 8;
{{- else if eq .MapVal "sint32"}}
                            if (!TryReadVarint(_entBin{{.Name}}, _ep{{.Name}}, out ulong _vs32{{.Name}}, out int _vsb32{{.Name}})) break;
                            _entVal{{.Name}} = ZigZagDecode32(_vs32{{.Name}}); _ep{{.Name}} += _vsb32{{.Name}};
{{- else if eq .MapVal "sint64"}}
                            if (!TryReadVarint(_entBin{{.Name}}, _ep{{.Name}}, out ulong _vs64{{.Name}}, out int _vsb64{{.Name}})) break;
                            _entVal{{.Name}} = ZigZagDecode64(_vs64{{.Name}}); _ep{{.Name}} += _vsb64{{.Name}};
{{- else if eq .MapVal "bool"}}
                            if (!TryReadVarint(_entBin{{.Name}}, _ep{{.Name}}, out ulong _vbool{{.Name}}, out int _vboolb{{.Name}})) break;
                            _entVal{{.Name}} = _vbool{{.Name}} != 0; _ep{{.Name}} += _vboolb{{.Name}};
{{- else}}
                            if (!TryReadVarint(_entBin{{.Name}}, _ep{{.Name}}, out ulong _vvar{{.Name}}, out int _vvarb{{.Name}})) break;
                            _entVal{{.Name}} = ({{.MapValCS}})_vvar{{.Name}}; _ep{{.Name}} += _vvarb{{.Name}};
{{- end}}
                        }
                        else
                        {
                            if (!SkipField(_entBin{{.Name}}, _ep{{.Name}}, _ew{{.Name}}, out int _eskip{{.Name}})) break;
                            _ep{{.Name}} += _eskip{{.Name}};
                        }
                    }
                    _{{.Name}}Dict ??= new {{.LocalType}}();
                    _{{.Name}}Dict[_entKey{{.Name}}] = _entVal{{.Name}};
                    _pos += (int)_elen{{.Name}};
                }
{{- else if .IsRepeated}}
                {
{{- if .IsPackable}}
                    _{{.Name}}List ??= new {{.LocalType}}();
                    if (_wireType == WireTypeLenDelim)
                    { // packed
                        if (!TryReadVarint(binary, _pos, out ulong _plen{{.Name}}, out int _plb{{.Name}}))
                            return Error.WithLoc(1, "bad packed {{.Name}}");
                        _pos += _plb{{.Name}};
                        int _packEnd{{.Name}} = _pos + (int)_plen{{.Name}};
                        while (_pos < _packEnd{{.Name}})
                        {
{{- if .IsFixed32}}
                            if (!TryReadFixed32(binary, _pos, out uint _pf32{{.Name}})) break;
{{- if eq .Type "float"}}
                            _{{.Name}}List.Add(BitConverter.UInt32BitsToSingle(_pf32{{.Name}}));
{{- else if eq .Type "sfixed32"}}
                            _{{.Name}}List.Add((int)_pf32{{.Name}});
{{- else}}
                            _{{.Name}}List.Add(_pf32{{.Name}});
{{- end}}
                            _pos += 4;
{{- else if .IsFixed64}}
                            if (!TryReadFixed64(binary, _pos, out ulong _pf64{{.Name}})) break;
{{- if eq .Type "double"}}
                            _{{.Name}}List.Add(BitConverter.UInt64BitsToDouble(_pf64{{.Name}}));
{{- else if eq .Type "sfixed64"}}
                            _{{.Name}}List.Add((long)_pf64{{.Name}});
{{- else}}
                            _{{.Name}}List.Add(_pf64{{.Name}});
{{- end}}
                            _pos += 8;
{{- else if .IsBool}}
                            if (!TryReadVarint(binary, _pos, out ulong _pbool{{.Name}}, out int _pboolb{{.Name}})) break;
                            _{{.Name}}List.Add(_pbool{{.Name}} != 0); _pos += _pboolb{{.Name}};
{{- else if .IsSint32}}
                            if (!TryReadVarint(binary, _pos, out ulong _psz{{.Name}}, out int _pszb{{.Name}})) break;
                            _{{.Name}}List.Add(ZigZagDecode32(_psz{{.Name}})); _pos += _pszb{{.Name}};
{{- else if .IsSint64}}
                            if (!TryReadVarint(binary, _pos, out ulong _psz64{{.Name}}, out int _psz64b{{.Name}})) break;
                            _{{.Name}}List.Add(ZigZagDecode64(_psz64{{.Name}})); _pos += _psz64b{{.Name}};
{{- else}}
                            if (!TryReadVarint(binary, _pos, out ulong _pv{{.Name}}, out int _pvb{{.Name}})) break;
                            _{{.Name}}List.Add(({{.ElemTypeCS}})_pv{{.Name}}); _pos += _pvb{{.Name}};
{{- end}}
                        }
                    }
                    else
                    { // non-packed single element
{{- if .IsFixed32}}
                        if (!TryReadFixed32(binary, _pos, out uint _npf32{{.Name}}))
                            return Error.WithLoc(1, "bad fixed32 {{.Name}}");
{{- if eq .Type "float"}}
                        _{{.Name}}List.Add(BitConverter.UInt32BitsToSingle(_npf32{{.Name}})); _pos += 4;
{{- else if eq .Type "sfixed32"}}
                        _{{.Name}}List.Add((int)_npf32{{.Name}}); _pos += 4;
{{- else}}
                        _{{.Name}}List.Add(_npf32{{.Name}}); _pos += 4;
{{- end}}
{{- else if .IsFixed64}}
                        if (!TryReadFixed64(binary, _pos, out ulong _npf64{{.Name}}))
                            return Error.WithLoc(1, "bad fixed64 {{.Name}}");
{{- if eq .Type "double"}}
                        _{{.Name}}List.Add(BitConverter.UInt64BitsToDouble(_npf64{{.Name}})); _pos += 8;
{{- else if eq .Type "sfixed64"}}
                        _{{.Name}}List.Add((long)_npf64{{.Name}}); _pos += 8;
{{- else}}
                        _{{.Name}}List.Add(_npf64{{.Name}}); _pos += 8;
{{- end}}
{{- else if .IsBool}}
                        if (!TryReadVarint(binary, _pos, out ulong _npbool{{.Name}}, out int _npboolb{{.Name}}))
                            return Error.WithLoc(1, "bad bool {{.Name}}");
                        _{{.Name}}List.Add(_npbool{{.Name}} != 0); _pos += _npboolb{{.Name}};
{{- else if .IsSint32}}
                        if (!TryReadVarint(binary, _pos, out ulong _npsz{{.Name}}, out int _npszb{{.Name}}))
                            return Error.WithLoc(1, "bad sint32 {{.Name}}");
                        _{{.Name}}List.Add(ZigZagDecode32(_npsz{{.Name}})); _pos += _npszb{{.Name}};
{{- else if .IsSint64}}
                        if (!TryReadVarint(binary, _pos, out ulong _npsz64{{.Name}}, out int _npsz64b{{.Name}}))
                            return Error.WithLoc(1, "bad sint64 {{.Name}}");
                        _{{.Name}}List.Add(ZigZagDecode64(_npsz64{{.Name}})); _pos += _npsz64b{{.Name}};
{{- else}}
                        if (!TryReadVarint(binary, _pos, out ulong _npv{{.Name}}, out int _npvb{{.Name}}))
                            return Error.WithLoc(1, "bad varint {{.Name}}");
                        _{{.Name}}List.Add(({{.ElemTypeCS}})_npv{{.Name}}); _pos += _npvb{{.Name}};
{{- end}}
                    }
{{- else}}
                    // repeated non-packable
                    _{{.Name}}List ??= new {{.LocalType}}();
{{- if .IsString}}
                    if (!TryReadVarint(binary, _pos, out ulong _rslen{{.Name}}, out int _rslb{{.Name}}))
                        return Error.WithLoc(1, "bad string {{.Name}}");
                    _pos += _rslb{{.Name}};
                    _{{.Name}}List.Add(Encoding.UTF8.GetString(binary.Slice(_pos, (int)_rslen{{.Name}}))); _pos += (int)_rslen{{.Name}};
{{- else if .IsBytes}}
                    if (!TryReadVarint(binary, _pos, out ulong _rblen{{.Name}}, out int _rblb{{.Name}}))
                        return Error.WithLoc(1, "bad bytes {{.Name}}");
                    _pos += _rblb{{.Name}};
                    _{{.Name}}List.Add(binary.Slice(_pos, (int)_rblen{{.Name}}).ToArray()); _pos += (int)_rblen{{.Name}};
{{- else if .ElemIsMsg}}
                    if (!TryReadVarint(binary, _pos, out ulong _rmlen{{.Name}}, out int _rmlb{{.Name}}))
                        return Error.WithLoc(1, "bad msg {{.Name}}");
                    _pos += _rmlb{{.Name}};
                    {{.ReadonlyElemTypeCS}} _rsub{{.Name}} = default;
                    var _rsuberr{{.Name}} = _rsub{{.Name}}.FromProtobuf(binary.Slice(_pos, (int)_rmlen{{.Name}}));
                    if (_rsuberr{{.Name}}.Err()) return _rsuberr{{.Name}};
                    _{{.Name}}List.Add(_rsub{{.Name}}); _pos += (int)_rmlen{{.Name}};
{{- else}}
                    if (!TryReadVarint(binary, _pos, out ulong _rvar{{.Name}}, out int _rvarb{{.Name}}))
                        return Error.WithLoc(1, "bad elem {{.Name}}");
                    _{{.Name}}List.Add(({{.ElemTypeCS}})_rvar{{.Name}}); _pos += _rvarb{{.Name}};
{{- end}}
{{- end}}
                }
{{- else if .IsMsg}}
                {
                    if (!TryReadVarint(binary, _pos, out ulong _mlen{{.Name}}, out int _mlb{{.Name}}))
                        return Error.WithLoc(1, "bad msg {{.Name}}");
                    _pos += _mlb{{.Name}};
                    var _subErr{{.Name}} = _{{.Name}}.FromProtobuf(binary.Slice(_pos, (int)_mlen{{.Name}}));
                    if (_subErr{{.Name}}.Err()) return _subErr{{.Name}};
                    _pos += (int)_mlen{{.Name}};
                }
{{- else if .IsString}}
                {
                    if (!TryReadVarint(binary, _pos, out ulong _slen{{.Name}}, out int _slb{{.Name}}))
                        return Error.WithLoc(1, "bad string {{.Name}}");
                    _pos += _slb{{.Name}};
                    _{{.Name}} = Encoding.UTF8.GetString(binary.Slice(_pos, (int)_slen{{.Name}}));
                    _pos += (int)_slen{{.Name}};
                }
{{- else if .IsBytes}}
                {
                    if (!TryReadVarint(binary, _pos, out ulong _blen{{.Name}}, out int _blb{{.Name}}))
                        return Error.WithLoc(1, "bad bytes {{.Name}}");
                    _pos += _blb{{.Name}};
                    _{{.Name}} = binary.Slice(_pos, (int)_blen{{.Name}}).ToArray();
                    _pos += (int)_blen{{.Name}};
                }
{{- else if .IsFixed32}}
                {
                    if (!TryReadFixed32(binary, _pos, out uint _f32v{{.Name}}))
                        return Error.WithLoc(1, "bad fixed32 {{.Name}}");
{{- if eq .Type "float"}}
                    _{{.Name}} = BitConverter.UInt32BitsToSingle(_f32v{{.Name}});
{{- else if eq .Type "sfixed32"}}
                    _{{.Name}} = (int)_f32v{{.Name}};
{{- else}}
                    _{{.Name}} = _f32v{{.Name}};
{{- end}}
                    _pos += 4;
                }
{{- else if .IsFixed64}}
                {
                    if (!TryReadFixed64(binary, _pos, out ulong _f64v{{.Name}}))
                        return Error.WithLoc(1, "bad fixed64 {{.Name}}");
{{- if eq .Type "double"}}
                    _{{.Name}} = BitConverter.UInt64BitsToDouble(_f64v{{.Name}});
{{- else if eq .Type "sfixed64"}}
                    _{{.Name}} = (long)_f64v{{.Name}};
{{- else}}
                    _{{.Name}} = _f64v{{.Name}};
{{- end}}
                    _pos += 8;
                }
{{- else if .IsBool}}
                {
                    if (!TryReadVarint(binary, _pos, out ulong _boolv{{.Name}}, out int _boolb{{.Name}}))
                        return Error.WithLoc(1, "bad bool {{.Name}}");
                    _{{.Name}} = _boolv{{.Name}} != 0;
                    _pos += _boolb{{.Name}};
                }
{{- else if .IsSint32}}
                {
                    if (!TryReadVarint(binary, _pos, out ulong _sz32v{{.Name}}, out int _sz32b{{.Name}}))
                        return Error.WithLoc(1, "bad sint32 {{.Name}}");
                    _{{.Name}} = ZigZagDecode32(_sz32v{{.Name}});
                    _pos += _sz32b{{.Name}};
                }
{{- else if .IsSint64}}
                {
                    if (!TryReadVarint(binary, _pos, out ulong _sz64v{{.Name}}, out int _sz64b{{.Name}}))
                        return Error.WithLoc(1, "bad sint64 {{.Name}}");
                    _{{.Name}} = ZigZagDecode64(_sz64v{{.Name}});
                    _pos += _sz64b{{.Name}};
                }
{{- else}}
                {
                    // varint / enum
                    if (!TryReadVarint(binary, _pos, out ulong _varv{{.Name}}, out int _varb{{.Name}}))
                        return Error.WithLoc(1, "bad varint {{.Name}}");
                    _{{.Name}} = ({{.WriterType}})_varv{{.Name}};
                    _pos += _varb{{.Name}};
                }
{{- end}}
                    break;
{{- end}}
                default:
                    if (!SkipField(binary, _pos, _wireType, out int _skip))
                        return Error.WithLoc(1, "truncated binary data");
                    _pos += _skip;
                    break;
            }
        }
{{- range .Fields}}
{{- if .IsMap}}
        this.{{.Name}} = _{{.Name}}Dict != null ? _{{.Name}}Dict.ToImmutableDictionary() : ImmutableDictionary<{{.MapKeyCS}}, {{.ReadonlyMapValCS}}>.Empty;
{{- else if .IsRepeated}}
        this.{{.Name}} = _{{.Name}}List;
{{- else if .IsString}}
        this.{{.Name}} = _{{.Name}} ?? string.Empty;
{{- else if .IsBytes}}
        this.{{.Name}} = _{{.Name}} ?? Array.Empty<byte>();
{{- else}}
        this.{{.Name}} = _{{.Name}};
{{- end}}
{{- end}}
        return default;
    }

    // ── FromJSON ─────────────────────────────────────────────────────────────

    public Error FromJSON(ReadOnlySpan<byte> text)
    {
        try
        {
            var _reader = new Utf8JsonReader(text, new JsonReaderOptions
            {
                AllowTrailingCommas = true,
                CommentHandling     = JsonCommentHandling.Skip
            });
            return FromJSONReader(ref _reader);
        }
        catch (System.Text.Json.JsonException ex)
        {
            return Error.WithLoc(1, ex.Message);
        }
    }

    internal Error FromJSONReader(ref Utf8JsonReader reader)
    {
        // If the reader is freshly created (None) or not yet at StartObject, advance.
        // When called from a nested context, caller already advanced to StartObject.
        if (reader.TokenType != JsonTokenType.StartObject)
        {
            if (!reader.Read() || reader.TokenType != JsonTokenType.StartObject)
                return Error.WithLoc(1, "expected {");
        }

        // local decode variables
{{- range .Fields}}
{{- if .IsMap}}
        {{.LocalType}}? _{{.Name}}Dict = null;
{{- else if .IsRepeated}}
        var _{{.Name}}List = this.{{.Name}} ?? new {{.LocalType}}();
        _{{.Name}}List.Clear();
{{- else if .IsString}}
        string? _{{.Name}} = null;
{{- else if .IsBytes}}
        byte[]? _{{.Name}} = null;
{{- else if .IsMsg}}
        {{.ReadonlyType}} _{{.Name}} = default;
{{- else if .IsEnum}}
        {{.WriterType}} _{{.Name}} = default;
{{- else if .IsBool}}
        bool _{{.Name}} = false;
{{- else}}
        {{.WriterType}} _{{.Name}} = {{csDefault .WriterType}};
{{- end}}
{{- end}}

        while (reader.Read() && reader.TokenType != JsonTokenType.EndObject)
        {
            if (reader.TokenType != JsonTokenType.PropertyName)
                return Error.WithLoc(1, "expected property name");
            var _propSpan = reader.ValueSpan;
            if (!reader.Read()) return Error.WithLoc(1, "unexpected end");
{{- range $i, $f := .Fields}}
            {{if $i}}else {{end}}if (_propSpan.SequenceEqual({{$goName}}Tags.JsonKey{{.Name}}))
{{- if .IsMap}}
                {
                    _{{.Name}}Dict ??= new {{.LocalType}}();
                    if (reader.TokenType == JsonTokenType.StartObject)
                    {
                        while (reader.Read() && reader.TokenType != JsonTokenType.EndObject)
                        {
{{- if eq .MapKeyCS "string"}}
                            string _mke{{.Name}} = reader.GetString()!;
{{- else if eq .MapKeyCS "bool"}}
                            bool _mke{{.Name}} = reader.ValueSpan.SequenceEqual("true"u8);
{{- else}}
                            if (!Utf8Parser.TryParse(reader.ValueSpan, out {{.MapKeyCS}} _mke{{.Name}}, out _))
                                return Error.WithLoc(1, "bad map key {{.Name}}");
{{- end}}
                            reader.Read();
{{- if .MapValIsMsg}}
                            {{.ReadonlyMapValCS}} _mvMsg{{.Name}} = default;
                            var _mvErr{{.Name}} = _mvMsg{{.Name}}.FromJSONReader(ref reader);
                            if (_mvErr{{.Name}}.Err()) return _mvErr{{.Name}};
                            _{{.Name}}Dict[_mke{{.Name}}] = _mvMsg{{.Name}};
{{- else if eq .MapVal "string"}}
                            _{{.Name}}Dict[_mke{{.Name}}] = reader.GetString() ?? string.Empty;
{{- else if eq .MapVal "bytes"}}
                            _{{.Name}}Dict[_mke{{.Name}}] = reader.GetBytesFromBase64();
{{- else if eq .MapVal "bool"}}
                            _{{.Name}}Dict[_mke{{.Name}}] = reader.ValueSpan.SequenceEqual("true"u8);
{{- else if eq .MapVal "double"}}
                            { if (!Utf8Parser.TryParse(reader.ValueSpan, out double _mvdv{{.Name}}, out _)) return Error.WithLoc(1, "bad map value {{.Name}}"); _{{.Name}}Dict[_mke{{.Name}}] = _mvdv{{.Name}}; }
{{- else if eq .MapVal "float"}}
                            { if (!Utf8Parser.TryParse(reader.ValueSpan, out float _mvfv{{.Name}}, out _)) return Error.WithLoc(1, "bad map value {{.Name}}"); _{{.Name}}Dict[_mke{{.Name}}] = _mvfv{{.Name}}; }
{{- else if eq .MapVal "int64"}}
                            { if (!Utf8Parser.TryParse(reader.ValueSpan, out long _mvl{{.Name}}, out _)) return Error.WithLoc(1, "bad map value {{.Name}}"); _{{.Name}}Dict[_mke{{.Name}}] = _mvl{{.Name}}; }
{{- else if eq .MapVal "uint64"}}
                            { if (!Utf8Parser.TryParse(reader.ValueSpan, out ulong _mvul{{.Name}}, out _)) return Error.WithLoc(1, "bad map value {{.Name}}"); _{{.Name}}Dict[_mke{{.Name}}] = _mvul{{.Name}}; }
{{- else if eq .MapVal "sint64"}}
                            { if (!Utf8Parser.TryParse(reader.ValueSpan, out long _mvl{{.Name}}, out _)) return Error.WithLoc(1, "bad map value {{.Name}}"); _{{.Name}}Dict[_mke{{.Name}}] = _mvl{{.Name}}; }
{{- else if eq .MapVal "sfixed64"}}
                            { if (!Utf8Parser.TryParse(reader.ValueSpan, out long _mvl{{.Name}}, out _)) return Error.WithLoc(1, "bad map value {{.Name}}"); _{{.Name}}Dict[_mke{{.Name}}] = _mvl{{.Name}}; }
{{- else if eq .MapVal "fixed64"}}
                            { if (!Utf8Parser.TryParse(reader.ValueSpan, out ulong _mvul{{.Name}}, out _)) return Error.WithLoc(1, "bad map value {{.Name}}"); _{{.Name}}Dict[_mke{{.Name}}] = _mvul{{.Name}}; }
{{- else}}
                            { if (!Utf8Parser.TryParse(reader.ValueSpan, out int _mviv{{.Name}}, out _)) return Error.WithLoc(1, "bad map value {{.Name}}"); _{{.Name}}Dict[_mke{{.Name}}] = ({{.MapValCS}})_mviv{{.Name}}; }
{{- end}}
                        }
                    }
                }
{{- else if .IsRepeated}}
                {
                    _{{.Name}}List ??= new {{.LocalType}}();
                    if (reader.TokenType == JsonTokenType.StartArray)
                    {
                        while (reader.Read() && reader.TokenType != JsonTokenType.EndArray)
                        {
{{- if .ElemIsMsg}}
                            {{.ReadonlyElemTypeCS}} _arrMsg{{.Name}} = default;
                            var _arrErr{{.Name}} = _arrMsg{{.Name}}.FromJSONReader(ref reader);
                            if (_arrErr{{.Name}}.Err()) return _arrErr{{.Name}};
                            _{{.Name}}List.Add(_arrMsg{{.Name}});
{{- else if .IsString}}
                            _{{.Name}}List.Add(reader.GetString() ?? string.Empty);
{{- else if .IsBytes}}
                            _{{.Name}}List.Add(reader.GetBytesFromBase64());
{{- else if .IsBool}}
                            _{{.Name}}List.Add(reader.ValueSpan.SequenceEqual("true"u8));
{{- else if eq .ElemTypeCS "double"}}
                            { if (!Utf8Parser.TryParse(reader.ValueSpan, out double _arrdv{{.Name}}, out _)) return Error.WithLoc(1, "bad list elem {{.Name}}"); _{{.Name}}List.Add(_arrdv{{.Name}}); }
{{- else if eq .ElemTypeCS "float"}}
                            { if (!Utf8Parser.TryParse(reader.ValueSpan, out float _arrfv{{.Name}}, out _)) return Error.WithLoc(1, "bad list elem {{.Name}}"); _{{.Name}}List.Add(_arrfv{{.Name}}); }
{{- else if .IsFixed64}}
                            { if (!Utf8Parser.TryParse(reader.ValueSpan, out long _arrfl{{.Name}}, out _)) return Error.WithLoc(1, "bad list elem {{.Name}}"); _{{.Name}}List.Add(({{.ElemTypeCS}})_arrfl{{.Name}}); }
{{- else if eq .ElemTypeCS "long"}}
                            { if (!Utf8Parser.TryParse(reader.ValueSpan, out long _arrl{{.Name}}, out _)) return Error.WithLoc(1, "bad list elem {{.Name}}"); _{{.Name}}List.Add(_arrl{{.Name}}); }
{{- else if eq .ElemTypeCS "ulong"}}
                            { if (!Utf8Parser.TryParse(reader.ValueSpan, out ulong _arrul{{.Name}}, out _)) return Error.WithLoc(1, "bad list elem {{.Name}}"); _{{.Name}}List.Add(_arrul{{.Name}}); }
{{- else}}
                            { if (!Utf8Parser.TryParse(reader.ValueSpan, out int _arriv{{.Name}}, out _)) return Error.WithLoc(1, "bad list elem {{.Name}}"); _{{.Name}}List.Add(({{.ElemTypeCS}})_arriv{{.Name}}); }
{{- end}}
                        }
                    }
                }
{{- else if .IsMsg}}
                {
                    var _jerr{{.Name}} = _{{.Name}}.FromJSONReader(ref reader);
                    if (_jerr{{.Name}}.Err()) return _jerr{{.Name}};
                }
{{- else if .IsString}}
                    _{{.Name}} = reader.GetString();
{{- else if .IsBytes}}
                    _{{.Name}} = reader.GetBytesFromBase64();
{{- else if .IsBool}}
                    _{{.Name}} = reader.ValueSpan.SequenceEqual("true"u8);
{{- else if .IsEnum}}
                    { if (!Utf8Parser.TryParse(reader.ValueSpan, out int _ev{{.Name}}, out _)) return Error.WithLoc(1, "bad {{.Name}}"); _{{.Name}} = ({{.WriterType}})_ev{{.Name}}; }
{{- else if eq .WriterType "double"}}
                    { if (!Utf8Parser.TryParse(reader.ValueSpan, out double _dv{{.Name}}, out _)) return Error.WithLoc(1, "bad {{.Name}}"); _{{.Name}} = _dv{{.Name}}; }
{{- else if eq .WriterType "float"}}
                    { if (!Utf8Parser.TryParse(reader.ValueSpan, out float _fv{{.Name}}, out _)) return Error.WithLoc(1, "bad {{.Name}}"); _{{.Name}} = _fv{{.Name}}; }
{{- else if .IsFixed64}}
                    { if (!Utf8Parser.TryParse(reader.ValueSpan, out long _fl{{.Name}}, out _)) return Error.WithLoc(1, "bad {{.Name}}"); _{{.Name}} = ({{.WriterType}})_fl{{.Name}}; }
{{- else if eq .WriterType "long"}}
                    { if (!Utf8Parser.TryParse(reader.ValueSpan, out long _fl{{.Name}}, out _)) return Error.WithLoc(1, "bad {{.Name}}"); _{{.Name}} = _fl{{.Name}}; }
{{- else if eq .WriterType "ulong"}}
                    { if (!Utf8Parser.TryParse(reader.ValueSpan, out ulong _ful{{.Name}}, out _)) return Error.WithLoc(1, "bad {{.Name}}"); _{{.Name}} = _ful{{.Name}}; }
{{- else}}
                    { if (!Utf8Parser.TryParse(reader.ValueSpan, out int _iv{{.Name}}, out _)) return Error.WithLoc(1, "bad {{.Name}}"); _{{.Name}} = ({{.WriterType}})_iv{{.Name}}; }
{{- end}}
{{- end}}
            else { reader.Skip(); }
        }
{{- range .Fields}}
{{- if .IsMap}}
        this.{{.Name}} = _{{.Name}}Dict != null ? _{{.Name}}Dict.ToImmutableDictionary() : ImmutableDictionary<{{.MapKeyCS}}, {{.ReadonlyMapValCS}}>.Empty;
{{- else if .IsRepeated}}
        this.{{.Name}} = _{{.Name}}List;
{{- else if .IsString}}
        this.{{.Name}} = _{{.Name}} ?? string.Empty;
{{- else if .IsBytes}}
        this.{{.Name}} = _{{.Name}} ?? Array.Empty<byte>();
{{- else}}
        this.{{.Name}} = _{{.Name}};
{{- end}}
{{- end}}
        return default;
    }

    // ── Clone ─────────────────────────────────────────────────────────────────

    public {{$goName}} Clone()
    {
        var _clone = new {{$goName}}();
{{- range .Fields}}
{{- if .IsMap}}
{{- if .MapValIsMsg}}
        if ({{.Name}} != null)
        {
            _clone.{{.Name}} = new Dictionary<{{.MapKeyCS}}, {{.MapValCS}}>({{.Name}}.Count);
            foreach (var _kv{{.Name}} in {{.Name}})
                _clone.{{.Name}}[_kv{{.Name}}.Key] = _kv{{.Name}}.Value.Clone();
        }
        else
        {
            _clone.{{.Name}} = new Dictionary<{{.MapKeyCS}}, {{.MapValCS}}>();
        }
{{- else}}
        _clone.{{.Name}} = {{.Name}} != null ? new Dictionary<{{.MapKeyCS}}, {{.MapValCS}}>({{.Name}}) : new Dictionary<{{.MapKeyCS}}, {{.MapValCS}}>();
{{- end}}
{{- else if .IsRepeated}}
{{- if .ElemIsMsg}}
        if ({{.Name}} != null)
        {
            var _lst{{.Name}} = new List<{{.ElemTypeCS}}>({{.Name}}.Count);
            foreach (var _item{{.Name}} in {{.Name}})
                _lst{{.Name}}.Add(_item{{.Name}}.Clone());
            _clone.{{.Name}} = _lst{{.Name}};
        }
        else
        {
            _clone.{{.Name}} = new List<{{.ElemTypeCS}}>();
        }
{{- else}}
        _clone.{{.Name}} = {{.Name}} != null ? new List<{{.ElemTypeCS}}>({{.Name}}) : new List<{{.ElemTypeCS}}>();
{{- end}}
{{- else if .IsMsg}}
        _clone.{{.Name}} = {{.Name}}.Clone();
{{- else}}
        _clone.{{.Name}} = {{.Name}};
{{- end}}
{{- end}}
        return _clone;
    }

    // ── Reset ─────────────────────────────────────────────────────────────────

    public void Reset()
    {
{{- range .Fields}}
{{- if .IsMap}}
        {{.Name}} = ImmutableDictionary<{{.MapKeyCS}}, {{.ReadonlyMapValCS}}>.Empty;
{{- else if .IsRepeated}}
        {{.Name}}?.Clear();
{{- else if .IsMsg}}
        {{.Name}}.Reset();
{{- else if .IsString}}
        {{.Name}} = string.Empty;
{{- else if .IsBytes}}
        {{.Name}} = Array.Empty<byte>();
{{- else if .IsBool}}
        {{.Name}} = false;
{{- else}}
        {{.Name}} = {{csDefault .ReadonlyType}};
{{- end}}
{{- end}}
    }
}

// ============================================================================
// {{$goName}} — mutable struct for building / serialising
// ============================================================================

public struct {{$goName}} : IResettable
{
{{- range .Fields}}
    [JsonPropertyName("{{.JsonName}}")]
    public {{.WriterType}} {{.Name}};
{{- end}}

    // ── ProtobufSize ────────────────────────────────────────────────────────

    public int ProtobufSize()
    {
        int _size = 0;
{{- range .Fields}}
{{- if .IsMap}}
        if ({{.Name}} != null)
        {
            foreach (var _kv{{.Name}} in {{.Name}})
            {
                int _entrySize{{.Name}} = 0;
{{- if eq .MapKey "string"}}
                int _klen{{.Name}} = StringByteCount(_kv{{.Name}}.Key);
                _entrySize{{.Name}} += TagSize(1, WireTypeLenDelim) + LenDelimSize(_klen{{.Name}});
{{- else if eq .MapKey "bool"}}
                _entrySize{{.Name}} += TagSize(1, WireTypeVarint) + VarintSize(_kv{{.Name}}.Key ? 1UL : 0UL);
{{- else if eq .MapKey "fixed32"}}
                _entrySize{{.Name}} += TagSize(1, WireType32Bit) + 4;
{{- else if eq .MapKey "sfixed32"}}
                _entrySize{{.Name}} += TagSize(1, WireType32Bit) + 4;
{{- else if eq .MapKey "fixed64"}}
                _entrySize{{.Name}} += TagSize(1, WireType64Bit) + 8;
{{- else if eq .MapKey "sfixed64"}}
                _entrySize{{.Name}} += TagSize(1, WireType64Bit) + 8;
{{- else if eq .MapKey "sint32"}}
                _entrySize{{.Name}} += TagSize(1, WireTypeVarint) + VarintSize(ZigZagEncode32(_kv{{.Name}}.Key));
{{- else if eq .MapKey "sint64"}}
                _entrySize{{.Name}} += TagSize(1, WireTypeVarint) + VarintSize(ZigZagEncode64(_kv{{.Name}}.Key));
{{- else}}
                _entrySize{{.Name}} += TagSize(1, WireTypeVarint) + VarintSize((ulong)_kv{{.Name}}.Key);
{{- end}}
{{- if .MapValIsMsg}}
                int _vsize{{.Name}} = _kv{{.Name}}.Value.ProtobufSize();
                _entrySize{{.Name}} += TagSize(2, WireTypeLenDelim) + LenDelimSize(_vsize{{.Name}});
{{- else if eq .MapVal "string"}}
                int _vlen{{.Name}} = StringByteCount(_kv{{.Name}}.Value);
                _entrySize{{.Name}} += TagSize(2, WireTypeLenDelim) + LenDelimSize(_vlen{{.Name}});
{{- else if eq .MapVal "bytes"}}
                int _vlen{{.Name}} = _kv{{.Name}}.Value != null ? _kv{{.Name}}.Value.Length : 0;
                _entrySize{{.Name}} += TagSize(2, WireTypeLenDelim) + LenDelimSize(_vlen{{.Name}});
{{- else if eq .MapVal "double"}}
                _entrySize{{.Name}} += TagSize(2, WireType64Bit) + 8;
{{- else if eq .MapVal "float"}}
                _entrySize{{.Name}} += TagSize(2, WireType32Bit) + 4;
{{- else if eq .MapVal "fixed32"}}
                _entrySize{{.Name}} += TagSize(2, WireType32Bit) + 4;
{{- else if eq .MapVal "sfixed32"}}
                _entrySize{{.Name}} += TagSize(2, WireType32Bit) + 4;
{{- else if eq .MapVal "fixed64"}}
                _entrySize{{.Name}} += TagSize(2, WireType64Bit) + 8;
{{- else if eq .MapVal "sfixed64"}}
                _entrySize{{.Name}} += TagSize(2, WireType64Bit) + 8;
{{- else if eq .MapVal "sint32"}}
                _entrySize{{.Name}} += TagSize(2, WireTypeVarint) + VarintSize(ZigZagEncode32(_kv{{.Name}}.Value));
{{- else if eq .MapVal "sint64"}}
                _entrySize{{.Name}} += TagSize(2, WireTypeVarint) + VarintSize(ZigZagEncode64(_kv{{.Name}}.Value));
{{- else if eq .MapVal "bool"}}
                _entrySize{{.Name}} += TagSize(2, WireTypeVarint) + VarintSize(_kv{{.Name}}.Value ? 1UL : 0UL);
{{- else}}
                _entrySize{{.Name}} += TagSize(2, WireTypeVarint) + VarintSize((ulong)_kv{{.Name}}.Value);
{{- end}}
                _size += TagSize({{$goName}}Tags.Tag{{.Name}}, WireTypeLenDelim) + LenDelimSize(_entrySize{{.Name}});
            }
        }
{{- else if .IsRepeated}}
        if ({{.Name}} != null && {{.Name}}.Count > 0)
        {
{{- if .IsPackable}}
{{- if .IsFixed32}}
            _size += TagSize({{$goName}}Tags.Tag{{.Name}}, WireTypeLenDelim) + LenDelimSize({{.Name}}.Count * 4);
{{- else if .IsFixed64}}
            _size += TagSize({{$goName}}Tags.Tag{{.Name}}, WireTypeLenDelim) + LenDelimSize({{.Name}}.Count * 8);
{{- else if .IsBool}}
            _size += TagSize({{$goName}}Tags.Tag{{.Name}}, WireTypeLenDelim) + LenDelimSize({{.Name}}.Count);
{{- else if .IsSint32}}
            int _packed{{.Name}} = 0;
            foreach (var _pv{{.Name}} in {{.Name}})
                _packed{{.Name}} += VarintSize(ZigZagEncode32(_pv{{.Name}}));
            _size += TagSize({{$goName}}Tags.Tag{{.Name}}, WireTypeLenDelim) + LenDelimSize(_packed{{.Name}});
{{- else if .IsSint64}}
            int _packed{{.Name}} = 0;
            foreach (var _pv{{.Name}} in {{.Name}})
                _packed{{.Name}} += VarintSize(ZigZagEncode64(_pv{{.Name}}));
            _size += TagSize({{$goName}}Tags.Tag{{.Name}}, WireTypeLenDelim) + LenDelimSize(_packed{{.Name}});
{{- else}}
            int _packed{{.Name}} = 0;
            foreach (var _pv{{.Name}} in {{.Name}})
                _packed{{.Name}} += VarintSize((ulong)_pv{{.Name}});
            _size += TagSize({{$goName}}Tags.Tag{{.Name}}, WireTypeLenDelim) + LenDelimSize(_packed{{.Name}});
{{- end}}
{{- else if .IsString}}
            foreach (var _sv{{.Name}} in {{.Name}})
            {
                int _len{{.Name}} = StringByteCount(_sv{{.Name}});
                _size += TagSize({{$goName}}Tags.Tag{{.Name}}, WireTypeLenDelim) + LenDelimSize(_len{{.Name}});
            }
{{- else if .IsBytes}}
            foreach (var _bv{{.Name}} in {{.Name}})
            {
                int _len{{.Name}} = _bv{{.Name}} != null ? _bv{{.Name}}.Length : 0;
                _size += TagSize({{$goName}}Tags.Tag{{.Name}}, WireTypeLenDelim) + LenDelimSize(_len{{.Name}});
            }
{{- else if .ElemIsMsg}}
            foreach (var _mv{{.Name}} in {{.Name}})
            {
                int _subSize{{.Name}} = _mv{{.Name}}.ProtobufSize();
                if (_subSize{{.Name}} > 0)
                    _size += TagSize({{$goName}}Tags.Tag{{.Name}}, WireTypeLenDelim) + LenDelimSize(_subSize{{.Name}});
            }
{{- else}}
            foreach (var _ev{{.Name}} in {{.Name}})
                _size += TagSize({{$goName}}Tags.Tag{{.Name}}, WireTypeVarint) + VarintSize((ulong)_ev{{.Name}});
{{- end}}
        }
{{- else if .IsMsg}}
        {
            int _subSize{{.Name}} = {{.Name}}.ProtobufSize();
            if (_subSize{{.Name}} > 0)
                _size += TagSize({{$goName}}Tags.Tag{{.Name}}, WireTypeLenDelim) + LenDelimSize(_subSize{{.Name}});
        }
{{- else if .IsString}}
        if (!string.IsNullOrEmpty({{.Name}}))
        {
            int _len{{.Name}} = StringByteCount({{.Name}});
            _size += TagSize({{$goName}}Tags.Tag{{.Name}}, WireTypeLenDelim) + LenDelimSize(_len{{.Name}});
        }
{{- else if .IsBytes}}
        if ({{.Name}} != null && {{.Name}}.Length > 0)
            _size += TagSize({{$goName}}Tags.Tag{{.Name}}, WireTypeLenDelim) + LenDelimSize({{.Name}}.Length);
{{- else if .IsBool}}
        if ({{.Name}})
            _size += TagSize({{$goName}}Tags.Tag{{.Name}}, WireTypeVarint) + 1;
{{- else if .IsFixed32}}
        if ({{.Name}} != {{csDefault .WriterType}})
            _size += TagSize({{$goName}}Tags.Tag{{.Name}}, WireType32Bit) + 4;
{{- else if .IsFixed64}}
        if ({{.Name}} != {{csDefault .WriterType}})
            _size += TagSize({{$goName}}Tags.Tag{{.Name}}, WireType64Bit) + 8;
{{- else if .IsSint32}}
        if ({{.Name}} != 0)
            _size += TagSize({{$goName}}Tags.Tag{{.Name}}, WireTypeVarint) + VarintSize(ZigZagEncode32({{.Name}}));
{{- else if .IsSint64}}
        if ({{.Name}} != 0)
            _size += TagSize({{$goName}}Tags.Tag{{.Name}}, WireTypeVarint) + VarintSize(ZigZagEncode64({{.Name}}));
{{- else if .IsEnum}}
        if ((int){{.Name}} != 0)
            _size += TagSize({{$goName}}Tags.Tag{{.Name}}, WireTypeVarint) + VarintSize((ulong)(int){{.Name}});
{{- else}}
        if ({{.Name}} != {{csDefault .WriterType}})
            _size += TagSize({{$goName}}Tags.Tag{{.Name}}, WireTypeVarint) + VarintSize((ulong){{.Name}});
{{- end}}
{{- end}}
        return _size;
    }

    // ── ToProtobuf ───────────────────────────────────────────────────────────

    public Error ToProtobuf(ref RentedBuffer buf)
    {
{{- range .Fields}}
{{- if .IsMap}}
        if ({{.Name}} != null)
        {
            foreach (var _kv{{.Name}} in {{.Name}})
            {
                WriteTag(ref buf, {{$goName}}Tags.Tag{{.Name}}, WireTypeLenDelim);
                int _entrySize{{.Name}} = 0;
{{- if eq .MapKey "string"}}
                int _klen{{.Name}} = StringByteCount(_kv{{.Name}}.Key);
                _entrySize{{.Name}} += TagSize(1, WireTypeLenDelim) + LenDelimSize(_klen{{.Name}});
{{- else if eq .MapKey "bool"}}
                _entrySize{{.Name}} += TagSize(1, WireTypeVarint) + VarintSize(_kv{{.Name}}.Key ? 1UL : 0UL);
{{- else if eq .MapKey "fixed32"}}
                _entrySize{{.Name}} += TagSize(1, WireType32Bit) + 4;
{{- else if eq .MapKey "sfixed32"}}
                _entrySize{{.Name}} += TagSize(1, WireType32Bit) + 4;
{{- else if eq .MapKey "fixed64"}}
                _entrySize{{.Name}} += TagSize(1, WireType64Bit) + 8;
{{- else if eq .MapKey "sfixed64"}}
                _entrySize{{.Name}} += TagSize(1, WireType64Bit) + 8;
{{- else if eq .MapKey "sint32"}}
                _entrySize{{.Name}} += TagSize(1, WireTypeVarint) + VarintSize(ZigZagEncode32(_kv{{.Name}}.Key));
{{- else if eq .MapKey "sint64"}}
                _entrySize{{.Name}} += TagSize(1, WireTypeVarint) + VarintSize(ZigZagEncode64(_kv{{.Name}}.Key));
{{- else}}
                _entrySize{{.Name}} += TagSize(1, WireTypeVarint) + VarintSize((ulong)_kv{{.Name}}.Key);
{{- end}}
{{- if .MapValIsMsg}}
                int _valMsgSize{{.Name}} = _kv{{.Name}}.Value.ProtobufSize();
                _entrySize{{.Name}} += TagSize(2, WireTypeLenDelim) + LenDelimSize(_valMsgSize{{.Name}});
{{- else if eq .MapVal "string"}}
                int _vlen{{.Name}} = StringByteCount(_kv{{.Name}}.Value);
                _entrySize{{.Name}} += TagSize(2, WireTypeLenDelim) + LenDelimSize(_vlen{{.Name}});
{{- else if eq .MapVal "bytes"}}
                int _vlen{{.Name}} = _kv{{.Name}}.Value != null ? _kv{{.Name}}.Value.Length : 0;
                _entrySize{{.Name}} += TagSize(2, WireTypeLenDelim) + LenDelimSize(_vlen{{.Name}});
{{- else if eq .MapVal "double"}}
                _entrySize{{.Name}} += TagSize(2, WireType64Bit) + 8;
{{- else if eq .MapVal "float"}}
                _entrySize{{.Name}} += TagSize(2, WireType32Bit) + 4;
{{- else if eq .MapVal "fixed32"}}
                _entrySize{{.Name}} += TagSize(2, WireType32Bit) + 4;
{{- else if eq .MapVal "sfixed32"}}
                _entrySize{{.Name}} += TagSize(2, WireType32Bit) + 4;
{{- else if eq .MapVal "fixed64"}}
                _entrySize{{.Name}} += TagSize(2, WireType64Bit) + 8;
{{- else if eq .MapVal "sfixed64"}}
                _entrySize{{.Name}} += TagSize(2, WireType64Bit) + 8;
{{- else if eq .MapVal "sint32"}}
                _entrySize{{.Name}} += TagSize(2, WireTypeVarint) + VarintSize(ZigZagEncode32(_kv{{.Name}}.Value));
{{- else if eq .MapVal "sint64"}}
                _entrySize{{.Name}} += TagSize(2, WireTypeVarint) + VarintSize(ZigZagEncode64(_kv{{.Name}}.Value));
{{- else if eq .MapVal "bool"}}
                _entrySize{{.Name}} += TagSize(2, WireTypeVarint) + VarintSize(_kv{{.Name}}.Value ? 1UL : 0UL);
{{- else}}
                _entrySize{{.Name}} += TagSize(2, WireTypeVarint) + VarintSize((ulong)_kv{{.Name}}.Value);
{{- end}}
                WriteVarint(ref buf, (ulong)_entrySize{{.Name}});
                // key (field 1)
{{- if eq .MapKey "string"}}
                WriteTag(ref buf, 1, WireTypeLenDelim);
                WriteString(ref buf, _kv{{.Name}}.Key);
{{- else if eq .MapKey "bool"}}
                WriteTag(ref buf, 1, WireTypeVarint);
                WriteVarint(ref buf, _kv{{.Name}}.Key ? 1UL : 0UL);
{{- else if eq .MapKey "fixed32"}}
                WriteTag(ref buf, 1, WireType32Bit);
                WriteFixed32(ref buf, _kv{{.Name}}.Key);
{{- else if eq .MapKey "sfixed32"}}
                WriteTag(ref buf, 1, WireType32Bit);
                WriteFixed32(ref buf, (uint)_kv{{.Name}}.Key);
{{- else if eq .MapKey "fixed64"}}
                WriteTag(ref buf, 1, WireType64Bit);
                WriteFixed64(ref buf, _kv{{.Name}}.Key);
{{- else if eq .MapKey "sfixed64"}}
                WriteTag(ref buf, 1, WireType64Bit);
                WriteFixed64(ref buf, (ulong)_kv{{.Name}}.Key);
{{- else if eq .MapKey "sint32"}}
                WriteTag(ref buf, 1, WireTypeVarint);
                WriteVarint(ref buf, ZigZagEncode32(_kv{{.Name}}.Key));
{{- else if eq .MapKey "sint64"}}
                WriteTag(ref buf, 1, WireTypeVarint);
                WriteVarint(ref buf, ZigZagEncode64(_kv{{.Name}}.Key));
{{- else}}
                WriteTag(ref buf, 1, WireTypeVarint);
                WriteVarint(ref buf, (ulong)_kv{{.Name}}.Key);
{{- end}}
                // value (field 2)
{{- if .MapValIsMsg}}
                WriteTag(ref buf, 2, WireTypeLenDelim);
                WriteVarint(ref buf, (ulong)_valMsgSize{{.Name}});
                _kv{{.Name}}.Value.ToProtobuf(ref buf);
{{- else if eq .MapVal "string"}}
                WriteTag(ref buf, 2, WireTypeLenDelim);
                WriteString(ref buf, _kv{{.Name}}.Value);
{{- else if eq .MapVal "bytes"}}
                WriteTag(ref buf, 2, WireTypeLenDelim);
                WriteBytes(ref buf, _kv{{.Name}}.Value);
{{- else if eq .MapVal "double"}}
                WriteTag(ref buf, 2, WireType64Bit);
                WriteFixed64(ref buf, BitConverter.DoubleToUInt64Bits(_kv{{.Name}}.Value));
{{- else if eq .MapVal "float"}}
                WriteTag(ref buf, 2, WireType32Bit);
                WriteFixed32(ref buf, BitConverter.SingleToUInt32Bits(_kv{{.Name}}.Value));
{{- else if eq .MapVal "fixed32"}}
                WriteTag(ref buf, 2, WireType32Bit);
                WriteFixed32(ref buf, _kv{{.Name}}.Value);
{{- else if eq .MapVal "sfixed32"}}
                WriteTag(ref buf, 2, WireType32Bit);
                WriteFixed32(ref buf, (uint)_kv{{.Name}}.Value);
{{- else if eq .MapVal "fixed64"}}
                WriteTag(ref buf, 2, WireType64Bit);
                WriteFixed64(ref buf, _kv{{.Name}}.Value);
{{- else if eq .MapVal "sfixed64"}}
                WriteTag(ref buf, 2, WireType64Bit);
                WriteFixed64(ref buf, (ulong)_kv{{.Name}}.Value);
{{- else if eq .MapVal "sint32"}}
                WriteTag(ref buf, 2, WireTypeVarint);
                WriteVarint(ref buf, ZigZagEncode32(_kv{{.Name}}.Value));
{{- else if eq .MapVal "sint64"}}
                WriteTag(ref buf, 2, WireTypeVarint);
                WriteVarint(ref buf, ZigZagEncode64(_kv{{.Name}}.Value));
{{- else if eq .MapVal "bool"}}
                WriteTag(ref buf, 2, WireTypeVarint);
                WriteVarint(ref buf, _kv{{.Name}}.Value ? 1UL : 0UL);
{{- else}}
                WriteTag(ref buf, 2, WireTypeVarint);
                WriteVarint(ref buf, (ulong)_kv{{.Name}}.Value);
{{- end}}
            }
        }
{{- else if .IsRepeated}}
        if ({{.Name}} != null && {{.Name}}.Count > 0)
        {
{{- if .IsPackable}}
{{- if .IsFixed32}}
            WriteTag(ref buf, {{$goName}}Tags.Tag{{.Name}}, WireTypeLenDelim);
            WriteVarint(ref buf, (ulong)({{.Name}}.Count * 4));
            foreach (var _pv{{.Name}} in {{.Name}})
                WriteFixed32(ref buf, {{if eq .Type "float"}}BitConverter.SingleToUInt32Bits(_pv{{.Name}}){{else if eq .Type "sfixed32"}}(uint)_pv{{.Name}}{{else}}_pv{{.Name}}{{end}});
{{- else if .IsFixed64}}
            WriteTag(ref buf, {{$goName}}Tags.Tag{{.Name}}, WireTypeLenDelim);
            WriteVarint(ref buf, (ulong)({{.Name}}.Count * 8));
            foreach (var _pv{{.Name}} in {{.Name}})
                WriteFixed64(ref buf, {{if eq .Type "double"}}BitConverter.DoubleToUInt64Bits(_pv{{.Name}}){{else if eq .Type "sfixed64"}}(ulong)_pv{{.Name}}{{else}}_pv{{.Name}}{{end}});
{{- else if .IsBool}}
            WriteTag(ref buf, {{$goName}}Tags.Tag{{.Name}}, WireTypeLenDelim);
            WriteVarint(ref buf, (ulong){{.Name}}.Count);
            foreach (var _pv{{.Name}} in {{.Name}})
                WriteVarint(ref buf, _pv{{.Name}} ? 1UL : 0UL);
{{- else if .IsSint32}}
            int _len{{.Name}} = 0;
            foreach (var _pv{{.Name}} in {{.Name}})
            { ulong _zv{{.Name}} = ZigZagEncode32(_pv{{.Name}}); do { _len{{.Name}}++; _zv{{.Name}} >>= 7; } while (_zv{{.Name}} != 0); }
            WriteTag(ref buf, {{$goName}}Tags.Tag{{.Name}}, WireTypeLenDelim);
            WriteVarint(ref buf, (ulong)_len{{.Name}});
            foreach (var _pv{{.Name}} in {{.Name}})
                WriteVarint(ref buf, ZigZagEncode32(_pv{{.Name}}));
{{- else if .IsSint64}}
            int _len{{.Name}} = 0;
            foreach (var _pv{{.Name}} in {{.Name}})
            { ulong _zv{{.Name}} = ZigZagEncode64(_pv{{.Name}}); do { _len{{.Name}}++; _zv{{.Name}} >>= 7; } while (_zv{{.Name}} != 0); }
            WriteTag(ref buf, {{$goName}}Tags.Tag{{.Name}}, WireTypeLenDelim);
            WriteVarint(ref buf, (ulong)_len{{.Name}});
            foreach (var _pv{{.Name}} in {{.Name}})
                WriteVarint(ref buf, ZigZagEncode64(_pv{{.Name}}));
{{- else}}
            int _len{{.Name}} = 0;
            foreach (var _pv{{.Name}} in {{.Name}})
            { ulong _vv{{.Name}} = (ulong)_pv{{.Name}}; do { _len{{.Name}}++; _vv{{.Name}} >>= 7; } while (_vv{{.Name}} != 0); }
            WriteTag(ref buf, {{$goName}}Tags.Tag{{.Name}}, WireTypeLenDelim);
            WriteVarint(ref buf, (ulong)_len{{.Name}});
            foreach (var _pv{{.Name}} in {{.Name}})
                WriteVarint(ref buf, (ulong)_pv{{.Name}});
{{- end}}
{{- else if .IsString}}
            foreach (var _sv{{.Name}} in {{.Name}})
            {
                WriteTag(ref buf, {{$goName}}Tags.Tag{{.Name}}, WireTypeLenDelim);
                WriteString(ref buf, _sv{{.Name}} ?? string.Empty);
            }
{{- else if .IsBytes}}
            foreach (var _bv{{.Name}} in {{.Name}})
            {
                WriteTag(ref buf, {{$goName}}Tags.Tag{{.Name}}, WireTypeLenDelim);
                WriteBytes(ref buf, _bv{{.Name}});
            }
{{- else if .ElemIsMsg}}
            foreach (var _mv{{.Name}} in {{.Name}})
            {
                var _msub{{.Name}} = new RentedBuffer(64);
                _mv{{.Name}}.ToProtobuf(ref _msub{{.Name}});
                WriteTag(ref buf, {{$goName}}Tags.Tag{{.Name}}, WireTypeLenDelim);
                WriteBytes(ref buf, _msub{{.Name}}.AsSpan());
                _msub{{.Name}}.Dispose();
            }
{{- else}}
            foreach (var _ev{{.Name}} in {{.Name}})
            {
                WriteTag(ref buf, {{$goName}}Tags.Tag{{.Name}}, WireTypeVarint);
                WriteVarint(ref buf, (ulong)_ev{{.Name}});
            }
{{- end}}
        }
{{- else if .IsMsg}}
        {
            var _msub{{.Name}} = new RentedBuffer(64);
            {{.Name}}.ToProtobuf(ref _msub{{.Name}});
            if (_msub{{.Name}}.Length > 0)
            {
                WriteTag(ref buf, {{$goName}}Tags.Tag{{.Name}}, WireTypeLenDelim);
                WriteBytes(ref buf, _msub{{.Name}}.AsSpan());
            }
            _msub{{.Name}}.Dispose();
        }
{{- else if .IsString}}
        if (!string.IsNullOrEmpty({{.Name}}))
        {
            WriteTag(ref buf, {{$goName}}Tags.Tag{{.Name}}, WireTypeLenDelim);
            WriteString(ref buf, {{.Name}});
        }
{{- else if .IsBytes}}
        if ({{.Name}} != null && {{.Name}}.Length > 0)
        {
            WriteTag(ref buf, {{$goName}}Tags.Tag{{.Name}}, WireTypeLenDelim);
            WriteBytes(ref buf, {{.Name}});
        }
{{- else if .IsBool}}
        if ({{.Name}})
        {
            WriteTag(ref buf, {{$goName}}Tags.Tag{{.Name}}, WireTypeVarint);
            WriteVarint(ref buf, 1UL);
        }
{{- else if .IsFixed32}}
        if ({{.Name}} != {{csDefault .WriterType}})
        {
            WriteTag(ref buf, {{$goName}}Tags.Tag{{.Name}}, WireType32Bit);
{{- if eq .Type "float"}}
            WriteFixed32(ref buf, BitConverter.SingleToUInt32Bits({{.Name}}));
{{- else if eq .Type "sfixed32"}}
            WriteFixed32(ref buf, (uint){{.Name}});
{{- else}}
            WriteFixed32(ref buf, {{.Name}});
{{- end}}
        }
{{- else if .IsFixed64}}
        if ({{.Name}} != {{csDefault .WriterType}})
        {
            WriteTag(ref buf, {{$goName}}Tags.Tag{{.Name}}, WireType64Bit);
{{- if eq .Type "double"}}
            WriteFixed64(ref buf, BitConverter.DoubleToUInt64Bits({{.Name}}));
{{- else if eq .Type "sfixed64"}}
            WriteFixed64(ref buf, (ulong){{.Name}});
{{- else}}
            WriteFixed64(ref buf, {{.Name}});
{{- end}}
        }
{{- else if .IsSint32}}
        if ({{.Name}} != 0)
        {
            WriteTag(ref buf, {{$goName}}Tags.Tag{{.Name}}, WireTypeVarint);
            WriteVarint(ref buf, ZigZagEncode32({{.Name}}));
        }
{{- else if .IsSint64}}
        if ({{.Name}} != 0)
        {
            WriteTag(ref buf, {{$goName}}Tags.Tag{{.Name}}, WireTypeVarint);
            WriteVarint(ref buf, ZigZagEncode64({{.Name}}));
        }
{{- else if .IsEnum}}
        if ((int){{.Name}} != 0)
        {
            WriteTag(ref buf, {{$goName}}Tags.Tag{{.Name}}, WireTypeVarint);
            WriteVarint(ref buf, (ulong)(int){{.Name}});
        }
{{- else}}
        if ({{.Name}} != {{csDefault .WriterType}})
        {
            WriteTag(ref buf, {{$goName}}Tags.Tag{{.Name}}, WireTypeVarint);
            WriteVarint(ref buf, (ulong){{.Name}});
        }
{{- end}}
{{- end}}
        return default;
    }

    // ── ToJSON ───────────────────────────────────────────────────────────────

    public void ToJSON(ref RentedBuffer buf)
    {
        buf.Append((byte)'{');
        bool _first = true;
{{- range .Fields}}
{{- if .IsMap}}
        if ({{.Name}} != null && {{.Name}}.Count > 0)
        {
            if (!_first) buf.Append((byte)','); _first = false;
            buf.Append((byte)'"'); buf.Append({{$goName}}Tags.JsonKey{{.Name}}); buf.Append("\":{"u8);
            bool _mfirst{{.Name}} = true;
            foreach (var _kv{{.Name}} in {{.Name}})
            {
                if (!_mfirst{{.Name}}) buf.Append((byte)','); _mfirst{{.Name}} = false;
                buf.Append((byte)'"');
{{- if eq .MapKeyCS "string"}}
                buf.AppendAsJsonEscapedString(_kv{{.Name}}.Key);
{{- else if eq .MapKeyCS "bool"}}
                buf.Append(_kv{{.Name}}.Key ? "true"u8 : "false"u8);
{{- else}}
                buf.Append((long)_kv{{.Name}}.Key);
{{- end}}
                buf.Append((byte)'"'); buf.Append((byte)':');
{{- if .MapValIsMsg}}
                _kv{{.Name}}.Value.ToJSON(ref buf);
{{- else if eq .MapVal "string"}}
                buf.Append((byte)'"'); buf.AppendAsJsonEscapedString(_kv{{.Name}}.Value); buf.Append((byte)'"');
{{- else if eq .MapVal "bytes"}}
                buf.Append((byte)'"'); buf.Append(Convert.ToBase64String(_kv{{.Name}}.Value)); buf.Append((byte)'"');
{{- else if eq .MapVal "bool"}}
                buf.Append(_kv{{.Name}}.Value);
{{- else if eq .MapVal "double"}}
                buf.Append(_kv{{.Name}}.Value);
{{- else if eq .MapVal "float"}}
                buf.Append((double)_kv{{.Name}}.Value);
{{- else if eq .MapVal "int64"}}
                buf.Append((byte)'"'); buf.Append((long)_kv{{.Name}}.Value); buf.Append((byte)'"');
{{- else if eq .MapVal "uint64"}}
                buf.Append((byte)'"'); buf.Append(_kv{{.Name}}.Value); buf.Append((byte)'"');
{{- else if eq .MapVal "sint64"}}
                buf.Append((byte)'"'); buf.Append((long)_kv{{.Name}}.Value); buf.Append((byte)'"');
{{- else if eq .MapVal "sfixed64"}}
                buf.Append((byte)'"'); buf.Append((long)_kv{{.Name}}.Value); buf.Append((byte)'"');
{{- else if eq .MapVal "fixed64"}}
                buf.Append((byte)'"'); buf.Append(_kv{{.Name}}.Value); buf.Append((byte)'"');
{{- else}}
                buf.Append((long)_kv{{.Name}}.Value);
{{- end}}
            }
            buf.Append((byte)'}');
        }
{{- else if .IsRepeated}}
        if ({{.Name}} != null && {{.Name}}.Count > 0)
        {
            if (!_first) buf.Append((byte)','); _first = false;
            buf.Append((byte)'"'); buf.Append({{$goName}}Tags.JsonKey{{.Name}}); buf.Append("\":["u8);
            for (int _i{{.Name}} = 0; _i{{.Name}} < {{.Name}}.Count; _i{{.Name}}++)
            {
                if (_i{{.Name}} > 0) buf.Append((byte)',');
                var _re{{.Name}} = {{.Name}}[_i{{.Name}}];
{{- if .ElemIsMsg}}
                _re{{.Name}}.ToJSON(ref buf);
{{- else if .IsString}}
                buf.Append((byte)'"'); buf.AppendAsJsonEscapedString(_re{{.Name}}); buf.Append((byte)'"');
{{- else if .IsBytes}}
                buf.Append((byte)'"'); buf.Append(Convert.ToBase64String(_re{{.Name}})); buf.Append((byte)'"');
{{- else if .IsBool}}
                buf.Append(_re{{.Name}});
{{- else if .IsFixed64}}
                buf.Append((byte)'"'); buf.Append((long)_re{{.Name}}); buf.Append((byte)'"');
{{- else if eq .ElemTypeCS "double"}}
                buf.Append(_re{{.Name}});
{{- else if eq .ElemTypeCS "float"}}
                buf.Append((double)_re{{.Name}});
{{- else if eq .ElemTypeCS "long"}}
                buf.Append((byte)'"'); buf.Append(_re{{.Name}}); buf.Append((byte)'"');
{{- else if eq .ElemTypeCS "ulong"}}
                buf.Append((byte)'"'); buf.Append(_re{{.Name}}); buf.Append((byte)'"');
{{- else}}
                buf.Append((long)_re{{.Name}});
{{- end}}
            }
            buf.Append((byte)']');
        }
{{- else if .IsMsg}}
        {
            if (!_first) buf.Append((byte)','); _first = false;
            buf.Append((byte)'"'); buf.Append({{$goName}}Tags.JsonKey{{.Name}}); buf.Append("\":"u8);
            {{.Name}}.ToJSON(ref buf);
        }
{{- else if .IsString}}
        if (!string.IsNullOrEmpty({{.Name}}))
        {
            if (!_first) buf.Append((byte)','); _first = false;
            buf.Append((byte)'"'); buf.Append({{$goName}}Tags.JsonKey{{.Name}}); buf.Append("\":\""u8);
            buf.AppendAsJsonEscapedString({{.Name}});
            buf.Append((byte)'"');
        }
{{- else if .IsBytes}}
        if ({{.Name}} != null && {{.Name}}.Length > 0)
        {
            if (!_first) buf.Append((byte)','); _first = false;
            buf.Append((byte)'"'); buf.Append({{$goName}}Tags.JsonKey{{.Name}}); buf.Append("\":\""u8);
            buf.Append(Convert.ToBase64String({{.Name}}));
            buf.Append((byte)'"');
        }
{{- else if .IsBool}}
        if ({{.Name}})
        {
            if (!_first) buf.Append((byte)','); _first = false;
            buf.Append((byte)'"'); buf.Append({{$goName}}Tags.JsonKey{{.Name}}); buf.Append("\":true"u8);
        }
{{- else if .IsEnum}}
        if ((int){{.Name}} != 0)
        {
            if (!_first) buf.Append((byte)','); _first = false;
            buf.Append((byte)'"'); buf.Append({{$goName}}Tags.JsonKey{{.Name}}); buf.Append("\":"u8);
            buf.Append((long)(int){{.Name}});
        }
{{- else if eq .WriterType "double"}}
        if ({{.Name}} != 0.0)
        {
            if (!_first) buf.Append((byte)','); _first = false;
            buf.Append((byte)'"'); buf.Append({{$goName}}Tags.JsonKey{{.Name}}); buf.Append("\":"u8);
            buf.Append({{.Name}});
        }
{{- else if eq .WriterType "float"}}
        if ({{.Name}} != 0.0f)
        {
            if (!_first) buf.Append((byte)','); _first = false;
            buf.Append((byte)'"'); buf.Append({{$goName}}Tags.JsonKey{{.Name}}); buf.Append("\":"u8);
            buf.Append((double){{.Name}});
        }
{{- else if .IsFixed64}}
        if ({{.Name}} != {{csDefault .WriterType}})
        {
            if (!_first) buf.Append((byte)','); _first = false;
            buf.Append((byte)'"'); buf.Append({{$goName}}Tags.JsonKey{{.Name}}); buf.Append("\":\""u8);
            buf.Append((long){{.Name}});
            buf.Append((byte)'"');
        }
{{- else if eq .WriterType "long"}}
        if ({{.Name}} != 0)
        {
            if (!_first) buf.Append((byte)','); _first = false;
            buf.Append((byte)'"'); buf.Append({{$goName}}Tags.JsonKey{{.Name}}); buf.Append("\":\""u8);
            buf.Append({{.Name}});
            buf.Append((byte)'"');
        }
{{- else if eq .WriterType "ulong"}}
        if ({{.Name}} != 0)
        {
            if (!_first) buf.Append((byte)','); _first = false;
            buf.Append((byte)'"'); buf.Append({{$goName}}Tags.JsonKey{{.Name}}); buf.Append("\":\""u8);
            buf.Append({{.Name}});
            buf.Append((byte)'"');
        }
{{- else}}
        if ({{.Name}} != {{csDefault .WriterType}})
        {
            if (!_first) buf.Append((byte)','); _first = false;
            buf.Append((byte)'"'); buf.Append({{$goName}}Tags.JsonKey{{.Name}}); buf.Append("\":"u8);
            buf.Append((long){{.Name}});
        }
{{- end}}
{{- end}}
        buf.Append((byte)'}');
    }

    // ── Reset ─────────────────────────────────────────────────────────────────

    public void Reset()
    {
{{- range .Fields}}
{{- if .IsMap}}
        {{.Name}}?.Clear();
{{- else if .IsRepeated}}
        {{.Name}}?.Clear();
{{- else if .IsMsg}}
        {{.Name}}.Reset();
{{- else if .IsString}}
        {{.Name}} = string.Empty;
{{- else}}
        {{.Name}} = {{csDefault .WriterType}};
{{- end}}
{{- end}}
    }
}
{{end}}
