// Code generated by https://github.com/ahfuzhang/BaoHuLu. DO NOT EDIT.

#pragma warning disable CS8600, CS8602, CS8618

using System;
using System.Collections.Generic;
using QiWa.Common;
using Xunit;
using {{.Namespace}};

namespace {{.Namespace}}.Tests;
{{range .Messages}}
{{- $goName := .GoName}}
{{- $roName := printf "Readonly%s" .GoName}}

// ── {{$goName}} ───────────────────────────────────────────────────────────────

public class {{$goName}}Tests
{
    /// <summary>Returns a pre-filled {{$goName}} instance for use in tests.</summary>
    public static {{$goName}} MakeSample{{$goName}}()
    {
        return new {{$goName}}
        {
{{range .Fields}}            {{.Name}} = {{csSampleLit .}},
{{end}}        };
    }

    // ── Empty ─────────────────────────────────────────────────────────────────

    [Fact]
    public void Empty_ProtobufSize_IsZero()
    {
        var m = new {{$goName}}();
        Assert.Equal(0, m.ProtobufSize());
    }

    [Fact]
    public void Empty_ToProtobuf_WritesNothing()
    {
        var m = new {{$goName}}();
        var buf = new RentedBuffer(16);
        m.ToProtobuf(ref buf);
        Assert.Equal(0, buf.Length);
        buf.Dispose();
    }

    // ── Protobuf roundtrip ────────────────────────────────────────────────────

    // Verifies that serialising a populated {{$goName}} and deserialising it
    // into a Readonly{{$goName}}, then cloning back to a writer, produces byte-identical
    // protobuf output (lossless roundtrip).
    [Fact]
    public void ProtobufRoundtrip()
    {
        var w = MakeSample{{$goName}}();
        int sz = w.ProtobufSize();
        var buf = new RentedBuffer(sz + 4);
        w.ToProtobuf(ref buf);
        Assert.Equal(sz, buf.Length);

        var r = new {{$roName}}();
        var err = r.FromProtobuf(buf.AsSpan());
        Assert.False(err.Err());

        var w2 = r.Clone();
        var buf2 = new RentedBuffer(w2.ProtobufSize() + 4);
        w2.ToProtobuf(ref buf2);

        Assert.Equal(buf.AsSpan().ToArray(), buf2.AsSpan().ToArray());
        buf.Dispose();
        buf2.Dispose();
    }

    // ── JSON roundtrip ────────────────────────────────────────────────────────

    // Verifies that ToJSON → FromJSON → Clone produces byte-identical JSON output.
    [Fact]
    public void JSONRoundtrip()
    {
        var w = MakeSample{{$goName}}();
        var jBuf = new RentedBuffer(256);
        w.ToJSON(ref jBuf);
        var json = jBuf.AsSpan().ToArray();

        var r = new {{$roName}}();
        var err = r.FromJSON(json);
        Assert.False(err.Err());

        var w2 = r.Clone();
        var jBuf2 = new RentedBuffer(256);
        w2.ToJSON(ref jBuf2);

        Assert.Equal(json, jBuf2.AsSpan().ToArray());
        jBuf.Dispose();
        jBuf2.Dispose();
    }

    // ── Reset ─────────────────────────────────────────────────────────────────

    [Fact]
    public void Reset_ClearsAllFields()
    {
        var w = MakeSample{{$goName}}();
        w.Reset();
        Assert.Equal(0, w.ProtobufSize());
    }

    [Fact]
    public void Readonly_Reset_Succeeds()
    {
        var w = MakeSample{{$goName}}();
        var buf = new RentedBuffer(w.ProtobufSize() + 4);
        w.ToProtobuf(ref buf);
        var r = new {{$roName}}();
        r.FromProtobuf(buf.AsSpan());
        r.Reset();
        buf.Dispose();
    }

    // ── Clone ─────────────────────────────────────────────────────────────────

    [Fact]
    public void Clone_PreservesData()
    {
        var w = MakeSample{{$goName}}();
        var buf = new RentedBuffer(w.ProtobufSize() + 4);
        w.ToProtobuf(ref buf);
        var r = new {{$roName}}();
        Assert.False(r.FromProtobuf(buf.AsSpan()).Err());
        var w2 = r.Clone();
        var buf2 = new RentedBuffer(w2.ProtobufSize() + 4);
        w2.ToProtobuf(ref buf2);
        Assert.Equal(buf.AsSpan().ToArray(), buf2.AsSpan().ToArray());
        buf.Dispose();
        buf2.Dispose();
    }

    // ── FromProtobuf error / edge cases ──────────────────────────────────────

    [Fact]
    public void FromProtobuf_EmptyInput_Succeeds()
    {
        var r = new {{$roName}}();
        Assert.False(r.FromProtobuf(ReadOnlySpan<byte>.Empty).Err());
        Assert.False(r.FromProtobuf(Array.Empty<byte>()).Err());
    }

    // field 100, wire-type 0, value 1
    //   tag  = (100 << 3) | 0 = 800 → varint [0xA0, 0x06]
    //   value = varint(1)             → [0x01]
    [Fact]
    public void FromProtobuf_UnknownVarintField_Ignored()
    {
        var unknown = new byte[] { 0xA0, 0x06, 0x01 };
        var r = new {{$roName}}();
        Assert.False(r.FromProtobuf(unknown).Err());
    }

    // Single-byte truncated multi-byte varint (high bit set, no continuation byte).
    [Fact]
    public void FromProtobuf_BadTag_ReturnsError()
    {
        var bad = new byte[] { 0x80 };
        var r = new {{$roName}}();
        Assert.True(r.FromProtobuf(bad).Err());
    }

    // field 100, wire-type 2, claims 100 bytes but provides none.
    //   tag    = (100 << 3) | 2 = 802 → varint [0xA2, 0x06]
    //   length = varint(100)           → [0x64]
    [Fact]
    public void FromProtobuf_TruncatedLenDelim_ReturnsError()
    {
        var bad = new byte[] { 0xA2, 0x06, 0x64 };
        var r = new {{$roName}}();
        Assert.True(r.FromProtobuf(bad).Err());
    }

    // ── FromJSON error cases ──────────────────────────────────────────────────

    [Fact]
    public void FromJSON_InvalidInput_ReturnsError()
    {
        var r = new {{$roName}}();
        Assert.True(r.FromJSON(System.Text.Encoding.UTF8.GetBytes("not-json")).Err());
        Assert.True(r.FromJSON(System.Text.Encoding.UTF8.GetBytes("[1,2,3]")).Err());
    }
{{- $strf := firstCsStringField .Fields}}
{{if $strf}}
    // Verifies that strings containing special escape characters (\n newline,
    // \t tab, \" double-quote, \\ backslash) survive both a protobuf roundtrip
    // and a JSON roundtrip without mangling.
    // Field under test: {{$strf.Name}} (string)
    [Fact]
    public void StringEscapes_RoundtripPreservesEscapes()
    {
        const string escStr = "hello\nworld\ttab\"quote\\backslash";
        var w = new {{$goName}} { {{$strf.Name}} = escStr };

        // Protobuf roundtrip
        var buf = new RentedBuffer(w.ProtobufSize() + 4);
        w.ToProtobuf(ref buf);
        var r = new {{$roName}}();
        Assert.False(r.FromProtobuf(buf.AsSpan()).Err());
        var w2 = r.Clone();
        Assert.Equal(escStr, w2.{{$strf.Name}});

        // JSON roundtrip
        var jBuf = new RentedBuffer(256);
        w.ToJSON(ref jBuf);
        var json = jBuf.AsSpan().ToArray();
        var r2 = new {{$roName}}();
        Assert.False(r2.FromJSON(json).Err());
        var w3 = r2.Clone();
        Assert.Equal(escStr, w3.{{$strf.Name}});

        buf.Dispose();
        jBuf.Dispose();
    }
{{end -}}
}
{{end}}
