{{- define "CsYamlFileHeader"}}// Code generated by https://github.com/ahfuzhang/BaoHuLu. DO NOT EDIT.
// source: {{.Namespace}}

#pragma warning disable CS8321, CS8600, CS8601, CS8602, CS8618, CS8625

using System;
using System.Buffers;
using System.Buffers.Text;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using QiWa.Common;

namespace {{.Namespace}};
{{end}}
{{- define "CsYamlWriterFile"}}{{template "CsYamlFileHeader" .}}
{{- with .Msg}}
{{- $goName := .GoName}}
{{- $msgCmtNums := .CommentLineNums}}
{{$hasYamlNames := false}}
{{- range .Fields}}{{if .YamlName}}{{$hasYamlNames = true}}{{end}}{{end -}}
{{- if $hasYamlNames}}
// yaml key constants for {{$goName}}.
internal static class _{{$goName}}_YamlKeys
{
{{- range .Fields}}
    internal const string {{.Name}} = "{{yamlKey .}}";
{{- end}}
}
{{end}}
{{- if hasAnyCsYamlComments .}}
// yaml comment constants for {{$goName}}.
internal static class _{{$goName}}_YamlComments
{
{{- range $i, $line := .Comment}}
{{- if gt (index $msgCmtNums $i) 0}}
    internal static ReadOnlySpan<byte> Line{{index $msgCmtNums $i}} => {{printf "%q" (printf "%s\n" $line)}}u8;
{{- end}}
{{- end}}
{{- range .Fields}}
{{- $f := .}}
{{- range $i, $line := .Comment}}
{{- if gt (index $f.CommentLineNums $i) 0}}
    internal static ReadOnlySpan<byte> Line{{index $f.CommentLineNums $i}} => {{printf "%q" (printf "%s\n" $line)}}u8;
{{- end}}
{{- end}}
{{- if gt .InlineCommentLineNum 0}}
    internal static ReadOnlySpan<byte> Line{{.InlineCommentLineNum}} => {{printf "%q" (printf "%s\n" .InlineComment)}}u8;
{{- end}}
{{- end}}
}
{{- end}}
// ============================================================================
// {{$goName}} — ToYAML serialization
// ============================================================================

public partial struct {{$goName}}
{
    public readonly void ToYAML(ref RentedBuffer _dst, int _indent)
    {
        string _sp = _indent > 0 ? new string(' ', _indent) : string.Empty;
        string _sp2 = new string(' ', _indent + 2);
        string _strVal(string s)
        {
            if (string.IsNullOrEmpty(s)) return s;
            foreach (char _c in s)
                if (_c < 0x20 || _c == ':' || _c == '#' || _c == '"' || _c == '\'' || _c == '\\' ||
                    _c == '{' || _c == '}' || _c == '[' || _c == ']')
                    return "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"")
                        .Replace("\n", "\\n").Replace("\r", "\\r").Replace("\t", "\\t") + "\"";
            return s;
        }
{{- range $i, $line := .Comment}}
        _dst.Append(_sp); _dst.Append("#"); _dst.Append({{csYamlCommentExpr $goName $msgCmtNums $i $line}});
{{- end}}
{{range .Fields}}
{{- $cmt := .Comment}}
{{- $cmtNums := .CommentLineNums}}
{{- if .IsMap}}
        if (this.{{.Name}} != null && this.{{.Name}}.Count > 0)
        {
{{- range $i, $line := $cmt}}
            _dst.Append(_sp); _dst.Append("#"); _dst.Append({{csYamlCommentExpr $goName $cmtNums $i $line}});
{{- end}}
{{- if gt .InlineCommentLineNum 0}}
            _dst.Append(_sp); _dst.Append({{if $hasYamlNames}}_{{$goName}}_YamlKeys.{{.Name}} + ":  "{{else}}"{{yamlKey .}}:  "{{end}}); _dst.Append("#"); _dst.Append({{csYamlInlineCommentExpr $goName .}});
{{- else}}
            _dst.Append(_sp); _dst.Append({{if $hasYamlNames}}_{{$goName}}_YamlKeys.{{.Name}} + ":\n"{{else}}"{{yamlKey .}}:\n"{{end}});
{{- end}}
            foreach (var _kv{{.Name}} in this.{{.Name}})
            {
                _dst.Append(_sp2);
{{- if eq .MapKeyCS "string"}}
                _dst.Append(_strVal(_kv{{.Name}}.Key ?? string.Empty));
{{- else if eq .MapKeyCS "bool"}}
                _dst.Append(_kv{{.Name}}.Key ? "true" : "false");
{{- else}}
                _dst.Append(_kv{{.Name}}.Key.ToString());
{{- end}}
                _dst.Append(": ");
{{- if .MapValIsMsg}}
                _dst.Append("\n");
{{- if .UseMapValWrapper}}
                if (_kv{{.Name}}.Value != null) _kv{{.Name}}.Value.Value.ToYAML(ref _dst, _indent + 4);
{{- else}}
                _kv{{.Name}}.Value.ToYAML(ref _dst, _indent + 4);
{{- end}}
{{- else if eq .MapVal "string"}}
                _dst.Append(_strVal(_kv{{.Name}}.Value ?? string.Empty)); _dst.Append("\n");
{{- else if eq .MapVal "bytes"}}
                _dst.Append(Convert.ToBase64String(_kv{{.Name}}.Value ?? Array.Empty<byte>())); _dst.Append("\n");
{{- else if eq .MapVal "bool"}}
                _dst.Append(_kv{{.Name}}.Value ? "true" : "false"); _dst.Append("\n");
{{- else if eq .MapVal "double"}}
                _dst.Append(_kv{{.Name}}.Value.ToString("R", CultureInfo.InvariantCulture)); _dst.Append("\n");
{{- else if eq .MapVal "float"}}
                _dst.Append(_kv{{.Name}}.Value.ToString("R", CultureInfo.InvariantCulture)); _dst.Append("\n");
{{- else if .MapValIsEnum}}
                _dst.Append(((int)_kv{{.Name}}.Value).ToString()); _dst.Append("\n");
{{- else}}
                _dst.Append(_kv{{.Name}}.Value.ToString()); _dst.Append("\n");
{{- end}}
            }
        }
{{- else if .IsRepeated}}
        if (this.{{.Name}} != null && this.{{.Name}}.Count > 0)
        {
{{- range $i, $line := $cmt}}
            _dst.Append(_sp); _dst.Append("#"); _dst.Append({{csYamlCommentExpr $goName $cmtNums $i $line}});
{{- end}}
{{- if gt .InlineCommentLineNum 0}}
            _dst.Append(_sp); _dst.Append({{if $hasYamlNames}}_{{$goName}}_YamlKeys.{{.Name}} + ":  "{{else}}"{{yamlKey .}}:  "{{end}}); _dst.Append("#"); _dst.Append({{csYamlInlineCommentExpr $goName .}});
{{- else}}
            _dst.Append(_sp); _dst.Append({{if $hasYamlNames}}_{{$goName}}_YamlKeys.{{.Name}} + ":\n"{{else}}"{{yamlKey .}}:\n"{{end}});
{{- end}}
            foreach (var _v{{.Name}} in this.{{.Name}})
            {
                _dst.Append(_sp2); _dst.Append("- ");
{{- if .ElemIsMsg}}
                _dst.Append("\n");
                _v{{.Name}}.ToYAML(ref _dst, _indent + 4);
{{- else if eq .Type "string"}}
                _dst.Append(_strVal(_v{{.Name}} ?? string.Empty)); _dst.Append("\n");
{{- else if eq .Type "bytes"}}
                _dst.Append(Convert.ToBase64String(_v{{.Name}} ?? Array.Empty<byte>())); _dst.Append("\n");
{{- else if eq .Type "bool"}}
                _dst.Append(_v{{.Name}} ? "true" : "false"); _dst.Append("\n");
{{- else if eq .Type "double"}}
                _dst.Append(_v{{.Name}}.ToString("R", CultureInfo.InvariantCulture)); _dst.Append("\n");
{{- else if eq .Type "float"}}
                _dst.Append(_v{{.Name}}.ToString("R", CultureInfo.InvariantCulture)); _dst.Append("\n");
{{- else}}
                _dst.Append(_v{{.Name}}.ToString()); _dst.Append("\n");
{{- end}}
            }
        }
{{- else if .IsMsg}}
{{- if .UseDirectWrapper}}
        if (this.{{.Name}} != null)
        {
{{- range $i, $line := $cmt}}
            _dst.Append(_sp); _dst.Append("#"); _dst.Append({{csYamlCommentExpr $goName $cmtNums $i $line}});
{{- end}}
{{- if gt .InlineCommentLineNum 0}}
            _dst.Append(_sp); _dst.Append({{if $hasYamlNames}}_{{$goName}}_YamlKeys.{{.Name}} + ":  "{{else}}"{{yamlKey .}}:  "{{end}}); _dst.Append("#"); _dst.Append({{csYamlInlineCommentExpr $goName .}});
{{- else}}
            _dst.Append(_sp); _dst.Append({{if $hasYamlNames}}_{{$goName}}_YamlKeys.{{.Name}} + ":\n"{{else}}"{{yamlKey .}}:\n"{{end}});
{{- end}}
            this.{{.Name}}.Value.ToYAML(ref _dst, _indent + 2);
        }
{{- else}}
        {
            int _mark{{.Name}} = _dst.Length;
{{- range $i, $line := $cmt}}
            _dst.Append(_sp); _dst.Append("#"); _dst.Append({{csYamlCommentExpr $goName $cmtNums $i $line}});
{{- end}}
{{- if gt .InlineCommentLineNum 0}}
            _dst.Append(_sp); _dst.Append({{if $hasYamlNames}}_{{$goName}}_YamlKeys.{{.Name}} + ":  "{{else}}"{{yamlKey .}}:  "{{end}}); _dst.Append("#"); _dst.Append({{csYamlInlineCommentExpr $goName .}});
{{- else}}
            _dst.Append(_sp); _dst.Append({{if $hasYamlNames}}_{{$goName}}_YamlKeys.{{.Name}} + ":\n"{{else}}"{{yamlKey .}}:\n"{{end}});
{{- end}}
            int _hdr{{.Name}} = _dst.Length;
            this.{{.Name}}.ToYAML(ref _dst, _indent + 2);
            if (_dst.Length == _hdr{{.Name}}) _dst.Length = _mark{{.Name}};
        }
{{- end}}
{{- else if .IsDecimal}}
        if (this.{{.Name}} != 0m)
        {
{{- range $i, $line := $cmt}}
            _dst.Append(_sp); _dst.Append("#"); _dst.Append({{csYamlCommentExpr $goName $cmtNums $i $line}});
{{- end}}
            _dst.Append(_sp); _dst.Append({{if $hasYamlNames}}_{{$goName}}_YamlKeys.{{.Name}} + ": "{{else}}"{{yamlKey .}}: "{{end}});
            _dst.Append(Math.Round(this.{{.Name}}, {{.DecimalRound}}, MidpointRounding.AwayFromZero).ToString("F{{.DecimalRound}}", CultureInfo.InvariantCulture));
{{- if gt .InlineCommentLineNum 0}}
            _dst.Append("  "); _dst.Append("#"); _dst.Append({{csYamlInlineCommentExpr $goName .}});
{{- else}}
            _dst.Append("\n");
{{- end}}
        }
{{- else if .IsBool}}
        if (this.{{.Name}})
        {
{{- range $i, $line := $cmt}}
            _dst.Append(_sp); _dst.Append("#"); _dst.Append({{csYamlCommentExpr $goName $cmtNums $i $line}});
{{- end}}
            _dst.Append(_sp); _dst.Append({{if $hasYamlNames}}_{{$goName}}_YamlKeys.{{.Name}} + ": true"{{else}}"{{yamlKey .}}: true"{{end}});
{{- if gt .InlineCommentLineNum 0}}
            _dst.Append("  "); _dst.Append("#"); _dst.Append({{csYamlInlineCommentExpr $goName .}});
{{- else}}
            _dst.Append("\n");
{{- end}}
        }
{{- else if .IsString}}
        if (!string.IsNullOrEmpty(this.{{.Name}}))
        {
{{- range $i, $line := $cmt}}
            _dst.Append(_sp); _dst.Append("#"); _dst.Append({{csYamlCommentExpr $goName $cmtNums $i $line}});
{{- end}}
            _dst.Append(_sp); _dst.Append({{if $hasYamlNames}}_{{$goName}}_YamlKeys.{{.Name}} + ": "{{else}}"{{yamlKey .}}: "{{end}}); _dst.Append(_strVal(this.{{.Name}}));
{{- if gt .InlineCommentLineNum 0}}
            _dst.Append("  "); _dst.Append("#"); _dst.Append({{csYamlInlineCommentExpr $goName .}});
{{- else}}
            _dst.Append("\n");
{{- end}}
        }
{{- else if .IsBytes}}
        if (this.{{.Name}} != null && this.{{.Name}}.Length > 0)
        {
{{- range $i, $line := $cmt}}
            _dst.Append(_sp); _dst.Append("#"); _dst.Append({{csYamlCommentExpr $goName $cmtNums $i $line}});
{{- end}}
            _dst.Append(_sp); _dst.Append({{if $hasYamlNames}}_{{$goName}}_YamlKeys.{{.Name}} + ": "{{else}}"{{yamlKey .}}: "{{end}}); _dst.Append(Convert.ToBase64String(this.{{.Name}}));
{{- if gt .InlineCommentLineNum 0}}
            _dst.Append("  "); _dst.Append("#"); _dst.Append({{csYamlInlineCommentExpr $goName .}});
{{- else}}
            _dst.Append("\n");
{{- end}}
        }
{{- else if eq .Type "double"}}
        if (this.{{.Name}} != 0.0)
        {
{{- range $i, $line := $cmt}}
            _dst.Append(_sp); _dst.Append("#"); _dst.Append({{csYamlCommentExpr $goName $cmtNums $i $line}});
{{- end}}
            _dst.Append(_sp); _dst.Append({{if $hasYamlNames}}_{{$goName}}_YamlKeys.{{.Name}} + ": "{{else}}"{{yamlKey .}}: "{{end}}); _dst.Append(this.{{.Name}}.ToString("R", CultureInfo.InvariantCulture));
{{- if gt .InlineCommentLineNum 0}}
            _dst.Append("  "); _dst.Append("#"); _dst.Append({{csYamlInlineCommentExpr $goName .}});
{{- else}}
            _dst.Append("\n");
{{- end}}
        }
{{- else if eq .Type "float"}}
        if (this.{{.Name}} != 0.0f)
        {
{{- range $i, $line := $cmt}}
            _dst.Append(_sp); _dst.Append("#"); _dst.Append({{csYamlCommentExpr $goName $cmtNums $i $line}});
{{- end}}
            _dst.Append(_sp); _dst.Append({{if $hasYamlNames}}_{{$goName}}_YamlKeys.{{.Name}} + ": "{{else}}"{{yamlKey .}}: "{{end}}); _dst.Append(this.{{.Name}}.ToString("R", CultureInfo.InvariantCulture));
{{- if gt .InlineCommentLineNum 0}}
            _dst.Append("  "); _dst.Append("#"); _dst.Append({{csYamlInlineCommentExpr $goName .}});
{{- else}}
            _dst.Append("\n");
{{- end}}
        }
{{- else if .IsEnum}}
        if ((int)this.{{.Name}} != 0)
        {
{{- range $i, $line := $cmt}}
            _dst.Append(_sp); _dst.Append("#"); _dst.Append({{csYamlCommentExpr $goName $cmtNums $i $line}});
{{- end}}
            _dst.Append(_sp); _dst.Append({{if $hasYamlNames}}_{{$goName}}_YamlKeys.{{.Name}} + ": "{{else}}"{{yamlKey .}}: "{{end}}); _dst.Append(((int)this.{{.Name}}).ToString());
{{- if gt .InlineCommentLineNum 0}}
            _dst.Append("  "); _dst.Append("#"); _dst.Append({{csYamlInlineCommentExpr $goName .}});
{{- else}}
            _dst.Append("\n");
{{- end}}
        }
{{- else}}
        if (this.{{.Name}} != {{csDefault .WriterType}})
        {
{{- range $i, $line := $cmt}}
            _dst.Append(_sp); _dst.Append("#"); _dst.Append({{csYamlCommentExpr $goName $cmtNums $i $line}});
{{- end}}
            _dst.Append(_sp); _dst.Append({{if $hasYamlNames}}_{{$goName}}_YamlKeys.{{.Name}} + ": "{{else}}"{{yamlKey .}}: "{{end}}); _dst.Append(this.{{.Name}}.ToString());
{{- if gt .InlineCommentLineNum 0}}
            _dst.Append("  "); _dst.Append("#"); _dst.Append({{csYamlInlineCommentExpr $goName .}});
{{- else}}
            _dst.Append("\n");
{{- end}}
        }
{{- end}}
{{end}}    }
}
{{end}}{{end}}
{{- define "CsYamlReadonlyFile"}}{{template "CsYamlFileHeader" .}}
{{- with .Msg}}
{{- $goName := .GoName}}
{{$hasYamlNames := false}}
{{- range .Fields}}{{if .YamlName}}{{$hasYamlNames = true}}{{end}}{{end -}}
// ============================================================================
// Readonly{{$goName}} — FromYAML deserialization
// ============================================================================

public partial struct Readonly{{$goName}}
{
    public Error FromYAML(ReadOnlySpan<byte> binary)
    {
        ReadOnlySpan<byte> _src = binary;

        static bool _isSpace(byte _c) =>
            _c == (byte)' ' || _c == (byte)'\t' || _c == (byte)'\r' || _c == (byte)'\n';

        static ReadOnlySpan<byte> _trimLine(ReadOnlySpan<byte> _v)
        {
            while (_v.Length > 0 && (_v[_v.Length - 1] == (byte)'\n' || _v[_v.Length - 1] == (byte)'\r'))
                _v = _v.Slice(0, _v.Length - 1);
            return _v;
        }

        static ReadOnlySpan<byte> _trimSpace(ReadOnlySpan<byte> _v)
        {
            int _s = 0;
            int _e = _v.Length;
            while (_s < _e && _isSpace(_v[_s])) _s++;
            while (_e > _s && _isSpace(_v[_e - 1])) _e--;
            return _v.Slice(_s, _e - _s);
        }

        static ReadOnlySpan<byte> _trimLeftSpaces(ReadOnlySpan<byte> _v)
        {
            int _s = 0;
            while (_s < _v.Length && _v[_s] == (byte)' ') _s++;
            return _v.Slice(_s);
        }

        static void _splitLines(ReadOnlySpan<byte> _bytes, List<int> _starts, List<int> _ends)
        {
            _starts.Clear();
            _ends.Clear();
            int _lineStart = 0;
            for (int _p = 0; _p < _bytes.Length; _p++)
            {
                if (_bytes[_p] == (byte)'\n')
                {
                    _starts.Add(_lineStart);
                    _ends.Add(_p + 1);
                    _lineStart = _p + 1;
                }
            }
            if (_lineStart < _bytes.Length || _bytes.Length == 0)
            {
                _starts.Add(_lineStart);
                _ends.Add(_bytes.Length);
            }
        }

        static ReadOnlySpan<byte> _lineAt(ReadOnlySpan<byte> _bytes, List<int> _starts, List<int> _ends, int _idx)
        {
            int _start = _starts[_idx];
            return _bytes.Slice(_start, _ends[_idx] - _start);
        }

        static int _firstNonEmptyIndent(ReadOnlySpan<byte> _bytes, List<int> _starts, List<int> _ends)
        {
            for (int _i = 0; _i < _starts.Count; _i++)
            {
                ReadOnlySpan<byte> _s = _trimLine(_lineAt(_bytes, _starts, _ends, _i));
                if (_trimSpace(_s).Length > 0)
                {
                    ReadOnlySpan<byte> _t = _trimLeftSpaces(_s);
                    return _s.Length - _t.Length;
                }
            }
            return -1;
        }

        static ReadOnlySpan<byte> _collectIndentedBlock(ReadOnlySpan<byte> _bytes, List<int> _starts, List<int> _ends, int _baseIndent, ref int _ip)
        {
            int _start = _ip + 1 < _starts.Count ? _starts[_ip + 1] : _bytes.Length;
            int _end = _start;
            int _j = _ip + 1;
            while (_j < _starts.Count)
            {
                ReadOnlySpan<byte> _sl = _trimLine(_lineAt(_bytes, _starts, _ends, _j));
                if (_trimSpace(_sl).Length == 0)
                {
                    _end = _ends[_j];
                    _j++;
                    continue;
                }
                ReadOnlySpan<byte> _st = _trimLeftSpaces(_sl);
                if (_sl.Length - _st.Length > _baseIndent)
                {
                    _end = _ends[_j];
                    _j++;
                }
                else break;
            }
            _ip = _j - 1;
            return _bytes.Slice(_start, _end - _start);
        }

        static ReadOnlySpan<byte> _collectListItemBlock(ReadOnlySpan<byte> _bytes, List<int> _starts, List<int> _ends, int _baseIndent, ref int _ip)
        {
            int _start = _ip + 1 < _starts.Count ? _starts[_ip + 1] : _bytes.Length;
            int _end = _start;
            int _j = _ip + 1;
            int _itemBase = -1;
            while (_j < _starts.Count)
            {
                ReadOnlySpan<byte> _ssl = _trimLine(_lineAt(_bytes, _starts, _ends, _j));
                if (_trimSpace(_ssl).Length == 0)
                {
                    _end = _ends[_j];
                    _j++;
                    continue;
                }
                ReadOnlySpan<byte> _sst = _trimLeftSpaces(_ssl);
                int _ssi = _ssl.Length - _sst.Length;
                if (_itemBase < 0 && _ssi > _baseIndent + 2) _itemBase = _ssi;
                if (_itemBase < 0 || _ssi >= _itemBase)
                {
                    _end = _ends[_j];
                    _j++;
                }
                else break;
            }
            _ip = _j - 1;
            return _bytes.Slice(_start, _end - _start);
        }

        static string _unquoteStr(ReadOnlySpan<byte> v)
        {
            if (v.Length == 0) return string.Empty;
            if (v.Length >= 2 && v[0] == (byte)'"' && v[v.Length - 1] == (byte)'"')
            {
                byte[] _buf = new byte[v.Length - 2];
                int _n = 0;
                for (int _ui = 1; _ui < v.Length - 1; _ui++)
                {
                    if (v[_ui] == (byte)'\\' && _ui + 1 < v.Length - 1)
                    {
                        _ui++;
                        switch (v[_ui])
                        {
                            case (byte)'"':  _buf[_n++] = (byte)'"';  break;
                            case (byte)'\\': _buf[_n++] = (byte)'\\'; break;
                            case (byte)'n':  _buf[_n++] = (byte)'\n'; break;
                            case (byte)'r':  _buf[_n++] = (byte)'\r'; break;
                            case (byte)'t':  _buf[_n++] = (byte)'\t'; break;
                            default:
                                _buf[_n++] = (byte)'\\';
                                _buf[_n++] = v[_ui];
                                break;
                        }
                    }
                    else
                        _buf[_n++] = v[_ui];
                }
                return Encoding.UTF8.GetString(_buf, 0, _n);
            }
            if (v.Length >= 2 && v[0] == (byte)'\'' && v[v.Length - 1] == (byte)'\'')
                return Encoding.UTF8.GetString(v.Slice(1, v.Length - 2));
            return Encoding.UTF8.GetString(v);
        }

        static bool _isTrue(ReadOnlySpan<byte> _v) =>
            _v.SequenceEqual("true"u8) || _v.SequenceEqual("1"u8);

        static bool _parseInt(ReadOnlySpan<byte> _v, out int _value) =>
            Utf8Parser.TryParse(_v, out _value, out int _consumed) && _consumed == _v.Length;

        static bool _parseUInt(ReadOnlySpan<byte> _v, out uint _value) =>
            Utf8Parser.TryParse(_v, out _value, out int _consumed) && _consumed == _v.Length;

        static bool _parseLong(ReadOnlySpan<byte> _v, out long _value) =>
            Utf8Parser.TryParse(_v, out _value, out int _consumed) && _consumed == _v.Length;

        static bool _parseULong(ReadOnlySpan<byte> _v, out ulong _value) =>
            Utf8Parser.TryParse(_v, out _value, out int _consumed) && _consumed == _v.Length;

        static bool _parseFloat(ReadOnlySpan<byte> _v, out float _value) =>
            Utf8Parser.TryParse(_v, out _value, out int _consumed) && _consumed == _v.Length;

        static bool _parseDouble(ReadOnlySpan<byte> _v, out double _value) =>
            Utf8Parser.TryParse(_v, out _value, out int _consumed) && _consumed == _v.Length;

        static bool _decodeBase64(ReadOnlySpan<byte> _v, out byte[] _value)
        {
            _value = new byte[Base64.GetMaxDecodedFromUtf8Length(_v.Length)];
            OperationStatus _status = Base64.DecodeFromUtf8(_v, _value, out int _consumed, out int _written);
            if (_status != OperationStatus.Done || _consumed != _v.Length)
            {
                _value = Array.Empty<byte>();
                return false;
            }
            if (_written != _value.Length) Array.Resize(ref _value, _written);
            return true;
        }

        var _lineStarts = new List<int>();
        var _lineEnds = new List<int>();
        _splitLines(_src, _lineStarts, _lineEnds);
        int _baseIndent = _firstNonEmptyIndent(_src, _lineStarts, _lineEnds);
        if (_baseIndent < 0) return default;

        for (int _i = 0; _i < _lineStarts.Count; _i++)
        {
            ReadOnlySpan<byte> _line = _trimLine(_lineAt(_src, _lineStarts, _lineEnds, _i));
            if (_trimSpace(_line).Length == 0) continue;
            ReadOnlySpan<byte> _trimmed = _trimLeftSpaces(_line);
            int _curIndent = _line.Length - _trimmed.Length;
            if (_curIndent != _baseIndent) continue;
            if (_trimmed.Length > 0 && _trimmed[0] == (byte)'#') continue;
            int _colonPos = _trimmed.IndexOf((byte)':');
            if (_colonPos < 0) continue;
            ReadOnlySpan<byte> _key = _trimmed.Slice(0, _colonPos);
            ReadOnlySpan<byte> _valBytes = _trimSpace(_trimmed.Slice(_colonPos + 1));

{{range $i, $f := .Fields}}
            {{if $i}}else {{end}}if (_key.SequenceEqual({{if $hasYamlNames}}Encoding.UTF8.GetBytes(_{{$goName}}_YamlKeys.{{.Name}}){{else}}"{{yamlKey .}}"u8{{end}}))
{{- if .IsMap}}
            {
                ReadOnlySpan<byte> _sub = _collectIndentedBlock(_src, _lineStarts, _lineEnds, _baseIndent, ref _i);
                var _sStarts = new List<int>();
                var _sEnds = new List<int>();
                _splitLines(_sub, _sStarts, _sEnds);
                int _sbase = _firstNonEmptyIndent(_sub, _sStarts, _sEnds);
                    if (_sbase >= 0)
                    {
{{- if .MapValIsMsg}}
                    var _dict{{.Name}} = new {{.EffReadonlyType}}();
                    for (int _mj = 0; _mj < _sStarts.Count; _mj++)
                    {
                        ReadOnlySpan<byte> _sl = _trimLine(_lineAt(_sub, _sStarts, _sEnds, _mj));
                        if (_trimSpace(_sl).Length == 0) continue;
                        ReadOnlySpan<byte> _st2 = _trimLeftSpaces(_sl);
                        if (_sl.Length - _st2.Length != _sbase) continue;
                        int _mcp = _st2.IndexOf((byte)':');
                        if (_mcp < 0) continue;
                        ReadOnlySpan<byte> _mkBytes = _trimSpace(_st2.Slice(0, _mcp));
{{- if eq .MapKeyCS "string"}}
                        string _mk = _unquoteStr(_st2.Slice(0, _mcp));
{{- else if eq .MapKeyCS "bool"}}
                        bool _mk = _isTrue(_mkBytes);
{{- else if eq .MapKeyCS "ulong"}}
                        if (!_parseULong(_mkBytes, out ulong _mk))
                            return Error.WithLoc(1, "bad map key {{yamlKey .}}");
{{- else if eq .MapKeyCS "long"}}
                        if (!_parseLong(_mkBytes, out long _mk))
                            return Error.WithLoc(1, "bad map key {{yamlKey .}}");
{{- else if eq .MapKeyCS "uint"}}
                        if (!_parseUInt(_mkBytes, out uint _mk))
                            return Error.WithLoc(1, "bad map key {{yamlKey .}}");
{{- else}}
                        if (!_parseInt(_mkBytes, out int _mk))
                            return Error.WithLoc(1, "bad map key {{yamlKey .}}");
{{- end}}
                        ReadOnlySpan<byte> _entryBytes = _collectIndentedBlock(_sub, _sStarts, _sEnds, _sbase, ref _mj);
                        var _mval{{.Name}} = new {{.WrapReadonlyMapValCS}}();
                        var _mverr{{.Name}} = _mval{{.Name}}.Value.FromYAML(_entryBytes);
                        if (_mverr{{.Name}}.Err()) return _mverr{{.Name}};
                        _dict{{.Name}}[_mk] = _mval{{.Name}};
                    }
{{- else}}
                    var _dict{{.Name}} = new {{.EffReadonlyType}}();
                    for (int _mj = 0; _mj < _sStarts.Count; _mj++)
                    {
                        ReadOnlySpan<byte> _ss = _trimLine(_lineAt(_sub, _sStarts, _sEnds, _mj));
                        if (_trimSpace(_ss).Length == 0) continue;
                        ReadOnlySpan<byte> _st2 = _trimLeftSpaces(_ss);
                        if (_ss.Length - _st2.Length != _sbase) continue;
                        int _dcp = _st2.IndexOf((byte)':');
                        if (_dcp < 0) continue;
                        ReadOnlySpan<byte> _mv = _trimSpace(_st2.Slice(_dcp + 1));
                        ReadOnlySpan<byte> _dkBytes = _trimSpace(_st2.Slice(0, _dcp));
{{- if eq .MapKeyCS "string"}}
                        string _dk = _unquoteStr(_st2.Slice(0, _dcp));
{{- else if eq .MapKeyCS "bool"}}
                        bool _dk = _isTrue(_dkBytes);
{{- else if eq .MapKeyCS "ulong"}}
                        if (!_parseULong(_dkBytes, out ulong _dk))
                            return Error.WithLoc(1, "bad map key {{yamlKey .}}");
{{- else if eq .MapKeyCS "long"}}
                        if (!_parseLong(_dkBytes, out long _dk))
                            return Error.WithLoc(1, "bad map key {{yamlKey .}}");
{{- else if eq .MapKeyCS "uint"}}
                        if (!_parseUInt(_dkBytes, out uint _dk))
                            return Error.WithLoc(1, "bad map key {{yamlKey .}}");
{{- else}}
                        if (!_parseInt(_dkBytes, out int _dk))
                            return Error.WithLoc(1, "bad map key {{yamlKey .}}");
{{- end}}
{{- if eq .MapVal "string"}}
                        _dict{{.Name}}[_dk] = _unquoteStr(_mv);
{{- else if eq .MapVal "bytes"}}
                        if (!_decodeBase64(_mv, out byte[] _bv{{.Name}}))
                            return Error.WithLoc(1, "bad base64 {{yamlKey .}}");
                        _dict{{.Name}}[_dk] = _bv{{.Name}};
{{- else if eq .MapVal "bool"}}
                        _dict{{.Name}}[_dk] = _isTrue(_mv);
{{- else if eq .MapVal "double"}}
                        if (!_parseDouble(_mv, out double _mvd{{.Name}}))
                            return Error.WithLoc(1, "bad double {{yamlKey .}}");
                        _dict{{.Name}}[_dk] = _mvd{{.Name}};
{{- else if eq .MapVal "float"}}
                        if (!_parseFloat(_mv, out float _mvf{{.Name}}))
                            return Error.WithLoc(1, "bad float {{yamlKey .}}");
                        _dict{{.Name}}[_dk] = _mvf{{.Name}};
{{- else if or (eq .MapVal "uint64") (eq .MapVal "fixed64")}}
                        if (!_parseULong(_mv, out ulong _mvu{{.Name}}))
                            return Error.WithLoc(1, "bad uint64 {{yamlKey .}}");
                        _dict{{.Name}}[_dk] = ({{.MapValCS}})_mvu{{.Name}};
{{- else if or (eq .MapVal "int64") (eq .MapVal "sint64") (eq .MapVal "sfixed64")}}
                        if (!_parseLong(_mv, out long _mvl{{.Name}}))
                            return Error.WithLoc(1, "bad int64 {{yamlKey .}}");
                        _dict{{.Name}}[_dk] = ({{.MapValCS}})_mvl{{.Name}};
{{- else if or (eq .MapVal "uint32") (eq .MapVal "fixed32")}}
                        if (!_parseUInt(_mv, out uint _mvui{{.Name}}))
                            return Error.WithLoc(1, "bad uint32 {{yamlKey .}}");
                        _dict{{.Name}}[_dk] = ({{.MapValCS}})_mvui{{.Name}};
{{- else}}
                        if (!_parseInt(_mv, out int _mvi{{.Name}}))
                            return Error.WithLoc(1, "bad int {{yamlKey .}}");
                        _dict{{.Name}}[_dk] = ({{.MapValCS}})_mvi{{.Name}};
{{- end}}
                    }
{{- end}}
                    this.{{.Name}} = _dict{{.Name}};
                }
                continue;
            }
{{- else if .IsRepeated}}
            {
                ReadOnlySpan<byte> _sub = _collectIndentedBlock(_src, _lineStarts, _lineEnds, _baseIndent, ref _i);
                var _sStarts = new List<int>();
                var _sEnds = new List<int>();
                _splitLines(_sub, _sStarts, _sEnds);
{{- if .ElemIsMsg}}
                var _list{{.Name}} = new {{.ReadonlyType}}();
                for (int _rj = 0; _rj < _sStarts.Count; _rj++)
                {
                    ReadOnlySpan<byte> _sl = _trimLine(_lineAt(_sub, _sStarts, _sEnds, _rj));
                    ReadOnlySpan<byte> _rst = _trimSpace(_sl);
                    if (_rst.Length == 0 || _rst[0] != (byte)'-') continue;
                    ReadOnlySpan<byte> _itemBytes = _collectListItemBlock(_sub, _sStarts, _sEnds, _baseIndent, ref _rj);
                    {{.ReadonlyElemTypeCS}} _elem{{.Name}} = default;
                    var _eerr{{.Name}} = _elem{{.Name}}.FromYAML(_itemBytes);
                    if (_eerr{{.Name}}.Err()) return _eerr{{.Name}};
                    _list{{.Name}}.Add(_elem{{.Name}});
                }
                this.{{.Name}} = _list{{.Name}};
{{- else}}
                var _list{{.Name}} = new {{.ReadonlyType}}();
                for (int _rj = 0; _rj < _sStarts.Count; _rj++)
                {
                    ReadOnlySpan<byte> _ss = _trimLine(_lineAt(_sub, _sStarts, _sEnds, _rj));
                    ReadOnlySpan<byte> _rst = _trimSpace(_ss);
                    if (_rst.Length == 0 || _rst[0] != (byte)'-') continue;
                    ReadOnlySpan<byte> _item = _trimSpace(_rst.Slice(1));
{{- if eq .Type "string"}}
                    _list{{.Name}}.Add(_unquoteStr(_item));
{{- else if eq .Type "bytes"}}
                    if (!_decodeBase64(_item, out byte[] _bitem{{.Name}}))
                        return Error.WithLoc(1, "bad base64 {{yamlKey .}}");
                    _list{{.Name}}.Add(_bitem{{.Name}});
{{- else if eq .Type "bool"}}
                    _list{{.Name}}.Add(_isTrue(_item));
{{- else if eq .Type "double"}}
                    if (!_parseDouble(_item, out double _vd{{.Name}}))
                        return Error.WithLoc(1, "bad double {{yamlKey .}}");
                    _list{{.Name}}.Add(_vd{{.Name}});
{{- else if eq .Type "float"}}
                    if (!_parseFloat(_item, out float _vf{{.Name}}))
                        return Error.WithLoc(1, "bad float {{yamlKey .}}");
                    _list{{.Name}}.Add(_vf{{.Name}});
{{- else if or (eq .Type "uint64") (eq .Type "fixed64")}}
                    if (!_parseULong(_item, out ulong _vu{{.Name}}))
                        return Error.WithLoc(1, "bad uint64 {{yamlKey .}}");
                    _list{{.Name}}.Add(({{.ElemTypeCS}})_vu{{.Name}});
{{- else if or (eq .Type "uint32") (eq .Type "fixed32")}}
                    if (!_parseUInt(_item, out uint _vui{{.Name}}))
                        return Error.WithLoc(1, "bad uint32 {{yamlKey .}}");
                    _list{{.Name}}.Add(({{.ElemTypeCS}})_vui{{.Name}});
{{- else if or (eq .Type "int64") (eq .Type "sint64") (eq .Type "sfixed64")}}
                    if (!_parseLong(_item, out long _vl{{.Name}}))
                        return Error.WithLoc(1, "bad int64 {{yamlKey .}}");
                    _list{{.Name}}.Add(({{.ElemTypeCS}})_vl{{.Name}});
{{- else if .IsEnum}}
                    if (!_parseInt(_item, out int _ve{{.Name}}))
                        return Error.WithLoc(1, "bad enum {{yamlKey .}}");
                    _list{{.Name}}.Add(({{.ElemTypeCS}})_ve{{.Name}});
{{- else}}
                    if (!_parseInt(_item, out int _vi{{.Name}}))
                        return Error.WithLoc(1, "bad int {{yamlKey .}}");
                    _list{{.Name}}.Add(({{.ElemTypeCS}})_vi{{.Name}});
{{- end}}
                }
                this.{{.Name}} = _list{{.Name}};
{{- end}}
                continue;
            }
{{- else if .IsMsg}}
            {
                ReadOnlySpan<byte> _sub = _collectIndentedBlock(_src, _lineStarts, _lineEnds, _baseIndent, ref _i);
{{- if .UseDirectWrapper}}
                if (this.{{.Name}} == null) this.{{.Name}} = new {{.EffReadonlyType}}();
                var _merr{{.Name}} = this.{{.Name}}.Value.FromYAML(_sub);
{{- else}}
                var _merr{{.Name}} = this.{{.Name}}.FromYAML(_sub);
{{- end}}
                if (_merr{{.Name}}.Err()) return _merr{{.Name}};
                continue;
            }
{{- else if .IsDecimal}}
            {
                if (!_parseDouble(_valBytes, out double _dval{{.Name}}))
                    return Error.WithLoc(1, "bad decimal {{yamlKey .}}");
                this.{{.Name}} = Math.Round((decimal)_dval{{.Name}}, {{.DecimalRound}}, MidpointRounding.AwayFromZero);
                continue;
            }
{{- else if .IsBool}}
            {
                this.{{.Name}} = _isTrue(_valBytes);
                continue;
            }
{{- else if .IsString}}
            {
                this.{{.Name}} = _unquoteStr(_valBytes);
                continue;
            }
{{- else if .IsBytes}}
            {
                if (!_decodeBase64(_valBytes, out byte[] _bval{{.Name}}))
                    return Error.WithLoc(1, "bad base64 {{yamlKey .}}");
                this.{{.Name}} = _bval{{.Name}};
                continue;
            }
{{- else if eq .Type "double"}}
            {
                if (!_parseDouble(_valBytes, out double _dv{{.Name}}))
                    return Error.WithLoc(1, "bad double {{yamlKey .}}");
                this.{{.Name}} = _dv{{.Name}};
                continue;
            }
{{- else if eq .Type "float"}}
            {
                if (!_parseFloat(_valBytes, out float _fv{{.Name}}))
                    return Error.WithLoc(1, "bad float {{yamlKey .}}");
                this.{{.Name}} = _fv{{.Name}};
                continue;
            }
{{- else if or (eq .Type "uint64") (eq .Type "fixed64")}}
            {
                if (!_parseULong(_valBytes, out ulong _uv{{.Name}}))
                    return Error.WithLoc(1, "bad uint64 {{yamlKey .}}");
                this.{{.Name}} = ({{.ReadonlyType}})_uv{{.Name}};
                continue;
            }
{{- else if or (eq .Type "uint32") (eq .Type "fixed32")}}
            {
                if (!_parseUInt(_valBytes, out uint _uiv{{.Name}}))
                    return Error.WithLoc(1, "bad uint32 {{yamlKey .}}");
                this.{{.Name}} = ({{.ReadonlyType}})_uiv{{.Name}};
                continue;
            }
{{- else if or (eq .Type "int64") (eq .Type "sint64") (eq .Type "sfixed64")}}
            {
                if (!_parseLong(_valBytes, out long _lv{{.Name}}))
                    return Error.WithLoc(1, "bad int64 {{yamlKey .}}");
                this.{{.Name}} = ({{.ReadonlyType}})_lv{{.Name}};
                continue;
            }
{{- else if .IsEnum}}
            {
                if (!_parseInt(_valBytes, out int _ev{{.Name}}))
                    return Error.WithLoc(1, "bad enum {{yamlKey .}}");
                this.{{.Name}} = ({{.ReadonlyType}})_ev{{.Name}};
                continue;
            }
{{- else}}
            {
                if (!_parseInt(_valBytes, out int _iv{{.Name}}))
                    return Error.WithLoc(1, "bad int {{yamlKey .}}");
                this.{{.Name}} = ({{.ReadonlyType}})_iv{{.Name}};
                continue;
            }
{{- end}}
{{end}}
        }
        return default;
    }
}
{{end}}{{end}}
