// Code generated by https://github.com/ahfuzhang/BaoHuLu. DO NOT EDIT.

#pragma warning disable CS8600, CS8602, CS8618, CS8625

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using QiWa.Common;
using Xunit;
using {{.Namespace}};

namespace {{.Namespace}}.Tests;

internal static class {{.BaseFileName}}TestValidate
{
    internal static readonly JsonSerializerOptions JsonOptions = new JsonSerializerOptions
    {
        IncludeFields = true,
    };

    private static void CompareByteArray(byte[] expected, byte[] actual, string fieldName)
    {
        if (ReferenceEquals(expected, actual))
        {
            return;
        }

        Assert.NotNull(expected);
        Assert.NotNull(actual);
        Assert.Equal(expected.Length, actual.Length);
        for (var i = 0; i < expected.Length; i++)
        {
            Assert.True(expected[i] == actual[i], $"{fieldName}[{i}] mismatch.");
        }
    }
{{range .Messages}}
{{- $goName := .GoName}}

    internal static void Compare{{$goName}}({{$goName}} expected, {{$goName}} actual)
    {
{{range .Fields}}
{{- if .IsMap}}
        if (expected.{{.Name}} == null)
        {
            Assert.Null(actual.{{.Name}});
        }
        else
        {
            Assert.NotNull(actual.{{.Name}});
            Assert.Equal(expected.{{.Name}}.Count, actual.{{.Name}}.Count);
            foreach (var kv in expected.{{.Name}})
            {
                Assert.True(actual.{{.Name}}.TryGetValue(kv.Key, out var actualVal), "Field {{.Name}} mismatch: missing map key.");
{{- if .MapValIsMsg}}
{{- if .UseMapValWrapper}}
                if (kv.Value?.Value != null)
                    Compare{{.MapValCS}}(kv.Value.Value, actualVal!.Value);
{{- else}}
                Compare{{.MapValCS}}(kv.Value, actualVal);
{{- end}}
{{- else if eq .MapValCS "byte[]"}}
                CompareByteArray(kv.Value, actualVal, "{{.Name}}");
{{- else}}
                Assert.Equal(kv.Value, actualVal);
{{- end}}
            }
        }
{{- else if .IsRepeated}}
        if (expected.{{.Name}} == null)
        {
            Assert.Null(actual.{{.Name}});
        }
        else
        {
            Assert.NotNull(actual.{{.Name}});
            Assert.Equal(expected.{{.Name}}.Count, actual.{{.Name}}.Count);
            for (var i = 0; i < expected.{{.Name}}.Count; i++)
            {
{{- if .ElemIsMsg}}
                Compare{{.ElemTypeCS}}(expected.{{.Name}}[i], actual.{{.Name}}[i]);
{{- else if eq .ElemTypeCS "byte[]"}}
                CompareByteArray(expected.{{.Name}}[i], actual.{{.Name}}[i], "{{.Name}}");
{{- else}}
                Assert.Equal(expected.{{.Name}}[i], actual.{{.Name}}[i]);
{{- end}}
            }
        }
{{- else if .IsMsg}}
{{- if .UseDirectWrapper}}
        if (expected.{{.Name}}?.Value != null)
            Compare{{.WriterType}}(expected.{{.Name}}.Value, actual.{{.Name}}.Value);
{{- else}}
        Compare{{.WriterType}}(expected.{{.Name}}, actual.{{.Name}});
{{- end}}
{{- else if .IsBytes}}
        CompareByteArray(expected.{{.Name}}, actual.{{.Name}}, "{{.Name}}");
{{- else}}
        Assert.Equal(expected.{{.Name}}, actual.{{.Name}});
{{- end}}
{{end}}    }

    internal static void CompareReadonly{{$goName}}({{$goName}} expected, Readonly{{$goName}} actual)
    {
{{range .Fields}}
{{- if .IsMap}}
        if (expected.{{.Name}} == null)
        {
            Assert.Null(actual.{{.Name}});
        }
        else
        {
            Assert.NotNull(actual.{{.Name}});
            Assert.Equal(expected.{{.Name}}.Count, actual.{{.Name}}.Count);
            foreach (var kv in expected.{{.Name}})
            {
                Assert.True(actual.{{.Name}}.TryGetValue(kv.Key, out var actualVal), "Field {{.Name}} mismatch: missing map key.");
{{- if .MapValIsMsg}}
{{- if .UseMapValWrapper}}
                if (kv.Value == null)
                {
                    Assert.Null(actualVal);
                }
                else
                {
                    Assert.NotNull(actualVal);
                    CompareReadonly{{.MapValCS}}(kv.Value.Value, actualVal!.Value);
                }
{{- else}}
                CompareReadonly{{.MapValCS}}(kv.Value, actualVal);
{{- end}}
{{- else if eq .MapValCS "byte[]"}}
                CompareByteArray(kv.Value, actualVal, "{{.Name}}");
{{- else}}
                Assert.Equal(kv.Value, actualVal);
{{- end}}
            }
        }
{{- else if .IsRepeated}}
        if (expected.{{.Name}} == null)
        {
            Assert.Null(actual.{{.Name}});
        }
        else
        {
            Assert.NotNull(actual.{{.Name}});
            Assert.Equal(expected.{{.Name}}.Count, actual.{{.Name}}.Count);
            for (var i = 0; i < expected.{{.Name}}.Count; i++)
            {
{{- if .ElemIsMsg}}
                CompareReadonly{{.ElemTypeCS}}(expected.{{.Name}}[i], actual.{{.Name}}[i]);
{{- else if eq .ElemTypeCS "byte[]"}}
                CompareByteArray(expected.{{.Name}}[i], actual.{{.Name}}[i], "{{.Name}}");
{{- else}}
                Assert.Equal(expected.{{.Name}}[i], actual.{{.Name}}[i]);
{{- end}}
            }
        }
{{- else if .IsMsg}}
{{- if .UseDirectWrapper}}
        if (expected.{{.Name}} == null)
        {
            Assert.Null(actual.{{.Name}});
        }
        else
        {
            Assert.NotNull(actual.{{.Name}});
            CompareReadonly{{.WriterType}}(expected.{{.Name}}.Value, actual.{{.Name}}!.Value);
        }
{{- else}}
        CompareReadonly{{.WriterType}}(expected.{{.Name}}, actual.{{.Name}});
{{- end}}
{{- else if .IsBytes}}
        CompareByteArray(expected.{{.Name}}, actual.{{.Name}}, "{{.Name}}");
{{- else}}
        Assert.Equal(expected.{{.Name}}, actual.{{.Name}});
{{- end}}
{{end}}    }
{{end}}
}
{{$baseFileName := .BaseFileName}}{{range .Messages}}
{{- $goName := .GoName}}
{{- $roName := printf "Readonly%s" .GoName}}

// ── {{$goName}} ───────────────────────────────────────────────────────────────

public class {{$goName}}Tests
{
    /// <summary>Returns a pre-filled {{$goName}} instance for use in tests.</summary>
    public static {{$goName}} MakeSample{{$goName}}()
    {
        return new {{$goName}}
        {
{{range .Fields}}            {{.Name}} = {{csSampleLit .}},
{{end}}        };
    }

    /// <summary>
    /// Returns a {{$goName}} with only scalar value-like fields populated.
    /// Strings, bytes, collections, and nested messages remain at default values.
    /// </summary>
    public static {{$goName}} MakeValueTypeOnly{{$goName}}()
    {
        return new {{$goName}}
        {
{{range .Fields}}{{if and (not .IsMap) (not .IsRepeated) (not .IsString) (not .IsBytes) (not .IsMsg)}}            {{.Name}} = {{csSampleLit .}},
{{end}}{{end}}        };
    }

    // ── Empty ─────────────────────────────────────────────────────────────────

    [Fact]
    public void Empty_ProtobufSize_IsZero()
    {
        var m = new {{$goName}}();
        Assert.Equal(0, m.ProtobufSize());
    }

    [Fact]
    public void Empty_ToProtobuf_WritesNothing()
    {
        var m = new {{$goName}}();
        var buf = new RentedBuffer(16);
        m.ToProtobuf(ref buf);
        Assert.Equal(0, buf.Length);
        buf.Dispose();
    }

    // ── Protobuf roundtrip ────────────────────────────────────────────────────

    // Verifies that serialising a populated {{$goName}} and deserialising it
    // into a Readonly{{$goName}}, then cloning back to a writer, produces byte-identical
    // protobuf output (lossless roundtrip).
    [Fact]
    public void ProtobufRoundtrip()
    {
        var w = MakeSample{{$goName}}();
        int sz = w.ProtobufSize();
        var buf = new RentedBuffer(sz + 4);
        w.ToProtobuf(ref buf);
        Assert.Equal(sz, buf.Length);

        var r = new {{$roName}}();
        var err = r.FromProtobuf(buf.AsSpan());
        Assert.False(err.Err());

        var w2 = new {{$goName}}();
        r.Clone(ref w2);
        var buf2 = new RentedBuffer(w2.ProtobufSize() + 4);
        w2.ToProtobuf(ref buf2);

        Assert.Equal(buf.AsSpan().ToArray(), buf2.AsSpan().ToArray());
        buf.Dispose();
        buf2.Dispose();
    }

    // ── JSON roundtrip ────────────────────────────────────────────────────────

    // Verifies that ToJSON → FromJSON → Clone produces byte-identical JSON output.
    [Fact]
    public void JSONRoundtrip()
    {
        var w = MakeSample{{$goName}}();
        var jBuf = new RentedBuffer(256);
        w.ToJSON(ref jBuf);
        var json = jBuf.AsSpan().ToArray();

        var r = new {{$roName}}();
        var err = r.FromJSON(json);
        Assert.False(err.Err());

        var w2 = new {{$goName}}();
        r.Clone(ref w2);
        var jBuf2 = new RentedBuffer(256);
        w2.ToJSON(ref jBuf2);

        Assert.Equal(json, jBuf2.AsSpan().ToArray());
        jBuf.Dispose();
        jBuf2.Dispose();
    }

{{- if .Yaml}}
    // Verifies that ToYAML → FromYAML preserves every field value without loss.
    [Fact]
    public void YAMLRoundtrip_PreservesAllFields()
    {
        var expected = MakeSample{{$goName}}();
        var yamlBuf = new RentedBuffer(256);
        expected.ToYAML(ref yamlBuf, 0);

        var r = new {{$roName}}();
        var err = r.FromYAML(yamlBuf.AsSpan());
        Assert.False(err.Err(), err.Message);

        {{$baseFileName}}TestValidate.CompareReadonly{{$goName}}(expected, r);

        yamlBuf.Dispose();
    }
{{- end}}

{{- if not .AsMap}}
    // Verifies that System.Text.Json serialisation and deserialisation preserve
    // every field value on the generated writer object.
    // Skipped for @AsMap messages: System.Text.Json serialises the writer struct
    // as {"FieldName": {"k": v}} (with field-name wrapper), but our custom ToJSON
    // produces {"k": v} (flat map). The formats are incompatible, so stdlib JSON
    // cannot validate our custom JSON representation. JSONRoundtrip covers that.
    [Fact]
    public void StdlibJSONRoundtrip_PreservesAllFields()
    {
        var expected = MakeSample{{$goName}}();
        var json = JsonSerializer.Serialize(expected, {{$baseFileName}}TestValidate.JsonOptions);
        var actual = JsonSerializer.Deserialize<{{$goName}}>(json, {{$baseFileName}}TestValidate.JsonOptions);

        {{$baseFileName}}TestValidate.Compare{{$goName}}(expected, actual);
    }
{{- end}}

    // ── Scalar-only coverage ────────────────────────────────────────────────

    // Verifies that a writer containing only scalar value-like fields can emit
    // protobuf and JSON, survive Reset(), then be parsed twice by the same
    // readonly view before that readonly view is Reset() too.
    [Fact]
    public void ValueTypeOnly_SerializeParseAndReset()
    {
        var w = MakeValueTypeOnly{{$goName}}();

        int sz = w.ProtobufSize();
        var buf = new RentedBuffer(sz + 4);
        Assert.False(w.ToProtobuf(ref buf).Err());
        Assert.Equal(sz, buf.Length);

        var jBuf = new RentedBuffer(256);
        w.ToJSON(ref jBuf);

        var protobuf = buf.AsSpan().ToArray();
        var json = jBuf.AsSpan().ToArray();

        w.Reset();
        Assert.Equal(0, w.ProtobufSize());

        var r = new {{$roName}}();
        Assert.False(r.FromProtobuf(protobuf).Err());
        Assert.False(r.FromJSON(json).Err());
        r.Reset();

        buf.Dispose();
        jBuf.Dispose();
    }

    // ── Reset ─────────────────────────────────────────────────────────────────

    [Fact]
    public void Reset_ClearsAllFields()
    {
        var w = MakeSample{{$goName}}();
        w.Reset();
        Assert.Equal(0, w.ProtobufSize());
    }

    [Fact]
    public void Readonly_Reset_Succeeds()
    {
        var w = MakeSample{{$goName}}();
        var buf = new RentedBuffer(w.ProtobufSize() + 4);
        w.ToProtobuf(ref buf);
        var r = new {{$roName}}();
        r.FromProtobuf(buf.AsSpan());
        r.Reset();
        buf.Dispose();
    }

    // ── Clone ─────────────────────────────────────────────────────────────────

    [Fact]
    public void Clone_PreservesData()
    {
        var w = MakeSample{{$goName}}();
        var buf = new RentedBuffer(w.ProtobufSize() + 4);
        w.ToProtobuf(ref buf);
        var r = new {{$roName}}();
        Assert.False(r.FromProtobuf(buf.AsSpan()).Err());
        var w2 = new {{$goName}}();
        r.Clone(ref w2);
        var buf2 = new RentedBuffer(w2.ProtobufSize() + 4);
        w2.ToProtobuf(ref buf2);
        Assert.Equal(buf.AsSpan().ToArray(), buf2.AsSpan().ToArray());
        buf.Dispose();
        buf2.Dispose();
    }

    // ── FromProtobuf error / edge cases ──────────────────────────────────────

    [Fact]
    public void FromProtobuf_EmptyInput_Succeeds()
    {
        var r = new {{$roName}}();
        Assert.False(r.FromProtobuf(ReadOnlySpan<byte>.Empty).Err());
        Assert.False(r.FromProtobuf(Array.Empty<byte>()).Err());
    }

    // field 100, wire-type 0, value 1
    //   tag  = (100 << 3) | 0 = 800 → varint [0xA0, 0x06]
    //   value = varint(1)             → [0x01]
    [Fact]
    public void FromProtobuf_UnknownVarintField_Ignored()
    {
        var unknown = new byte[] { 0xA0, 0x06, 0x01 };
        var r = new {{$roName}}();
        Assert.False(r.FromProtobuf(unknown).Err());
    }

    // Single-byte truncated multi-byte varint (high bit set, no continuation byte).
    [Fact]
    public void FromProtobuf_BadTag_ReturnsError()
    {
        var bad = new byte[] { 0x80 };
        var r = new {{$roName}}();
        Assert.True(r.FromProtobuf(bad).Err());
    }

    // field 100, wire-type 2, claims 100 bytes but provides none.
    //   tag    = (100 << 3) | 2 = 802 → varint [0xA2, 0x06]
    //   length = varint(100)           → [0x64]
    [Fact]
    public void FromProtobuf_TruncatedLenDelim_ReturnsError()
    {
        var bad = new byte[] { 0xA2, 0x06, 0x64 };
        var r = new {{$roName}}();
        Assert.True(r.FromProtobuf(bad).Err());
    }

    // Serialises a populated {{$goName}}, then appends unknown fields of every
    // wire type that a proto3 parser must be able to skip.  Covers the
    // skip-unknown-field branches for all four live wire types.
    // The field number is chosen above the highest defined field to guarantee
    // it is unknown to the parser.
    [Fact]
    public void FromProtobuf_UnknownTrailingFields_AllWireTypes_Ignored()
    {
{{- $uf := safeUnknownFieldNum .Fields}}
        var w = MakeSample{{$goName}}();
        var buf = new RentedBuffer(w.ProtobufSize() + 4);
        w.ToProtobuf(ref buf);
        var valid = buf.AsSpan().ToArray();
        buf.Dispose();

        var cases = new[]
        {
            valid.Concat({{csTagByteArray $uf 0}}.Concat(new byte[] { 0x01 })).ToArray(),                                             // wire 0: varint
            valid.Concat({{csTagByteArray $uf 1}}.Concat(new byte[] { 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08 })).ToArray(), // wire 1: 64-bit
            valid.Concat({{csTagByteArray $uf 2}}.Concat(new byte[] { 0x03, 0x61, 0x62, 0x63 })).ToArray(),                          // wire 2: len-delim
            valid.Concat({{csTagByteArray $uf 5}}.Concat(new byte[] { 0x01, 0x02, 0x03, 0x04 })).ToArray(),                          // wire 5: 32-bit
        };
        foreach (var data in cases)
        {
            var r = new {{$roName}}();
            Assert.False(r.FromProtobuf(data).Err());
        }
    }

    // ── FromJSON error cases ──────────────────────────────────────────────────

    [Fact]
    public void FromJSON_InvalidInput_ReturnsError()
    {
        var r = new {{$roName}}();
        Assert.True(r.FromJSON(System.Text.Encoding.UTF8.GetBytes("not-json")).Err());
        Assert.True(r.FromJSON(System.Text.Encoding.UTF8.GetBytes("[1,2,3]")).Err());
    }
{{- $hasYaml := .Yaml}}
{{- range .Fields}}{{if .IsMap}}

    // Verifies that a map with two entries serialises and deserialises correctly,
    // covering the comma-separator branch in ToJSON.
    [Fact]
    public void MapField_{{.Name}}_TwoEntries_RoundtripBothEntries()
    {
        var w = new {{$goName}}();
        w.{{.Name}} = new {{if .EffWriterType}}{{.EffWriterType}}{{else}}{{.WriterType}}{{end}}
        {
            { {{if eq .MapKeyCS "string"}}"first_key"{{else if eq .MapKeyCS "long"}}1L{{else if eq .MapKeyCS "ulong"}}1UL{{else if eq .MapKeyCS "uint"}}1U{{else if eq .MapKeyCS "bool"}}true{{else}}1{{end}}, {{if .MapValIsMsg}}{{if .UseMapValWrapper}}new {{.WrapMapValCS}}(){{else}}new {{.MapValCS}}(){{end}}{{else if .MapValIsEnum}}({{.MapValCS}})1{{else if eq .MapValCS "string"}}"val1"{{else if eq .MapValCS "byte[]"}}new byte[] { 0x01 }{{else if eq .MapValCS "bool"}}true{{else if eq .MapValCS "float"}}1.5f{{else if eq .MapValCS "double"}}1.5{{else if eq .MapValCS "long"}}1L{{else if eq .MapValCS "ulong"}}1UL{{else if eq .MapValCS "uint"}}1U{{else}}1{{end}} },
            { {{if eq .MapKeyCS "string"}}"second_key"{{else if eq .MapKeyCS "long"}}2L{{else if eq .MapKeyCS "ulong"}}2UL{{else if eq .MapKeyCS "uint"}}2U{{else if eq .MapKeyCS "bool"}}false{{else}}2{{end}}, {{if .MapValIsMsg}}{{if .UseMapValWrapper}}new {{.WrapMapValCS}}(){{else}}new {{.MapValCS}}(){{end}}{{else if .MapValIsEnum}}({{.MapValCS}})2{{else if eq .MapValCS "string"}}"val2"{{else if eq .MapValCS "byte[]"}}new byte[] { 0x02 }{{else if eq .MapValCS "bool"}}false{{else if eq .MapValCS "float"}}2.5f{{else if eq .MapValCS "double"}}2.5{{else if eq .MapValCS "long"}}2L{{else if eq .MapValCS "ulong"}}2UL{{else if eq .MapValCS "uint"}}2U{{else}}2{{end}} },
        };
        int sz = w.ProtobufSize();
        var buf = new RentedBuffer(sz + 4);
        Assert.False(w.ToProtobuf(ref buf).Err());
        var r = new {{$roName}}();
        Assert.False(r.FromProtobuf(buf.AsSpan()).Err());
        Assert.Equal(2, r.{{.Name}}.Count);
        buf.Dispose();
        var jBuf = new RentedBuffer(256);
        w.ToJSON(ref jBuf);
        var r2 = new {{$roName}}();
        Assert.False(r2.FromJSON(jBuf.AsSpan().ToArray()).Err());
        Assert.Equal(2, r2.{{.Name}}.Count);
        jBuf.Dispose();
    }
{{- if or (eq .MapValCS "string") (eq .MapValCS "byte[]")}}

    // Verifies serialisation/deserialisation when a map value is null, covering
    // null-value branches in ProtobufSize, ToProtobuf, and ToJSON.
    [Fact]
    public void MapField_{{.Name}}_NullValue_Roundtrip()
    {
        var w = new {{$goName}}();
        w.{{.Name}} = new {{if .EffWriterType}}{{.EffWriterType}}{{else}}{{.WriterType}}{{end}} { { {{if eq .MapKeyCS "string"}}"null_val_key"{{else if eq .MapKeyCS "long"}}1L{{else if eq .MapKeyCS "ulong"}}1UL{{else if eq .MapKeyCS "uint"}}1U{{else if eq .MapKeyCS "bool"}}true{{else}}1{{end}}, null } };
        int sz = w.ProtobufSize();
        var buf = new RentedBuffer(sz + 4);
        Assert.False(w.ToProtobuf(ref buf).Err());
        buf.Dispose();
        var jBuf = new RentedBuffer(64);
        w.ToJSON(ref jBuf);
        jBuf.Dispose();
    }
{{- end}}
{{- if eq .MapKeyCS "string"}}

    // Verifies serialisation/deserialisation when the map key is an empty string,
    // covering zero-length key branches in ProtobufSize and ToProtobuf.
    [Fact]
    public void MapField_{{.Name}}_EmptyStringKey_Roundtrip()
    {
        var w = new {{$goName}}();
        w.{{.Name}} = new {{if .EffWriterType}}{{.EffWriterType}}{{else}}{{.WriterType}}{{end}} { { string.Empty, {{if .MapValIsMsg}}{{if .UseMapValWrapper}}new {{.WrapMapValCS}}(){{else}}new {{.MapValCS}}(){{end}}{{else if .MapValIsEnum}}({{.MapValCS}})0{{else if eq .MapValCS "string"}}string.Empty{{else if eq .MapValCS "byte[]"}}Array.Empty<byte>(){{else if eq .MapValCS "bool"}}false{{else if eq .MapValCS "float"}}0f{{else if eq .MapValCS "double"}}0.0{{else if eq .MapValCS "long"}}0L{{else if eq .MapValCS "ulong"}}0UL{{else if eq .MapValCS "uint"}}0U{{else}}0{{end}} } };
        int sz = w.ProtobufSize();
        var buf = new RentedBuffer(sz + 4);
        Assert.False(w.ToProtobuf(ref buf).Err());
        var r = new {{$roName}}();
        Assert.False(r.FromProtobuf(buf.AsSpan()).Err());
        buf.Dispose();
        var jBuf = new RentedBuffer(64);
        w.ToJSON(ref jBuf);
        var r2 = new {{$roName}}();
        Assert.False(r2.FromJSON(jBuf.AsSpan().ToArray()).Err());
        jBuf.Dispose();
    }
{{- end}}
{{- if and $hasYaml (eq .MapKeyCS "string") (eq .MapValCS "string")}}

    // Verifies that map entries containing YAML-special characters survive a
    // ToYAML → FromYAML roundtrip, covering the quoting branch in _strVal.
    // Key uses backslash (no colon) to avoid the YAML colon-split ambiguity;
    // value uses colons which also trigger _strVal quoting.
    [Fact]
    public void MapField_{{.Name}}_YAMLSpecialChars_RoundtripPreserved()
    {
        var w = new {{$goName}}();
        w.{{.Name}} = new {{.WriterType}} { { "backslash\\key", "value:has:colon" } };
        var yamlBuf = new RentedBuffer(256);
        w.ToYAML(ref yamlBuf, 0);
        var r = new {{$roName}}();
        Assert.False(r.FromYAML(yamlBuf.AsSpan()).Err());
        Assert.True(r.{{.Name}}.TryGetValue("backslash\\key", out var gotVal));
        Assert.Equal("value:has:colon", gotVal);
        yamlBuf.Dispose();
    }
{{- end}}
{{end}}{{end}}
{{- range .Fields}}{{if .UseDirectWrapper}}

    // Verifies that recursive field {{.Name}} with a non-null inner value survives
    // both a protobuf and JSON roundtrip, exercising wrapper encode/decode paths.
    [Fact]
    public void RecursiveField_{{.Name}}_PopulatedValue_Roundtrip()
    {
        var inner = MakeValueTypeOnly{{$goName}}();
        var w = new {{$goName}} { {{.Name}} = new {{.EffWriterType}} { Value = inner } };

        // Protobuf roundtrip
        int sz = w.ProtobufSize();
        var buf = new RentedBuffer(sz + 4);
        Assert.False(w.ToProtobuf(ref buf).Err());
        Assert.Equal(sz, buf.Length);
        var r = new {{$roName}}();
        Assert.False(r.FromProtobuf(buf.AsSpan()).Err());
        var w2 = new {{$goName}}();
        r.Clone(ref w2);
        Assert.NotNull(w2.{{.Name}});
        buf.Dispose();

        // JSON roundtrip
        var jBuf = new RentedBuffer(256);
        w.ToJSON(ref jBuf);
        var r2 = new {{$roName}}();
        Assert.False(r2.FromJSON(jBuf.AsSpan().ToArray()).Err());
        var w3 = new {{$goName}}();
        r2.Clone(ref w3);
        Assert.NotNull(w3.{{.Name}});
        jBuf.Dispose();
    }
{{end}}{{end}}
{{- $strf := firstCsStringField .Fields}}
{{if $strf}}
    // Verifies that strings containing special escape characters (\n newline,
    // \t tab, \" double-quote, \\ backslash) survive both a protobuf roundtrip
    // and a JSON roundtrip without mangling.
    // Field under test: {{$strf.Name}} (string)
    [Fact]
    public void StringEscapes_RoundtripPreservesEscapes()
    {
        const string escStr = "hello\nworld\ttab\"quote\\backslash";
        var w = new {{$goName}} { {{$strf.Name}} = escStr };

        // Protobuf roundtrip
        var buf = new RentedBuffer(w.ProtobufSize() + 4);
        w.ToProtobuf(ref buf);
        var r = new {{$roName}}();
        Assert.False(r.FromProtobuf(buf.AsSpan()).Err());
        var w2 = new {{$goName}}();
        r.Clone(ref w2);
        Assert.Equal(escStr, w2.{{$strf.Name}});

        // JSON roundtrip
        var jBuf = new RentedBuffer(256);
        w.ToJSON(ref jBuf);
        var json = jBuf.AsSpan().ToArray();
        var r2 = new {{$roName}}();
        Assert.False(r2.FromJSON(json).Err());
        var w3 = new {{$goName}}();
        r2.Clone(ref w3);
        Assert.Equal(escStr, w3.{{$strf.Name}});

        buf.Dispose();
        jBuf.Dispose();
    }
{{end -}}
{{range csDecimalFields .Fields}}
    // Verifies that the decimal field {{.Name}} (round:{{.DecimalRound}}) preserves its
    // configured rounding precision through both protobuf and JSON roundtrips.
    [Fact]
    public void DecimalPrecision_{{.Name}}_RoundtripPreservesRounding()
    {
        var w = new {{$goName}} { {{.Name}} = 1.123456789m };

        // ── Protobuf roundtrip ────────────────────────────────────────────────
        var buf = new RentedBuffer(w.ProtobufSize() + 4);
        Assert.False(w.ToProtobuf(ref buf).Err());
        var r = new {{$roName}}();
        Assert.False(r.FromProtobuf(buf.AsSpan()).Err());
        var w2 = new {{$goName}}();
        r.Clone(ref w2);
        Assert.NotEqual(0m, w2.{{.Name}});

        // ── JSON roundtrip ────────────────────────────────────────────────────
        var jBuf = new RentedBuffer(256);
        w.ToJSON(ref jBuf);
        var r2 = new {{$roName}}();
        Assert.False(r2.FromJSON(jBuf.AsSpan().ToArray()).Err());
        var w3 = new {{$goName}}();
        r2.Clone(ref w3);
        Assert.NotEqual(0m, w3.{{.Name}});

        buf.Dispose();
        jBuf.Dispose();
    }
{{end -}}
}
{{end}}
